Repository dnnsoftware/Dnn.Platform, pull requests merged in 2018-06, with the labels that each got.

#2113 #2053 - Update Contributing Document
  CONTRIBUTING.md
Labels: Community, Review in Progress

#2114 Added Policy Documentation to the Repository
  .github/PULL_REQUEST_PROCESS.md
  .github/RELEASE_SCHEDULE.md
  .github/VERSIONING_POLICY.md
  README.md
Labels: Community

#2098 DNN-20914: save module permissions into database.
  DNN Platform/Modules/DnnExportImport/Components/Services/PagesExportService.cs
Labels: esw
