Repository dnnsoftware/Dnn.Platform, pull requests merged in 2018-10, with the labels that each got.

#2153 Fixes #DNN-8338 SI: Full Exports Do Not Update Existing HTML Pro Modules
  DNN Platform/Modules/DnnExportImport/Components/Services/PagesExportService.cs
Labels: esw

#2331 copy terms into localized pages
  DNN Platform/Library/Entities/Tabs/TabController.cs
Labels: esw

#2342 Performance fix for CoreMessaging_GetMessageConversations and Journal_ListForGroup Procedure
  Website/Providers/DataProviders/SqlDataProvider/09.03.00.SqlDataProvider
Labels: Community, Noteworthy

#2281 Implement Parent by Url
  DNN Platform/Modules/DnnExportImport/Components/Services/PagesExportService.cs
Labels: esw

#2179 renewal token must be validate before renewing access token.
  DNN Platform/Dnn.AuthServices.Jwt/Components/Common/Controllers/JwtController.cs
Labels: Community

#2288 Add UI to Manage Google Analytic Tracking Code
  DNN Platform/Connectors/GoogleAnalytics/App_LocalResources/SharedResources.resx
  DNN Platform/Connectors/GoogleAnalytics/Connector.css
  DNN Platform/Connectors/GoogleAnalytics/Constants.cs
  DNN Platform/Connectors/GoogleAnalytics/Dnn.GoogleAnalyticsConnector.csproj
  DNN Platform/Connectors/GoogleAnalytics/GoogleAnalyticsConnector.cs
  DNN Platform/Connectors/GoogleAnalytics/GoogleAnalyticsConnector.dnn
  DNN Platform/Connectors/GoogleAnalytics/Images/GoogleAnalytics_32X32_Standard.png
  DNN Platform/Connectors/GoogleAnalytics/License.txt
  DNN Platform/Connectors/GoogleAnalytics/Module.build
  DNN Platform/Connectors/GoogleAnalytics/ReleaseNotes.txt
  DNN Platform/Connectors/GoogleAnalytics/Scripts/connector.js
  DNN Platform/Connectors/GoogleAnalytics/connector.htm
  DNN_Platform.sln
Labels: Community, Noteworthy

#2197 DNN-22117: add sp GetFilesRecursive to get files from folder and all sub folders in one time.
  DNN Platform/Library/Data/DataProvider.cs
  DNN Platform/Library/Services/FileSystem/FolderManager.cs
  Website/Providers/DataProviders/SqlDataProvider/09.03.00.SqlDataProvider
Labels: esw

#2370 CI: Fixing broken builds due to change in build number variable
  build.cake
Labels: Community, DevOps

#2373 DNN-25706: fix broken unit tests.
  DNN Platform/Tests/DotNetNuke.Tests.Core/Providers/Folder/FolderManagerTests.cs
  DNN Platform/Tests/DotNetNuke.Tests.Web/InternalServices/SearchServiceControllerTests.cs
Labels: esw

#2368 Checking for option of EnableEmailasUsername before validating user
  Website/DesktopModules/AuthenticationServices/DNN/Login.ascx.cs
Labels: esw

#2385 DNN-25771: set default database connection provider to compactible for upgrade process.
  DNN Platform/Library/Data/SqlDataProvider.cs
Labels: esw

#2362 Social Profile: visibility of user profile properties
  DNN Platform/Library/Entities/Users/Profile/ProfilePropertyAccess.cs
Labels: esw

#2388 Member Directory Search: adding unused text to page
  DNN Platform/Modules/MemberDirectory/module.css
Labels: esw

#2356 Portal deletion removes home folder linked to other portal
  DNN Platform/Library/Entities/Portals/PortalController.cs
Labels: esw

#2404 DOCS: API docs on Application and Collections
  DNN Platform/Library/Application/Application.cs
  DNN Platform/Library/Application/AssemblyStatusAttribute.cs
  DNN Platform/Library/Collections/CollectionExtensions.cs
  DNN Platform/Library/Collections/EnumerableExtensions.cs
  DNN Platform/Library/Collections/PagedList.cs
  DNN Platform/Library/Collections/PagedSelector.cs
  DNN Platform/Library/Collections/PagingExtensions.cs
Labels: Community

#2420 DNN-26075: sort the files list to alphabetically order.
  DNN Platform/Library/Services/Upgrade/Upgrade.cs
Labels: esw

#2369 Cookieconsent and terms and privacy tabs
  DNN Platform/Library/Data/DataProvider.cs
  DNN Platform/Library/Entities/Portals/PortalController.cs
  DNN Platform/Library/Entities/Portals/PortalInfo.cs
  DNN Platform/Library/Entities/Portals/PortalSettings.cs
  DNN Platform/Library/Entities/Portals/PortalSettingsController.cs
  DNN Platform/Library/Entities/Tabs/TabController.cs
  DNN Platform/Tests/DNN.Integration.Test.Framework/Helpers/PortalInfoHelper.cs
  DNN Platform/Tests/DotNetNuke.Tests.Core/Controllers/Search/InternalSearchControllerTests.cs
  DNN Platform/Tests/DotNetNuke.Tests.Core/Controllers/Search/SearchControllerTests.cs
  DNN Platform/Tests/DotNetNuke.Tests.Core/Controllers/Search/SearchHelperTests.cs
  DNN Platform/Tests/DotNetNuke.Tests.Core/Entities/Portals/PortalSettingsControllerTests.cs
  DNN Platform/Tests/DotNetNuke.Tests.Core/Services/Mobile/RedirectionControllerTests.cs
  DNN Platform/Tests/DotNetNuke.Tests.Web/Api/JwtAuthMessageHandlerTests.cs
  DNN Platform/Tests/DotNetNuke.Tests.Web/Api/StandardTabAndModuleInfoProviderTests.cs
  DNN Platform/Tests/DotNetNuke.Tests.Web/InternalServices/SearchServiceControllerTests.cs
  DNN Platform/Website/Templates/Blank Website.template
  DNN Platform/Website/Templates/Default Website.template
  Website/App_GlobalResources/GlobalResources.resx
  Website/Default.aspx.cs
  Website/DotNetNuke.Website.csproj
  Website/Providers/DataProviders/SqlDataProvider/09.03.00.01.SqlDataProvider
  Website/Providers/DataProviders/SqlDataProvider/09.03.00.02.SqlDataProvider
  Website/Resources/Shared/components/CookieConsent/cookieconsent.min.css
  Website/Resources/Shared/components/CookieConsent/cookieconsent.min.js
  Website/admin/Skins/Privacy.ascx.cs
  Website/admin/Skins/Terms.ascx.cs
  Website/js/Debug/dnn.cookieconsent.js
  Website/js/dnn.cookieconsent.js
Labels: Community, feature, noteworthy
