Repository dnnsoftware/Dnn.Platform, pull requests merged in 2018-07, with the labels that each got.

#2134 Fix bug #DNN-21129
  DNN Platform/DotNetNuke.Web/InternalServices/FileUploadController.cs
Labels: esw

#2076 Don't hardcode NuGet source
  Build/BuildScripts/CreateCommunityPackages.build
  Build_Deploy_Package.bat
  Build_Install_Package.bat
  Build_Source_Package.bat
  Build_Upgrade_Package.bat
Labels: CLA on file, Community

#2171 Adds support for RedirectToAction from a DnnController
  DNN Platform/DotNetNuke.Web.Mvc/Framework/ActionResults/DnnRedirecttoRouteResult.cs
  DNN Platform/DotNetNuke.Web.Mvc/Framework/Controllers/DnnController.cs
Labels: Community

#2159 DNN-21505: Upgrade page is displayed after install Evoq Engage 9.2.2.7-2
  Build/Symbols/DotNetNuke_Symbols.dnn
  DNN Platform/Admin Modules/Dnn.Modules.Console/dnn_Console.dnn
  DNN Platform/Admin Modules/Dnn.Modules.ModuleCreator/dnn_ModuleCreator.dnn
  DNN Platform/Connectors/Azure/AzureConnector.dnn
  DNN Platform/DotNetNuke.Web.Deprecated/dnn_Web_Deprecated.dnn
  DNN Platform/DotNetNuke.WebUtility/DotNetNuke.ClientAPI.dnn
  DNN Platform/DotNetNuke.Website.Deprecated/dnn_Website_Deprecated.dnn
  DNN Platform/Modules/CoreMessaging/CoreMessaging.dnn
  DNN Platform/Modules/DDRMenu/DDRMenu.dnn
  DNN Platform/Modules/DigitalAssets/dnn_DigitalAssets.dnn
  DNN Platform/Modules/DnnExportImport/dnn_SiteExportImport.dnn
  DNN Platform/Modules/Groups/SocialGroups.dnn
  DNN Platform/Modules/HTML/dnn_HTML.dnn
  DNN Platform/Modules/HtmlEditorManager/dnn_HtmlEditorManager.dnn
  DNN Platform/Modules/Journal/Journal.dnn
  DNN Platform/Modules/MemberDirectory/MemberDirectory.dnn
  DNN Platform/Modules/RazorHost/Manifest.dnn
  DNN Platform/Modules/RazorHost/RazorHost.dnn
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Facebook/Facebook_Auth.dnn
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Google/Google_Auth.dnn
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.LiveConnect/Live_Auth.dnn
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Twitter/Twitter_Auth.dnn
  DNN Platform/Providers/ClientCapabilityProviders/Provider.AspNetCCP/AspNetClientCapabilityProvider.dnn
  DNN Platform/Providers/FolderProviders/FolderProviders.dnn
  SolutionInfo.cs
  Website/DotNetNuke.Website.csproj
  Website/Providers/DataProviders/SqlDataProvider/09.02.02.SqlDataProvider
Labels: esw

#2175 DNN-21870: only clean user count cache during create user process.
  DNN Platform/Library/Entities/Users/UserController.cs
  Website/DesktopModules/Admin/Security/Register.ascx.cs
  Website/DesktopModules/Admin/Security/User.ascx.cs
Labels: esw
