Repository dnnsoftware/Dnn.Platform, pull requests merged in 2018-08, with the labels that each got.

#2199 DNN-22200: avoid insert duplicate key in race condition.
  DNN Platform/Library/Services/Search/Controllers/ModuleResultController.cs
Labels: esw

#2088 Installation resource files reviewed
  Website/Install/App_LocalResources/Installwizard.aspx.es-ES.resx
  Website/Install/App_LocalResources/UpgradeWizard.aspx.es-ES.resx
Labels: CLA on file, Community

#2204 CI: Enable the CreateSymbols and CreateSource build tasks.
  Build/BuildScripts/CreateCommunityPackages.build
  build.cake
Labels: Community

#2214 Documentation Updates
  .github/PULL_REQUEST_PROCESS.md
  .github/RELEASE_SCHEDULE.md
  .github/VERSIONING_POLICY.md
  CONTRIBUTING.md
Labels: Community, Noteworthy

#2198 DNN-21973: retry the search when there have exception throw during search process.
  DNN Platform/Library/Services/Search/Internals/Constants.cs
  DNN Platform/Library/Services/Search/Internals/LuceneControllerImpl.cs
Labels: esw

#2229 Adds Dnn 9.2.1 to the issue template
  .github/ISSUE_TEMPLATE.md
Labels: Community

#2212 DNN-22224: Registration form registering is failing when Use email as…
  Website/DesktopModules/Admin/Security/Register.ascx.cs
Labels: esw

#2209 DNN-22144: Email as username breaks login/Unauthorized message
  Website/DesktopModules/AuthenticationServices/DNN/Login.ascx.cs
Labels: esw

#2173 DNN-21290: Import/Export Circular Dependency in pages cause pages not…
  DNN Platform/Modules/DnnExportImport/Components/Services/PagesExportService.cs
Labels: esw

#2221 CI: Added Powershell script for publishing artifacts
  Build/BuildScripts/PublishArtifacts.ps1
Labels: Community

#2240 DNN-2236: change the word DotNetNuke to DNN in text elements in .resx…
  DNN Platform/Modules/HtmlEditorManager/App_LocalResources/ProviderConfiguration.ascx.resx
  DNN Platform/Providers/HtmlEditorProviders/RadEditorProvider/App_LocalResources/ProviderConfig.ascx.resx
  DNN Platform/Website/Templates/Default Website.template.en-US.resx
  Website/App_GlobalResources/GlobalResources.resx
  Website/DesktopModules/Admin/Authentication/App_LocalResources/Authentication.ascx.resx
  Website/DesktopModules/AuthenticationServices/DNN/App_LocalResources/Settings.ascx.resx
  Website/Install/App_LocalResources/Installwizard.aspx.resx
  Website/Install/App_LocalResources/UpgradeWizard.aspx.resx
Labels: Community

#2235 Add system.data to web.config file for VSTS unit tests to pass.
  DNN Platform/Tests/App.config
Labels: Community

#2237 Fixed issue where the browser covered the region and country dropdowns
  DNN Platform/Website/Templates/Blank Website.template
  DNN Platform/Website/Templates/Default Website.template
  Website/DesktopModules/Admin/Security/Profile.ascx
Labels: Community

#2222 Defect/dnn 21619
  DNN Platform/Library/Entities/Content/ContentController.cs
Labels: esw

#2230 DNN-22201: release write lock as well.
  DNN Platform/Library/Services/Search/Internals/LuceneControllerImpl.cs
Labels: esw
