Repository dnnsoftware/Dnn.Platform, pull requests merged in 2018-09, with the labels that each got.

#2293 DNN-23121: encode the value.
  DNN Platform/Library/Services/Exceptions/BasePortalException.cs
Labels: esw

#2278 Long running query causes DTU spikes to 100%
  Website/Providers/DataProviders/SqlDataProvider/09.03.00.SqlDataProvider
Labels: esw

#2297 Bugfix: avoid creation of portals using an existing home folder.
  DNN Platform/Library/Entities/Portals/PortalController.cs
  Website/App_GlobalResources/SharedResources.resx
Labels: esw

#2301 Customer defect: null ref expection raised after facebook login
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Facebook/Login.ascx.cs
Labels: esw

#1343 Dnn-8448: Support host-level OAuth authentication provider configuration
  DNN Platform/Library/Services/Authentication/AuthenticationController.cs
  DNN Platform/Library/Services/Authentication/OAuth/OAuthConfigBase.cs
  DNN Platform/Modules/CoreMessaging/Subscriptions.ascx.cs
  Website/App_GlobalResources/SharedResources.resx
  Website/DesktopModules/Admin/Authentication/Login.ascx.cs
  Website/DesktopModules/AuthenticationServices/DNN/Login.ascx.cs
  Website/admin/Skins/Login.ascx.cs
  Website/admin/Skins/User.ascx.cs
  Website/admin/Skins/UserAndLogin.ascx.cs
Labels: Awaiting Issue Triage, CLA on file, Community

#1902 DNN-8513: Create a new extension point in the DNN core at the Database Connection Level.
  DNN Platform/DotNetNuke.Web/Common/DotNetNukeHttpApplication.cs
  DNN Platform/Library/Data/DatabaseConnectionProvider.cs
  DNN Platform/Library/Data/PetaPoco/PetaPocoHelper.cs
  DNN Platform/Library/Data/SqlDataProvider.cs
  DNN Platform/Library/Data/SqlDatabaseConnectionProvider.cs
  DNN Platform/Library/DotNetNuke.Library.csproj
  DNN Platform/Tests/App.config
  DNN Platform/Tests/DotNetNuke.Tests.Data/DatabaseConnectionProviderTests.cs
  DNN Platform/Tests/DotNetNuke.Tests.Data/DotNetNuke.Tests.Data.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Data/Fakes/FakeDbConnectionProvider.cs
  DNN Platform/Website/Install/Config/09.03.00.config
  DNN_Platform.sln
  Website/development.config
  Website/release.config
Labels: Community

#1898 DNN-8374 adding locking functionality to the instance and individual sites
  DNN Platform/DotNetNuke.Web/InternalServices/ControlBarController.cs
  DNN Platform/Library/Entities/Host/Host.cs
  DNN Platform/Library/Entities/Portals/PortalSettings.cs
  DNN Platform/Library/UI/Modules/ModuleInstanceContext.cs
Labels: Awaiting Response, CLA on file, Community

#1897 DNN-8450 Allow override of prefixing the service name for OAuth providers
  DNN Platform/Library/Security/Membership/AspNetMembershipProvider.cs
  DNN Platform/Library/Security/Membership/MembershipProvider.cs
  DNN Platform/Library/Services/Authentication/OAuth/OAuthClientBase.cs
  DNN Platform/Library/Services/Authentication/UserAuthenticatedEventArgs.cs
  Website/DesktopModules/Admin/Authentication/Login.ascx.cs
Labels: Awaiting Response, CLA on file, Community

#2326 Updated Pull Request Documentation
  .github/PULL_REQUEST_PROCESS.md
Labels: Community
