Repository dnnsoftware/Dnn.Platform, pull requests merged in 2018-11, with the labels that each got.

#2418 Merge unsynced file updates that are required for the GA connector.
  DNN Platform/Connectors/GoogleAnalytics/Connector.css
  DNN Platform/Connectors/GoogleAnalytics/Scripts/connector.js
  DNN Platform/Connectors/GoogleAnalytics/connector.htm
Labels: Community

#2376 Close #2263: change support@dotnetnuke.com to support@dnnsoftware.com
  Build/Symbols/DotNetNuke_Symbols.dnn
  DNN Platform/Components/Microsoft.CodeDom.Providers.DotNetCompilerPlatform/releaseNotes.txt
  DNN Platform/Modules/DDRMenu/DDRMenu.dnn
  DNN Platform/Modules/DigitalAssets/ReleaseNotes.txt
  DNN Platform/Modules/DnnExportImport/ReleaseNotes.txt
Labels: Community

#2443 Unique build numbers on VSTS
  Build/cake/version.cake
Labels: DevOps

#2428 DNN-26206: find dnn node from dictionary to improve performance.
  DNN Platform/Library/UI/Navigation.cs
Labels: esw

#2456 Defect/dnn 26006
  DNN Platform/Library/Common/Globals.cs
Labels: esw

#2462 do not export modules which already deleted from page.
  DNN Platform/Modules/DnnExportImport/Components/Controllers/EntitiesController.cs
  DNN Platform/Modules/DnnExportImport/Components/Interfaces/IEntitiesController.cs
  DNN Platform/Modules/DnnExportImport/Components/Providers/DataProvider.cs
  DNN Platform/Modules/DnnExportImport/Components/Services/PagesExportService.cs
  DNN Platform/Modules/DnnExportImport/Providers/DataProviders/SqlDataProvider/09.03.00.SqlDataProvider
Labels: esw

#2484 Locked cache file caused site load failure
  DNN Platform/Library/Services/ModuleCache/FileProvider.cs
  DNN Platform/Library/Services/OutputCache/Providers/FileProvider.cs
Labels: esw

#2488 Account Login Module: Login Button Disabled
  Website/DesktopModules/AuthenticationServices/DNN/Login.ascx
Labels: esw

#2417 - Replacing http to https if SSL is setup
  Website/Default.aspx.cs
Labels: esw

#2482 Customer defect/dnn 26844
  DNN Platform/Library/Services/Search/Internals/SearchSecurityTrimmer.cs
  DNN Platform/Tests/DotNetNuke.Tests.Core/Controllers/Search/SearchControllerTests.cs
Labels: esw

#2493 CI: Added Cake.LongPath.Module
  tools/Modules/packages.config
Labels: DevOps
