Repository dnnsoftware/Dnn.Platform, pull requests merged in 2019-05, with the labels that each got.

#2751 Remove missing license from DotNetNuke.Web.Deprecated nuget package configuration
  Build/Tools/NuGet/DotNetNuke.Web.Deprecated.nuspec
Labels: DevOps

#2666 Increase version column in desktopmodules table to support revision number.
  DNN Platform/Library/Services/Installer/Installers/ModuleInstaller.cs
  Website/Providers/DataProviders/SqlDataProvider/09.04.00.SqlDataProvider
Labels: esw

#2758 Updated all C# projects to build using C# 7.0
  DNN Platform/Admin Modules/Dnn.Modules.Console/Dnn.Modules.Console.csproj
  DNN Platform/Admin Modules/Dnn.Modules.ModuleCreator/Dnn.Modules.ModuleCreator.csproj
  DNN Platform/Connectors/Azure/Dnn.AzureConnector.csproj
  DNN Platform/Connectors/GoogleAnalytics/Dnn.GoogleAnalyticsConnector.csproj
  DNN Platform/Controls/CountryListBox/CountryListBox.csproj
  DNN Platform/Dnn.AuthServices.Jwt/Dnn.AuthServices.Jwt.csproj
  DNN Platform/DotNetNuke.Instrumentation/DotNetNuke.Instrumentation.csproj
  DNN Platform/DotNetNuke.Log4net/DotNetNuke.Log4Net.csproj
  DNN Platform/DotNetNuke.Web.Client/DotNetNuke.Web.Client.csproj
  DNN Platform/DotNetNuke.Web.Deprecated/DotNetNuke.Web.Deprecated.csproj
  DNN Platform/DotNetNuke.Web.Mvc/DotNetNuke.Web.Mvc.csproj
  DNN Platform/DotNetNuke.Web.Razor/DotNetNuke.Web.Razor.csproj
  DNN Platform/DotNetNuke.Web/DotNetNuke.Web.csproj
  DNN Platform/DotNetNuke.Website.Deprecated/DotNetNuke.Website.Deprecated.csproj
  DNN Platform/HttpModules/DotNetNuke.HttpModules.csproj
  DNN Platform/Library/DotNetNuke.Library.csproj
  DNN Platform/Modules/CoreMessaging/DotNetNuke.Modules.CoreMessaging.csproj
  DNN Platform/Modules/DDRMenu/DotNetNuke.Modules.DDRMenu.csproj
  DNN Platform/Modules/DigitalAssets/DotNetNuke.Modules.DigitalAssets.csproj
  DNN Platform/Modules/DnnExportImport/DnnExportImport.csproj
  DNN Platform/Modules/DnnExportImportLibrary/DnnExportImportLibrary.csproj
  DNN Platform/Modules/Groups/DotNetNuke.Modules.Groups.csproj
  DNN Platform/Modules/HTML/DotNetNuke.Modules.Html.csproj
  DNN Platform/Modules/HtmlEditorManager/DotNetNuke.Modules.HtmlEditorManager.csproj
  DNN Platform/Modules/Journal/DotNetNuke.Modules.Journal.csproj
  DNN Platform/Modules/MemberDirectory/DotNetNuke.Modules.MemberDirectory.csproj
  DNN Platform/Modules/RazorHost/DotNetNuke.Modules.RazorHost.csproj
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Facebook/DotNetNuke.Authentication.Facebook.csproj
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Google/DotNetNuke.Authentication.Google.csproj
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.LiveConnect/DotNetNuke.Authentication.LiveConnect.csproj
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Twitter/DotNetNuke.Authentication.Twitter.csproj
  DNN Platform/Providers/ClientCapabilityProviders/Provider.AspNetCCP/DotNetNuke.Providers.AspNetCCP.csproj
  DNN Platform/Providers/FolderProviders/DotNetNuke.Providers.FolderProviders.csproj
  DNN Platform/Skins/Xcillion/DotNetNuke.Skins.Xcillion.csproj
  DNN Platform/Syndication/DotNetNuke.Syndication.csproj
  DNN Platform/Tests/DNN.Integration.Test.Framework/DNN.Integration.Test.Framework.csproj
  DNN Platform/Tests/DotNetNuke.Tests.AspNetCCP/DotNetNuke.Tests.AspNetCCP.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Authentication/DotNetNuke.Tests.Authentication.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Content/DotNetNuke.Tests.Content.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Core/DotNetNuke.Tests.Core.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Data/DotNetNuke.Tests.Data.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Integration/DotNetNuke.Tests.Integration.csproj
  DNN Platform/Tests/DotNetNuke.Tests.UI/DotNetNuke.Tests.UI.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Urls/DotNetNuke.Tests.Urls.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Utilities/DotNetNuke.Tests.Utilities.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Web.Mvc/DotNetNuke.Tests.Web.Mvc.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Web/DotNetNuke.Tests.Web.csproj
  Website/DotNetNuke.Website.csproj
Labels: noteworthy

#2763 Remove GetAzureCompactScript from SqlDataProvider
  DNN Platform/Library/Data/SqlDataProvider.cs
Labels: noteworthy

#2509 Force user logout after password changed in other place.
  DNN Platform/HttpModules/Membership/MembershipModule.cs
  Website/DesktopModules/Admin/Security/EditUser.ascx.cs
  Website/Install/DotNetNuke.install.config.resources
Labels: esw, noteworthy

#2797 Addition of [Obsolete] Attribute to Users Online
  DNN Platform/HttpModules/Users Online/UsersOnlineModule.cs
  DNN Platform/Library/Data/DataProvider.cs
  DNN Platform/Library/Entities/Host/Host.cs
  DNN Platform/Library/Entities/Users/Membership/UserMembership.cs
  DNN Platform/Library/Entities/Users/UserController.cs
  DNN Platform/Library/Entities/Users/Users Online/AnonymousUserInfo.cs
  DNN Platform/Library/Entities/Users/Users Online/BaseUserInfo.cs
  DNN Platform/Library/Entities/Users/Users Online/OnlineUserInfo.cs
  DNN Platform/Library/Entities/Users/Users Online/PurgeUsersOnline.cs
  DNN Platform/Library/Entities/Users/Users Online/UserOnlineController.cs
  DNN Platform/Library/Security/Membership/AspNetMembershipProvider.cs
  DNN Platform/Library/Security/Membership/MembershipProvider.cs
  DNN Platform/Tests/App.config
Labels: noteworthy

#2804 Make Default Module Action Menu Configurable
  DNN Platform/Library/Entities/Portals/PortalSettings.cs
  DNN Platform/Library/Entities/Portals/PortalSettingsController.cs
  DNN Platform/Library/UI/Containers/Container.cs
Labels: noteworthy

#2810 Fix for #2809 and #2760 and #2778
  DNN Platform/Library/Common/Globals.cs
  Website/Default.aspx
Labels: bug

#2811 Amended d06a05289d3372dfaf7205956ab01929fbf61ebb
  Website/Resources/Shared/scripts/TreeView/dnn.DynamicTreeView.js
Labels: bug, esw

#2818 Updating DevOps badge URL
  README.md
Labels: DevOps

#2815 Bump version to v10.0.0
  Website/Providers/DataProviders/SqlDataProvider/10.00.00.SqlDataProvider
  gitversion.yml
Labels: DevOps

#2817 Update PetaPoco to Nuget Reference and fix TableName attribute bug
  DNN Platform/Components/PetaPoco/bin/PetaPoco.dll
  DNN Platform/Library/Data/PetaPoco/PetaPocoMapper.cs
  DNN Platform/Library/DotNetNuke.Library.csproj
  DNN Platform/Library/Module.build
  DNN Platform/Library/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Data/DotNetNuke.Tests.Data.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Integration/DotNetNuke.Tests.Integration.csproj
Labels: DevOps
