Repository dnnsoftware/Dnn.Platform, pull requests merged in 2019-10, with the labels that each got.

#3072 Addition of configuration for StaleBot
  .github/stale.yml
Labels: noteworthy

#3094 Remove reference to empty fs npm package
  Dnn.AdminExperience/Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/Users.Web/src/_exportables/package.json
  Dnn.AdminExperience/yarn.lock
Labels: Enhancement

#3032 Updates .Net 4.7.2 warning for NL and DE languages
  Website/Install/App_LocalResources/Installwizard.aspx.de-DE.resx
  Website/Install/App_LocalResources/Installwizard.aspx.nl-NL.resx
Labels: Enhancement

#3024 Permissions for default folders
  DNN Platform/Website/Templates/Blank Website.template
Labels: bug

#3167 Fixes errors with previous build scripts following PB merge
  DNN_Platform.sln
  Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/Dnn.EditBar.UI.csproj
  Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/Module.build
  Dnn.AdminExperience/Extensions/Content/Dnn.PersonaBar.Extensions/Module.build
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/Module.build
Labels: DevOps

#3165 Updates issue templates and build docs
  .github/BUILD.md
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: chore

#3171 Documentation action cleanup
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/scripts/serversummary.js
Labels: Enhancement

#3173 Update bug report issue template
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: Enhancement

#3152 Remove Thread Cancellation from OAuthClientBase Implementation
  DNN Platform/Library/Services/Authentication/OAuth/OAuthClientBase.cs
Labels: bug

#3175 Update "help and other questions" issue template
  .github/ISSUE_TEMPLATE/help-and-other-questions.md
Labels: Enhancement

#3177 Update "request for comments" issue template
  .github/ISSUE_TEMPLATE/request-for-comments.md
Labels: Enhancement

#3198 Make white-space visible in log viewer
  Dnn.AdminExperience/Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/Servers.Web/src/components/Tabs/tabs.less
Labels: bug

#2182 JWT Audience
  DNN Platform/Dnn.AuthServices.Jwt/Components/Common/Controllers/JwtController.cs
  DNN Platform/Dnn.AuthServices.Jwt/Components/Entity/LoginData.cs
Labels: Community, noteworthy

#3204 Move email above username field.
  Website/controls/user.ascx
Labels: Enhancement

#2870 Sitemap.aspx does not produce alternate links in multilingual website
  DNN Platform/Library/Services/Sitemap/SitemapBuilder.cs
Labels: Enhancement, Needs testing

#2887 Closes Issue#2885: Allow multiple DesktopModules in a single package
  DNN Platform/Library/Entities/Modules/DesktopModuleInfo.cs
  DNN Platform/Library/Services/Installer/Installers/ModuleInstaller.cs
Labels: Enhancement, Needs testing

#3033 Portal settings setters should not persist to DB
  DNN Platform/Library/Entities/Portals/PortalSettings.cs
Labels: bug

#2625 Username is changed to email address in the user profile
  DNN Platform/Website/DesktopModules/AuthenticationServices/DNN/Login.ascx.cs
Labels: Enhancement, esw

#3217 Improve Stale bot implementation
  .github/stale.yml
Labels: Enhancement
