Repository dnnsoftware/Dnn.Platform, pull requests merged in 2019-09, with the labels that each got.

#2998 Fixes DDRMenu Razor Bug with Dependency Injection
  DNN Platform/DotNetNuke.Web.Razor/DotNetNukeWebPage.cs
Labels: bug

#2988 DNN-32726: avoid null reference exception when call to Globals.LinkClick method.
  DNN Platform/Library/Services/FileSystem/Providers/StandardFolderProvider.cs
Labels: bug

#2970 DNN-30542 - Asset Manager activity wheel constantly spins
  DNN Platform/Modules/DigitalAssets/ClientScripts/dnn.DigitalAssets.js
Labels: bug

#2973 Add missing HTML encoding to ExceptionInfo
  DNN Platform/Library/Services/Exceptions/ExceptionInfo.cs
Labels: Enhancement

#2979 Fix potential XML namespace bug
  DNN Platform/Library/Services/Installer/XmlMerge.cs
  DNN Platform/Tests/DotNetNuke.Tests.Integration/DotNetNuke.Tests.Integration.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Integration/Services/Installer/MergeFiles/ShouldPreserveEmptyNamespaceOnSaveMerge.xml
  DNN Platform/Tests/DotNetNuke.Tests.Integration/Services/Installer/MergeFiles/ShouldPreserveEmptyNamespaceOnSaveTarget.xml
  DNN Platform/Tests/DotNetNuke.Tests.Integration/Services/Installer/XmlMergeTests.cs
  DNN Platform/Website/Install/Config/08.00.00.22.config
  DNN Platform/Website/Install/Config/08.00.00.30.config
Labels: bug

#2980 Fix invalid binding redirects when upgrading to DNN 9.4.0
  DNN Platform/Library/Services/Upgrade/Upgrade.cs
Labels: bug

#2996 Fix exception loading JS library
  DNN Platform/Library/Framework/JavaScriptLibraries/IJavaScriptLibraryController.cs
  DNN Platform/Library/Framework/JavaScriptLibraries/JavaScript.cs
  DNN Platform/Library/Framework/JavaScriptLibraries/JavaScriptLibraryController.cs
Labels: bug, noteworthy

#3000 enable jquery browser detection.
  Website/Resources/Shared/components/FileUpload/dnn.FileUpload.js
Labels: bug

#3001 fix several bugs around export/import area.
  DNN Platform/Modules/DnnExportImport/Components/Common/CompressionUtil.cs
  DNN Platform/Modules/DnnExportImport/Components/Services/PagesExportService.cs
  DNN Platform/Modules/DnnExportImport/Components/Services/ThemesExportService.cs
Labels: bug

#3006 DNN-33314: import portal languages correctly.
  DNN Platform/Modules/DnnExportImport/Components/Services/PortalExportService.cs
Labels: bug

#3022 Fix missing modules after import site
  DNN Platform/Modules/DnnExportImport/Components/Services/PagesExportService.cs
Labels: bug

#3025 Warns before install/upgrade about needing .Net Framework 4.7.2
  DNN Platform/Library/Services/Upgrade/Internals/Steps/IISVerificationStep.cs
  Website/Install/App_LocalResources/Installwizard.aspx.de-DE.resx
  Website/Install/App_LocalResources/Installwizard.aspx.es-ES.resx
  Website/Install/App_LocalResources/Installwizard.aspx.fr-FR.resx
  Website/Install/App_LocalResources/Installwizard.aspx.it-IT.resx
  Website/Install/App_LocalResources/Installwizard.aspx.nl-NL.resx
  Website/Install/App_LocalResources/Installwizard.aspx.resx
  Website/Install/UpgradeWizard.aspx.cs
Labels: Enhancement

#3003 Use standalone version of Selectize script
  DNN Platform/JavaScript Libraries/Selectize/Selectize.dnn
  DNN Platform/JavaScript Libraries/Selectize/selectize.min.js
Labels: bug
