Repository dnnsoftware/Dnn.Platform, pull requests merged in 2019-11, with the labels that each got.

#3242 Improve querystring parse
  DNN Platform/Modules/DigitalAssets/FileProperties.ascx.cs
Labels: Enhancement

#3282 Fixes an upgrade issue that affects 9.4.1 => 9.4.2 upgrades
  DNN Platform/Components/Telerik/DotNetNuke.Telerik.Web.dnn
Labels: bug

#3266 Improve Stale bot messaging
  .github/stale.yml
Labels: Enhancement

#3256 Moves Remember Login above Login Button: referenced in issue #2471 #3255
  DNN Platform/Website/DesktopModules/AuthenticationServices/DNN/Login.ascx
Labels: Enhancement

#3249 DNN-32474 - Not able to delete custom roles if their associated social group folder isn't empty
  DNN Platform/Library/Services/FileSystem/FolderManager.cs
  DNN Platform/Tests/DotNetNuke.Tests.Core/Providers/Folder/FolderManagerTests.cs
Labels: bug

#3244 Move Country Above Region in UserProfile.cs
  DNN Platform/Library/Entities/Users/Profile/UserProfile.cs
Labels: chore

#3306 Move Email Above Username in User.ascx #3305
  DNN Platform/Website/controls/user.ascx
Labels: Enhancement

#3304 Fix NuGet warning NU5048
  Build/Tools/NuGet/Dnn.PersonaBar.Library.nuspec
  Build/Tools/NuGet/DotNetNuke.Abstractions.nuspec
  Build/Tools/NuGet/DotNetNuke.Bundle.nuspec
  Build/Tools/NuGet/DotNetNuke.Core.nuspec
  Build/Tools/NuGet/DotNetNuke.DependencyInjection.nuspec
  Build/Tools/NuGet/DotNetNuke.Instrumentation.nuspec
  Build/Tools/NuGet/DotNetNuke.Providers.FolderProviders.nuspec
  Build/Tools/NuGet/DotNetNuke.SiteExportImport.nuspec
  Build/Tools/NuGet/DotNetNuke.Web.Client.nuspec
  Build/Tools/NuGet/DotNetNuke.Web.Deprecated.nuspec
  Build/Tools/NuGet/DotNetNuke.Web.Mvc.nuspec
  Build/Tools/NuGet/DotNetNuke.Web.nuspec
  Build/Tools/NuGet/DotNetNuke.WebApi.nuspec
  Build/Tools/NuGet/logo-for-nuget.png
  DNN Platform/Tests/DNN.Integration.Test.Framework/DNN.Integration.Test.Framework.nuspec
  Dnn.AdminExperience/EditBar/Dnn.EditBar.Library/Dnn.EditBar.Library.nuspec
Labels: Enhancement

#3307 Word-Break added to Journal P
  DNN Platform/Modules/Journal/module.css
Labels: Enhancement

#2898 Fix ModuleSettings > Added to Pages grid, pager wasn't working Issue #2897
  DNN Platform/Website/Portals/_default/Skins/_default/WebControlSkin/Default/GridView.Default.css
  DNN Platform/Website/admin/Modules/Modulesettings.ascx
  DNN Platform/Website/admin/Modules/Modulesettings.ascx.cs
Labels: bug

#3316 Allow only alphanumeric characters to be used when forming url from name
  Dnn.AdminExperience/Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/Sites.Web/src/components/CreatePortal/index.jsx
Labels: bug

#3232 Reduce Warning errors - Warnings without Code Type
  DNN Platform/Tests/DotNetNuke.Tests.Core/DotNetNuke.Tests.Core.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Urls/DotNetNuke.Tests.Urls.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Utilities/DotNetNuke.Tests.Utilities.csproj
  Dnn.AdminExperience/EditBar/Dnn.EditBar.Library/Dnn.EditBar.Library.csproj
  Dnn.AdminExperience/EditBar/Dnn.EditBar.Library/packages.config
  Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/app.config
Labels: chore

#3314 Ensure UpdateDnnManifests doesn't run for building dev site
  Build/Cake/thirdparty.cake
Labels: DevOps

#3315 Reload page when the code tells you to
  Dnn.AdminExperience/Extensions/Content/Dnn.PersonaBar.Extensions/WebApps/Servers.Web/src/components/App.jsx
Labels: Enhancement

#3322 Google Analytics TrackingID is stored in lowercase #3318
  DNN Platform/Connectors/GoogleAnalytics/GoogleAnalyticsConnector.cs
Labels: bug

#3325 Updates checksums for Dnn 9.4.3
  Dnn.AdminExperience/Extensions/Content/Dnn.PersonaBar.Extensions/Components/Security/Resources/sums.resources
Labels: bug

#3356 Streamline issue templates to focus on bugs and enhancements
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/enhancement-request.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/help-and-other-questions.md
  .github/ISSUE_TEMPLATE/request-for-comments.md
Labels: Enhancement, noteworthy
