Repository dnnsoftware/Dnn.Platform, pull requests merged in 2019-02, with the labels that each got.

#2578 After export with Content Localization site language flags disappears from pages
  DNN Platform/Modules/DnnExportImport/Components/Services/PagesExportService.cs
Labels: bug

#2590 Update development branch with fixes from 9.3.0-rc2
  DNN Platform/Library/Services/Upgrade/Upgrade.cs
  DNN Platform/Modules/DnnExportImport/Components/Services/PagesExportService.cs
  DNN Platform/Skins/Xcillion/Skin/skin.css
Labels: DevOps

#2562 Fixed parallel build
  .nuget/NuGet.Config
  DNN Platform/Modules/CoreMessaging/DotNetNuke.Modules.CoreMessaging.csproj
  DNN Platform/Modules/DigitalAssets/DotNetNuke.Modules.DigitalAssets.csproj
  DNN Platform/Modules/Groups/DotNetNuke.Modules.Groups.csproj
  DNN Platform/Modules/HTML/DotNetNuke.Modules.Html.csproj
  DNN Platform/Modules/HtmlEditorManager/DotNetNuke.Modules.HtmlEditorManager.csproj
  DNN Platform/Modules/Journal/DotNetNuke.Modules.Journal.csproj
  DNN Platform/Modules/MemberDirectory/DotNetNuke.Modules.MemberDirectory.csproj
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Facebook/DotNetNuke.Authentication.Facebook.csproj
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Google/DotNetNuke.Authentication.Google.csproj
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.LiveConnect/DotNetNuke.Authentication.LiveConnect.csproj
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Twitter/DotNetNuke.Authentication.Twitter.csproj
  DNN Platform/Providers/HtmlEditorProviders/RadEditorProvider/DotNetNuke.RadEditorProvider.csproj
  DNN Platform/Skins/Xcillion/DotNetNuke.Skins.Xcillion.csproj
  DNN Platform/Tests/DotNetNuke.Tests.AspNetCCP/DotNetNuke.Tests.AspNetCCP.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Authentication/DotNetNuke.Tests.Authentication.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Content/DotNetNuke.Tests.Content.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Core/DotNetNuke.Tests.Core.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Integration/DotNetNuke.Tests.Integration.csproj
  DNN Platform/Tests/DotNetNuke.Tests.UI/DotNetNuke.Tests.UI.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Urls/DotNetNuke.Tests.Urls.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Utilities/DotNetNuke.Tests.Utilities.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Web/DotNetNuke.Tests.Web.csproj
  DNN_Platform.sln
Labels: DevOps

#2598 Inclusion of NDepend logo on the readme.
  .github/images/PoweredByNDepend.png
  README.md
Labels: Community, DevOps
