Repository dnnsoftware/Dnn.Platform, pull requests merged in 2020-11, with the labels that each got.

#4255 Feature/add google tagmanager connector
  DNN Platform/Connectors/GoogleTagManager/App_LocalResources/SharedResources.resx
  DNN Platform/Connectors/GoogleTagManager/Connector.css
  DNN Platform/Connectors/GoogleTagManager/Constants.cs
  DNN Platform/Connectors/GoogleTagManager/Dnn.GoogleTagManagerConnector.csproj
  DNN Platform/Connectors/GoogleTagManager/GoogleTagManager.config
  DNN Platform/Connectors/GoogleTagManager/GoogleTagManagerConnector.cs
  DNN Platform/Connectors/GoogleTagManager/GoogleTagManagerConnector.dnn
  DNN Platform/Connectors/GoogleTagManager/GoogleTagManagerController.cs
  DNN Platform/Connectors/GoogleTagManager/GoogleTagManagerEngine.cs
  DNN Platform/Connectors/GoogleTagManager/Images/GoogleTagManager_32X32_Standard.png
  DNN Platform/Connectors/GoogleTagManager/License.txt
  DNN Platform/Connectors/GoogleTagManager/Module.build
  DNN Platform/Connectors/GoogleTagManager/ReleaseNotes.txt
  DNN Platform/Connectors/GoogleTagManager/Scripts/connector.js
  DNN Platform/Connectors/GoogleTagManager/connector.htm
  DNN Platform/Connectors/GoogleTagManager/packages.config
  DNN_Platform.sln
Labels: Type: Feature

#4276 Installs JWT provider by default
  DNN Platform/Dnn.AuthServices.Jwt/Auth/JwtAuthMessageHandler.cs
  DNN Platform/Dnn.AuthServices.Jwt/Components/Common/Controllers/IJwtController.cs
  DNN Platform/Dnn.AuthServices.Jwt/Components/Common/Controllers/JwtController.cs
  DNN Platform/Dnn.AuthServices.Jwt/Components/Entity/LoginData.cs
  DNN Platform/Dnn.AuthServices.Jwt/Components/Entity/LoginResultData.cs
  DNN Platform/Dnn.AuthServices.Jwt/Components/Entity/PersistedToken.cs
  DNN Platform/Dnn.AuthServices.Jwt/Components/Entity/RenewalDto.cs
  DNN Platform/Dnn.AuthServices.Jwt/Components/Schedule/PurgeExpiredTokensTask.cs
  DNN Platform/Dnn.AuthServices.Jwt/Data/DataService.cs
  DNN Platform/Dnn.AuthServices.Jwt/Data/IDataService.cs
  DNN Platform/Dnn.AuthServices.Jwt/Dnn.AuthServices.Jwt.csproj
  DNN Platform/Dnn.AuthServices.Jwt/Library.build
  DNN Platform/Dnn.AuthServices.Jwt/Services/MobileController.cs
  DNN Platform/Dnn.AuthServices.Jwt/Services/ServiceRouteMapper.cs
  DNN Platform/DotNetNuke.Web/Api/Auth/AuthMessageHandlerBase.cs
Labels: Type: Enhancement

#4277 Upgrade optional packages when they've already been installed
  DNN Platform/Dnn.AuthServices.Jwt/Library.build
  DNN Platform/Library/Services/Upgrade/Upgrade.cs
Labels: Area: Platform > Library, Type: Enhancement

#4280 Prevents JWT upgrade to change existing config
  DNN Platform/Dnn.AuthServices.Jwt/Dnn.Jwt.dnn
Labels: Area: Platform > Dnn.AuthServices.Jwt, Type: Bug

#4281 Implement EnablePopups switch in portal settings PB module
  Dnn.AdminExperience/ClientSide/SiteSettings.Web/src/components/moreSettings/index.jsx
  Dnn.AdminExperience/ClientSide/SiteSettings.Web/src/components/moreSettings/style.less
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/DTO/SiteSettings/UpdateOtherSettingsRequest.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/SiteSettingsController.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.SiteSettings/App_LocalResources/SiteSettings.resx
Labels: Area: AE > PersonaBar Ext > SiteSettings.Web, Type: Enhancement

#4283 Updates develop with the latest changes from 9.8.0 rc
  .github/images/PoweredByNDepend.png
  DNN Platform/Connectors/GoogleTagManager/Images/GoogleTagManager_32X32_Standard.png
  DNN Platform/Dnn.AuthServices.Jwt/Auth/JwtAuthMessageHandler.cs
  DNN Platform/Dnn.AuthServices.Jwt/Components/Common/Controllers/IJwtController.cs
  DNN Platform/Dnn.AuthServices.Jwt/Components/Common/Controllers/JwtController.cs
  DNN Platform/Dnn.AuthServices.Jwt/Components/Entity/LoginData.cs
  DNN Platform/Dnn.AuthServices.Jwt/Components/Entity/LoginResultData.cs
  DNN Platform/Dnn.AuthServices.Jwt/Components/Entity/PersistedToken.cs
  DNN Platform/Dnn.AuthServices.Jwt/Components/Entity/RenewalDto.cs
  DNN Platform/Dnn.AuthServices.Jwt/Components/Schedule/PurgeExpiredTokensTask.cs
  DNN Platform/Dnn.AuthServices.Jwt/Data/DataService.cs
  DNN Platform/Dnn.AuthServices.Jwt/Data/IDataService.cs
  DNN Platform/Dnn.AuthServices.Jwt/Dnn.AuthServices.Jwt.csproj
  DNN Platform/Dnn.AuthServices.Jwt/Dnn.Jwt.dnn
  DNN Platform/Dnn.AuthServices.Jwt/Services/MobileController.cs
  DNN Platform/Dnn.AuthServices.Jwt/Services/ServiceRouteMapper.cs
  DNN Platform/DotNetNuke.Web/Api/Auth/AuthMessageHandlerBase.cs
  DNN Platform/HttpModules/Localization/LocalizationModule.cs
  DNN Platform/HttpModules/Membership/MembershipModule.cs
  DNN Platform/Library/Services/Localization/Localization.cs
  DNN Platform/Library/Services/Upgrade/Upgrade.cs
  DNN Platform/Website/development.config
  DNN Platform/Website/release.config
Labels: Type: Maintenance

#4284 Fixed an issue where new users would have no preferred locale.
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Users/RegisterController.cs
Labels: Type: Bug

#4285 Fixed an issue where all emails where missing the body
  DNN Platform/Library/Services/Mail/CoreMailProvider.cs
Labels: Type: Bug

#4279 do not cache output if page is redirected
  DNN Platform/HttpModules/OutputCaching/OutputCacheModule.cs
  DNN Platform/Library/Services/OutputCache/OutputCacheResponseFilter.cs
Labels: Type: Bug

#4286 Add two more settings to the personabar
  Dnn.AdminExperience/ClientSide/SiteSettings.Web/src/components/moreSettings/index.jsx
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/DTO/SiteSettings/UpdateOtherSettingsRequest.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/SiteSettingsController.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.SiteSettings/App_LocalResources/SiteSettings.resx
Labels: Area: AE > PersonaBar Ext > SiteSettings.Web, Type: Enhancement

#4290 Merge latest changes from 9.8.0 into develop
  DNN Platform/Library/Services/Mail/CoreMailProvider.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Users/RegisterController.cs
Labels: Type: Maintenance

#4259 Remove deprecation for some DataProvider methods
  DNN Platform/Library/Data/DataProvider.cs
Labels: Type: Maintenance

#4258 Fix data reader not getting disposed
  DNN Platform/Library/Data/SqlDataProvider.cs
Labels: Type: Bug

#4257 Fixes invalid extension error message for 0 errors
  Dnn.AdminExperience/ClientSide/Extensions.Web/src/components/InstallExtensionModal/FileUpload/index.jsx
Labels: Type: Bug

#4287 Mark EnableSkinWidgets as obsolete and remove from serialization
  DNN Platform/DotNetNuke.Abstractions/Portals/IPortalSettings.cs
  DNN Platform/Library/Entities/Portals/PortalSettings.cs
  DNN Platform/Library/Entities/Portals/PortalSettingsController.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Sites/SitesController.cs
Labels: Area: Platform > Library, Area: Platform > Skins, Type: Enhancement

#4301 Issue-4300 - Edit Account - New Password field validation lines are not correct
  DNN Platform/Website/Resources/Shared/scripts/dnn.PasswordStrength.js
Labels: Type: Bug

#4302 Fix data provider always failing
  DNN Platform/Library/Data/SqlDataProvider.cs
Labels: Type: Bug

#4312 Ensure properties in DTO objects use backing fields
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Users/Dto/UserBasicDto.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Users/Dto/UserDetailDto.cs
Labels: Area: AE > PersonaBar Ext > Users.Web, Area: Localization, Type: Bug

#4315 Update bug report template after 9.8.0 release
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: Type: Documentation

#4326 Fix build error
  DNN Platform/DotNetNuke.ModulePipeline/DotNetNuke.ModulePipeline.csproj
Labels: Type: Build/Release

#4249 Fix DevOps build badge
  README.md
Labels: Type: Build/Release, Type: Documentation, Type: Maintenance

#4250 Fix some integration tests
  DNN Platform/Library/Properties/AssemblyInfo.cs
  DNN Platform/Tests/DotNetNuke.Tests.Data/DotNetNuke.Tests.Data.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Data/RepositoryBaseTests.cs
  DNN Platform/Tests/DotNetNuke.Tests.Data/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Urls/DotNetNuke.Tests.Urls.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Urls/ExtensionUrlProviderControllerTests.cs
  DNN Platform/Tests/DotNetNuke.Tests.Urls/packages.config
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.Security.Tests/Dnn.PersonaBar.Security.Tests.csproj
Labels: Type: Maintenance

#4321 Fixes AddContentItem Audit Trail for CreatedByUserId & LastModifiedByUserId
  DNN Platform/Library/Entities/Content/ContentController.cs
  DNN Platform/Tests/DotNetNuke.Tests.Content/ContentControllerTests.cs
Labels: Type: Bug

#4325 remove dragover state from element when dragged BETWEEN pages
  Dnn.AdminExperience/ClientSide/Pages.Web/src/components/dnn-persona-bar-page-treeview/src/PersonaBarPageTreeview.jsx
Labels: Type: Bug

#4327 Use YAML for build pipeline
  README.md
  azure-pipelines.yml
Labels: Type: Build/Release

#4330 Trying to adjust included branches for azure pipeline
  azure-pipelines.yml
Labels: Type: Build/Release

#4228 Changed WebConfigurationManager for ConfigurationManager
  DNN Platform/Library/Common/Utilities/Config.cs
Labels: Noteworthy, Type: Enhancement

#4337 Issue-4336 - Umlaut characters in URL cause module setting error
  DNN Platform/Library/Entities/Urls/AdvancedUrlRewriter.cs
  DNN Platform/Tests/DotNetNuke.Tests.Core/DotNetNuke.Tests.Core.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Core/Entities/Urls/AdvancedUrlRewriterTests.cs
Labels: Area: Localization, Type: Bug

#4339 Update BUILD documentation for Cake v1 changes
  .github/BUILD.md
Labels: Type: Documentation

#4322 Use latest Cake.Frosting
  .gitignore
  Build/Build.csproj
  Build/Build.sln
  Build/Cake/Extensions.cs
  Build/Cake/build.cs
  Build/Cake/ci.cake
  Build/Cake/ci.cs
  Build/Cake/compiling.cake
  Build/Cake/compiling.cs
  Build/Cake/create-database.cake
  Build/Cake/create-database.cs
  Build/Cake/database.cake
  Build/Cake/database.cs
  Build/Cake/devsite.cake
  Build/Cake/devsite.cs
  Build/Cake/nuget.cake
  Build/Cake/nuget.cs
  Build/Cake/packaging.cake
  Build/Cake/packaging.cs
  Build/Cake/settings.cake
  Build/Cake/settings.cs
  Build/Cake/testing.cake
  Build/Cake/testing.cs
  Build/Cake/thirdparty.cake
  Build/Cake/thirdparty.cs
  Build/Cake/unit-tests.cake
  Build/Cake/unit-tests.cs
  Build/Cake/version.cake
  Build/Cake/version.cs
  Build/Program.cs
  azure-pipelines.yml
  build.config
  build.ps1
  build.sh
Labels: Type: Build/Release
