Repository dnnsoftware/Dnn.Platform, pull requests merged in 2020-08, with the labels that each got.

#3952 Reset invalidation link on email change
  DNN Platform/Website/DesktopModules/Admin/Security/EditUser.ascx.cs
Labels: Type: Bug

#3962 Add better wildcard file search support
  DNN Platform/Library/Services/FileSystem/FolderManager.cs
  DNN Platform/Modules/ResourceManager/Components/SearchController.cs
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/less/components.less
Labels: Type: Bug

#3963 Optimize WildcardToRegex for file search
  DNN Platform/Library/Services/FileSystem/FolderManager.cs
Labels: Type: Enhancement, Type: Feature

#3958 Merge fixes from release/9.7.0 to develop
  .github/ISSUE_TEMPLATE/bug-report.md
  Build/Symbols/DotNetNuke_Symbols.dnn
  DNN Platform/Admin Modules/Dnn.Modules.Console/dnn_Console.dnn
  DNN Platform/Admin Modules/Dnn.Modules.ModuleCreator/dnn_ModuleCreator.dnn
  DNN Platform/Components/Telerik/DotNetNuke.Telerik.Web.dnn
  DNN Platform/Connectors/Azure/AzureConnector.dnn
  DNN Platform/Connectors/GoogleAnalytics/GoogleAnalyticsConnector.dnn
  DNN Platform/Dnn.AuthServices.Jwt/Dnn.Jwt.dnn
  DNN Platform/DotNetNuke.Web.Deprecated/dnn_Web_Deprecated.dnn
  DNN Platform/DotNetNuke.WebUtility/DotNetNuke.ClientAPI.dnn
  DNN Platform/DotNetNuke.Website.Deprecated/dnn_Website_Deprecated.dnn
  DNN Platform/Modules/CoreMessaging/CoreMessaging.dnn
  DNN Platform/Modules/DDRMenu/DDRMenu.dnn
  DNN Platform/Modules/DigitalAssets/dnn_DigitalAssets.dnn
  DNN Platform/Modules/DnnExportImport/dnn_SiteExportImport.dnn
  DNN Platform/Modules/Groups/SocialGroups.dnn
  DNN Platform/Modules/HTML/dnn_HTML.dnn
  DNN Platform/Modules/HtmlEditorManager/dnn_HtmlEditorManager.dnn
  DNN Platform/Modules/Journal/Journal.dnn
  DNN Platform/Modules/MemberDirectory/MemberDirectory.dnn
  DNN Platform/Modules/RazorHost/Manifest.dnn
  DNN Platform/Modules/RazorHost/RazorHost.dnn
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Facebook/Facebook_Auth.dnn
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Google/Google_Auth.dnn
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.LiveConnect/Live_Auth.dnn
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Twitter/Twitter_Auth.dnn
  DNN Platform/Providers/CachingProviders/DotNetNuke.Providers.Caching.SimpleWebFarmCachingProvider/SimpleWebFarmCachingProvider.dnn
  DNN Platform/Providers/ClientCapabilityProviders/Provider.AspNetCCP/AspNetClientCapabilityProvider.dnn
  DNN Platform/Providers/FolderProviders/FolderProviders.dnn
  DNN Platform/Skins/Xcillion/DNN_Skin_Xcillion.dnn
  DNN Platform/Website/DesktopModules/Admin/Security/EditUser.ascx.cs
  Dnn.AdminExperience/ClientSide/AdminLogs.Web/package.json
  Dnn.AdminExperience/ClientSide/Bundle.Web/package.json
  Dnn.AdminExperience/ClientSide/Dnn.React.Common/package.json
  Dnn.AdminExperience/ClientSide/Extensions.Web/package.json
  Dnn.AdminExperience/ClientSide/Licensing.Web/package.json
  Dnn.AdminExperience/ClientSide/Pages.Web/package.json
  Dnn.AdminExperience/ClientSide/Prompt.Web/package.json
  Dnn.AdminExperience/ClientSide/Roles.Web/package.json
  Dnn.AdminExperience/ClientSide/Security.Web/package.json
  Dnn.AdminExperience/ClientSide/Seo.Web/package.json
  Dnn.AdminExperience/ClientSide/Servers.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteImportExport.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteSettings.Web/package.json
  Dnn.AdminExperience/ClientSide/Sites.Web/package.json
  Dnn.AdminExperience/ClientSide/Sites.Web/src/_exportables/package.json
  Dnn.AdminExperience/ClientSide/TaskScheduler.Web/package.json
  Dnn.AdminExperience/ClientSide/Themes.Web/package.json
  Dnn.AdminExperience/ClientSide/Users.Web/package.json
  Dnn.AdminExperience/ClientSide/Users.Web/src/_exportables/package.json
  Dnn.AdminExperience/ClientSide/Vocabularies.Web/package.json
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Dnn.PersonaBar.Extensions.dnn
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/PagesController.cs
  Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/Dnn.EditBar.UI.dnn
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/Dnn.PersonaBar.UI.dnn
  SolutionInfo.cs
  package.json
Labels: Type: Build/Release

#3957 Issue-3956 - Adding a page URL always defaults to 'Page and Child pages' site alias option.
  DNN Platform/Website/DotNetNuke.Website.csproj
  DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.07.01.SqlDataProvider
  Dnn.AdminExperience/ClientSide/Pages.Web/src/components/Seo/PageUrls/EditUrl.jsx
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Pages/PageUrlsController.cs
Labels: Type: Bug

#3954 Issue-3953 - Default site alias comes as pre-selected on SEO URL edit page
  Dnn.AdminExperience/ClientSide/Pages.Web/src/components/Seo/PageUrls/EditUrl.jsx
Labels: Type: Bug

#3950 Prevent Role Groups dropdown expand on delete
  Dnn.AdminExperience/ClientSide/Roles.Web/src/components/roles/FiltersBar/index.jsx
  Dnn.AdminExperience/ClientSide/Roles.Web/src/components/roles/RoleEditor/RoleGroupEditor/index.jsx
Labels: Type: Bug

#3965 Added retry to CompressionUtil.OpenCreate to prevent failures during site export
  DNN Platform/Modules/DnnExportImport/Components/Common/CompressionUtil.cs
Labels: Area: AE > PersonaBar Ext > SiteImportExport.Web, Type: Bug

#3996 Provide administrators role id to the test url page
  Dnn.AdminExperience/ClientSide/Seo.Web/src/actions/seo.js
  Dnn.AdminExperience/ClientSide/Seo.Web/src/components/testUrl/index.jsx
  Dnn.AdminExperience/ClientSide/Seo.Web/src/reducers/seoReducer.js
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/SeoController.cs
Labels: Area: AE > PersonaBar Ext > SEO.Web, Type: Bug

#4000 Update mergeable to check for Status: On Hold label
  .github/mergeable.yml
Labels: Type: Enhancement

#3998 Standardize on CR/LF line endings
  .editorconfig
Labels: Type: Maintenance

#4007 Fixes services framework usage in permission grid for the file manager
  DNN Platform/Modules/ResourceManager/Components/PermissionHelper.cs
  DNN Platform/Modules/ResourceManager/Dnn.Modules.ResourceManager.csproj
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/.babelrc
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/.eslintrc.js
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/components/FolderDetails.jsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/components/Permissions.jsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/globals/dnnSf.js
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/package.json
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/yarn.lock
  DNN Platform/Modules/ResourceManager/Services/Dto/FolderPermissions.cs
  DNN Platform/Modules/ResourceManager/Services/Dto/Permission.cs
  DNN Platform/Modules/ResourceManager/Services/Dto/Permissions.cs
  DNN Platform/Modules/ResourceManager/Services/Dto/RolePermission.cs
  DNN Platform/Modules/ResourceManager/Services/Dto/UserPermission.cs
  DNN Platform/Modules/ResourceManager/Services/ItemsController.cs
  DNN Platform/Modules/ResourceManager/View.ascx
  Dnn.AdminExperience/ClientSide/Dnn.React.Common/src/PermissionGrid/Grid.jsx
  Dnn.AdminExperience/ClientSide/Dnn.React.Common/src/PermissionGrid/RoleGroupFilter/index.jsx
  Dnn.AdminExperience/ClientSide/Dnn.React.Common/src/PermissionGrid/Suggestion/index.jsx
  Dnn.AdminExperience/ClientSide/Dnn.React.Common/src/PermissionGrid/index.jsx
  yarn.lock
Labels: Type: Feature

#4001 Add documentation to new .NET Standard projects
  DNN Platform/DotNetNuke.Abstractions/README.md
  DNN Platform/DotNetNuke.DependencyInjection/README.md
Labels: Type: Documentation

#4016 Improves GitVersion speed
  gitversion.yml
Labels: Type: Build/Release

#4010 Implement saving permissions
  DNN Platform/Modules/ResourceManager/Components/ItemsManager.cs
  DNN Platform/Modules/ResourceManager/Components/PermissionHelper.cs
  DNN Platform/Modules/ResourceManager/Dnn.Modules.ResourceManager.csproj
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/action types/itemDetailsActionsTypes.js
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/actions/itemDetailsActions.js
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/components/FolderDetails.jsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/components/Permissions.jsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/containers/ItemDetailsContainer.jsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/reducers/itemDetails.js
  DNN Platform/Modules/ResourceManager/Services/Dto/FolderDetailsRequest.cs
  DNN Platform/Modules/ResourceManager/Services/Dto/FolderPermissions.cs
  DNN Platform/Modules/ResourceManager/Services/ItemsController.cs
Labels: Type: Feature

#3980 Popup message content changed to avoid plural confusion
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Security/App_LocalResources/Security.resx
Labels: Type: Bug

#4018 Fixes #4003 bug in TokenReplace getting Module by Id
  DNN Platform/Library/Services/Tokens/TokenReplace.cs
Labels: Type: Bug

#3990 Created IHostSettingsService for Dependency Injection
  DNN Platform/DotNetNuke.Abstractions/Application/IHostSettingsService.cs
  DNN Platform/DotNetNuke.Abstractions/Settings/IConfigurationSetting.cs
  DNN Platform/Library/DotNetNuke.Library.csproj
  DNN Platform/Library/Entities/ConfigurationSetting.cs
  DNN Platform/Library/Entities/Controllers/HostController.cs
  DNN Platform/Library/Entities/Controllers/IHostController.cs
  DNN Platform/Library/Obsolete/HostController.cs
  DNN Platform/Library/Startup.cs
  DNN Platform/Tests/DotNetNuke.Tests.Content/AttachmentControllerTests.cs
  DNN Platform/Tests/DotNetNuke.Tests.Content/ContentControllerTests.cs
  DNN Platform/Tests/DotNetNuke.Tests.Content/ContentTypeControllerTests.cs
  DNN Platform/Tests/DotNetNuke.Tests.Content/DotNetNuke.Tests.Content.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Content/ScopeTypeControllerTests.cs
  DNN Platform/Tests/DotNetNuke.Tests.Content/TermControllerTests.cs
  DNN Platform/Tests/DotNetNuke.Tests.Content/VocabularyControllerTests.cs
  DNN Platform/Tests/DotNetNuke.Tests.Core/Common/NavigationManagerTests.cs
  DNN Platform/Tests/DotNetNuke.Tests.Core/Controllers/Host/HostControllerTest.cs
  DNN Platform/Tests/DotNetNuke.Tests.Core/Controllers/Messaging/NotificationsControllerTests.cs
  DNN Platform/Tests/DotNetNuke.Tests.Core/Controllers/Messaging/SubscriptionTypeControllerTests.cs
  DNN Platform/Tests/DotNetNuke.Tests.Core/Controllers/Portal/PortalGroupControllerTests.cs
  DNN Platform/Tests/DotNetNuke.Tests.Core/Controllers/Search/InternalSearchControllerTests.cs
  DNN Platform/Tests/DotNetNuke.Tests.Core/Controllers/Search/LuceneControllerTests.cs
  DNN Platform/Tests/DotNetNuke.Tests.Core/Controllers/Search/SearchControllerTests.cs
  DNN Platform/Tests/DotNetNuke.Tests.Core/Controllers/Search/SearchHelperTests.cs
  DNN Platform/Tests/DotNetNuke.Tests.Core/Controllers/Social/RelationshipControllerTests.cs
  DNN Platform/Tests/DotNetNuke.Tests.Core/Entities/Modules/Settings/ModuleSettingsTests.cs
  DNN Platform/Tests/DotNetNuke.Tests.Core/Entities/Modules/Settings/NullableSettingsTests.cs
  DNN Platform/Tests/DotNetNuke.Tests.Core/Entities/Modules/Settings/PortalSettingsTests.cs
  DNN Platform/Tests/DotNetNuke.Tests.Core/Entities/Modules/Settings/TabModuleSettingsTests.cs
  DNN Platform/Tests/DotNetNuke.Tests.Core/Entities/Portals/PortalSettingsControllerTests.cs
  DNN Platform/Tests/DotNetNuke.Tests.Core/Providers/Folder/FileContentTypeManagerTests.cs
  DNN Platform/Tests/DotNetNuke.Tests.Core/Providers/Folder/FileManagerTests.cs
  DNN Platform/Tests/DotNetNuke.Tests.Core/Providers/Folder/FolderManagerTests.cs
  DNN Platform/Tests/DotNetNuke.Tests.Core/Services/Mobile/PreviewProfileControllerTests.cs
  DNN Platform/Tests/DotNetNuke.Tests.Core/Services/Mobile/RedirectionControllerTests.cs
  DNN Platform/Tests/DotNetNuke.Tests.Core/Services/Tokens/TokenReplaceTests.cs
  DNN Platform/Tests/DotNetNuke.Tests.Core/Services/UserRequest/UserRequestIPAddressControllerTest.cs
  DNN Platform/Tests/DotNetNuke.Tests.Web/InternalServices/SearchServiceControllerTests.cs
  DNN Platform/Tests/DotNetNuke.Tests.Web/InternalServices/TabVersionControllerTests.cs
Labels: Type: Enhancement

#4015 Prevents creation of custom registration form without DisplayName and no DisplayNameFormat
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Security/Attributes/RegistrationFieldsAttribute.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Security/Constants.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/DTO/UpdateRegistrationSettingsRequest.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Security/App_LocalResources/Security.resx
Labels: Type: Enhancement

#4020 Update bug-report.md
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: Type: Build/Release
