Repository dnnsoftware/Dnn.Platform, pull requests merged in 2020-04, with the labels that each got.

#3655 validate file upload request.
  DNN Platform/DotNetNuke.Web/InternalServices/FileUploadController.cs
  DNN Platform/DotNetNuke.Web/UI/WebControls/DnnFileUploadOptions.cs
  DNN Platform/Library/Common/Utilities/ValidationUtils.cs
  DNN Platform/Library/DotNetNuke.Library.csproj
  DNN Platform/Library/Services/Personalization/PersonalizationController.cs
  DNN Platform/Website/Resources/Shared/components/FileUpload/dnn.FileUpload.js
Labels: Area: Platform > Library, Type: Enhancement

#3663 Ensure the portal ID being used for consent is the parent portal
  DNN Platform/Library/Security/Membership/AspNetMembershipProvider.cs
Labels: Area: Platform > Library, Type: Bug

#3657 Fixed "Allow Indexing" module setting
  DNN Platform/Website/admin/Modules/Modulesettings.ascx.cs
Labels: Area: Platform > Library, Type: Bug

#3648 Adds objectQualifier and databaseOwner to messaging sql for upgrades
  DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.05.01.SqlDataProvider
Labels: Type: Bug

#3664 SiteGroups Personabar Extension
  DNN Platform/Library/Entities/Portals/PortalController.cs
  DNN Platform/Library/Entities/Portals/PortalGroupController.cs
  DNN Platform/Library/Services/Log/EventLog/EventLogController.cs
  DNN Platform/Website/DotNetNuke.Website.csproj
  DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.06.00.SqlDataProvider
  DNN Platform/Website/Providers/DataProviders/SqlDataProvider/DotNetNuke.Data.SqlDataProvider
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/.babelrc
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/.eslintignore
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/.eslintrc.js
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/.eslintskipwords.js
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/.gitignore
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/jsconfig.json
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/src/components/App.jsx
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/src/components/AssignedSelector.jsx
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/src/components/AssignedSelector.less
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/src/components/Editor.jsx
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/src/components/Editor.less
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/src/components/NewGroup.jsx
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/src/components/Row.jsx
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/src/components/Row.less
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/src/components/Table.jsx
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/src/components/Table.less
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/src/components/common/CollapsibleSwitcher/index.jsx
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/src/components/common/CollapsibleSwitcher/style.less
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/src/components/common/IconButton/index.jsx
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/src/components/common/IconButton/style.less
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/src/img/common/add.svg
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/src/img/common/arrow_down.svg
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/src/img/common/arrow_left.svg
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/src/img/common/arrow_right.svg
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/src/img/common/calendar_end.svg
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/src/img/common/calendar_start.svg
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/src/img/common/checkmark.svg
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/src/img/common/edit.svg
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/src/img/common/lock_closed.svg
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/src/img/common/search.svg
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/src/img/common/trash.svg
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/src/img/common/users.svg
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/src/img/common/x.svg
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/src/localization/index.js
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/src/main.jsx
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/src/services/SiteGroupsService.js
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/src/utils/index.jsx
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/webpack.config.js
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/SiteGroups/IManagePortalGroups.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/SiteGroups/Models/PortalGroupInfo.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/SiteGroups/Models/PortalInfo.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/SiteGroups/PortalGroupAdapter.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/SiteGroups/SiteGroups.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Sites/SitesController.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Dnn.PersonaBar.Extensions.csproj
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Dnn.PersonaBar.Extensions.dnn
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/SiteGroupsController.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/SitesController.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.SiteGroups/App_LocalResources/SiteGroups.resx
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.SiteGroups/SiteGroups.html
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.SiteGroups/css/SiteGroups.css
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.SiteGroups/scripts/SiteGroups.js
  package.json
Labels: Area: AE > Dnn.PersonaBar.Extensions, Type: Feature

#3669 Improve portal groups logging migration script to log by default
  DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.06.00.SqlDataProvider
Labels: Area: AE > PersonaBar Ext > AdminLogs.Web, Type: Bug

#3668 Fixed portal alias update on website change
  Dnn.AdminExperience/ClientSide/SiteSettings.Web/src/components/siteAliasSettings/siteAliases/index.jsx
Labels: Area: AE > Dnn.PersonaBar.UI, Effort: Low, Type: Bug

#3672 Updates version to 9.6.0
  gitversion.yml
Labels: Type: Build/Release

#3673 Adjusted Telerik Bindings
  DNN Platform/Website/Install/Config/09.06.00.config
Labels: Alert: Breaking Change, Area: AE > Dnn.PersonaBar.UI, Effort: Low, Type: Bug

#3674 Fixes #3671
  DNN Platform/Website/Install/Config/09.06.00.config
Labels: Type: Maintenance

#3633 File extension whitelists for end users
  DNN Platform/DotNetNuke.Web/InternalServices/FileUploadController.cs
  DNN Platform/Library/Common/Utilities/FileExtensionWhitelist.cs
  DNN Platform/Library/Data/DataProvider.cs
  DNN Platform/Library/Entities/Host/Host.cs
  DNN Platform/Library/Entities/Portals/PortalSettings.cs
  DNN Platform/Library/Entities/Portals/PortalSettingsController.cs
  DNN Platform/Library/Entities/Users/UserInfo.cs
  DNN Platform/Library/Security/PortalSecurity.cs
  DNN Platform/Library/Services/FileSystem/FileManager.cs
  DNN Platform/Library/Services/Upgrade/Upgrade.cs
  DNN Platform/Tests/DotNetNuke.Tests.Core/Entities/Portals/TestFiles/HostSettings.csv
  DNN Platform/Website/DotNetNuke.Website.csproj
  DNN Platform/Website/Install/DotNetNuke.install.config.resources
  DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.06.00.SqlDataProvider
  DNN Platform/Website/Providers/DataProviders/SqlDataProvider/UnInstall.SqlDataProvider
  Dnn.AdminExperience/ClientSide/Security.Web/src/components/otherSettings/index.jsx
  Dnn.AdminExperience/ClientSide/SiteSettings.Web/src/actions/siteBehavior.js
  Dnn.AdminExperience/ClientSide/SiteSettings.Web/src/components/body/index.jsx
  Dnn.AdminExperience/ClientSide/SiteSettings.Web/src/components/moreSettings/index.jsx
  Dnn.AdminExperience/ClientSide/SiteSettings.Web/src/components/moreSettings/style.less
  Dnn.AdminExperience/ClientSide/SiteSettings.Web/src/components/privacySettings/index.jsx
  Dnn.AdminExperience/ClientSide/SiteSettings.Web/src/services/applicationService.js
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/DTO/SiteSettings/UpdateOtherSettingsRequest.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/DTO/UpdateOtherSettingsRequest.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/SecurityController.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/SiteSettingsController.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Security/App_LocalResources/Security.resx
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.SiteSettings/App_LocalResources/SiteSettings.resx
Labels: Area: AE > PersonaBar Ext > Security.Web, Area: AE > PersonaBar Ext > SiteSettings.Web, Area: Platform > Library, Type: Enhancement

#3675 Bring back Export Portal Template
  Dnn.AdminExperience/ClientSide/Sites.Web/src/_exportables/src/Components/ExportPortal/index.jsx
  Dnn.AdminExperience/ClientSide/Sites.Web/src/_exportables/src/Components/ExportPortal/style.less
  Dnn.AdminExperience/ClientSide/Sites.Web/src/_exportables/src/Components/ListView/index.jsx
  Dnn.AdminExperience/ClientSide/Sites.Web/src/components/App.jsx
  Dnn.AdminExperience/ClientSide/Sites.Web/src/components/PortalList/index.jsx
Labels: Type: Enhancement

#3665 Fixed Invalid Username/EmailAddress When Containing 'onfocus'
  DNN Platform/Library/Security/PortalSecurity.cs
Labels: Area: Platform > Library, Type: Bug

#3685 jQuery 3.5.0
  DNN Platform/JavaScript Libraries/jQuery/jQuery.dnn
  DNN Platform/JavaScript Libraries/jQuery/jquery.js
  DNN Platform/JavaScript Libraries/jQuery/jquery.min.map
  DNN Platform/JavaScript Libraries/jQueryMigrate/jQueryMigrate.dnn
  DNN Platform/JavaScript Libraries/jQueryMigrate/jquery-migrate.js
Labels: Type: Maintenance

#3683 Remove items from default web.config
  DNN Platform/Components/Telerik/DotNetNuke.Telerik.Web.dnn
  DNN Platform/Tests/App.config
  DNN Platform/Website/Install/Config/05.02.00.config
  DNN Platform/Website/Install/Config/05.02.01.config
  DNN Platform/Website/Install/Config/09.06.00.config
Labels: Type: Bug

#3689 Merges latest fixes in develop into release/9.6.0 for RC2
  DNN Platform/Components/Telerik/DotNetNuke.Telerik.Web.dnn
  DNN Platform/JavaScript Libraries/jQuery/jQuery.dnn
  DNN Platform/JavaScript Libraries/jQuery/jquery.js
  DNN Platform/JavaScript Libraries/jQuery/jquery.min.map
  DNN Platform/JavaScript Libraries/jQueryMigrate/jQueryMigrate.dnn
  DNN Platform/JavaScript Libraries/jQueryMigrate/jquery-migrate.js
  DNN Platform/Tests/App.config
  DNN Platform/Website/Install/Config/05.02.00.config
  DNN Platform/Website/Install/Config/05.02.01.config
  DNN Platform/Website/Install/Config/09.06.00.config
Labels: Type: Build/Release

#3699 Correct CONTRIBUTING links in issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/enhancement-request.md
Labels: Status: Review, Type: Documentation

#3698 Provide better feedback in export
  DNN Platform/Website/admin/Modules/Export.ascx.cs
Labels: Area: Platform > Website, Type: Enhancement

#3696 Add DI support to scheduler
  DNN Platform/Library/Services/Scheduling/ProcessGroup.cs
  DNN Platform/Library/Startup.cs
Labels: Type: Enhancement

#3700 Fix for import/export
  DNN Platform/Library/Services/Upgrade/Upgrade.cs
  DNN Platform/Website/Install/DotNetNuke.install.config.resources
  DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.06.00.SqlDataProvider
  DNN Platform/Website/admin/Modules/Export.ascx.cs
  DNN Platform/Website/admin/Modules/Import.ascx.cs
Labels: Type: Enhancement

#3702 Fixed user role icons not showing
  Dnn.AdminExperience/ClientSide/Dnn.React.Common/src/DatePicker/index.jsx
Labels: Type: Bug

#3704 Corrects typos and errors in module settings resx
  DNN Platform/Website/admin/Modules/App_LocalResources/ModuleSettings.ascx.resx
Labels: Area: Localization, Type: Enhancement

#3711 Merge latest changes from Release/9.6.0 into develop
  DNN Platform/Library/Services/Upgrade/Upgrade.cs
  DNN Platform/Website/Install/DotNetNuke.install.config.resources
  DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.06.00.SqlDataProvider
  DNN Platform/Website/admin/Modules/Export.ascx.cs
  DNN Platform/Website/admin/Modules/Import.ascx.cs
Labels: Type: Build/Release
