Repository dnnsoftware/Dnn.Platform, pull requests merged in 2020-12, with the labels that each got.

#4345 Inherit Monaco font (instead of using Roboto)
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
Labels: Area: AE > Dnn.PersonaBar.UI, Type: Bug

#4341 Update vsdoc file for jQuery to 3.4.1
  DNN Platform/Website/Resources/Shared/scripts/jquery/jquery-vsdoc.js
Labels: Type: Maintenance

#4342 Properly configure SiteMap on portal creation
  DNN Platform/Library/Entities/Portals/PortalController.cs
  DNN Platform/Website/Portals/_default/Blank Website.template
  DNN Platform/Website/Portals/_default/Default Website.template
Labels: Type: Bug

#4347 Removed "Running Default" check from Default.aspx
  DNN Platform/Library/Entities/Urls/FriendlyUrlSettings.cs
  DNN Platform/Library/Entities/Users/UserController.cs
  DNN Platform/Library/Security/Membership/UserLoginStatus.cs
  DNN Platform/Website/App_GlobalResources/SharedResources.resx
  DNN Platform/Website/Default.aspx.cs
  DNN Platform/Website/DesktopModules/Admin/Authentication/Login.ascx.cs
Labels: Area: Platform > DotNetNuke.Web, Type: Enhancement

#4351 Revert "Simplify cookie setting to avoid duplicate language cookies being set"
  DNN Platform/Library/Services/Localization/Localization.cs
Labels: Type: Bug

#4350 Allows upgrades from de-teleriked dnn instances
  Build/Cake/packaging.cs
Labels: Type: Maintenance

#4197 child page without a parent should not be validated
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Pages/BulkPagesController.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Pages/App_LocalResources/Pages.resx
Labels: Type: Bug

#4356 Don't check user permissions unless there's a user
  DNN Platform/Library/Services/GeneratedImage/ImageHandlerInternal.cs
Labels: Type: Bug

#4364 DNN-42147 Denying the `ADD` permission for a role on an asset makes it invisible to users on CKE Editor.
  DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.08.01.SqlDataProvider
Labels: Type: Bug

#4365 Try to fix flaky test
  DNN Platform/Library/Collections/ReaderWriterLockStrategy.cs
  DNN Platform/Tests/DotNetNuke.Tests.Core/Collections/ExclusiveLockSharedDictionaryTests.cs
  DNN Platform/Tests/DotNetNuke.Tests.Core/Collections/ReaderWriterLockSharedDictionaryTests.cs
  DNN Platform/Tests/DotNetNuke.Tests.Core/Collections/SharedDictionaryTests.cs
Labels: Type: Build/Release

#4368 Remove duplicate references
  DNN Platform/Library/DotNetNuke.Library.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Content/DotNetNuke.Tests.Content.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Integration/DotNetNuke.Tests.Integration.csproj
  DNN Platform/Website/DotNetNuke.Website.csproj
Labels: Type: Build/Release, Type: Maintenance

#4366 Warnings as Errors for test projects
  DNN Platform/Tests/.editorconfig
  DNN Platform/Tests/DNN.Integration.Test.Framework/DNN.Integration.Test.Framework.csproj
  DNN Platform/Tests/DotNetNuke.Tests.AspNetCCP/DotNetNuke.Tests.AspNetCCP.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Authentication/DotNetNuke.Tests.Authentication.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Content/DotNetNuke.Tests.Content.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Core/DotNetNuke.Tests.Core.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Data/DotNetNuke.Tests.Data.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Integration/DotNetNuke.Tests.Integration.csproj
  DNN Platform/Tests/DotNetNuke.Tests.UI/DotNetNuke.Tests.UI.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Urls/DotNetNuke.Tests.Urls.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Web.Mvc/DotNetNuke.Tests.Web.Mvc.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Web/DotNetNuke.Tests.Web.csproj
  Dnn.AdminExperience/Tests/.editorconfig
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.Pages.Tests/Dnn.PersonaBar.Pages.Tests.csproj
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.Pages.Tests/PagesControllerUnitTests.cs
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.Security.Tests/Dnn.PersonaBar.Security.Tests.csproj
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.Users.Tests/Dnn.PersonaBar.Users.Tests.csproj
Labels: Type: Maintenance

#4376 Enable warnings as errors for CountryListBox
  DNN Platform/Controls/CountryListBox/CountryListBox.cs
  DNN Platform/Controls/CountryListBox/CountryListBox.csproj
  DNN Platform/Controls/CountryListBox/CountryLookup.cs
Labels: Type: Maintenance

#4381 Enable warnings as errors for HTML Editor Manager
  DNN Platform/Modules/HtmlEditorManager/Components/UpgradeController.cs
  DNN Platform/Modules/HtmlEditorManager/DotNetNuke.Modules.HtmlEditorManager.csproj
  DNN Platform/Modules/HtmlEditorManager/Views/IProviderConfigurationView.cs
  DNN Platform/Modules/HtmlEditorManager/Views/ProviderConfiguration.ascx.cs
Labels: Type: Maintenance

#4380 Enable warnings as errors for GTM Connector
  DNN Platform/Connectors/GoogleTagManager/Dnn.GoogleTagManagerConnector.csproj
  DNN Platform/Connectors/GoogleTagManager/GoogleTagManagerConnector.cs
  DNN Platform/Connectors/GoogleTagManager/GoogleTagManagerController.cs
  DNN Platform/Connectors/GoogleTagManager/GoogleTagManagerEngine.cs
Labels: Type: Maintenance

#4379 Enable warnings as errors for Azure Connector
  DNN Platform/Connectors/Azure/Components/AzureConnector.cs
  DNN Platform/Connectors/Azure/Components/Constants.cs
  DNN Platform/Connectors/Azure/Dnn.AzureConnector.csproj
  DNN Platform/Connectors/Azure/Services/ServiceRouteMapper.cs
  DNN Platform/Connectors/Azure/Services/ServicesController.cs
Labels: Type: Maintenance

#4378 Enable warnings as errors for ModulePipeline
  DNN Platform/DotNetNuke.ModulePipeline/DotNetNuke.ModulePipeline.csproj
  DNN Platform/DotNetNuke.ModulePipeline/ModuleControlPipeline.cs
  DNN Platform/DotNetNuke.ModulePipeline/Startup.cs
Labels: Type: Maintenance

#4377 Enable warnings as errors for AspNetClientCapability
  DNN Platform/Library/Services/ClientCapability/ClientCapability.cs
  DNN Platform/Providers/ClientCapabilityProviders/Provider.AspNetCCP/AspNetClientCapability.cs
  DNN Platform/Providers/ClientCapabilityProviders/Provider.AspNetCCP/AspNetClientCapabilityProvider.cs
  DNN Platform/Providers/ClientCapabilityProviders/Provider.AspNetCCP/Components/FeatureController.cs
  DNN Platform/Providers/ClientCapabilityProviders/Provider.AspNetCCP/DotNetNuke.Providers.AspNetCCP.csproj
  DNN Platform/Providers/ClientCapabilityProviders/Provider.AspNetCCP/Properties/Constants.cs
  DNN Platform/Providers/ClientCapabilityProviders/Provider.AspNetCCP/Properties/RetailerConstants.cs
Labels: Type: Maintenance

#4371 Enable warnings as errors for SimpleWebFarmCachingProvider
  DNN Platform/Providers/CachingProviders/DotNetNuke.Providers.Caching.SimpleWebFarmCachingProvider/DotNetNuke.Providers.Caching.SimpleWebFarmCachingProvider.csproj
  DNN Platform/Providers/CachingProviders/DotNetNuke.Providers.Caching.SimpleWebFarmCachingProvider/SimpleWebFarmCachingProvider.cs
  DNN Platform/Providers/CachingProviders/DotNetNuke.Providers.Caching.SimpleWebFarmCachingProvider/SimpleWebFarmSynchronizationHandler.cs
Labels: Type: Maintenance

#4372 Enable warnings as errors for 3rd party auth providers
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Facebook/Components/FacebookClient.cs
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Facebook/Components/FacebookUserData.cs
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Facebook/DotNetNuke.Authentication.Facebook.csproj
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Facebook/Login.ascx.cs
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Facebook/Settings.ascx.cs
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Google/Components/GoogleClient.cs
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Google/Components/GoogleUserData.cs
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Google/DotNetNuke.Authentication.Google.csproj
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Google/Login.ascx.cs
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Google/Settings.ascx.cs
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.LiveConnect/Components/LiveClient.cs
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.LiveConnect/Components/LiveUserData.cs
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.LiveConnect/DotNetNuke.Authentication.LiveConnect.csproj
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.LiveConnect/Login.ascx.cs
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.LiveConnect/Settings.ascx.cs
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Twitter/Components/TwitterClient.cs
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Twitter/Components/TwitterUserData.cs
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Twitter/DotNetNuke.Authentication.Twitter.csproj
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Twitter/Login.ascx.cs
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Twitter/Settings.ascx.cs
Labels: Type: Maintenance

#4370 Resolve some warnings in DnnExportImportLibrary
  DNN Platform/Modules/DnnExportImportLibrary/Dto/Pages/ExportTab.cs
  DNN Platform/Modules/DnnExportImportLibrary/Interfaces/IExportImportRepository.cs
  DNN Platform/Modules/DnnExportImportLibrary/Repository/ExportImportRepository.cs
Labels: Type: Maintenance

#4369 Enable warnings as errors in Dnn.EditBar.Library
  Dnn.AdminExperience/EditBar/Dnn.EditBar.Library/Constants.cs
  Dnn.AdminExperience/EditBar/Dnn.EditBar.Library/Dnn.EditBar.Library.csproj
  Dnn.AdminExperience/EditBar/Dnn.EditBar.Library/Items/BaseMenuItem.cs
Labels: Type: Maintenance

#4375 Enable warnings as errors for JWT
  DNN Platform/Dnn.AuthServices.Jwt/Components/Common/Controllers/JwtController.cs
  DNN Platform/Dnn.AuthServices.Jwt/Components/Entity/RenewalDto.cs
  DNN Platform/Dnn.AuthServices.Jwt/Dnn.AuthServices.Jwt.csproj
  DNN Platform/Dnn.AuthServices.Jwt/Services/MobileController.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/ExtensionsController.cs
Labels: Type: Maintenance

#4373 Clean up warnings in DnnExportImport
  DNN Platform/Modules/DnnExportImport/Components/Controllers/BaseController.cs
  DNN Platform/Modules/DnnExportImport/Components/Controllers/BusinessController.cs
  DNN Platform/Modules/DnnExportImport/Components/Controllers/EntitiesController.cs
  DNN Platform/Modules/DnnExportImport/Components/Controllers/ExportController.cs
  DNN Platform/Modules/DnnExportImport/Components/Controllers/ImportController.cs
  DNN Platform/Modules/DnnExportImport/Components/Controllers/SettingsController.cs
  DNN Platform/Modules/DnnExportImport/Components/Dto/ExportDto.cs
  DNN Platform/Modules/DnnExportImport/Components/Dto/ExportFileInfo.cs
  DNN Platform/Modules/DnnExportImport/Components/Dto/ImportDto.cs
  DNN Platform/Modules/DnnExportImport/Components/Dto/ImportExportSummary.cs
  DNN Platform/Modules/DnnExportImport/Components/Dto/ImportPackageInfo.cs
  DNN Platform/Modules/DnnExportImport/Components/Dto/Jobs/AllJobsResult.cs
  DNN Platform/Modules/DnnExportImport/Components/Dto/Jobs/JobItem.cs
  DNN Platform/Modules/DnnExportImport/Components/Dto/PageToExport.cs
  DNN Platform/Modules/DnnExportImport/Components/Dto/TriCheckedState.cs
  DNN Platform/Modules/DnnExportImport/Components/Engines/ExportImportEngine.cs
  DNN Platform/Modules/DnnExportImport/Components/Entities/ExportImportChekpoint.cs
  DNN Platform/Modules/DnnExportImport/Components/Entities/ExportImportJob.cs
  DNN Platform/Modules/DnnExportImport/Components/Interfaces/IDateTimeConverter.cs
  DNN Platform/Modules/DnnExportImport/Components/Providers/DataProvider.cs
  DNN Platform/Modules/DnnExportImport/Components/Services/AssetsExportService.cs
  DNN Platform/Modules/DnnExportImport/Components/Services/PackagesExportService.cs
  DNN Platform/Modules/DnnExportImport/Components/Services/PageTemplatesExportService.cs
  DNN Platform/Modules/DnnExportImport/Components/Services/PagesExportService.cs
  DNN Platform/Modules/DnnExportImport/Components/Services/PortalExportService.cs
  DNN Platform/Modules/DnnExportImport/Components/Services/ProfilePropertiesService.cs
  DNN Platform/Modules/DnnExportImport/Components/Services/RolesExportService.cs
  DNN Platform/Modules/DnnExportImport/Components/Services/ThemesExportService.cs
  DNN Platform/Modules/DnnExportImport/Components/Services/UsersDataExportService.cs
  DNN Platform/Modules/DnnExportImport/Components/Services/VocabularyService.cs
  DNN Platform/Modules/DnnExportImport/Components/Services/WorkflowsExportService.cs
  DNN Platform/Modules/DnnExportImport/DnnExportImport.csproj
  DNN Platform/Modules/DnnExportImport/Services/ExportImportController.cs
Labels: Type: Maintenance

#4392 Updates bug report template as per 9.8.1rc1 release
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: Type: Documentation
