Repository dnnsoftware/Dnn.Platform, pull requests merged in 2020-07, with the labels that each got.

#3884 Improve install page nl-NL text
  DNN Platform/Website/Install/App_LocalResources/Installwizard.aspx.nl-NL.resx
Labels: Area: Localization, Type: Enhancement

#3890 Fix bug #3849 causing captcha image not to show in IE 11
  DNN Platform/Library/UI/WebControls/CaptchaHandler.cs
Labels: Type: Bug

#3897 Tabs that are not Indexed shouldn't be in the SiteMap
  DNN Platform/Library/Services/Sitemap/CoreSitemapProvider.cs
Labels: Type: Enhancement

#3820 Implement a Token Provider interface
  DNN Platform/DotNetNuke.Web/Common/DotNetNukeHttpApplication.cs
  DNN Platform/Library/DotNetNuke.Library.csproj
  DNN Platform/Library/Services/Tokens/BaseCustomTokenReplace.cs
  DNN Platform/Library/Services/Tokens/BaseTokenReplace.cs
  DNN Platform/Library/Services/Tokens/CoreTokenProvider.cs
  DNN Platform/Library/Services/Tokens/TokenContext.cs
  DNN Platform/Library/Services/Tokens/TokenProvider.cs
  DNN Platform/Library/Services/Tokens/TokenReplace.cs
  DNN Platform/Tests/App.config
  DNN Platform/Tests/DotNetNuke.Tests.Core/Services/Tokens/TokenReplaceTests.cs
  DNN Platform/Website/development.config
  DNN Platform/Website/release.config
Labels: Type: Feature

#3891 Include CSS and JS CDF methods in the Dnn helper for Razor
  DNN Platform/DotNetNuke.Web.Mvc/DotNetNuke.Web.Mvc.csproj
  DNN Platform/DotNetNuke.Web.Mvc/Helpers/DnnHelper.cs
Labels: Type: Enhancement

#3845 Move after login/logout/registration redirection to site settings
  Dnn.AdminExperience/ClientSide/Security.Web/src/components/basicSettings/index.jsx
  Dnn.AdminExperience/ClientSide/Security.Web/src/components/registrationSettings/index.jsx
  Dnn.AdminExperience/ClientSide/SiteSettings.Web/src/components/defaultPagesSettings/index.jsx
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/DTO/SiteSettings/UpdateDefaultPagesSettingsRequest.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/DTO/UpdateBasicLoginSettingsRequest.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/DTO/UpdateRegistrationSettingsRequest.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/SecurityController.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/SiteSettingsController.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Security/App_LocalResources/Security.resx
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.SiteSettings/App_LocalResources/SiteSettings.resx
Labels: Area: AE > Dnn.PersonaBar.Extensions, Area: AE > PersonaBar Ext > Security.Web, Area: AE > PersonaBar Ext > SiteSettings.Web, Type: Enhancement

#3795 Move Prompt to core libraries
  DNN Platform/DotNetNuke.Abstractions/INavigationManager.cs
  DNN Platform/DotNetNuke.Abstractions/Portals/IPortalAliasInfo.cs
  DNN Platform/DotNetNuke.Abstractions/Portals/IPortalSettings.cs
  DNN Platform/DotNetNuke.Abstractions/Prompt/ICommand.cs
  DNN Platform/DotNetNuke.Abstractions/Prompt/ICommandHelp.cs
  DNN Platform/DotNetNuke.Abstractions/Prompt/ICommandOption.cs
  DNN Platform/DotNetNuke.Abstractions/Prompt/ICommandRepository.cs
  DNN Platform/DotNetNuke.Abstractions/Prompt/IConsoleCommand.cs
  DNN Platform/DotNetNuke.Abstractions/Prompt/IConsoleResultModel.cs
  DNN Platform/DotNetNuke.Abstractions/Prompt/IPagingInfo.cs
  DNN Platform/DotNetNuke.Abstractions/Users/IUserInfo.cs
  DNN Platform/Library/DotNetNuke.Library.csproj
  DNN Platform/Library/Entities/Modules/Prompt/AddModule.cs
  DNN Platform/Library/Entities/Modules/Prompt/ListModules.cs
  DNN Platform/Library/Entities/Modules/Prompt/PromptModuleInfo.cs
  DNN Platform/Library/Entities/Modules/Settings/SerializationController.cs
  DNN Platform/Library/Entities/Modules/Settings/SettingsRepository.cs
  DNN Platform/Library/Entities/Portals/PortalAliasInfo.cs
  DNN Platform/Library/Entities/Users/UserInfo.cs
  DNN Platform/Library/Prompt/Attributes/ConsoleCommandAttribute.cs
  DNN Platform/Library/Prompt/Attributes/ConsoleCommandParameterAttribute.cs
  DNN Platform/Library/Prompt/Command.cs
  DNN Platform/Library/Prompt/CommandRepository.cs
  DNN Platform/Library/Prompt/Common/Constants.cs
  DNN Platform/Library/Prompt/ConsoleCommand.cs
  DNN Platform/Library/Prompt/Output/CommandHelp.cs
  DNN Platform/Library/Prompt/Output/CommandOption.cs
  DNN Platform/Library/Prompt/Output/ConsoleErrorResultModel.cs
  DNN Platform/Library/Prompt/Output/ConsoleResultModel.cs
  DNN Platform/Library/Prompt/Output/PagingInfo.cs
  DNN Platform/Website/App_GlobalResources/Prompt.resx
  DNN Platform/Website/DotNetNuke.Website.csproj
  DNN_Platform.sln.DotSettings
  Dnn.AdminExperience/ClientSide/Prompt.Web/src/components/App.jsx
  Dnn.AdminExperience/ClientSide/Prompt.Web/src/globals/promptInit.js
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Prompt/Commands/Commands/ListCommands.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Prompt/Commands/Module/AddModule.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Prompt/Commands/Module/ListModules.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Prompt/Constants.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Prompt/IModulesController.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Prompt/Models/Command.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Prompt/Models/CommandHelp.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Prompt/Models/CommandOption.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Prompt/ModulesController.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Prompt/Repositories/CommandRepository.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Prompt/Repositories/ICommandRepository.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Dnn.PersonaBar.Extensions.csproj
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/CommandController.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Prompt/App_LocalResources/Prompt.resx
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Prompt/scripts/Prompt.js
  Dnn.AdminExperience/Library/Dnn.PersonaBar.Library/Constants.cs
  Dnn.AdminExperience/Library/Dnn.PersonaBar.Library/Prompt/Attributes/ConsoleCommandAttribute.cs
  Dnn.AdminExperience/Library/Dnn.PersonaBar.Library/Prompt/Attributes/FlagParameterAttribute.cs
  Dnn.AdminExperience/Library/Dnn.PersonaBar.Library/Prompt/ConsoleCommandBase.cs
  Dnn.AdminExperience/Library/Dnn.PersonaBar.Library/Prompt/IConsoleCommand.cs
  Dnn.AdminExperience/Library/Dnn.PersonaBar.Library/Prompt/Models/ConsoleErrorResultModel.cs
  Dnn.AdminExperience/Library/Dnn.PersonaBar.Library/Prompt/Models/ConsoleResultModel.cs
  Dnn.AdminExperience/Library/Dnn.PersonaBar.Library/Prompt/Models/PagingInfo.cs
Labels: Area: AE > Dnn.PersonaBar.Extensions, Area: AE > Dnn.PersonaBar.Library, Area: AE > PersonaBar Ext > Prompt.Web, Area: Platform > Library, Type: Enhancement

#3900 Fixes for #3820 Token Provider
  DNN Platform/Tests/App.config
  DNN Platform/Website/Install/Config/09.07.00.config
  DNN_Platform.sln
Labels: Type: Bug

#3905 Move using statements inside namespace for DotNetNuke.Abstractions project
  DNN Platform/DotNetNuke.Abstractions/INavigationManager.cs
  DNN Platform/DotNetNuke.Abstractions/Portals/IPortalAliasInfo.cs
  DNN Platform/DotNetNuke.Abstractions/Portals/IPortalSettings.cs
  DNN Platform/DotNetNuke.Abstractions/Prompt/ICommandHelp.cs
  DNN Platform/DotNetNuke.Abstractions/Prompt/ICommandRepository.cs
  DNN Platform/DotNetNuke.Abstractions/Prompt/IConsoleCommand.cs
  DNN Platform/DotNetNuke.Abstractions/Users/IUserInfo.cs
Labels: Area: Platform > DotNetNuke.Abstractions, Type: Enhancement

#3915 fixed typo
  Dnn.AdminExperience/ClientSide/Prompt.Web/src/utils/__mocks__/utilities.js
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Pages/App_LocalResources/Pages.resx
Labels: Type: Bug

#3909 Fixes stylecop warnings on FolderManager.cs
  DNN Platform/Library/DotNetNuke.Library.csproj
  DNN Platform/Library/Services/FileSystem/FolderManager.cs
  DNN Platform/Library/Services/FileSystem/SyncFolderData.cs
  DNN Platform/Library/Services/Log/EventLog/EventLogController.cs
  DNN Platform/Library/Services/Log/EventLog/IEventLogController.cs
Labels: Type: Documentation

#3919 Enable Scheduling - Add TZ to page StartDate and EndDate
  DNN Platform/Library/Common/Utilities/Null.cs
  DNN Platform/Library/Entities/Tabs/TabInfo.cs
  Dnn.AdminExperience/ClientSide/Pages.Web/src/components/PageDetails/PageDetailsFooter/PageDetailsFooter.jsx
  Dnn.AdminExperience/ClientSide/Pages.Web/src/services/pageService.js
Labels: Area: AE > PersonaBar Ext > Pages.Web, Type: Bug

#3917 Visualizer not able to change settings in shared pages
  DNN Platform/Library/Entities/Tabs/TabChangeTracker.cs
  DNN Platform/Tests/DotNetNuke.Tests.Core/DotNetNuke.Tests.Core.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Core/Entities/Tabs/TabChangeTrackerTests.cs
  Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/editBar/resources/ContentEditorManager/Js/ModuleService.js
Labels: Type: Enhancement

#3898 Modify Logo skin object to handle SVGs
  DNN Platform/Website/admin/Skins/Logo.ascx.cs
  DNN Platform/Website/admin/Skins/Logo.ascx.designer.cs
  DNN Platform/Website/admin/Skins/Logo.xml
  DNN Platform/Website/admin/Skins/logo.ascx
Labels: Type: Enhancement

#3927 Retry determining Globals.Status if it was Error
  DNN Platform/Library/Common/Globals.cs
Labels: Type: Bug

#3930 Ensure DI services are disposed in WebForms
  DNN Platform/Library/Entities/Modules/PortalModuleBase.cs
Labels: Type: Bug

#3923 Prevented unnecessary call to getCultureList method on website change
  Dnn.AdminExperience/ClientSide/SiteSettings.Web/src/components/siteLanguageSelector/index.jsx
Labels: Type: Bug

#3932 Add List-Services command to Prompt
  DNN Platform/DotNetNuke.Web/Common/DotNetNukeHttpApplication.cs
  DNN Platform/DotNetNuke.Web/DependencyInjectionInitialize.cs
  DNN Platform/DotNetNuke.Web/DotNetNuke.Web.csproj
  DNN Platform/DotNetNuke.Web/Prompt/ListServices.cs
  DNN Platform/DotNetNuke.Web/Startup.cs
  DNN Platform/Website/App_GlobalResources/Prompt.resx
Labels: Area: AE > PersonaBar Ext > Prompt.Web, Area: Platform > DotNetNuke.DependencyInjection, Type: Feature

#3903 Abstracted AllowIndex logic into TabInfo property
  DNN Platform/Library/Entities/Tabs/TabInfo.cs
  DNN Platform/Library/Services/Search/TabIndexer.cs
  DNN Platform/Library/Services/Sitemap/CoreSitemapProvider.cs
Labels: Type: Bug

#3938 Use Ordinal comparison for Boolean check
  DNN Platform/Library/Entities/Tabs/TabInfo.cs
Labels: Type: Enhancement

#3941 Deprecate TabInfo.TabPermissionsSpecified
  DNN Platform/Library/Entities/Tabs/TabInfo.cs
Labels: Type: Maintenance

#3939 Address StyleCop warnings for TabInfo and TabIndexer
  DNN Platform/Library/Entities/Tabs/TabInfo.cs
  DNN Platform/Library/Services/Search/TabIndexer.cs
Labels: Type: Documentation

#3944 Fixes a wrong merge conflict resolution that broke the pages module.
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/PagesController.cs
Labels: Type: Bug
