Repository dnnsoftware/Dnn.Platform, pull requests merged in 2020-10, with the labels that each got.

#4141 Remove beacon setting on upgrade
  DNN Platform/Website/Install/Config/09.07.03.config
Labels: Type: Maintenance

#4149 Implemented file/folder move in resource manager.
  DNN Platform/Modules/ResourceManager/App_LocalResources/ResourceManager.resx
  DNN Platform/Modules/ResourceManager/Components/Common/Utils.cs
  DNN Platform/Modules/ResourceManager/Components/IItemsManager.cs
  DNN Platform/Modules/ResourceManager/Components/ItemsManager.cs
  DNN Platform/Modules/ResourceManager/Dnn.Modules.ResourceManager.csproj
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/action types/itemDetailsActionsTypes.js
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/actions/itemDetailsActions.js
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/components/FileDetails.jsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/components/Item.jsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/containers/AssetsPanelContainer.jsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/containers/ItemContainer.jsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/containers/ItemMoveContainer.jsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/containers/ManageFolderTypesPanelContainer.jsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/containers/TopBarContainer.jsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/less/Assets.less
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/reducers/itemDetails.js
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/services/itemsService.js
  DNN Platform/Modules/ResourceManager/Services/Dto/MoveFileRequest.cs
  DNN Platform/Modules/ResourceManager/Services/Dto/MoveFolderRequest.cs
  DNN Platform/Modules/ResourceManager/Services/ItemsController.cs
  yarn.lock
Labels: Type: Feature

#4151 Adds 09.07.03.config into the project
  DNN Platform/Website/DotNetNuke.Website.csproj
Labels: Type: Documentation

#4150 Rebases feature/resource-manager with latest changes from develop
  DNN Platform/Admin Modules/Dnn.Modules.ModuleCreator/Dnn.Modules.ModuleCreator.csproj
  DNN Platform/DotNetNuke.Website.Deprecated/DotNetNuke.Website.Deprecated.csproj
  DNN Platform/DotNetNuke.Website.Deprecated/admin/ControlPanel/AddModule.ascx.cs
  DNN Platform/DotNetNuke.Website.Deprecated/admin/ControlPanel/AddModule.ascx.designer.cs
  DNN Platform/DotNetNuke.Website.Deprecated/admin/ControlPanel/AddPage.ascx.cs
  DNN Platform/DotNetNuke.Website.Deprecated/admin/ControlPanel/AddPage.ascx.designer.cs
  DNN Platform/DotNetNuke.Website.Deprecated/admin/ControlPanel/ControlBar.ascx.cs
  DNN Platform/DotNetNuke.Website.Deprecated/admin/ControlPanel/ControlBar.ascx.designer.cs
  DNN Platform/DotNetNuke.Website.Deprecated/admin/ControlPanel/RibbonBar.ascx.cs
  DNN Platform/DotNetNuke.Website.Deprecated/admin/ControlPanel/RibbonBar.ascx.designer.cs
  DNN Platform/DotNetNuke.Website.Deprecated/admin/ControlPanel/SwitchSite.ascx.cs
  DNN Platform/DotNetNuke.Website.Deprecated/admin/ControlPanel/SwitchSite.ascx.designer.cs
  DNN Platform/DotNetNuke.Website.Deprecated/admin/ControlPanel/UpdatePage.ascx.cs
  DNN Platform/DotNetNuke.Website.Deprecated/admin/ControlPanel/UpdatePage.ascx.designer.cs
  DNN Platform/Library/Entities/Portals/PortalAliasController.cs
  DNN Platform/Library/Entities/Portals/PortalAliasInfo.cs
  DNN Platform/Modules/HTML/DotNetNuke.Modules.Html.csproj
  DNN Platform/Modules/HTML/EditHtml.ascx.cs
  DNN Platform/Modules/HTML/dnn_HTML.dnn
  DNN Platform/Modules/HtmlEditorManager/DotNetNuke.Modules.HtmlEditorManager.csproj
  DNN Platform/Modules/RazorHost/DotNetNuke.Modules.RazorHost.csproj
  DNN Platform/Tests/App.config
  DNN Platform/Tests/DotNetNuke.Tests.Authentication/DotNetNuke.Tests.Authentication.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Content/DotNetNuke.Tests.Content.csproj
  DNN Platform/Website/App_GlobalResources/GlobalResources.resx
  DNN Platform/Website/DotNetNuke.Website.csproj
  DNN Platform/Website/Install/Config/09.07.03.config
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Pages/PagesControllerImpl.cs
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/Services/ComponentsController.cs
Labels: Type: Maintenance

#4153 Add host setting option and ability to use settings outside module context
  DNN Platform/Library/DotNetNuke.Library.csproj
  DNN Platform/Library/Entities/Modules/Settings/HostSettingAttribute.cs
  DNN Platform/Library/Entities/Modules/Settings/ISettingsRepository.cs
  DNN Platform/Library/Entities/Modules/Settings/SettingsRepository.cs
Labels: Type: Enhancement

#3984 Support C# Async Constructs During Page Rendering
  DNN Platform/HttpModules/DotNetNuke.HttpModules.csproj
  DNN Platform/HttpModules/Localization/LocalizationModule.cs
  DNN Platform/Library/Framework/PageBase.cs
  DNN Platform/Library/Services/Localization/Localization.cs
  DNN Platform/Modules/CoreMessaging/DotNetNuke.Modules.CoreMessaging.csproj
  DNN Platform/Modules/CoreMessaging/Services/SubscriptionsController.cs
  DNN Platform/Website/Default.aspx
  DNN Platform/Website/Install/Config/09.08.00.config
  DNN Platform/Website/development.config
  DNN Platform/Website/release.config
Labels: Type: Feature

#4144 export after changing a module pane in a page and importing in anothe…
  DNN Platform/Modules/DnnExportImport/Components/Services/PagesExportService.cs
Labels: Type: Bug

#4160 Properly named CSS class & keeps the other for compatibility for now
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/UserControls/PersonaBarContainer.ascx
Labels: Type: Bug

#4159 Adds IEventLogger to Dependency Injection
  DNN Platform/DotNetNuke.Abstractions/Logging/EventLogType.cs
  DNN Platform/DotNetNuke.Abstractions/Logging/IEventLogConfigService.cs
  DNN Platform/DotNetNuke.Abstractions/Logging/IEventLogService.cs
  DNN Platform/DotNetNuke.Abstractions/Logging/IEventLogger.cs
  DNN Platform/DotNetNuke.Abstractions/Logging/IExceptionInfo.cs
  DNN Platform/DotNetNuke.Abstractions/Logging/ILogDetailInfo.cs
  DNN Platform/DotNetNuke.Abstractions/Logging/ILogInfo.cs
  DNN Platform/DotNetNuke.Abstractions/Logging/ILogProperties.cs
  DNN Platform/DotNetNuke.Abstractions/Logging/ILogTypeConfigInfo.cs
  DNN Platform/DotNetNuke.Abstractions/Logging/ILogTypeInfo.cs
  DNN Platform/DotNetNuke.Abstractions/Logging/NotificationThresholdTimeTypes.cs
  DNN Platform/DotNetNuke.Web/InternalServices/EventLogServiceController.cs
  DNN Platform/Library/DotNetNuke.Library.csproj
  DNN Platform/Library/Obsolete/EventLogController.cs
  DNN Platform/Library/Obsolete/LogInfo.cs
  DNN Platform/Library/Obsolete/LogTypeConfigInfo.cs
  DNN Platform/Library/Obsolete/LogTypeInfo.cs
  DNN Platform/Library/Services/Exceptions/ExceptionInfo.cs
  DNN Platform/Library/Services/Log/EventLog/DBLoggingProvider.cs
  DNN Platform/Library/Services/Log/EventLog/EventLogController.cs
  DNN Platform/Library/Services/Log/EventLog/EventLogExtensions.cs
  DNN Platform/Library/Services/Log/EventLog/ILogController.cs
  DNN Platform/Library/Services/Log/EventLog/LogController.cs
  DNN Platform/Library/Services/Log/EventLog/LogDetailInfo.cs
  DNN Platform/Library/Services/Log/EventLog/LogInfo.cs
  DNN Platform/Library/Services/Log/EventLog/LogProperties.cs
  DNN Platform/Library/Services/Log/EventLog/LogTypeConfigInfo.cs
  DNN Platform/Library/Services/Log/EventLog/LogTypeInfo.cs
  DNN Platform/Library/Services/Log/EventLog/LoggingProvider.cs
  DNN Platform/Library/Startup.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/AdminLogs/AdminLogsController.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/AdminLogsController.cs
Labels: Type: Enhancement

#4165 Adds support for editing the robots.txt on a website
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/ConfigConsole/ConfigConsoleController.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.ConfigConsole/scripts/ConfigConsole.js
Labels: Type: Enhancement

#4172 Issues/fix pr 4165
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/ConfigConsole/ConfigConsoleController.cs
Labels: Type: Bug

#4158 Resolves an infinite redirect loop issue
  DNN Platform/Library/Entities/Urls/AdvancedUrlRewriter.cs
Labels: Type: Bug

#4176 Lowercases the meta tag names
  DNN Platform/Website/Default.aspx
Labels: Type: Enhancement

#4170 Swap CodeMirror in SqlConsole for monaco-editor
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.SqlConsole/SqlConsole.html
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.SqlConsole/css/SqlConsole.css
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.SqlConsole/scripts/SqlConsole.js
Labels: Type: Feature

#4173 Swap CodeMirror in ConfigConsole for monaco-editor
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.ConfigConsole/ConfigConsole.html
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.ConfigConsole/css/ConfigConsole.css
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.ConfigConsole/scripts/ConfigConsole.js
Labels: Type: Feature

#4178 Fixes Event Log from Failing Silently during Application Startup
  DNN Platform/Library/Services/Log/EventLog/LogController.cs
Labels: Type: Bug

#4179 Fix MSBuild issue with Dnn.PersonaBar.Extensions
  Build/BuildScripts/AEModule.build
Labels: Type: Build/Release

#4185 Anonymous users denied access to profile picture when configured as n…
  DNN Platform/Library/Services/GeneratedImage/ImageHandlerInternal.cs
Labels: Type: Bug

#4180 Updated DDR Menu to be System Package
  DNN Platform/Modules/DDRMenu/DDRMenu.dnn
Labels: Area: Platform > Modules, Type: Maintenance

#4182 Mark Webslice for Removal
  DNN Platform/Library/Entities/Modules/ModuleInfo.cs
  DNN Platform/Modules/DnnExportImportLibrary/Dto/Pages/ExportTabModule.cs
Labels: Type: Maintenance

#4183 Updated the UpdateDatabase procedure to set version numbers
  DNN Platform/Website/DotNetNuke.Website.csproj
  DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.08.00.SqlDataProvider
Labels: Type: Documentation, Type: Maintenance

#4184 Resolved issue with Keyword and Description Defaults
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Pages/Converters.cs
Labels: Area: AE > PersonaBar Ext > Pages.Web, Type: Bug

#4164 Parse date with invariant culture to fix non-Gregorian calendar dates…
  DNN Platform/Library/Services/Search/Controllers/SearchControllerImpl.cs
  DNN Platform/Library/Services/Search/Internals/InternalSearchControllerImpl.cs
Labels: Type: Bug

#4087 Add ISerializationManager for Dependency Injection
  DNN Platform/DotNetNuke.Abstractions/ISerializationManager.cs
  DNN Platform/Library/DotNetNuke.Library.csproj
  DNN Platform/Library/Entities/Modules/Settings/SerializationController.cs
  DNN Platform/Library/Entities/Modules/Settings/SerializationManager.cs
  DNN Platform/Library/Entities/Modules/Settings/SettingsRepository.cs
  DNN Platform/Library/Obsolete/SerializationController.cs
  DNN Platform/Library/Prompt/ConsoleCommand.cs
  DNN Platform/Library/Startup.cs
  DNN Platform/Tests/DotNetNuke.Tests.Core/Entities/Modules/Settings/ModuleSettingsTests.cs
  DNN Platform/Tests/DotNetNuke.Tests.Core/Entities/Modules/Settings/NullableSettingsTests.cs
  DNN Platform/Tests/DotNetNuke.Tests.Core/Entities/Modules/Settings/PortalSettingsTests.cs
  DNN Platform/Tests/DotNetNuke.Tests.Core/Entities/Modules/Settings/TabModuleSettingsTests.cs
Labels: Type: Enhancement

#4155 Enable dependency injection for IServiceRouteMapper
  DNN Platform/DotNetNuke.Web/Api/Internal/ServicesRoutingManager.cs
Labels: Type: Enhancement

#4187 Introduce MailAttachment class
  DNN Platform/Library/DotNetNuke.Library.csproj
  DNN Platform/Library/Services/Mail/CoreMailProvider.cs
  DNN Platform/Library/Services/Mail/Mail.cs
  DNN Platform/Library/Services/Mail/MailAttachment.cs
  DNN Platform/Library/Services/Mail/MailInfo.cs
Labels: Type: Enhancement

#4188 Updated Release Schedule Documentation
  .github/RELEASE_SCHEDULE.md
Labels: Type: Documentation

#4193 Update bug-report.md
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: Type: Documentation

#4171 Reset redirect url for redirecting to 'Redirect After Login' page
  DNN Platform/Website/DesktopModules/Admin/Authentication/Login.ascx.cs
Labels: Type: Bug

#4192 Fixed issue country/region field showed Id instead of name when using arrow keys
  DNN Platform/Website/Resources/Shared/components/CountriesRegions/dnn.CountriesRegions.js
Labels: Type: Bug

#4202 Fixes an issue where folder search would not work in resrouce manager
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/components/FolderSelector/FolderPicker.jsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/components/FolderSelector/FolderSelector.jsx
Labels: Type: Bug

#4198 Fix tooltip Sitemap page priority
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Seo/App_LocalResources/Seo.resx
Labels: Type: Documentation

#4194 Resolves multiple stylcop warnings in Library and HttpModules projects
  DNN Platform/HttpModules/Analytics/AnalyticsModule.cs
  DNN Platform/HttpModules/Compression/Filters/DeflateFilter.cs
  DNN Platform/HttpModules/Compression/Filters/GZipFilter.cs
  DNN Platform/HttpModules/Compression/Filters/HttpOutputFilter.cs
  DNN Platform/HttpModules/DependencyInjection/ServiceRequestScopeModule.cs
  DNN Platform/HttpModules/Exception/ExceptionModule.cs
  DNN Platform/HttpModules/MobileRedirect/MobileRedirectModule.cs
  DNN Platform/HttpModules/OutputCaching/OutputCacheModule.cs
  DNN Platform/HttpModules/Personalization/PersonalizationModule.cs
  DNN Platform/HttpModules/RequestFilter/RequestFilterModule.cs
  DNN Platform/HttpModules/Services/ServicesModule.cs
  DNN Platform/HttpModules/UrlRewrite/BasicUrlRewriter.cs
  DNN Platform/HttpModules/UrlRewrite/FriendlyUrlProvider.cs
  DNN Platform/HttpModules/UrlRewrite/UrlRewriteModule.cs
  DNN Platform/HttpModules/Users Online/UsersOnlineModule.cs
  DNN Platform/Library/Application/ApplicationStatusInfo.cs
  DNN Platform/Library/Application/AssemblyStatusAttribute.cs
  DNN Platform/Library/Application/DotNetNukeContext.cs
  DNN Platform/Library/Collections/CollectionExtensions.cs
  DNN Platform/Library/Collections/ExclusiveLockStrategy.cs
  DNN Platform/Library/Collections/IIndexable.cs
  DNN Platform/Library/Collections/ILockStrategy.cs
  DNN Platform/Library/Collections/ISharedCollectionLock.cs
  DNN Platform/Library/Collections/ReadLockRequiredException.cs
  DNN Platform/Library/Collections/WriteLockRequiredException.cs
  DNN Platform/Library/Common/Utilities/CBO.cs
  DNN Platform/Library/ComponentModel/ComponentTypeCollection.cs
  DNN Platform/Library/ComponentModel/DataAnnotations/DeclareColumnsAttribute.cs
  DNN Platform/Library/ComponentModel/DataAnnotations/IgnoreColumnAttribute.cs
  DNN Platform/Library/ComponentModel/DataAnnotations/IncludeColumnAttribute.cs
  DNN Platform/Library/ComponentModel/DataAnnotations/ReadOnlyColumnAttribute.cs
  DNN Platform/Library/Entities/Modules/Prompt/ListModules.cs
  DNN Platform/Library/Entities/Modules/Settings/ModuleSettingAttribute.cs
  DNN Platform/Library/Entities/Modules/Settings/PortalSettingAttribute.cs
  DNN Platform/Library/Entities/Modules/Settings/TabModuleSettingAttribute.cs
  DNN Platform/Library/Entities/Portals/PortalAliasInfo.cs
  DNN Platform/Library/Entities/Urls/AdvancedUrlRewriter.cs
  DNN Platform/Library/Entities/Urls/RewriteController.cs
  DNN Platform/Library/Entities/Urls/TabIndexController.cs
  DNN Platform/Library/Entities/Users/Profile/UserProfile.cs
  DNN Platform/Library/Prompt/Attributes/ConsoleCommandParameterAttribute.cs
  DNN Platform/Library/Services/FileSystem/IFileManager.cs
  DNN Platform/Library/Services/Mail/Mail.cs
  DNN Platform/Library/Services/Search/Internals/Constants.cs
  DNN Platform/Library/Services/Search/ModuleIndexer.cs
  DNN Platform/Library/Services/Tokens/BaseCustomTokenReplace.cs
  DNN Platform/Library/Services/Tokens/CoreTokenProvider.cs
  DNN Platform/Library/Services/Tokens/TokenContext.cs
  DNN Platform/Library/Services/Tokens/TokenReplace.cs
  DNN Platform/Library/Services/Upgrade/Upgrade.cs
  DNN Platform/Library/WebControls/WebControlBase.cs
Labels: Type: Documentation, Type: Maintenance

#4210 Remove impractical rule
  .github/PULL_REQUEST_PROCESS.md
Labels: Type: Maintenance

#4220 Ensure comments are only inserted when necessary
  DNN Platform/Library/Services/Installer/XmlMerge.cs
Labels: Type: Bug

#4218 avoid I/O process frequency during export process.
  DNN Platform/Modules/DnnExportImport/Components/Services/PackagesExportService.cs
Labels: Type: Bug

#4223 Issue-4222 - Registration Module system messages use an incorrect language
  DNN Platform/HttpModules/Membership/MembershipModule.cs
Labels: Type: Bug

#4226 Updated .NET & SQL requirements in InstallWizard localization files
  DNN Platform/Website/Install/App_LocalResources/Installwizard.aspx.de-DE.resx
  DNN Platform/Website/Install/App_LocalResources/Installwizard.aspx.es-ES.resx
  DNN Platform/Website/Install/App_LocalResources/Installwizard.aspx.fr-FR.resx
  DNN Platform/Website/Install/App_LocalResources/Installwizard.aspx.it-IT.resx
  DNN Platform/Website/Install/App_LocalResources/Installwizard.aspx.nl-NL.resx
  DNN Platform/Website/Install/App_LocalResources/Installwizard.aspx.resx
Labels: Type: Documentation

#4225 Moved UserMode from PortalSettings to Personalization class
  DNN Platform/Admin Modules/Dnn.Modules.Console/Components/BusinessController.cs
  DNN Platform/DotNetNuke.Website.Deprecated/admin/ControlPanel/AddModule.ascx.cs
  DNN Platform/DotNetNuke.Website.Deprecated/admin/ControlPanel/ControlBar.ascx.cs
  DNN Platform/Library/Common/Globals.cs
  DNN Platform/Library/Entities/Portals/PortalSettings.cs
  DNN Platform/Library/Services/Personalization/Personalization.cs
  DNN Platform/Library/UI/Containers/ActionBase.cs
  DNN Platform/Library/UI/Containers/ActionManager.cs
  DNN Platform/Library/UI/ControlPanels/ControlPanelBase.cs
  DNN Platform/Library/UI/Modules/Html5/Html5ModuleTokenReplace.cs
  DNN Platform/Library/UI/Modules/ModuleHost.cs
  DNN Platform/Library/UI/Modules/ModuleInstanceContext.cs
  DNN Platform/Library/UI/Skins/Pane.cs
  DNN Platform/Library/UI/WebControls/ActionLink.cs
  DNN Platform/Modules/HTML/Components/HtmlTextController.cs
  DNN Platform/Modules/HTML/HtmlModule.ascx.cs
  DNN Platform/Website/Default.aspx.cs
  DNN Platform/Website/admin/Containers/PrintModule.ascx.cs
  DNN Platform/Website/admin/Containers/Title.ascx.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Pages/PagesControllerImpl.cs
  Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/Controllers/ContentEditorManager.cs
  Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/Items/AddExistingModuleMenu.cs
  Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/Items/AddModuleMenu.cs
  Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/Items/ExitEditModeMenu.cs
  Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/Items/PageSettingsMenu.cs
  Dnn.AdminExperience/Library/Dnn.PersonaBar.Library/Containers/PersonaBarContainer.cs
Labels: Type: Documentation, Type: Maintenance

#4231 Resolved all build warnings in RazorHost project
  DNN Platform/Library/Entities/Modules/IActionable.cs
  DNN Platform/Library/Entities/Modules/ModuleSettingsBase.cs
  DNN Platform/Library/UI/Modules/IModuleControl.cs
  DNN Platform/Library/UI/Modules/ISettingsControl.cs
  DNN Platform/Library/UI/Modules/ModuleUserControlBase.cs
  DNN Platform/Modules/RazorHost/AddScript.ascx.cs
  DNN Platform/Modules/RazorHost/CreateModule.ascx.cs
  DNN Platform/Modules/RazorHost/DotNetNuke.Modules.RazorHost.csproj
  DNN Platform/Modules/RazorHost/EditScript.ascx.cs
  DNN Platform/Modules/RazorHost/RazorHost.ascx.cs
  DNN Platform/Modules/RazorHost/RazorHostSettingsExtensions.cs
  DNN Platform/Modules/RazorHost/Settings.ascx.cs
Labels: Type: Documentation, Type: Maintenance

#4211 Resolves some build warnings in the ImportExport project.
  DNN Platform/Modules/DnnExportImport/Components/Common/CompressionUtil.cs
  DNN Platform/Modules/DnnExportImport/Components/Common/Constants.cs
  DNN Platform/Modules/DnnExportImport/Components/Common/Enums.cs
  DNN Platform/Modules/DnnExportImport/Components/Common/SummaryList.cs
  DNN Platform/Modules/DnnExportImport/Components/Common/Util.cs
  DNN Platform/Modules/DnnExportImport/Components/Controllers/BaseController.cs
  DNN Platform/Modules/DnnExportImport/Components/Controllers/EntitiesController.cs
  DNN Platform/Modules/DnnExportImport/Components/Controllers/ExportController.cs
  DNN Platform/Modules/DnnExportImport/Components/Dto/SummaryItem.cs
  DNN Platform/Modules/DnnExportImport/Components/Services/PagesExportService.cs
  DNN Platform/Modules/DnnExportImport/Components/Services/UsersDataExportService.cs
Labels: Type: Documentation, Type: Maintenance

#4215 Resolved 249 build warnings in Library project
  DNN Platform/DotNetNuke.Abstractions/Application/IApplicationStatusInfo.cs
  DNN Platform/Library/Collections/PageSelector{T}.cs
  DNN Platform/Library/Common/Controls/Form.cs
  DNN Platform/Library/Common/Extensions/HttpContextDependencyInjectionExtensions.cs
  DNN Platform/Library/Common/Globals.cs
  DNN Platform/Library/Common/Utilities/HtmlUtils.cs
  DNN Platform/Library/DotNetNuke.Library.csproj
  DNN Platform/Library/Services/Personalization/PersonalizationController.cs
Labels: Type: Documentation, Type: Maintenance

#4224 Resolves some build warnings in DDRMenu Project
  DNN Platform/Library/UI/Containers/ActionBase.cs
  DNN Platform/Library/UI/Containers/IActionControl.cs
  DNN Platform/Modules/DDRMenu/Actions.cs
  DNN Platform/Modules/DDRMenu/Common/DNNContext.cs
  DNN Platform/Modules/DDRMenu/Common/PathResolver.cs
  DNN Platform/Modules/DDRMenu/Common/Utilities.cs
  DNN Platform/Modules/DDRMenu/Controller.cs
  DNN Platform/Modules/DDRMenu/DDRMenuControl.cs
  DNN Platform/Modules/DDRMenu/DDRMenuNavigationProvider.cs
  DNN Platform/Modules/DDRMenu/DNNAbstract.cs
  DNN Platform/Modules/DDRMenu/INodeManipulator.cs
  DNN Platform/Modules/DDRMenu/Localisation/Apollo.cs
  DNN Platform/Modules/DDRMenu/Localisation/Ealo.cs
  DNN Platform/Modules/DDRMenu/Localisation/Generic.cs
  DNN Platform/Modules/DDRMenu/Localisation/ILocalisation.cs
  DNN Platform/Modules/DDRMenu/Localisation/Localiser.cs
  DNN Platform/Modules/DDRMenu/MenuBase.cs
  DNN Platform/Modules/DDRMenu/MenuNode.cs
  DNN Platform/Modules/DDRMenu/MenuSettings.ascx.cs
  DNN Platform/Modules/DDRMenu/MenuView.ascx.cs
  DNN Platform/Modules/DDRMenu/Settings.cs
  DNN Platform/Modules/DDRMenu/SkinObject.cs
  DNN Platform/Modules/DDRMenu/TemplateEngine/RazorTemplateProcessor.cs
  DNN Platform/Modules/DDRMenu/TemplateEngine/TemplateDefinition.cs
  DNN Platform/Modules/DDRMenu/TemplateEngine/TokenTemplateProcessor.cs
  DNN Platform/Modules/DDRMenu/TemplateEngine/XsltTemplateProcessor.cs
Labels: Type: Documentation, Type: Maintenance

#4236 Resolves some more build warnings on library project
  DNN Platform/Library/Common/Controls/Form.cs
  DNN Platform/Library/Common/HttpContextSource.cs
  DNN Platform/Library/Common/Initialize.cs
  DNN Platform/Library/Common/Internal/EventHandlersContainer.cs
  DNN Platform/Library/Common/Internal/IEventHandlersContainer.cs
  DNN Platform/Library/ComponentModel/ComponentBase.cs
  DNN Platform/Library/Entities/EventManager.cs
  DNN Platform/Library/Entities/IEventManager.cs
  DNN Platform/Library/Framework/ServiceLocator.cs
  DNN Platform/Library/Services/Tokens/BaseCustomTokenReplace.cs
  DNN Platform/Tests/DotNetNuke.Tests.Core/Providers/Folder/FileManagerTests.cs
Labels: Type: Documentation, Type: Maintenance

#4238 check the module permission to add module.
  DNN Platform/DotNetNuke.Web/InternalServices/ControlBarController.cs
Labels: Type: Bug

#4240 Adding Page ID to the Page Management
  Dnn.AdminExperience/ClientSide/Pages.Web/src/components/PageTypeSelector/PageTypeSelector.jsx
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Pages/App_LocalResources/Pages.resx
Labels: Type: Enhancement

#4244 Deprecates IEventLogController in favor of DI
  DNN Platform/Library/Entities/Users/Social/RelationshipControllerImpl.cs
  DNN Platform/Library/Obsolete/EventLogController.cs
  DNN Platform/Library/Services/Log/EventLog/IEventLogController.cs
  DNN Platform/Tests/DotNetNuke.Tests.Core/Controllers/Social/RelationshipControllerTests.cs
Labels: Type: Documentation, Type: Maintenance

#4248 SCAYT language code configuration fixed
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Web/EditorControl.cs
Labels: Type: Bug

#4245 Relaxed compile warnings on Tests projects
  DNN Platform/Tests/.editorconfig
  DNN_Platform.sln
  Dnn.AdminExperience/Tests/.editorconfig
Labels: Type: Documentation, Type: Maintenance

#4251 Ensure new Localization HTTP module is running soon enough
  DNN Platform/Website/Install/Config/09.08.00.config
Labels: Type: Bug

#4253 Merge latest changes from 9.8.0 into develop
  Build/Symbols/DotNetNuke_Symbols.dnn
  DNN Platform/Admin Modules/Dnn.Modules.Console/dnn_Console.dnn
  DNN Platform/Components/Telerik/DotNetNuke.Telerik.Web.dnn
  DNN Platform/Connectors/Azure/AzureConnector.dnn
  DNN Platform/Connectors/GoogleAnalytics/GoogleAnalyticsConnector.dnn
  DNN Platform/DotNetNuke.Web.Deprecated/dnn_Web_Deprecated.dnn
  DNN Platform/DotNetNuke.Web/InternalServices/ControlBarController.cs
  DNN Platform/DotNetNuke.WebUtility/DotNetNuke.ClientAPI.dnn
  DNN Platform/DotNetNuke.Website.Deprecated/dnn_Website_Deprecated.dnn
  DNN Platform/Modules/CoreMessaging/CoreMessaging.dnn
  DNN Platform/Modules/DDRMenu/DDRMenu.dnn
  DNN Platform/Modules/DigitalAssets/dnn_DigitalAssets.dnn
  DNN Platform/Modules/DnnExportImport/dnn_SiteExportImport.dnn
  DNN Platform/Modules/Groups/SocialGroups.dnn
  DNN Platform/Modules/HTML/dnn_HTML.dnn
  DNN Platform/Modules/HtmlEditorManager/dnn_HtmlEditorManager.dnn
  DNN Platform/Modules/Journal/Journal.dnn
  DNN Platform/Modules/MemberDirectory/MemberDirectory.dnn
  DNN Platform/Modules/RazorHost/Manifest.dnn
  DNN Platform/Modules/RazorHost/RazorHost.dnn
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/components/FolderSelector/FolderPicker.jsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/components/FolderSelector/FolderSelector.jsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/package.json
  DNN Platform/Modules/ResourceManager/ResourceManager.dnn
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Facebook/Facebook_Auth.dnn
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Google/Google_Auth.dnn
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.LiveConnect/Live_Auth.dnn
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Twitter/Twitter_Auth.dnn
  DNN Platform/Providers/CachingProviders/DotNetNuke.Providers.Caching.SimpleWebFarmCachingProvider/SimpleWebFarmCachingProvider.dnn
  DNN Platform/Providers/ClientCapabilityProviders/Provider.AspNetCCP/AspNetClientCapabilityProvider.dnn
  DNN Platform/Providers/FolderProviders/FolderProviders.dnn
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/DNNConnect.CKEditorProvider.dnn
  DNN Platform/Skins/Xcillion/DNN_Skin_Xcillion.dnn
  DNN Platform/Website/Install/Config/09.08.00.config
  Dnn.AdminExperience/ClientSide/AdminLogs.Web/package.json
  Dnn.AdminExperience/ClientSide/Bundle.Web/package.json
  Dnn.AdminExperience/ClientSide/Dnn.React.Common/package.json
  Dnn.AdminExperience/ClientSide/Extensions.Web/package.json
  Dnn.AdminExperience/ClientSide/Licensing.Web/package.json
  Dnn.AdminExperience/ClientSide/Pages.Web/package.json
  Dnn.AdminExperience/ClientSide/Prompt.Web/package.json
  Dnn.AdminExperience/ClientSide/Roles.Web/package.json
  Dnn.AdminExperience/ClientSide/Security.Web/package.json
  Dnn.AdminExperience/ClientSide/Seo.Web/package.json
  Dnn.AdminExperience/ClientSide/Servers.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteImportExport.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteSettings.Web/package.json
  Dnn.AdminExperience/ClientSide/Sites.Web/package.json
  Dnn.AdminExperience/ClientSide/Sites.Web/src/_exportables/package.json
  Dnn.AdminExperience/ClientSide/TaskScheduler.Web/package.json
  Dnn.AdminExperience/ClientSide/Themes.Web/package.json
  Dnn.AdminExperience/ClientSide/Users.Web/package.json
  Dnn.AdminExperience/ClientSide/Users.Web/src/_exportables/package.json
  Dnn.AdminExperience/ClientSide/Vocabularies.Web/package.json
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Dnn.PersonaBar.Extensions.dnn
  Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/Dnn.EditBar.UI.dnn
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/Dnn.PersonaBar.UI.dnn
  SolutionInfo.cs
  package.json
Labels: Type: Maintenance

#4264 Remove Localization HTTP module from config
  DNN Platform/Website/development.config
  DNN Platform/Website/release.config
Labels: Type: Bug

#4265 Fix Localization Issues
  DNN Platform/HttpModules/Localization/LocalizationModule.cs
  DNN Platform/HttpModules/Membership/MembershipModule.cs
  DNN Platform/Library/Services/Localization/Localization.cs
Labels: Type: Bug
