Repository dnnsoftware/Dnn.Platform, pull requests merged in 2020-09, with the labels that each got.

#4026 Fixes 2 wrong svg imports in resource-manager
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/components/FolderSelector/FolderSelector.jsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/components/FolderSelector/Folders.jsx
Labels: Type: Bug

#4025 Fixes frontend build warnigns in resource-manager
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/components/FolderDetails.jsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/components/Permissions.jsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/containers/AssetsPanelContainer.jsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/containers/DropZoneContainer.jsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/globals/dnnSf.js
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/webpack.config.js
Labels: Type: Build/Release

#4024 Removes svg from resource-manager build
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/webpack.config.js
Labels: Type: Build/Release

#4030 Correct nl-NL typo's in Install & Upgrade .resx
  DNN Platform/Website/Install/App_LocalResources/Installwizard.aspx.nl-NL.resx
  DNN Platform/Website/Install/App_LocalResources/UpgradeWizard.aspx.nl-NL.resx
Labels: Type: Bug

#4033 Add official code of conduct file
  .github/CODE_OF_CONDUCT.md
Labels: Type: Documentation

#4034 Correct location for code of conduct
  CODE_OF_CONDUCT.md
Labels: Type: Documentation

#4041 Fixed an issue with user management in portal groups
  DNN Platform/Library/Entities/Users/IUserController.cs
  DNN Platform/Library/Entities/Users/UserController.cs
Labels: Type: Bug

#4021 Created IPortalAliasService for Dependency Injection
  DNN Platform/DotNetNuke.Abstractions/Portals/IPortalAliasInfo.cs
  DNN Platform/DotNetNuke.Abstractions/Portals/IPortalAliasService.cs
  DNN Platform/DotNetNuke.Abstractions/Portals/IPortalInfo.cs
  DNN Platform/DotNetNuke.Abstractions/Urls/BrowserTypes.cs
  DNN Platform/Library/Entities/Portals/PortalAliasCollection.cs
  DNN Platform/Library/Entities/Portals/PortalAliasController.cs
  DNN Platform/Library/Entities/Portals/PortalAliasInfo.cs
  DNN Platform/Library/Entities/Portals/PortalInfo.cs
  DNN Platform/Library/Entities/Urls/BrowserTypes.cs
  DNN Platform/Library/Obsolete/PortalAliasController.cs
  DNN Platform/Library/Startup.cs
  DNN Platform/Tests/DotNetNuke.Tests.Web/Api/PortalAliasRouteManagerTests.cs
  DNN Platform/Tests/DotNetNuke.Tests.Web/Api/ServiceRoutingManagerTests.cs
Labels: Type: Enhancement

#4048 Fixed bug with hierarchical vocabularies
  Dnn.AdminExperience/ClientSide/Vocabularies.Web/src/components/VocabularyList/RightPane/index.jsx
Labels: Type: Bug

#4052 Updated IHostSettingsService to use IDictionary instead of Dictionary
  DNN Platform/DotNetNuke.Abstractions/Application/IHostSettingsService.cs
  DNN Platform/Library/Entities/Controllers/HostController.cs
  DNN Platform/Library/Obsolete/HostController.cs
Labels: Type: Bug

#4055 Change 'DNN Error' to 'Application Error'
  DNN Platform/Website/ErrorPage.aspx
Labels: Type: Maintenance

#4032 Implement clickable column headers on the users table
  Dnn.AdminExperience/ClientSide/Dnn.React.Common/src/GridCell/index.jsx
  Dnn.AdminExperience/ClientSide/Users.Web/src/_exportables/package.json
  Dnn.AdminExperience/ClientSide/Users.Web/src/_exportables/src/components/UserTable/HeaderRow/index.jsx
  Dnn.AdminExperience/ClientSide/Users.Web/src/_exportables/src/components/UserTable/HeaderRow/style.less
  Dnn.AdminExperience/ClientSide/Users.Web/src/_exportables/src/components/UserTable/index.jsx
  Dnn.AdminExperience/ClientSide/Users.Web/src/components/Body/index.jsx
Labels: Area: AE > PersonaBar Ext > Users.Web, Type: Enhancement

#4022 pencil icon moved to the right ... menu
  Dnn.AdminExperience/ClientSide/Pages.Web/src/components/dnn-persona-bar-page-treeview/src/PersonaBarPageTreeMenu.jsx
  Dnn.AdminExperience/ClientSide/Pages.Web/src/components/dnn-persona-bar-page-treeview/src/PersonaBarPageTreeview.jsx
  Dnn.AdminExperience/ClientSide/Pages.Web/src/components/dnn-persona-bar-page-treeview/src/styles.less
Labels: Type: Enhancement

#4063 Create dropdown for refresh/sync and restyle
  DNN Platform/Modules/ResourceManager/App_LocalResources/ResourceManager.resx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/containers/TopBarContainer.jsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/less/Assets.less
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/less/components.less
Labels: Type: Enhancement

#4057 Updates debug build documentation to indicate restarting visual studio
  .github/BUILD.md
Labels: Type: Documentation

#4067 Issue-4066 - Create multiple pages validation passed with same page name on same hierarchy
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Pages/BulkPagesController.cs
Labels: Type: Bug

#4072 Wire up sync this folder and recursive
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/actions/folderPanelActions.js
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/containers/TopBarContainer.jsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/services/itemsService.js
  DNN Platform/Modules/ResourceManager/Services/ItemsController.cs
  Dnn.AdminExperience/ClientSide/Dnn.React.Common/src/Dropdown/index.jsx
Labels: Type: Feature

#4070 Issue 4038
  DNN Platform/Library/Entities/Host/Host.cs
  Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/HttpModules/EditBarModule.cs
  Dnn.AdminExperience/Library/Dnn.PersonaBar.Library/Containers/PersonaBarContainer.cs
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/App_LocalResources/PersonaBar.resx
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/scripts/main.js
Labels: Area: AE > Dnn.PersonaBar.UI, Type: Feature

#4050 Treat Build Warnings as Errors for Abstractions & DependencyInjection Projects
  DNN Platform/DotNetNuke.Abstractions/Application/IApplicationInfo.cs
  DNN Platform/DotNetNuke.Abstractions/Application/IApplicationStatusInfo.cs
  DNN Platform/DotNetNuke.Abstractions/Application/IDnnContext.cs
  DNN Platform/DotNetNuke.Abstractions/Application/IHostSettingsService.cs
  DNN Platform/DotNetNuke.Abstractions/Application/ReleaseMode.cs
  DNN Platform/DotNetNuke.Abstractions/Application/UpgradeStatus.cs
  DNN Platform/DotNetNuke.Abstractions/DotNetNuke.Abstractions.csproj
  DNN Platform/DotNetNuke.Abstractions/INavigationManager.cs
  DNN Platform/DotNetNuke.Abstractions/Portals/IPortalAliasInfo.cs
  DNN Platform/DotNetNuke.Abstractions/Portals/IPortalAliasService.cs
  DNN Platform/DotNetNuke.Abstractions/Portals/IPortalInfo.cs
  DNN Platform/DotNetNuke.Abstractions/Portals/IPortalSettings.cs
  DNN Platform/DotNetNuke.Abstractions/Prompt/ICommand.cs
  DNN Platform/DotNetNuke.Abstractions/Prompt/ICommandHelp.cs
  DNN Platform/DotNetNuke.Abstractions/Prompt/ICommandOption.cs
  DNN Platform/DotNetNuke.Abstractions/Prompt/ICommandRepository.cs
  DNN Platform/DotNetNuke.Abstractions/Prompt/IConsoleCommand.cs
  DNN Platform/DotNetNuke.Abstractions/Prompt/IConsoleResultModel.cs
  DNN Platform/DotNetNuke.Abstractions/Prompt/IPagingInfo.cs
  DNN Platform/DotNetNuke.Abstractions/Settings/IConfigurationSetting.cs
  DNN Platform/DotNetNuke.Abstractions/Urls/BrowserTypes.cs
  DNN Platform/DotNetNuke.Abstractions/Users/IUserInfo.cs
  DNN Platform/DotNetNuke.DependencyInjection/DotNetNuke.DependencyInjection.csproj
  DNN Platform/DotNetNuke.DependencyInjection/Extensions/TypeExtensions.cs
  DNN Platform/DotNetNuke.DependencyInjection/IDnnStartup.cs
Labels: Type: Maintenance

#4059 Fixed an issue where a new page was created by "Add page", the "Advanced/More/Secure Connection" property was always stored as "Off", regardless of the setting in the UI
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Pages/PagesControllerImpl.cs
Labels: Type: Bug

#4064 Ability to set mobile view cookie name in root web.config
  DNN Platform/Library/Entities/Urls/FriendlyUrlController.cs
  DNN Platform/Website/Install/Config/09.07.02.config
  DNN Platform/Website/development.config
  DNN Platform/Website/release.config
Labels: Type: Enhancement

#4053 Use request scope in PortalModuleBase
  DNN Platform/Library/Common/ServiceScopeContainer.cs
  DNN Platform/Library/DotNetNuke.Library.csproj
  DNN Platform/Library/Entities/Modules/PortalModuleBase.cs
  DNN Platform/Tests/DotNetNuke.Tests.Web/Api/Internals/ServiceContainerTests.cs
  DNN Platform/Tests/DotNetNuke.Tests.Web/DotNetNuke.Tests.Web.csproj
Labels: Type: Enhancement

#4068 Warns admins about running search indexer on wrong server
  Dnn.AdminExperience/ClientSide/TaskScheduler.Web/src/components/scheduler/schedulerEditor/index.jsx
  Dnn.AdminExperience/ClientSide/TaskScheduler.Web/src/utils/index.jsx
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/TaskScheduler/TaskSchedulerController.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/TaskSchedulerController.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.TaskScheduler/App_LocalResources/TaskScheduler.resx
Labels: Type: Enhancement

#4065 Fixes stylecop warnings in resource manager project.
  DNN Platform/Modules/ResourceManager/Components/Common/Utils.cs
  DNN Platform/Modules/ResourceManager/Components/Constants.cs
  DNN Platform/Modules/ResourceManager/Components/GroupManager.cs
  DNN Platform/Modules/ResourceManager/Components/IGroupManager.cs
  DNN Platform/Modules/ResourceManager/Components/IItemsManager.cs
  DNN Platform/Modules/ResourceManager/Components/ILocalizationController.cs
  DNN Platform/Modules/ResourceManager/Components/IPermissionsManager.cs
  DNN Platform/Modules/ResourceManager/Components/ISearchController.cs
  DNN Platform/Modules/ResourceManager/Components/IThumbnailsManager.cs
  DNN Platform/Modules/ResourceManager/Components/ItemsManager.cs
  DNN Platform/Modules/ResourceManager/Components/LocalizationController.cs
  DNN Platform/Modules/ResourceManager/Components/Models/Localization.cs
  DNN Platform/Modules/ResourceManager/Components/Models/ThumbnailContent.cs
  DNN Platform/Modules/ResourceManager/Components/PermissionHelper.cs
  DNN Platform/Modules/ResourceManager/Components/PermissionsManager.cs
  DNN Platform/Modules/ResourceManager/Components/SearchController.cs
  DNN Platform/Modules/ResourceManager/Components/SettingsManager.cs
  DNN Platform/Modules/ResourceManager/Components/ThumbnailsManager.cs
  DNN Platform/Modules/ResourceManager/Dnn.Modules.ResourceManager.csproj
  DNN Platform/Modules/ResourceManager/EditFolderMapping.ascx.cs
  DNN Platform/Modules/ResourceManager/Exceptions/FolderPermissionNotMetException.cs
  DNN Platform/Modules/ResourceManager/Exceptions/ModeValidationException.cs
  DNN Platform/Modules/ResourceManager/Exceptions/NotFoundException.cs
  DNN Platform/Modules/ResourceManager/Helpers/LocalizationHelper.cs
  DNN Platform/Modules/ResourceManager/Properties/AssemblyInfo.cs
  DNN Platform/Modules/ResourceManager/Services/Attributes/ResourceManagerExceptionFilter.cs
  DNN Platform/Modules/ResourceManager/Services/Dto/CreateNewFolderRequest.cs
  DNN Platform/Modules/ResourceManager/Services/Dto/DeleteFileRequest.cs
  DNN Platform/Modules/ResourceManager/Services/Dto/DeleteFolderRequest.cs
  DNN Platform/Modules/ResourceManager/Services/Dto/FileDetailsRequest.cs
  DNN Platform/Modules/ResourceManager/Services/Dto/FolderDetailsRequest.cs
  DNN Platform/Modules/ResourceManager/Services/Dto/FolderPermissions.cs
  DNN Platform/Modules/ResourceManager/Services/Dto/Permission.cs
  DNN Platform/Modules/ResourceManager/Services/Dto/Permissions.cs
  DNN Platform/Modules/ResourceManager/Services/Dto/RolePermission.cs
  DNN Platform/Modules/ResourceManager/Services/Dto/ThumbnailDownloadRequest.cs
  DNN Platform/Modules/ResourceManager/Services/Dto/UserPermission.cs
  DNN Platform/Modules/ResourceManager/Services/ItemsController.cs
  DNN Platform/Modules/ResourceManager/Services/LocalizationController.cs
  DNN Platform/Modules/ResourceManager/Services/RouteMapper.cs
  DNN Platform/Modules/ResourceManager/Settings.ascx.cs
  DNN Platform/Modules/ResourceManager/View.ascx.cs
  SolutionInfo.cs
Labels: Type: Documentation

#4076 Fixed an issue that prevents 9.7.0 to 9.7.1 upgrades
  DNN Platform/Website/DotNetNuke.Website.csproj
  DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.06.01.SqlDataProvider
  DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.07.00.SqlDataProvider
  DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.07.02.SqlDataProvider
Labels: Type: Bug

#4078 Updates versions as per release candidate creation
  .github/ISSUE_TEMPLATE/bug-report.md
  Build/Symbols/DotNetNuke_Symbols.dnn
  DNN Platform/Admin Modules/Dnn.Modules.Console/dnn_Console.dnn
  DNN Platform/Admin Modules/Dnn.Modules.ModuleCreator/dnn_ModuleCreator.dnn
  DNN Platform/Components/Telerik/DotNetNuke.Telerik.Web.dnn
  DNN Platform/Connectors/Azure/AzureConnector.dnn
  DNN Platform/Connectors/GoogleAnalytics/GoogleAnalyticsConnector.dnn
  DNN Platform/Dnn.AuthServices.Jwt/Dnn.Jwt.dnn
  DNN Platform/DotNetNuke.Web.Deprecated/dnn_Web_Deprecated.dnn
  DNN Platform/DotNetNuke.WebUtility/DotNetNuke.ClientAPI.dnn
  DNN Platform/DotNetNuke.Website.Deprecated/dnn_Website_Deprecated.dnn
  DNN Platform/Modules/CoreMessaging/CoreMessaging.dnn
  DNN Platform/Modules/DDRMenu/DDRMenu.dnn
  DNN Platform/Modules/DigitalAssets/dnn_DigitalAssets.dnn
  DNN Platform/Modules/DnnExportImport/dnn_SiteExportImport.dnn
  DNN Platform/Modules/Groups/SocialGroups.dnn
  DNN Platform/Modules/HTML/dnn_HTML.dnn
  DNN Platform/Modules/HtmlEditorManager/dnn_HtmlEditorManager.dnn
  DNN Platform/Modules/Journal/Journal.dnn
  DNN Platform/Modules/MemberDirectory/MemberDirectory.dnn
  DNN Platform/Modules/RazorHost/Manifest.dnn
  DNN Platform/Modules/RazorHost/RazorHost.dnn
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Facebook/Facebook_Auth.dnn
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Google/Google_Auth.dnn
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.LiveConnect/Live_Auth.dnn
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Twitter/Twitter_Auth.dnn
  DNN Platform/Providers/CachingProviders/DotNetNuke.Providers.Caching.SimpleWebFarmCachingProvider/SimpleWebFarmCachingProvider.dnn
  DNN Platform/Providers/ClientCapabilityProviders/Provider.AspNetCCP/AspNetClientCapabilityProvider.dnn
  DNN Platform/Providers/FolderProviders/FolderProviders.dnn
  DNN Platform/Skins/Xcillion/DNN_Skin_Xcillion.dnn
  Dnn.AdminExperience/ClientSide/AdminLogs.Web/package.json
  Dnn.AdminExperience/ClientSide/Bundle.Web/package.json
  Dnn.AdminExperience/ClientSide/Dnn.React.Common/package.json
  Dnn.AdminExperience/ClientSide/Extensions.Web/package.json
  Dnn.AdminExperience/ClientSide/Licensing.Web/package.json
  Dnn.AdminExperience/ClientSide/Pages.Web/package.json
  Dnn.AdminExperience/ClientSide/Prompt.Web/package.json
  Dnn.AdminExperience/ClientSide/Roles.Web/package.json
  Dnn.AdminExperience/ClientSide/Security.Web/package.json
  Dnn.AdminExperience/ClientSide/Seo.Web/package.json
  Dnn.AdminExperience/ClientSide/Servers.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteImportExport.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteSettings.Web/package.json
  Dnn.AdminExperience/ClientSide/Sites.Web/package.json
  Dnn.AdminExperience/ClientSide/Sites.Web/src/_exportables/package.json
  Dnn.AdminExperience/ClientSide/TaskScheduler.Web/package.json
  Dnn.AdminExperience/ClientSide/Themes.Web/package.json
  Dnn.AdminExperience/ClientSide/Users.Web/package.json
  Dnn.AdminExperience/ClientSide/Users.Web/src/_exportables/package.json
  Dnn.AdminExperience/ClientSide/Vocabularies.Web/package.json
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Dnn.PersonaBar.Extensions.dnn
  Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/Dnn.EditBar.UI.dnn
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/Dnn.PersonaBar.UI.dnn
  SolutionInfo.cs
  package.json
Labels: Type: Build/Release

#4080 Enabled StyleCop & Fixed All Build Errors/Warnings
  DNN Platform/Modules/ResourceManager/Components/Common/Utils.cs
  DNN Platform/Modules/ResourceManager/Components/Constants.cs
  DNN Platform/Modules/ResourceManager/Components/GroupManager.cs
  DNN Platform/Modules/ResourceManager/Components/IGroupManager.cs
  DNN Platform/Modules/ResourceManager/Components/IItemsManager.cs
  DNN Platform/Modules/ResourceManager/Components/IPermissionsManager.cs
  DNN Platform/Modules/ResourceManager/Components/ISearchController.cs
  DNN Platform/Modules/ResourceManager/Components/IThumbnailsManager.cs
  DNN Platform/Modules/ResourceManager/Components/ItemsManager.cs
  DNN Platform/Modules/ResourceManager/Components/LocalizationController.cs
  DNN Platform/Modules/ResourceManager/Components/Models/Localization.cs
  DNN Platform/Modules/ResourceManager/Components/Models/ThumbnailContent.cs
  DNN Platform/Modules/ResourceManager/Components/PermissionHelper.cs
  DNN Platform/Modules/ResourceManager/Components/PermissionsManager.cs
  DNN Platform/Modules/ResourceManager/Components/SearchController.cs
  DNN Platform/Modules/ResourceManager/Components/SettingsManager.cs
  DNN Platform/Modules/ResourceManager/Components/ThumbnailsManager.cs
  DNN Platform/Modules/ResourceManager/Dnn.Modules.ResourceManager.csproj
  DNN Platform/Modules/ResourceManager/Exceptions/FolderPermissionNotMetException.cs
  DNN Platform/Modules/ResourceManager/Exceptions/ModeValidationException.cs
  DNN Platform/Modules/ResourceManager/Exceptions/NotFoundException.cs
  DNN Platform/Modules/ResourceManager/Helpers/LocalizationHelper.cs
  DNN Platform/Modules/ResourceManager/Properties/AssemblyInfo.cs
  DNN Platform/Modules/ResourceManager/Services/Attributes/ResourceManagerExceptionFilter.cs
  DNN Platform/Modules/ResourceManager/Services/Dto/CreateNewFolderRequest.cs
  DNN Platform/Modules/ResourceManager/Services/Dto/DeleteFileRequest.cs
  DNN Platform/Modules/ResourceManager/Services/Dto/DeleteFolderRequest.cs
  DNN Platform/Modules/ResourceManager/Services/Dto/FileDetailsRequest.cs
  DNN Platform/Modules/ResourceManager/Services/Dto/FolderDetailsRequest.cs
  DNN Platform/Modules/ResourceManager/Services/Dto/FolderPermissions.cs
  DNN Platform/Modules/ResourceManager/Services/Dto/Permission.cs
  DNN Platform/Modules/ResourceManager/Services/Dto/Permissions.cs
  DNN Platform/Modules/ResourceManager/Services/Dto/RolePermission.cs
  DNN Platform/Modules/ResourceManager/Services/Dto/ThumbnailDownloadRequest.cs
  DNN Platform/Modules/ResourceManager/Services/Dto/UserPermission.cs
  DNN Platform/Modules/ResourceManager/Services/ItemsController.cs
  DNN Platform/Modules/ResourceManager/Services/LocalizationController.cs
  DNN Platform/Modules/ResourceManager/Services/RouteMapper.cs
  DNN Platform/Modules/ResourceManager/Settings.ascx.cs
  DNN Platform/Modules/ResourceManager/View.ascx.cs
  DNN Platform/Modules/ResourceManager/packages.config
  DNN Platform/Modules/ResourceManager/web.Debug.config
  DNN Platform/Modules/ResourceManager/web.Release.config
  DNN Platform/Modules/ResourceManager/web.config
Labels: Type: Maintenance

#4074 Search Results UI Alignment changes
  DNN Platform/Website/DesktopModules/Admin/SearchResults/module.css
Labels: Type: Enhancement

#4092 Fix deprecation message referencing wrong type
  DNN Platform/Library/Entities/Controllers/IHostController.cs
Labels: Type: Documentation

#4103 Resolve styling issue for checked Accept License checkbox in Extension installer
  Dnn.AdminExperience/ClientSide/Dnn.React.Common/src/Checkbox/style.less
Labels: Type: Bug

#4104 Replace momentjs with dayjs for Servers.Web
  DNN Platform/Website/Licenses/dayjs (MIT).txt.resources
  Dnn.AdminExperience/ClientSide/Servers.Web/package.json
  Dnn.AdminExperience/ClientSide/Servers.Web/src/components/Tabs/LogFileRow/index.jsx
  Dnn.AdminExperience/ClientSide/Servers.Web/src/services/logsTabService.js
  yarn.lock
Labels: Type: Enhancement

#4108 Replace momentjs with dayjs in Users.Web
  Dnn.AdminExperience/ClientSide/Users.Web/src/_exportables/package.json
  Dnn.AdminExperience/ClientSide/Users.Web/src/_exportables/src/helpers.js
  yarn.lock
Labels: Type: Enhancement

#4109 Fixed an issue where the React common components would interfere with container css class
  Dnn.AdminExperience/ClientSide/Dnn.React.Common/src/ScrollBar/styles.less
Labels: Type: Bug

#4117 Removal of references to the Dashboard Project Type
  DNN Platform/Library/Services/Installer/Util.cs
  DNN Platform/Website/App_GlobalResources/SharedResources.resx
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Extensions/Constants.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Extensions/ExtensionsController.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Extensions/App_LocalResources/Extensions.resx
Labels: Type: Maintenance

#4113 Fix module dialog adding new module to wrong pane
  Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/editBar/resources/ContentEditorManager/Js/ModuleDialog.js
Labels: Type: Bug

#4115 DNN Platform Documentation Fixes
  .github/PULL_REQUEST_PROCESS.md
  .github/RELEASE_SCHEDULE.md
  .github/VERSIONING_POLICY.md
  NOTICE.md
Labels: Type: Documentation

#4121 Remove the Improvement Program
  DNN Platform/DotNetNuke.Website.Deprecated/admin/ControlPanel/ControlBar.ascx.cs
  DNN Platform/Library/DotNetNuke.Library.csproj
  DNN Platform/Library/Entities/Host/Host.cs
  DNN Platform/Library/Services/ImprovementsProgram/BeaconService.cs
  DNN Platform/Library/Services/ImprovementsProgram/IBeaconService.cs
  DNN Platform/Library/Services/ImprovementsProgram/RolesEnum.cs
  DNN Platform/Website/Install/App_LocalResources/Installwizard.aspx.de-DE.resx
  DNN Platform/Website/Install/App_LocalResources/Installwizard.aspx.es-ES.resx
  DNN Platform/Website/Install/App_LocalResources/Installwizard.aspx.fr-FR.resx
  DNN Platform/Website/Install/App_LocalResources/Installwizard.aspx.it-IT.resx
  DNN Platform/Website/Install/App_LocalResources/Installwizard.aspx.nl-NL.resx
  DNN Platform/Website/Install/App_LocalResources/Installwizard.aspx.resx
  DNN Platform/Website/Install/App_LocalResources/UpgradeWizard.aspx.de-DE.resx
  DNN Platform/Website/Install/App_LocalResources/UpgradeWizard.aspx.es-ES.resx
  DNN Platform/Website/Install/App_LocalResources/UpgradeWizard.aspx.fr-FR.resx
  DNN Platform/Website/Install/App_LocalResources/UpgradeWizard.aspx.it-IT.resx
  DNN Platform/Website/Install/App_LocalResources/UpgradeWizard.aspx.nl-NL.resx
  DNN Platform/Website/Install/App_LocalResources/UpgradeWizard.aspx.resx
  DNN Platform/Website/Install/Config/09.07.03.config
  DNN Platform/Website/Install/DotNetNuke.install.config.resources
  DNN Platform/Website/Install/InstallWizard.aspx
  DNN Platform/Website/Install/InstallWizard.aspx.cs
  DNN Platform/Website/Install/UpgradeWizard.aspx
  DNN Platform/Website/Install/UpgradeWizard.aspx.cs
  DNN Platform/Website/Install/UpgradeWizard.aspx.designer.cs
  DNN Platform/Website/development.config
  DNN Platform/Website/release.config
  DNN_Platform.sln
  Dnn.AdminExperience/ClientSide/Prompt.Web/src/utils/__mocks__/utilities.js
  Dnn.AdminExperience/ClientSide/SiteSettings.Web/src/components/privacySettings/index.jsx
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/DTO/SiteSettings/UpdatePrivacySettingsRequest.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/SiteSettingsController.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.SiteSettings/App_LocalResources/SiteSettings.resx
  Dnn.AdminExperience/Library/Dnn.PersonaBar.Library/Containers/PersonaBarContainer.cs
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/scripts/util.js
Labels: Type: Maintenance

#4082 module friendly name updated as part of module extension update
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Extensions/Editors/ModulePackageEditor.cs
Labels: Type: Bug

#4124 Error message to use correct error icon
  Dnn.AdminExperience/ClientSide/Pages.Web/src/components/App.jsx
Labels: Type: Bug

#4126 Purge Expired JWT tokens task
  DNN Platform/Dnn.AuthServices.Jwt/Components/Schedule/PurgeExpiredTokensTask.cs
  DNN Platform/Dnn.AuthServices.Jwt/Data/DataService.cs
  DNN Platform/Dnn.AuthServices.Jwt/Data/Scripts/09.08.00.SqlDataProvider
  DNN Platform/Dnn.AuthServices.Jwt/Data/Scripts/Uninstall.SqlDataProvider
  DNN Platform/Dnn.AuthServices.Jwt/Dnn.AuthServices.Jwt.csproj
  DNN Platform/Dnn.AuthServices.Jwt/Dnn.Jwt.dnn
Labels: Area: Platform > Dnn.AuthServices.Jwt, Type: Enhancement

#4127 Update mergeable to not allow merging of PRs with Future:... milestone
  .github/mergeable.yml
Labels: Type: Maintenance

#4122 Treat warnings as errors for DotNetNuke.Instrumentation
  DNN Platform/DotNetNuke.Instrumentation/DnnLog.cs
  DNN Platform/DotNetNuke.Instrumentation/DnnLogger.cs
  DNN Platform/DotNetNuke.Instrumentation/DotNetNuke.Instrumentation.csproj
  DNN Platform/DotNetNuke.Instrumentation/ILog.cs
  DNN Platform/DotNetNuke.Instrumentation/ILoggerSource.cs
  DNN Platform/DotNetNuke.Instrumentation/LoggerSource.cs
  DNN Platform/DotNetNuke.Instrumentation/LoggerSourceImpl.cs
Labels: Type: Maintenance

#4089 Update SMTP Test Email Logic
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/ServerSettingsSmtpAdminController.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/ServerSettingsSmtpHostController.cs
Labels: Type: Bug

#4129 Address React invariant violation
  Dnn.AdminExperience/ClientSide/Servers.Web/src/components/App.jsx
Labels: Type: Bug

#3976 Fix for issue Newly created sub-folder not shown if the parent folder…
  DNN Platform/Library/Common/Utilities/PathUtils.cs
Labels: Type: Bug

#4131 Add portal name to SMTP test email for better identification
  DNN Platform/Website/App_GlobalResources/GlobalResources.resx
Labels: Type: Enhancement

#4136 Fixes an issue where Dnn would not install
  DNN Platform/Website/DotNetNuke.Website.csproj
  DNN Platform/Website/Install/Config/09.07.03.config
Labels: Type: Bug

#4139 Hide new members that differ only by case
  DNN Platform/Library/Entities/Portals/PortalAliasController.cs
  DNN Platform/Library/Entities/Portals/PortalAliasInfo.cs
Labels: Type: Bug

#4142 Remove Telerik references
  DNN Platform/Admin Modules/Dnn.Modules.ModuleCreator/Dnn.Modules.ModuleCreator.csproj
  DNN Platform/DotNetNuke.Website.Deprecated/DotNetNuke.Website.Deprecated.csproj
  DNN Platform/DotNetNuke.Website.Deprecated/admin/ControlPanel/AddModule.ascx.cs
  DNN Platform/DotNetNuke.Website.Deprecated/admin/ControlPanel/AddModule.ascx.designer.cs
  DNN Platform/DotNetNuke.Website.Deprecated/admin/ControlPanel/AddPage.ascx.cs
  DNN Platform/DotNetNuke.Website.Deprecated/admin/ControlPanel/AddPage.ascx.designer.cs
  DNN Platform/DotNetNuke.Website.Deprecated/admin/ControlPanel/ControlBar.ascx.cs
  DNN Platform/DotNetNuke.Website.Deprecated/admin/ControlPanel/ControlBar.ascx.designer.cs
  DNN Platform/DotNetNuke.Website.Deprecated/admin/ControlPanel/RibbonBar.ascx.cs
  DNN Platform/DotNetNuke.Website.Deprecated/admin/ControlPanel/RibbonBar.ascx.designer.cs
  DNN Platform/DotNetNuke.Website.Deprecated/admin/ControlPanel/SwitchSite.ascx.cs
  DNN Platform/DotNetNuke.Website.Deprecated/admin/ControlPanel/SwitchSite.ascx.designer.cs
  DNN Platform/DotNetNuke.Website.Deprecated/admin/ControlPanel/UpdatePage.ascx.cs
  DNN Platform/DotNetNuke.Website.Deprecated/admin/ControlPanel/UpdatePage.ascx.designer.cs
  DNN Platform/Modules/HTML/DotNetNuke.Modules.Html.csproj
  DNN Platform/Modules/HTML/EditHtml.ascx.cs
  DNN Platform/Modules/HTML/dnn_HTML.dnn
  DNN Platform/Modules/HtmlEditorManager/DotNetNuke.Modules.HtmlEditorManager.csproj
  DNN Platform/Modules/RazorHost/DotNetNuke.Modules.RazorHost.csproj
  DNN Platform/Tests/App.config
  DNN Platform/Tests/DotNetNuke.Tests.Authentication/DotNetNuke.Tests.Authentication.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Content/DotNetNuke.Tests.Content.csproj
Labels: Type: Maintenance
