Repository dnnsoftware/Dnn.Platform, pull requests merged in 2020-05, with the labels that each got.

#3707 Add Services Framework call to Toast skin object
  DNN Platform/Website/admin/Skins/Toast.ascx.cs
Labels: Type: Bug

#3721 Fixed content export validation
  DNN Platform/Website/admin/Modules/Export.ascx.cs
Labels: Type: Bug

#3719 Bump version to 9.6.0
  Build/Symbols/DotNetNuke_Symbols.dnn
  DNN Platform/Admin Modules/Dnn.Modules.Console/dnn_Console.dnn
  DNN Platform/Admin Modules/Dnn.Modules.ModuleCreator/dnn_ModuleCreator.dnn
  DNN Platform/Components/Telerik/DotNetNuke.Telerik.Web.dnn
  DNN Platform/Connectors/Azure/AzureConnector.dnn
  DNN Platform/Connectors/GoogleAnalytics/GoogleAnalyticsConnector.dnn
  DNN Platform/Dnn.AuthServices.Jwt/Dnn.Jwt.dnn
  DNN Platform/DotNetNuke.Web.Deprecated/dnn_Web_Deprecated.dnn
  DNN Platform/DotNetNuke.WebUtility/DotNetNuke.ClientAPI.dnn
  DNN Platform/DotNetNuke.Website.Deprecated/dnn_Website_Deprecated.dnn
  DNN Platform/Modules/CoreMessaging/CoreMessaging.dnn
  DNN Platform/Modules/DDRMenu/DDRMenu.dnn
  DNN Platform/Modules/DigitalAssets/dnn_DigitalAssets.dnn
  DNN Platform/Modules/DnnExportImport/dnn_SiteExportImport.dnn
  DNN Platform/Modules/Groups/SocialGroups.dnn
  DNN Platform/Modules/HTML/dnn_HTML.dnn
  DNN Platform/Modules/HtmlEditorManager/dnn_HtmlEditorManager.dnn
  DNN Platform/Modules/Journal/Journal.dnn
  DNN Platform/Modules/MemberDirectory/MemberDirectory.dnn
  DNN Platform/Modules/RazorHost/Manifest.dnn
  DNN Platform/Modules/RazorHost/RazorHost.dnn
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Facebook/Facebook_Auth.dnn
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Google/Google_Auth.dnn
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.LiveConnect/Live_Auth.dnn
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Twitter/Twitter_Auth.dnn
  DNN Platform/Providers/CachingProviders/DotNetNuke.Providers.Caching.SimpleWebFarmCachingProvider/SimpleWebFarmCachingProvider.dnn
  DNN Platform/Providers/ClientCapabilityProviders/Provider.AspNetCCP/AspNetClientCapabilityProvider.dnn
  DNN Platform/Providers/FolderProviders/FolderProviders.dnn
  DNN Platform/Skins/Xcillion/DNN_Skin_Xcillion.dnn
  Dnn.AdminExperience/ClientSide/AdminLogs.Web/package.json
  Dnn.AdminExperience/ClientSide/Bundle.Web/package.json
  Dnn.AdminExperience/ClientSide/Dnn.React.Common/package.json
  Dnn.AdminExperience/ClientSide/Extensions.Web/package.json
  Dnn.AdminExperience/ClientSide/Licensing.Web/package.json
  Dnn.AdminExperience/ClientSide/Pages.Web/package.json
  Dnn.AdminExperience/ClientSide/Prompt.Web/package.json
  Dnn.AdminExperience/ClientSide/Roles.Web/package.json
  Dnn.AdminExperience/ClientSide/Security.Web/package.json
  Dnn.AdminExperience/ClientSide/Seo.Web/package.json
  Dnn.AdminExperience/ClientSide/Servers.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteImportExport.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteSettings.Web/package.json
  Dnn.AdminExperience/ClientSide/Sites.Web/package.json
  Dnn.AdminExperience/ClientSide/Sites.Web/src/_exportables/package.json
  Dnn.AdminExperience/ClientSide/TaskScheduler.Web/package.json
  Dnn.AdminExperience/ClientSide/Themes.Web/package.json
  Dnn.AdminExperience/ClientSide/Users.Web/package.json
  Dnn.AdminExperience/ClientSide/Users.Web/src/_exportables/package.json
  Dnn.AdminExperience/ClientSide/Vocabularies.Web/package.json
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Dnn.PersonaBar.Extensions.dnn
  Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/Dnn.EditBar.UI.dnn
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/Dnn.PersonaBar.UI.dnn
  SolutionInfo.cs
Labels: Type: Build/Release

#3726 Ensure yarn runs when module is built
  Build/BuildScripts/AEModule.build
  Build/Cake/version.cake
  DNN Platform/Modules/ResourceManager/Module.build
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/package.json
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/webpack.config.js
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/yarn.lock
  DNN Platform/Modules/ResourceManager/ResourceManager.dnn
  DNN Platform/Modules/ResourceManager/View.ascx.cs
Labels: Type: Bug, Type: Build/Release

#3727 Fix resource manager to use the revised upload file handler in the core
  DNN Platform/Library/Common/Utilities/ValidationUtils.cs
  DNN Platform/Library/Services/FileSystem/FileManager.cs
  DNN Platform/Library/Services/FileSystem/IFileManager.cs
  DNN Platform/Modules/ResourceManager/App_LocalResources/ResourceManager.resx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/.eslintskipwords.js
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/actions/addAssetPanelActions.js
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/components/FileDetails.jsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/components/FolderDetails.jsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/components/FolderSelector/FolderPicker.jsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/components/Item.jsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/containers/DropZoneContainer.jsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/globals/api.js
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/app/services/itemsService.js
  DNN Platform/Modules/ResourceManager/View.ascx
  DNN Platform/Modules/ResourceManager/View.ascx.cs
Labels: Type: Bug

#3728 Redo PR #3333
  DNN Platform/Website/DesktopModules/Admin/SearchResults/SearchResults.ascx.cs
Labels: Type: Bug

#3729 Update jQuery to 3.5.1
  DNN Platform/JavaScript Libraries/jQuery/jQuery.dnn
  DNN Platform/JavaScript Libraries/jQuery/jquery.js
  DNN Platform/JavaScript Libraries/jQuery/jquery.min.map
Labels: Type: Maintenance

#3734 Resource Manager Standardization & Improvement
  DNN Platform/Modules/ResourceManager/Components/Common/Utils.cs
  DNN Platform/Modules/ResourceManager/Components/Constants.cs
  DNN Platform/Modules/ResourceManager/Components/GroupManager.cs
  DNN Platform/Modules/ResourceManager/Components/IGroupManager.cs
  DNN Platform/Modules/ResourceManager/Components/IItemsManager.cs
  DNN Platform/Modules/ResourceManager/Components/ILocalizationController.cs
  DNN Platform/Modules/ResourceManager/Components/IPermissionsManager.cs
  DNN Platform/Modules/ResourceManager/Components/ISearchController.cs
  DNN Platform/Modules/ResourceManager/Components/IThumbnailsManager.cs
  DNN Platform/Modules/ResourceManager/Components/ItemsManager.cs
  DNN Platform/Modules/ResourceManager/Components/LocalizationController.cs
  DNN Platform/Modules/ResourceManager/Components/Models/Localization.cs
  DNN Platform/Modules/ResourceManager/Components/Models/ThumbnailContent.cs
  DNN Platform/Modules/ResourceManager/Components/PermissionsManager.cs
  DNN Platform/Modules/ResourceManager/Components/SearchController.cs
  DNN Platform/Modules/ResourceManager/Components/SettingsManager.cs
  DNN Platform/Modules/ResourceManager/Components/ThumbnailsManager.cs
  DNN Platform/Modules/ResourceManager/Exceptions/FolderPermissionNotMetException.cs
  DNN Platform/Modules/ResourceManager/Exceptions/ModeValidationException.cs
  DNN Platform/Modules/ResourceManager/Exceptions/NotFoundException.cs
  DNN Platform/Modules/ResourceManager/Helpers/LocalizationHelper.cs
  DNN Platform/Modules/ResourceManager/License.txt
  DNN Platform/Modules/ResourceManager/ReleaseNotes.txt
  DNN Platform/Modules/ResourceManager/Scripts/resourceManager-bundle.js
  DNN Platform/Modules/ResourceManager/Services/Attributes/ResourceManagerExceptionFilter.cs
  DNN Platform/Modules/ResourceManager/Services/Dto/CreateNewFolderRequest.cs
  DNN Platform/Modules/ResourceManager/Services/Dto/DeleteFileRequest.cs
  DNN Platform/Modules/ResourceManager/Services/Dto/DeleteFolderRequest.cs
  DNN Platform/Modules/ResourceManager/Services/Dto/FileDetailsRequest.cs
  DNN Platform/Modules/ResourceManager/Services/Dto/FolderDetailsRequest.cs
  DNN Platform/Modules/ResourceManager/Services/Dto/ThumbnailDownloadRequest.cs
  DNN Platform/Modules/ResourceManager/Services/ItemsController.cs
  DNN Platform/Modules/ResourceManager/Services/LocalizationController.cs
  DNN Platform/Modules/ResourceManager/Services/RouteMapper.cs
  DNN Platform/Modules/ResourceManager/Settings.ascx.cs
  DNN Platform/Modules/ResourceManager/View.ascx.cs
  SolutionInfo.cs
Labels: Type: Enhancement

#3736 Fixed an issue with search results page rendering
  DNN Platform/Website/Resources/Shared/scripts/dnn.searchBox.js
Labels: Type: Bug

#3740 Change "Dotnetnuke Professional" to "DNN Platform" in 2 releasenotes.txt files
  Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/releaseNotes.txt
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/releaseNotes.txt
Labels: Type: Maintenance

#3737 Update date in sln info file
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Google/Images/google_32X32.jpg
  DNN Platform/Skins/Xcillion/Container/Boxed.jpg
  DNN Platform/Skins/Xcillion/Container/Title_h2.jpg
  DNN Platform/Skins/Xcillion/Container/Title_h2_centered.jpg
  DNN Platform/Skins/Xcillion/Container/Title_h2_circles.jpg
  DNN Platform/Skins/Xcillion/Container/Title_h2_elegant.jpg
  DNN Platform/Skins/Xcillion/Container/Title_h2_hexagon.jpg
  DNN Platform/Skins/Xcillion/Container/Title_h2_open_rectangle.jpg
  DNN Platform/Skins/Xcillion/Container/Title_h2_rectangle.jpg
  DNN Platform/Skins/Xcillion/Container/Title_h2_slashed.jpg
  DNN Platform/Skins/Xcillion/Container/Title_h3.jpg
  DNN Platform/Skins/Xcillion/Container/Title_h3_centered.jpg
  DNN Platform/Skins/Xcillion/Container/Title_h4.jpg
  DNN Platform/Skins/Xcillion/Container/Title_h4_centered.jpg
  DNN Platform/Skins/Xcillion/Skin/Includes/latest-thumb2.jpg
  SolutionInfo.cs
Labels: Type: Maintenance

#3738 Merge version bump from Master to Develop
  Build/Symbols/DotNetNuke_Symbols.dnn
  DNN Platform/Admin Modules/Dnn.Modules.Console/dnn_Console.dnn
  DNN Platform/Admin Modules/Dnn.Modules.ModuleCreator/dnn_ModuleCreator.dnn
  DNN Platform/Components/Telerik/DotNetNuke.Telerik.Web.dnn
  DNN Platform/Connectors/Azure/AzureConnector.dnn
  DNN Platform/Connectors/GoogleAnalytics/GoogleAnalyticsConnector.dnn
  DNN Platform/Dnn.AuthServices.Jwt/Dnn.Jwt.dnn
  DNN Platform/DotNetNuke.Web.Deprecated/dnn_Web_Deprecated.dnn
  DNN Platform/DotNetNuke.WebUtility/DotNetNuke.ClientAPI.dnn
  DNN Platform/DotNetNuke.Website.Deprecated/dnn_Website_Deprecated.dnn
  DNN Platform/Modules/CoreMessaging/CoreMessaging.dnn
  DNN Platform/Modules/DDRMenu/DDRMenu.dnn
  DNN Platform/Modules/DigitalAssets/dnn_DigitalAssets.dnn
  DNN Platform/Modules/DnnExportImport/dnn_SiteExportImport.dnn
  DNN Platform/Modules/Groups/SocialGroups.dnn
  DNN Platform/Modules/HTML/dnn_HTML.dnn
  DNN Platform/Modules/HtmlEditorManager/dnn_HtmlEditorManager.dnn
  DNN Platform/Modules/Journal/Journal.dnn
  DNN Platform/Modules/MemberDirectory/MemberDirectory.dnn
  DNN Platform/Modules/RazorHost/Manifest.dnn
  DNN Platform/Modules/RazorHost/RazorHost.dnn
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Facebook/Facebook_Auth.dnn
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Google/Google_Auth.dnn
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.LiveConnect/Live_Auth.dnn
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Twitter/Twitter_Auth.dnn
  DNN Platform/Providers/CachingProviders/DotNetNuke.Providers.Caching.SimpleWebFarmCachingProvider/SimpleWebFarmCachingProvider.dnn
  DNN Platform/Providers/ClientCapabilityProviders/Provider.AspNetCCP/AspNetClientCapabilityProvider.dnn
  DNN Platform/Providers/FolderProviders/FolderProviders.dnn
  DNN Platform/Skins/Xcillion/DNN_Skin_Xcillion.dnn
  Dnn.AdminExperience/ClientSide/AdminLogs.Web/package.json
  Dnn.AdminExperience/ClientSide/Bundle.Web/package.json
  Dnn.AdminExperience/ClientSide/Dnn.React.Common/package.json
  Dnn.AdminExperience/ClientSide/Extensions.Web/package.json
  Dnn.AdminExperience/ClientSide/Licensing.Web/package.json
  Dnn.AdminExperience/ClientSide/Pages.Web/package.json
  Dnn.AdminExperience/ClientSide/Prompt.Web/package.json
  Dnn.AdminExperience/ClientSide/Roles.Web/package.json
  Dnn.AdminExperience/ClientSide/Security.Web/package.json
  Dnn.AdminExperience/ClientSide/Seo.Web/package.json
  Dnn.AdminExperience/ClientSide/Servers.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteImportExport.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteSettings.Web/package.json
  Dnn.AdminExperience/ClientSide/Sites.Web/package.json
  Dnn.AdminExperience/ClientSide/Sites.Web/src/_exportables/package.json
  Dnn.AdminExperience/ClientSide/TaskScheduler.Web/package.json
  Dnn.AdminExperience/ClientSide/Themes.Web/package.json
  Dnn.AdminExperience/ClientSide/Users.Web/package.json
  Dnn.AdminExperience/ClientSide/Users.Web/src/_exportables/package.json
  Dnn.AdminExperience/ClientSide/Vocabularies.Web/package.json
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Dnn.PersonaBar.Extensions.dnn
  Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/Dnn.EditBar.UI.dnn
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/Dnn.PersonaBar.UI.dnn
  SolutionInfo.cs
Labels: Type: Build/Release, Type: Maintenance

#3741 Adds action to automated versioning on RC
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/workflows/updateVersions.yml
  Build/Cake/unversionedManifests.txt
  Build/Cake/version.cake
Labels: Type: Build/Release

#3742 Locks versions of image-actions
  .github/workflows/image-actions.yml
Labels: Type: Build/Release

#3746 Fix typo in versioning action
  .github/workflows/updateVersions.yml
Labels: Type: Build/Release

#3747 Limit rc action to run only on release branches
  .github/workflows/updateVersions.yml
Labels: Type: Build/Release

#3755 Restores icons in language editor
  Dnn.AdminExperience/ClientSide/SiteSettings.Web/src/components/editLanguagePanel/resourceEditor/fullEditor.jsx
Labels: Type: Bug

#3748 Fixes some errors in exceptions localization
  DNN Platform/Website/App_GlobalResources/Exceptions.resx
Labels: Type: Documentation

#3758 DB Performance Improvement
  DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.06.02.SqlDataProvider
Labels: Effort: Low, Priority: Low, Type: Enhancement

#3760 Merge latest changes from Release/9.6.1 into develop
  .github/ISSUE_TEMPLATE/bug-report.md
  Build/Symbols/DotNetNuke_Symbols.dnn
  DNN Platform/Admin Modules/Dnn.Modules.Console/dnn_Console.dnn
  DNN Platform/Admin Modules/Dnn.Modules.ModuleCreator/dnn_ModuleCreator.dnn
  DNN Platform/Components/Telerik/DotNetNuke.Telerik.Web.dnn
  DNN Platform/Connectors/Azure/AzureConnector.dnn
  DNN Platform/Connectors/GoogleAnalytics/GoogleAnalyticsConnector.dnn
  DNN Platform/Dnn.AuthServices.Jwt/Dnn.Jwt.dnn
  DNN Platform/DotNetNuke.Web.Deprecated/dnn_Web_Deprecated.dnn
  DNN Platform/DotNetNuke.WebUtility/DotNetNuke.ClientAPI.dnn
  DNN Platform/DotNetNuke.Website.Deprecated/dnn_Website_Deprecated.dnn
  DNN Platform/Modules/CoreMessaging/CoreMessaging.dnn
  DNN Platform/Modules/DDRMenu/DDRMenu.dnn
  DNN Platform/Modules/DigitalAssets/dnn_DigitalAssets.dnn
  DNN Platform/Modules/DnnExportImport/dnn_SiteExportImport.dnn
  DNN Platform/Modules/Groups/SocialGroups.dnn
  DNN Platform/Modules/HTML/dnn_HTML.dnn
  DNN Platform/Modules/HtmlEditorManager/dnn_HtmlEditorManager.dnn
  DNN Platform/Modules/Journal/Journal.dnn
  DNN Platform/Modules/MemberDirectory/MemberDirectory.dnn
  DNN Platform/Modules/RazorHost/Manifest.dnn
  DNN Platform/Modules/RazorHost/RazorHost.dnn
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Facebook/Facebook_Auth.dnn
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Google/Google_Auth.dnn
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.LiveConnect/Live_Auth.dnn
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Twitter/Twitter_Auth.dnn
  DNN Platform/Providers/CachingProviders/DotNetNuke.Providers.Caching.SimpleWebFarmCachingProvider/SimpleWebFarmCachingProvider.dnn
  DNN Platform/Providers/ClientCapabilityProviders/Provider.AspNetCCP/AspNetClientCapabilityProvider.dnn
  DNN Platform/Providers/FolderProviders/FolderProviders.dnn
  DNN Platform/Skins/Xcillion/DNN_Skin_Xcillion.dnn
  Dnn.AdminExperience/ClientSide/AdminLogs.Web/package.json
  Dnn.AdminExperience/ClientSide/Bundle.Web/package.json
  Dnn.AdminExperience/ClientSide/Dnn.React.Common/package.json
  Dnn.AdminExperience/ClientSide/Extensions.Web/package.json
  Dnn.AdminExperience/ClientSide/Licensing.Web/package.json
  Dnn.AdminExperience/ClientSide/Pages.Web/package.json
  Dnn.AdminExperience/ClientSide/Prompt.Web/package.json
  Dnn.AdminExperience/ClientSide/Roles.Web/package.json
  Dnn.AdminExperience/ClientSide/Security.Web/package.json
  Dnn.AdminExperience/ClientSide/Seo.Web/package.json
  Dnn.AdminExperience/ClientSide/Servers.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteImportExport.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteSettings.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteSettings.Web/src/components/editLanguagePanel/resourceEditor/fullEditor.jsx
  Dnn.AdminExperience/ClientSide/Sites.Web/package.json
  Dnn.AdminExperience/ClientSide/Sites.Web/src/_exportables/package.json
  Dnn.AdminExperience/ClientSide/TaskScheduler.Web/package.json
  Dnn.AdminExperience/ClientSide/Themes.Web/package.json
  Dnn.AdminExperience/ClientSide/Users.Web/package.json
  Dnn.AdminExperience/ClientSide/Users.Web/src/_exportables/package.json
  Dnn.AdminExperience/ClientSide/Vocabularies.Web/package.json
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Dnn.PersonaBar.Extensions.dnn
  Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/Dnn.EditBar.UI.dnn
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/Dnn.PersonaBar.UI.dnn
  SolutionInfo.cs
  package.json
Labels: Type: Build/Release

#3769 Fix logo/icon upload in site setting for #3722
  Dnn.AdminExperience/ClientSide/Dnn.React.Common/src/FileUpload/index.jsx
  Dnn.AdminExperience/ClientSide/SiteSettings.Web/src/components/basicSettings/index.jsx
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/SiteSettingsController.cs
Labels: Type: Bug

#3773 Install ugrade nl nl resx update issue 3764
  DNN Platform/Website/Install/App_LocalResources/Blank Website.template.nl-NL.resx
  DNN Platform/Website/Install/App_LocalResources/Default Website.template.nl-NL.resx
  DNN Platform/Website/Install/App_LocalResources/Installwizard.aspx.nl-NL.resx
  DNN Platform/Website/Install/App_LocalResources/UpgradeWizard.aspx.nl-NL.resx
Labels: Area: Localization, Effort: Low, Type: Bug

#3784 adjust version
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: Type: Build/Release

#3786 Remove or update logo in distribution
  DNN Platform/Website/DotNetNuke.Website.csproj
  DNN Platform/Website/images/Branding/logo.gif
Labels: Type: Maintenance

#3788 Improved wording #3785
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Security/App_LocalResources/Security.resx
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.SiteSettings/App_LocalResources/SiteSettings.resx
Labels: Type: Enhancement

#3790 Remove Dutch template files #3789
  DNN Platform/Website/Install/App_LocalResources/Blank Website.template.nl-NL.resx
  DNN Platform/Website/Install/App_LocalResources/Default Website.template.nl-NL.resx
Labels: Type: Maintenance

#3780 Fix weird shorting in site settings PB heading
  Dnn.AdminExperience/ClientSide/Dnn.React.Common/src/PersonaBarPageHeader/index.jsx
Labels: Type: Enhancement

#3787 Fix module settings localization #3781 #3782
  DNN Platform/Website/admin/Modules/App_LocalResources/ModuleSettings.ascx.resx
Labels: Type: Enhancement
