Repository dnnsoftware/Dnn.Platform, pull requests merged in 2020-03, with the labels that each got.

#3596 Add debug build to lerna
  Dnn.AdminExperience/ClientSide/AdminLogs.Web/package.json
  Dnn.AdminExperience/ClientSide/Bundle.Web/package.json
  Dnn.AdminExperience/ClientSide/Dnn.React.Common/package.json
  Dnn.AdminExperience/ClientSide/Extensions.Web/package.json
  Dnn.AdminExperience/ClientSide/Licensing.Web/package.json
  Dnn.AdminExperience/ClientSide/Pages.Web/package.json
  Dnn.AdminExperience/ClientSide/Prompt.Web/package.json
  Dnn.AdminExperience/ClientSide/Roles.Web/package.json
  Dnn.AdminExperience/ClientSide/Security.Web/package.json
  Dnn.AdminExperience/ClientSide/Seo.Web/package.json
  Dnn.AdminExperience/ClientSide/Servers.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteImportExport.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteSettings.Web/package.json
  Dnn.AdminExperience/ClientSide/Sites.Web/package.json
  Dnn.AdminExperience/ClientSide/TaskScheduler.Web/package.json
  Dnn.AdminExperience/ClientSide/Themes.Web/package.json
  Dnn.AdminExperience/ClientSide/Users.Web/package.json
  Dnn.AdminExperience/ClientSide/Vocabularies.Web/package.json
  package.json
Labels: Type: Build/Release

#3570 Removes obsolete admin.css styling
  DNN Platform/Website/Portals/_default/admin.css
Labels: Alert: Breaking Change, Type: Bug

#3585 Adjust version numbers
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: Type: Build/Release

#3606 Fix missing databaseOwner/objectQualifier in CoreMessaging sproc.
  DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.05.01.SqlDataProvider
Labels: Type: Bug

#3584 Fix bug #3583 for double Html decoding when using custom portal templates
  DNN Platform/Library/Entities/Modules/ModuleController.cs
Labels: Type: Bug

#3582 .dnnActions change inline-block to block
  DNN Platform/Website/Portals/_default/admin.css
Labels: Type: Bug

#3610 Fix to data consent feature when wrapped in UpdatePanel
  DNN Platform/Website/DesktopModules/Admin/Security/DataConsent.ascx
  DNN Platform/Website/DesktopModules/Admin/Security/DataConsent.ascx.cs
Labels: Area: Platform > Website, Type: Bug

#3588 get the real client ip address.
  DNN Platform/Library/Common/Utilities/NetworkUtils.cs
  DNN Platform/Website/DesktopModules/Admin/Authentication/Login.ascx.cs
Labels: Type: Bug

#3616 SimpleWebFarmCachingProvider
  DNN Platform/Providers/CachingProviders/DotNetNuke.Providers.Caching.SimpleWebFarmCachingProvider/DotNetNuke.Providers.Caching.SimpleWebFarmCachingProvider.csproj
  DNN Platform/Providers/CachingProviders/DotNetNuke.Providers.Caching.SimpleWebFarmCachingProvider/Properties/AssemblyInfo.cs
  DNN Platform/Providers/CachingProviders/DotNetNuke.Providers.Caching.SimpleWebFarmCachingProvider/Provider.build
  DNN Platform/Providers/CachingProviders/DotNetNuke.Providers.Caching.SimpleWebFarmCachingProvider/SimpleWebFarmCachingProvider.cs
  DNN Platform/Providers/CachingProviders/DotNetNuke.Providers.Caching.SimpleWebFarmCachingProvider/SimpleWebFarmCachingProvider.dnn
  DNN Platform/Providers/CachingProviders/DotNetNuke.Providers.Caching.SimpleWebFarmCachingProvider/SimpleWebFarmSynchronizationHandler.cs
  DNN Platform/Providers/CachingProviders/DotNetNuke.Providers.Caching.SimpleWebFarmCachingProvider/license.txt
  DNN Platform/Providers/CachingProviders/DotNetNuke.Providers.Caching.SimpleWebFarmCachingProvider/releaseNotes.txt
  DNN_Platform.sln
Labels: Effort: Medium, Priority: Medium, Type: Enhancement

#3615 Fixes an issue with backup/restore in build
  build.cake
Labels: Type: Build/Release

#3618 Fixes to build process
  Build/Cake/devsite.cake
  DNN Platform/Providers/CachingProviders/DotNetNuke.Providers.Caching.SimpleWebFarmCachingProvider/DotNetNuke.Providers.Caching.SimpleWebFarmCachingProvider.csproj
  DNN Platform/Providers/CachingProviders/DotNetNuke.Providers.Caching.SimpleWebFarmCachingProvider/Properties/AssemblyInfo.cs
  DNN Platform/Providers/CachingProviders/DotNetNuke.Providers.Caching.SimpleWebFarmCachingProvider/SimpleWebFarmCachingProvider.dnn
  Dnn.AdminExperience/ClientSide/Bundle.Web/package.json
  package.json
Labels: Type: Build/Release

#3631 Fixed widget.js 404 error
  DNN Platform/Website/Resources/Shared/scripts/jquery/jquery.fileupload.js
Labels: Type: Bug

#3632 Pr3631redo
  DNN Platform/Website/Resources/Shared/scripts/jquery/jquery.fileupload.js
Labels: Type: Bug

#3642 Fix errors setting up dev site
  Build/Cake/database.cake
  Build/Cake/sql/create-db.sql
Labels: Type: Build/Release

#3635 Fix error when MVC module is on a page multiple times
  DNN Platform/DotNetNuke.Web.Mvc/Extensions/StartupExtensions.cs
Labels: Type: Bug

#3640 DNN-30135 - Issue when loading the Persona Bar: Not Thread Safe
  Dnn.AdminExperience/Library/Dnn.PersonaBar.Library/Repository/PersonaBarRepository.cs
Labels: Type: Bug

#3653 Fixes #3651 — UI/UX Dropdown page picker within Personabar
  Dnn.AdminExperience/ClientSide/Dnn.React.Common/src/PermissionGrid/RoleGroupFilter/style.less
Labels: Area: AE > Dnn.React.Common, Type: Enhancement

#3652 Fixed the issue that caused all modules to be relocated to same pane
  Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/editBar/resources/ContentEditorManager/Js/ContentEditor.js
  Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/editBar/resources/ContentEditorManager/Js/ModuleDialog.js
Labels: Type: Bug
