Repository dnnsoftware/Dnn.Platform, pull requests merged in 2021-11, with the labels that each got.

#4890 Standardized DNN Manifest Items
  Build/Symbols/DotNetNuke_Symbols.dnn
  DNN Platform/Admin Modules/Dnn.Modules.Console/dnn_Console.dnn
  DNN Platform/Components/MailKit/MailKit.dnn
  DNN Platform/Components/Microsoft.AspNetMvc/Microsoft.AspNetMvc.dnn
  DNN Platform/Components/Microsoft.AspNetWebApi/Microsoft.AspNetWebApi.dnn
  DNN Platform/Components/Microsoft.AspNetWebPages/Microsoft.AspNetWebPages.dnn
  DNN Platform/Components/Microsoft.CodeDom.Providers.DotNetCompilerPlatform/Microsoft.CodeDom.Providers.DotNetCompilerPlatform.dnn
  DNN Platform/Components/Microsoft.Extensions.FileSystemGlobbing/Microsoft.Extensions.FileSystemGlobbing.dnn
  DNN Platform/Components/Newtonsoft/DotNetNuke.Newtonsoft.Json.dnn
  DNN Platform/Components/Telerik/DotNetNuke.Telerik.Web.dnn
  DNN Platform/Connectors/Azure/AzureConnector.dnn
  DNN Platform/Connectors/GoogleAnalytics/GoogleAnalyticsConnector.dnn
  DNN Platform/Connectors/GoogleTagManager/GoogleTagManagerConnector.dnn
  DNN Platform/Dnn.AuthServices.Jwt/Dnn.Jwt.dnn
  DNN Platform/DotNetNuke.Web.Deprecated/dnn_Web_Deprecated.dnn
  DNN Platform/DotNetNuke.WebUtility/DotNetNuke.ClientAPI.dnn
  DNN Platform/DotNetNuke.Website.Deprecated/dnn_Website_Deprecated.dnn
  DNN Platform/JavaScript Libraries/Knockout/Knockout.dnn
  DNN Platform/JavaScript Libraries/KnockoutMapping/KnockoutMapping.dnn
  DNN Platform/JavaScript Libraries/Selectize/Selectize.dnn
  DNN Platform/JavaScript Libraries/jQuery/jQuery.dnn
  DNN Platform/JavaScript Libraries/jQueryMigrate/jQueryMigrate.dnn
  DNN Platform/JavaScript Libraries/jQueryUI/jQueryUI.dnn
  DNN Platform/Modules/CoreMessaging/CoreMessaging.dnn
  DNN Platform/Modules/DDRMenu/DDRMenu.dnn
  DNN Platform/Modules/DigitalAssets/dnn_DigitalAssets.dnn
  DNN Platform/Modules/DnnExportImport/dnn_SiteExportImport.dnn
  DNN Platform/Modules/Groups/SocialGroups.dnn
  DNN Platform/Modules/HTML/dnn_HTML.dnn
  DNN Platform/Modules/HtmlEditorManager/dnn_HtmlEditorManager.dnn
  DNN Platform/Modules/Journal/Journal.dnn
  DNN Platform/Modules/MemberDirectory/MemberDirectory.dnn
  DNN Platform/Modules/RazorHost/RazorHost.dnn
  DNN Platform/Modules/ResourceManager/ResourceManager.dnn
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Facebook/Facebook_Auth.dnn
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Google/Google_Auth.dnn
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.LiveConnect/Live_Auth.dnn
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Twitter/Twitter_Auth.dnn
  DNN Platform/Providers/CachingProviders/DotNetNuke.Providers.Caching.SimpleWebFarmCachingProvider/SimpleWebFarmCachingProvider.dnn
  DNN Platform/Providers/ClientCapabilityProviders/Provider.AspNetCCP/AspNetClientCapabilityProvider.dnn
  DNN Platform/Providers/FolderProviders/FolderProviders.dnn
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/DNNConnect.CKEditorProvider.dnn
  DNN Platform/Skins/Xcillion/DNN_Skin_Xcillion.dnn
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Dnn.PersonaBar.Extensions.dnn
  Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/Dnn.EditBar.UI.dnn
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/Dnn.PersonaBar.UI.dnn
Labels: Type: Documentation

#4899 fix null pointer exception when called from scheduled tasks (fixes #4898)
  DNN Platform/DotNetNuke.Web.Client/ClientResourceSettings.cs
Labels: Type: Enhancement

#4897 Fixed getting Folders by Permissions
  DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.10.03.SqlDataProvider
Labels: Type: Bug

#4901 fix issue #4900 - created and used overloads that take the portalId as parameter
  DNN Platform/DotNetNuke.Web.Client/ClientResourceSettings.cs
  DNN Platform/Library/Entities/Portals/PortalSettingsController.cs
Labels: Type: Bug

#4907 Fix #4906: cache the roles array in the user info object.
  DNN Platform/Library/Entities/Users/UserInfo.cs
Labels: Type: Enhancement

#4911 Fix #4910: check the page name with case insensitive.
  DNN Platform/Library/Entities/Urls/AdvancedFriendlyUrlProvider.cs
Labels: Type: Bug

#4909 Standardize Upload interfaces
  DNN Platform/DotNetNuke.Web/InternalServices/FileUploadController.cs
  DNN Platform/Website/Resources/Shared/components/FileUpload/dnn.FileUpload.js
  Dnn.AdminExperience/ClientSide/Dnn.React.Common/src/FileUpload/index.jsx
Labels: Type: Enhancement, Area: AE > Dnn.React.Common

#4868 upgrade knockout js to 3.5.1.
  DNN Platform/JavaScript Libraries/Knockout/03.03.00.txt
  DNN Platform/JavaScript Libraries/Knockout/Knockout.dnn
  DNN Platform/JavaScript Libraries/Knockout/knockout.js
  DNN Platform/Website/Resources/Shared/scripts/knockout.js
  DNN_Platform.sln
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/scripts/contrib/knockout.js
Labels: Type: Maintenance

#4913 Add workflow to auto-open PRs to v9.11 branch
  .github/workflows/open-merged-pr-to-future-9.11.0.yml
Labels: Type: Maintenance

#4914 Update version in Yarn lock file after bumping
  .github/workflows/updateVersions.yml
Labels: Type: Maintenance

#4916 Update website templates to set `User Registration` to `None` by default
  DNN Platform/Website/Portals/_default/Blank Website.template
  DNN Platform/Website/Portals/_default/Default Website.template
Labels: Type: Enhancement, Area: Platform > Website, Effort: Low, Priority: High, Status: Review

#4921 Updated website templates to make `Activity Feed`, `My Profile`, `Friends`, and `Messages` pages visible to `Registered Users` only by default
  DNN Platform/Website/Portals/_default/Blank Website.template
  DNN Platform/Website/Portals/_default/Default Website.template
Labels: Type: Enhancement, Area: Platform > Website, Effort: Low, Priority: High, Status: Review
