Repository dnnsoftware/Dnn.Platform, pull requests merged in 2021-04, with the labels that each got.

#4576 Use binary logger instead of console logger for speedier builds
  .gitignore
  Build/Build.csproj
  Build/Program.cs
  Build/Tasks/Build.cs
Labels: Type: Build/Release

#4582 Fixed an issue that prevented MailKit configuration upon upgrades
  DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.09.00.SqlDataProvider
Labels: Type: Bug

#4577 Add initial dependabot config
  .github/dependabot.yml
Labels: Type: Build/Release, Type: Maintenance

#4575 Add package for MailKit
  Build/Tasks/OtherPackages.cs
  Build/Tasks/PackageMailKit.cs
  Build/Tasks/packaging.json
  Build/Tasks/unversionedManifests.txt
  DNN Platform/Components/MailKit/License.txt
  DNN Platform/Components/MailKit/MailKit.dnn
Labels: Type: Build/Release

#4597 Add capability to add existing modules from other sites in site group
  DNN Platform/DotNetNuke.Web/InternalServices/ItemListServiceController.cs
  Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/editBar/resources/ContentEditorManager/Js/ExistingModuleDialog.js
  Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/editBar/resources/ContentEditorManager/Js/ModuleDialog.js
  Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/editBar/resources/ContentEditorManager/Styles/ContentEditor.css
Labels: Area: AE > Dnn.EditBar.UI, Effort: Medium, Priority: Low, Status: Review, Type: Feature

#4602 Don't include System.Buffers in bin
  Build/Tasks/packaging.json
Labels: Type: Build/Release

#4606 Updates develop with latest changes from 9.9.1
  Build/Tasks/packaging.json
Labels: Type: Build/Release

#4608 Produce snupkg format for NuGet
  Build/Tasks/CreateNugetPackages.cs
Labels: Type: Build/Release

#4619 Fix MailKitMailProvider using incorrect priority
  DNN Platform/Library/Services/Mail/MailKitMailProvider.cs
Labels: Type: Bug

#4631 Fix HTML Editor Manager failure to load
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Helper/TreeViewHelper.cs
Labels: Type: Bug

#4603 Adjust labels used by dependabot
  .github/dependabot.yml
Labels: Type: Build/Release, Type: Maintenance

#4615 Update PasswordReset.ascx.cs
  DNN Platform/Website/admin/Security/PasswordReset.ascx
  DNN Platform/Website/admin/Security/PasswordReset.ascx.cs
Labels: Type: Bug

#4622 Use ConcurrentDictionary in FolderManager.cs
  DNN Platform/Library/Services/FileSystem/FolderManager.cs
Labels: Type: Bug
