Repository dnnsoftware/Dnn.Platform, pull requests merged in 2021-12, with the labels that each got.

#4925 Fixed SEO tab not updating correctly after deleting a URL
  Dnn.AdminExperience/ClientSide/Pages.Web/src/components/Seo/PageUrls/Table.jsx
Labels: Type: Bug

#4926 Adjust release merge workflow
  .github/workflows/open-merged-pr-to-future-9.11.0.yml
Labels: Type: Build/Release

#4755 Add workflow to auto-open PRs to v10 branch
  .github/workflows/open-merged-pr-to-future.yml
Labels: Type: Maintenance

#4929 Updated Module.css to fix #4928
  DNN Platform/Modules/ResourceManager/module.css
Labels: Type: Enhancement

#4932 HTML encode message input
  DNN Platform/Website/admin/Security/SendPassword.ascx.cs
Labels: Type: Bug

#4930 No module message should be able to contain any scripts
  DNN Platform/Library/UI/Skins/Skin.cs
Labels: Type: Bug, Area: Platform > Library

#4933 Revert "No module message should be able to contain any scripts"
  DNN Platform/Library/UI/Skins/Skin.cs
Labels: Type: Feature

#4959 Make check for RequestVerificationToken case insensitive as per RFC 7230 and RFC 7540.
  DNN Platform/DotNetNuke.Web.Mvc/Framework/ActionFilters/ValidateAntiForgeryTokenAttribute.cs
Labels: Type: Bug, Area: Platform > DotNetNuke.Web.Mvc

#4931 Update 9.11.0 branch with changes from develop
  .github/workflows/open-merged-pr-to-future-9.11.0.yml
  .github/workflows/open-merged-pr-to-future.yml
  .github/workflows/updateVersions.yml
  DNN Platform/DotNetNuke.Web.Mvc/Framework/ActionFilters/ValidateAntiForgeryTokenAttribute.cs
  DNN Platform/Modules/ResourceManager/module.css
  DNN Platform/Website/admin/Security/SendPassword.ascx.cs
  Dnn.AdminExperience/ClientSide/Pages.Web/src/components/Seo/PageUrls/Table.jsx
Labels: Type: Maintenance
