Repository dnnsoftware/Dnn.Platform, pull requests merged in 2021-08, with the labels that each got.

#4761 Issue-4760 - Deleting the parent page while the child page is open doesn't redirect
  Dnn.AdminExperience/ClientSide/Pages.Web/src/actions/__test__/pageActions.test.js
  Dnn.AdminExperience/ClientSide/Pages.Web/src/actions/pageActions.js
Labels: Type: Bug

#4754 Fixed an issue with issue template and version update action
  .github/workflows/updateVersions.yml
Labels: Type: Bug

#4773 Issue-4772 - Wrong PortalId is getting set when there are multiple sites existing
  Dnn.AdminExperience/ClientSide/SiteSettings.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteSettings.Web/src/reducers/__tests__/siteInfoReducer.test.js
  Dnn.AdminExperience/ClientSide/SiteSettings.Web/src/reducers/siteInfoReducer.js
Labels: Type: Bug

#4780 Updates CDF to v1.9.10
  .nuget/NuGet.Config
  DNN Platform/DotNetNuke.Web.Client/DotNetNuke.Web.Client.csproj
  DNN Platform/DotNetNuke.Web.Client/packages.config
  DNN Platform/DotNetNuke.Web.Deprecated/DotNetNuke.Web.Deprecated.csproj
  DNN Platform/DotNetNuke.Web/DotNetNuke.Web.csproj
  DNN Platform/DotNetNuke.Web/packages.config
  DNN Platform/DotNetNuke.Website.Deprecated/DotNetNuke.Website.Deprecated.csproj
  DNN Platform/Library/DotNetNuke.Library.csproj
  DNN Platform/Library/packages.config
  DNN Platform/Website/DotNetNuke.Website.csproj
  DNN Platform/Website/packages.config
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/Dnn.PersonaBar.UI.csproj
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/packages.config
Labels: Type: Maintenance

#4777 Add missing columns to messaging stored procs
  DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.10.01.SqlDataProvider
Labels: Type: Bug

#4774 Added lint task to all node projects
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/package.json
  Dnn.AdminExperience/ClientSide/AdminLogs.Web/package.json
  Dnn.AdminExperience/ClientSide/Bundle.Web/package.json
  Dnn.AdminExperience/ClientSide/Dnn.React.Common/package.json
  Dnn.AdminExperience/ClientSide/Pages.Web/package.json
  Dnn.AdminExperience/ClientSide/Prompt.Web/package.json
  Dnn.AdminExperience/ClientSide/Roles.Web/package.json
  Dnn.AdminExperience/ClientSide/Security.Web/package.json
  Dnn.AdminExperience/ClientSide/Seo.Web/package.json
  Dnn.AdminExperience/ClientSide/Servers.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteImportExport.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteSettings.Web/package.json
  Dnn.AdminExperience/ClientSide/Sites.Web/package.json
  Dnn.AdminExperience/ClientSide/TaskScheduler.Web/package.json
  Dnn.AdminExperience/ClientSide/Themes.Web/package.json
  Dnn.AdminExperience/ClientSide/Users.Web/package.json
  Dnn.AdminExperience/ClientSide/Vocabularies.Web/package.json
Labels: Type: Maintenance

#4778 Use Yarn 3
  .gitignore
  .yarn/releases/yarn-3.0.0.cjs
  .yarnrc.yml
  Build/BuildScripts/AEModule.build
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/package.json
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/webpack.config.js
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/yarn.lock
  Dnn.AdminExperience/ClientSide/AdminLogs.Web/package.json
  Dnn.AdminExperience/ClientSide/AdminLogs.Web/webpack.config.js
  Dnn.AdminExperience/ClientSide/Bundle.Web/package.json
  Dnn.AdminExperience/ClientSide/Bundle.Web/webpack.config.js
  Dnn.AdminExperience/ClientSide/Dnn.React.Common/package.json
  Dnn.AdminExperience/ClientSide/Extensions.Web/package.json
  Dnn.AdminExperience/ClientSide/Extensions.Web/webpack.config.js
  Dnn.AdminExperience/ClientSide/Licensing.Web/package.json
  Dnn.AdminExperience/ClientSide/Licensing.Web/webpack.config.js
  Dnn.AdminExperience/ClientSide/Pages.Web/package.json
  Dnn.AdminExperience/ClientSide/Pages.Web/webpack.config.js
  Dnn.AdminExperience/ClientSide/Prompt.Web/package.json
  Dnn.AdminExperience/ClientSide/Prompt.Web/webpack.config.js
  Dnn.AdminExperience/ClientSide/Roles.Web/package.json
  Dnn.AdminExperience/ClientSide/Roles.Web/webpack.config.js
  Dnn.AdminExperience/ClientSide/Security.Web/package.json
  Dnn.AdminExperience/ClientSide/Security.Web/webpack.config.js
  Dnn.AdminExperience/ClientSide/Seo.Web/package.json
  Dnn.AdminExperience/ClientSide/Seo.Web/webpack.config.js
  Dnn.AdminExperience/ClientSide/Servers.Web/package.json
  Dnn.AdminExperience/ClientSide/Servers.Web/webpack.config.js
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/webpack.config.js
  Dnn.AdminExperience/ClientSide/SiteImportExport.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteImportExport.Web/webpack.config.js
  Dnn.AdminExperience/ClientSide/SiteSettings.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteSettings.Web/webpack.config.js
  Dnn.AdminExperience/ClientSide/Sites.Web/package.json
  Dnn.AdminExperience/ClientSide/Sites.Web/src/_exportables/package.json
  Dnn.AdminExperience/ClientSide/Sites.Web/src/_exportables/webpack.config.js
  Dnn.AdminExperience/ClientSide/Sites.Web/webpack.config.js
  Dnn.AdminExperience/ClientSide/TaskScheduler.Web/package.json
  Dnn.AdminExperience/ClientSide/TaskScheduler.Web/webpack.config.js
  Dnn.AdminExperience/ClientSide/Themes.Web/package.json
  Dnn.AdminExperience/ClientSide/Themes.Web/webpack.config.js
  Dnn.AdminExperience/ClientSide/Users.Web/package.json
  Dnn.AdminExperience/ClientSide/Users.Web/src/_exportables/package.json
  Dnn.AdminExperience/ClientSide/Users.Web/src/_exportables/webpack.config.js
  Dnn.AdminExperience/ClientSide/Users.Web/webpack.config.js
  Dnn.AdminExperience/ClientSide/Vocabularies.Web/package.json
  Dnn.AdminExperience/ClientSide/Vocabularies.Web/webpack.config.js
  azure-pipelines.yml
  package.json
  yarn.lock
Labels: Type: Build/Release, Type: Maintenance

#4795 Merges latest changes for 9.10.1 into develop
  .github/ISSUE_TEMPLATE/bug-report.md
  Build/Symbols/DotNetNuke_Symbols.dnn
  DNN Platform/Admin Modules/Dnn.Modules.Console/dnn_Console.dnn
  DNN Platform/Components/Telerik/DotNetNuke.Telerik.Web.dnn
  DNN Platform/Connectors/Azure/AzureConnector.dnn
  DNN Platform/Connectors/GoogleAnalytics/GoogleAnalyticsConnector.dnn
  DNN Platform/Connectors/GoogleTagManager/GoogleTagManagerConnector.dnn
  DNN Platform/Dnn.AuthServices.Jwt/Dnn.Jwt.dnn
  DNN Platform/DotNetNuke.Web.Deprecated/dnn_Web_Deprecated.dnn
  DNN Platform/DotNetNuke.WebUtility/DotNetNuke.ClientAPI.dnn
  DNN Platform/DotNetNuke.Website.Deprecated/dnn_Website_Deprecated.dnn
  DNN Platform/Modules/CoreMessaging/CoreMessaging.dnn
  DNN Platform/Modules/DDRMenu/DDRMenu.dnn
  DNN Platform/Modules/DigitalAssets/dnn_DigitalAssets.dnn
  DNN Platform/Modules/DnnExportImport/dnn_SiteExportImport.dnn
  DNN Platform/Modules/Groups/SocialGroups.dnn
  DNN Platform/Modules/HTML/dnn_HTML.dnn
  DNN Platform/Modules/HtmlEditorManager/dnn_HtmlEditorManager.dnn
  DNN Platform/Modules/Journal/Journal.dnn
  DNN Platform/Modules/MemberDirectory/MemberDirectory.dnn
  DNN Platform/Modules/RazorHost/Manifest.dnn
  DNN Platform/Modules/RazorHost/RazorHost.dnn
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/package.json
  DNN Platform/Modules/ResourceManager/ResourceManager.dnn
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Facebook/Facebook_Auth.dnn
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Google/Google_Auth.dnn
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.LiveConnect/Live_Auth.dnn
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Twitter/Twitter_Auth.dnn
  DNN Platform/Providers/CachingProviders/DotNetNuke.Providers.Caching.SimpleWebFarmCachingProvider/SimpleWebFarmCachingProvider.dnn
  DNN Platform/Providers/ClientCapabilityProviders/Provider.AspNetCCP/AspNetClientCapabilityProvider.dnn
  DNN Platform/Providers/FolderProviders/FolderProviders.dnn
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/DNNConnect.CKEditorProvider.dnn
  DNN Platform/Skins/Xcillion/DNN_Skin_Xcillion.dnn
  Dnn.AdminExperience/ClientSide/AdminLogs.Web/package.json
  Dnn.AdminExperience/ClientSide/Bundle.Web/package.json
  Dnn.AdminExperience/ClientSide/Dnn.React.Common/package.json
  Dnn.AdminExperience/ClientSide/Extensions.Web/package.json
  Dnn.AdminExperience/ClientSide/Licensing.Web/package.json
  Dnn.AdminExperience/ClientSide/Pages.Web/package.json
  Dnn.AdminExperience/ClientSide/Prompt.Web/package.json
  Dnn.AdminExperience/ClientSide/Roles.Web/package.json
  Dnn.AdminExperience/ClientSide/Security.Web/package.json
  Dnn.AdminExperience/ClientSide/Seo.Web/package.json
  Dnn.AdminExperience/ClientSide/Servers.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteImportExport.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteSettings.Web/package.json
  Dnn.AdminExperience/ClientSide/Sites.Web/package.json
  Dnn.AdminExperience/ClientSide/Sites.Web/src/_exportables/package.json
  Dnn.AdminExperience/ClientSide/TaskScheduler.Web/package.json
  Dnn.AdminExperience/ClientSide/Themes.Web/package.json
  Dnn.AdminExperience/ClientSide/Users.Web/package.json
  Dnn.AdminExperience/ClientSide/Users.Web/src/_exportables/package.json
  Dnn.AdminExperience/ClientSide/Vocabularies.Web/package.json
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Dnn.PersonaBar.Extensions.dnn
  Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/Dnn.EditBar.UI.dnn
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/Dnn.PersonaBar.UI.dnn
  SolutionInfo.cs
  package.json
Labels: Type: Build/Release

#4797 Updates issue template as per current state
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: Type: Documentation

#4802 Fixed an issue that prevented inserting links using the default HTML Editor Provider
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/js/ckeditor/4.15.1/plugins/dnnpages/lang/fr.js
Labels: Type: Bug, Area: Platform > Modules, Effort: Low, Priority: Medium

#4803 Corrected a typo in CKEditor for dnnpages plugin in french
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/js/ckeditor/4.15.1/plugins/dnnpages/lang/fr.js
Labels: Type: Maintenance
