Repository dnnsoftware/Dnn.Platform, pull requests merged in 2021-05, with the labels that each got.

#4677 Deleted InvalidConfiguration.ascx.resx in HtmlEditormanager
  DNN Platform/Modules/HtmlEditorManager/Controls/App_LocalResources/InvalidConfiguration.ascx.resx
Labels: Type: Documentation

#4675 Improved wording on Site Groups localization
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.SiteGroups/App_LocalResources/SiteGroups.resx
Labels: Type: Documentation

#4678 Clarified text on module anchor feature
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.SiteSettings/App_LocalResources/SiteSettings.resx
Labels: Type: Documentation

#4671 Update BreadCrumb.ascx.cs
  DNN Platform/Website/admin/Skins/BreadCrumb.ascx.cs
  DNN Platform/Website/admin/Skins/BreadCrumb.xml
Labels: Type: Bug

#4674 Fixed some typos in Prompt localization
  DNN Platform/Website/App_GlobalResources/Prompt.resx
Labels: Type: Documentation

#4676 Removed unused localization strings in GlobalResources.resx
  DNN Platform/Website/App_GlobalResources/GlobalResources.resx
Labels: Type: Documentation

#4685 Issue-4684 - Exporting a page after changing a module's order within the same pane doesn't reflect in imported site
  DNN Platform/Modules/DnnExportImport/Components/Services/PagesExportService.cs
Labels: Type: Bug

#4687 Added support for Azure folder provider cache control
  DNN Platform/Providers/FolderProviders/AzureFolderProvider/AzureFolderProvider.cs
Labels: Type: Enhancement

#4691 Improve base styling of PersonaBar & EditBar and allow customization
  DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.09.02.SqlDataProvider
  Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/Controllers/EditBarController.cs
  Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/Dnn.EditBar.UI.csproj
  Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/editBar/css/main.css
  Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/editBar/css/theme.css
  Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/editBar/scripts/bootstrap.js
  Dnn.AdminExperience/Library/Dnn.PersonaBar.Library/Containers/PersonaBarContainer.cs
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/Dnn.PersonaBar.UI.csproj
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/personaBarContainer.css
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/theme.css
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/images/nav_content.svg
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/images/nav_edit.svg
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/images/nav_manage.svg
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/images/nav_settings.svg
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/scripts/bootstrap.js
Labels: Type: Enhancement

#4693 Update version from 9.9.0 to 9.9.1
  Build/Symbols/DotNetNuke_Symbols.dnn
  DNN Platform/Admin Modules/Dnn.Modules.Console/dnn_Console.dnn
  DNN Platform/Components/Telerik/DotNetNuke.Telerik.Web.dnn
  DNN Platform/Connectors/Azure/AzureConnector.dnn
  DNN Platform/Connectors/GoogleAnalytics/GoogleAnalyticsConnector.dnn
  DNN Platform/Connectors/GoogleTagManager/GoogleTagManagerConnector.dnn
  DNN Platform/Dnn.AuthServices.Jwt/Dnn.Jwt.dnn
  DNN Platform/DotNetNuke.Web.Deprecated/dnn_Web_Deprecated.dnn
  DNN Platform/DotNetNuke.WebUtility/DotNetNuke.ClientAPI.dnn
  DNN Platform/DotNetNuke.Website.Deprecated/dnn_Website_Deprecated.dnn
  DNN Platform/Modules/CoreMessaging/CoreMessaging.dnn
  DNN Platform/Modules/DDRMenu/DDRMenu.dnn
  DNN Platform/Modules/DigitalAssets/dnn_DigitalAssets.dnn
  DNN Platform/Modules/DnnExportImport/dnn_SiteExportImport.dnn
  DNN Platform/Modules/Groups/SocialGroups.dnn
  DNN Platform/Modules/HTML/dnn_HTML.dnn
  DNN Platform/Modules/HtmlEditorManager/dnn_HtmlEditorManager.dnn
  DNN Platform/Modules/Journal/Journal.dnn
  DNN Platform/Modules/MemberDirectory/MemberDirectory.dnn
  DNN Platform/Modules/RazorHost/Manifest.dnn
  DNN Platform/Modules/RazorHost/RazorHost.dnn
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/package.json
  DNN Platform/Modules/ResourceManager/ResourceManager.dnn
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Facebook/Facebook_Auth.dnn
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Google/Google_Auth.dnn
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.LiveConnect/Live_Auth.dnn
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Twitter/Twitter_Auth.dnn
  DNN Platform/Providers/CachingProviders/DotNetNuke.Providers.Caching.SimpleWebFarmCachingProvider/SimpleWebFarmCachingProvider.dnn
  DNN Platform/Providers/ClientCapabilityProviders/Provider.AspNetCCP/AspNetClientCapabilityProvider.dnn
  DNN Platform/Providers/FolderProviders/FolderProviders.dnn
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/DNNConnect.CKEditorProvider.dnn
  DNN Platform/Skins/Xcillion/DNN_Skin_Xcillion.dnn
  Dnn.AdminExperience/ClientSide/AdminLogs.Web/package.json
  Dnn.AdminExperience/ClientSide/Bundle.Web/package.json
  Dnn.AdminExperience/ClientSide/Dnn.React.Common/package.json
  Dnn.AdminExperience/ClientSide/Extensions.Web/package.json
  Dnn.AdminExperience/ClientSide/Licensing.Web/package.json
  Dnn.AdminExperience/ClientSide/Pages.Web/package.json
  Dnn.AdminExperience/ClientSide/Prompt.Web/package.json
  Dnn.AdminExperience/ClientSide/Roles.Web/package.json
  Dnn.AdminExperience/ClientSide/Security.Web/package.json
  Dnn.AdminExperience/ClientSide/Seo.Web/package.json
  Dnn.AdminExperience/ClientSide/Servers.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteImportExport.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteSettings.Web/package.json
  Dnn.AdminExperience/ClientSide/Sites.Web/package.json
  Dnn.AdminExperience/ClientSide/Sites.Web/src/_exportables/package.json
  Dnn.AdminExperience/ClientSide/TaskScheduler.Web/package.json
  Dnn.AdminExperience/ClientSide/Themes.Web/package.json
  Dnn.AdminExperience/ClientSide/Users.Web/package.json
  Dnn.AdminExperience/ClientSide/Users.Web/src/_exportables/package.json
  Dnn.AdminExperience/ClientSide/Vocabularies.Web/package.json
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Dnn.PersonaBar.Extensions.dnn
  Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/Dnn.EditBar.UI.dnn
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/Dnn.PersonaBar.UI.dnn
  SolutionInfo.cs
Labels: Type: Maintenance
