Repository dnnsoftware/Dnn.Platform, pull requests merged in 2021-03, with the labels that each got.

#4532 Fixed an issue where checksums where not generated in CI builds
  Build/Cake/build.cs
  Build/Cake/ci.cs
Labels: Type: Build/Release

#4533 Remove NuGet dependency from Instrumentation
  Build/Tools/NuGet/DotNetNuke.Instrumentation.nuspec
Labels: Type: Build/Release

#4478 Update Compress Images GitHub Actions workflow
  .github/workflows/image-actions.yml
Labels: Type: Build/Release

#4544 Fix typo in image-actions
  .github/workflows/image-actions.yml
Labels: Type: Bug, Type: Build/Release

#4546 Fixed an issue where CK-Editor provider did not include image files in install package
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/DNNConnect.CKEditorProvider.csproj
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Provider.build
Labels: Type: Bug

#4482 Fixes #4481 AzureFolderProvider uploading same file with different case
  DNN Platform/Providers/FolderProviders/AzureFolderProvider/AzureFolderProvider.cs
Labels: Type: Bug

#4547 fixed redirect to primary alias when PortalAliasMapping is set to redirect
  DNN Platform/Library/Entities/Urls/AdvancedUrlRewriter.cs
Labels: Type: Bug

#4552 Upgrade Cake to 1.1.0
  Build/Build.csproj
  Build/Cake/build.cs
  Build/Program.cs
Labels: Type: Build/Release

#4498 Add async support to mail providers
  DNN Platform/Library/Services/Mail/CoreMailProvider.cs
  DNN Platform/Library/Services/Mail/MailKitMailProvider.cs
  DNN Platform/Library/Services/Mail/MailProvider.cs
Labels: Type: Enhancement

#4531 Enable URL integration tests to run
  DNN Platform/Admin Modules/Dnn.Modules.Console/Dnn.Modules.Console.csproj
  DNN Platform/Connectors/Azure/Dnn.AzureConnector.csproj
  DNN Platform/Connectors/GoogleAnalytics/Dnn.GoogleAnalyticsConnector.csproj
  DNN Platform/Connectors/GoogleTagManager/Dnn.GoogleTagManagerConnector.csproj
  DNN Platform/Controls/CountryListBox/CountryListBox.csproj
  DNN Platform/Dnn.AuthServices.Jwt/Dnn.AuthServices.Jwt.csproj
  DNN Platform/DotNetNuke.Instrumentation/DotNetNuke.Instrumentation.csproj
  DNN Platform/DotNetNuke.Log4net/DotNetNuke.Log4Net.csproj
  DNN Platform/DotNetNuke.Web.Client/DotNetNuke.Web.Client.csproj
  DNN Platform/DotNetNuke.Web.Mvc/DotNetNuke.Web.Mvc.csproj
  DNN Platform/DotNetNuke.Web.Razor/DotNetNuke.Web.Razor.csproj
  DNN Platform/DotNetNuke.WebUtility/DotNetNuke.WebUtility.vbproj
  DNN Platform/HttpModules/DotNetNuke.HttpModules.csproj
  DNN Platform/Library/Properties/AssemblyInfo.cs
  DNN Platform/Modules/CoreMessaging/DotNetNuke.Modules.CoreMessaging.csproj
  DNN Platform/Modules/DDRMenu/DotNetNuke.Modules.DDRMenu.csproj
  DNN Platform/Modules/DnnExportImport/DnnExportImport.csproj
  DNN Platform/Modules/DnnExportImportLibrary/DnnExportImportLibrary.csproj
  DNN Platform/Modules/Groups/DotNetNuke.Modules.Groups.csproj
  DNN Platform/Modules/HtmlEditorManager/DotNetNuke.Modules.HtmlEditorManager.csproj
  DNN Platform/Modules/Journal/DotNetNuke.Modules.Journal.csproj
  DNN Platform/Modules/MemberDirectory/DotNetNuke.Modules.MemberDirectory.csproj
  DNN Platform/Modules/RazorHost/DotNetNuke.Modules.RazorHost.csproj
  DNN Platform/Modules/ResourceManager/Dnn.Modules.ResourceManager.csproj
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Facebook/DotNetNuke.Authentication.Facebook.csproj
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Google/DotNetNuke.Authentication.Google.csproj
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.LiveConnect/DotNetNuke.Authentication.LiveConnect.csproj
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Twitter/DotNetNuke.Authentication.Twitter.csproj
  DNN Platform/Providers/CachingProviders/DotNetNuke.Providers.Caching.SimpleWebFarmCachingProvider/DotNetNuke.Providers.Caching.SimpleWebFarmCachingProvider.csproj
  DNN Platform/Providers/ClientCapabilityProviders/Provider.AspNetCCP/DotNetNuke.Providers.AspNetCCP.csproj
  DNN Platform/Providers/FolderProviders/DotNetNuke.Providers.FolderProviders.csproj
  DNN Platform/Syndication/DotNetNuke.Syndication.csproj
  DNN Platform/Tests/App.config
  DNN Platform/Tests/DotNetNuke.Tests.Integration/DotNetNuke.Tests.Integration.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Integration/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Urls/DotNetNuke.Tests.Urls.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Urls/UrlRewriteTests.cs
  DNN Platform/Tests/DotNetNuke.Tests.Urls/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Utilities/DnnWebTest.cs
  DNN Platform/Tests/DotNetNuke.Tests.Utilities/DotNetNuke.Tests.Utilities.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Utilities/packages.config
  DNN Platform/Website/DotNetNuke.Website.csproj
  DNN_Platform.sln.DotSettings
Labels: Type: Maintenance
