Repository dnnsoftware/Dnn.Platform, pull requests merged in 2021-06, with the labels that each got.

#4702 Improve Validation IP Address for login
  DNN Platform/Website/DesktopModules/Admin/Authentication/Login.ascx.cs
Labels: Type: Bug

#4655 Fix for #4654: Unable to Upload File into Assets On Turkish Localization
  DNN Platform/DotNetNuke.Web/InternalServices/FileUploadController.cs
  DNN Platform/Tests/DotNetNuke.Tests.Utilities/Mocks/MockComponentProvider.cs
  DNN Platform/Tests/DotNetNuke.Tests.Web/DotNetNuke.Tests.Web.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Web/InternalServices/FileUploadControllerTests.cs
Labels: Type: Bug

#4712 Deprecating DisplayCopyright Host Setting
  DNN Platform/Library/Entities/Host/Host.cs
Labels: Type: Maintenance

#4714 Issue-4673 - SQL Console raises error for variable declarations with "@" character
  DNN Platform/Library/Data/PetaPoco/PetaPocoExt.cs
  DNN Platform/Tests/DotNetNuke.Tests.Data/DotNetNuke.Tests.Data.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Data/PetaPocoExtTests.cs
Labels: Type: Bug

#4695 Bring back update notification
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/Dnn.PersonaBar.UI.csproj
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/Services/Dto/FrameworkQueryDTO.cs
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/Services/ServerSummaryController.cs
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/App_LocalResources/PersonaBar.resx
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/index.html
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/scripts/main.js
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/scripts/serversummary.js
Labels: Noteworthy, Type: Enhancement

#4641 add email to password sent message for error tracing, fixes #4605
  DNN Platform/Website/admin/Security/App_LocalResources/SendPassword.ascx.resx
  DNN Platform/Website/admin/Security/SendPassword.ascx.cs
Labels: Type: Enhancement

#4708 Fixed an issue where UserInfo.UserName was wrong with "Use email as username" setting turned on
  DNN Platform/Library/Entities/Users/UserInfo.cs
Labels: Area: Platform > Library, Type: Bug

#4722 Removed the logo from the Under Construction page
  DNN Platform/Website/Install/UnderConstruction.template.htm
Labels: Type: Bug

#4703 Fix for #4672: Cache-Setting 'NoCaching' not saved
  Dnn.AdminExperience/ClientSide/Servers.Web/src/components/Tabs/Performance.jsx
Labels: Type: Bug
