Repository dnnsoftware/Dnn.Platform, pull requests merged in 2021-09, with the labels that each got.

#4800 Upgrade to Cake 1.2.0
  Build/Build.csproj
  Build/Context.cs
  Build/Program.cs
  Build/Tasks/Build.cs
  Build/Tasks/BuildAll.cs
  Build/Tasks/CreateNugetPackages.cs
  Build/Tasks/UnitTests.cs
  build.config
  gitversion.yml
Labels: Type: Build/Release, Type: Maintenance

#4811 Allow multiple DesktopModules per PackageID
  DNN Platform/Library/Entities/Modules/DesktopModuleInfo.cs
  DNN Platform/Library/Services/Installer/Installers/ModuleInstaller.cs
Labels: Type: Enhancement, Noteworthy

#4824 Custom Analyzer types generate System.MissingMethodException
  DNN Platform/Library/Framework/Reflection.cs
  DNN Platform/Library/Services/Search/Internals/LuceneControllerImpl.cs
  DNN Platform/Tests/DotNetNuke.Tests.Core/DotNetNuke.Tests.Core.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Core/Framework/ReflectionTests.cs
  DNN Platform/Tests/DotNetNuke.Tests.Core/Services/Search/Internals/LuceneControllerImplTests.cs
Labels: Type: Bug

#4786 Avoid HTML module using Globals.DependencyProvider
  DNN Platform/Modules/HTML/Components/HtmlTextController.cs
  DNN Platform/Modules/HTML/EditHtml.ascx.cs
  DNN Platform/Modules/HTML/HtmlModule.ascx.cs
  DNN Platform/Modules/HTML/Settings.ascx.cs
Labels: Type: Enhancement

#4788 Resolve serialization issue
  DNN Platform/Library/Services/Authentication/AuthenticationConfigBase.cs
Labels: Type: Bug

#4805 Add back alternate views for core mail provider
  DNN Platform/Library/Services/Mail/CoreMailProvider.cs
  DNN Platform/Tests/DotNetNuke.Tests.Core/Services/Mail/MailTests.cs
Labels: Type: Bug

#4790 IE11 corrections fixes #4787
  Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/editBar/css/main.css
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
Labels: Type: Enhancement

#4827 Added documentation about yarn updates
  .github/BUILD.md
Labels: Type: Documentation

#4828 Fixed an issue where it was impossible to edit html on child portals
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/DNNConnect.CKEditorProvider.csproj
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Web/EditorControl.cs
Labels: Type: Bug

#4815 Marked nuget dependency from DotNetNuke.Web on Microsoft.AspNet.WebApi.Core
  Build/Tools/NuGet/DotNetNuke.Web.nuspec
Labels: Type: Maintenance

#4831 Removed module specific styling for a default DNN Button
  DNN Platform/Modules/CoreMessaging/module.css
Labels: Type: Enhancement

#4837 Removal of "Dummy" from code
  DNN Platform/DotNetNuke.Web.Deprecated/UI/WebControls/TermsSelector.cs
  DNN Platform/DotNetNuke.WebUtility/js/MicrosoftAjax.js
  DNN Platform/Library/Entities/Modules/ModuleController.cs
  DNN Platform/Library/Entities/Urls/TabPathController.cs
  DNN Platform/Library/Security/Roles/RoleController.cs
  DNN Platform/Library/Services/GeneratedImage/DnnImageHandler.cs
  DNN Platform/Library/Services/Search/ModuleIndexer.cs
  DNN Platform/Providers/ClientCapabilityProviders/Provider.AspNetCCP/AspNetClientCapabilityProvider.cs
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Services/CloudServicesController.cs
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Utilities/Utility.cs
  DNN Platform/Website/DesktopModules/Admin/Security/ProfileDefinitions.ascx.cs
  DNN Platform/Website/js/Debug/MicrosoftAjax.js
Labels: Type: Enhancement

#4813 Always upload build artifacts
  azure-pipelines.yml
Labels: Type: Build/Release

#4838 Remove unused RestSharp reference
  DNN Platform/Connectors/Azure/Dnn.AzureConnector.csproj
  DNN Platform/Connectors/Azure/packages.config
Labels: Type: Maintenance
