Repository dnnsoftware/Dnn.Platform, pull requests merged in 2021-01, with the labels that each got.

#4396 Add back method which was removed in #3969
  DNN Platform/Library/Services/Mail/Mail.cs
Labels: Area: Platform > Library, Type: Bug

#4393 Fix Issue #3466 - Incorrect Redirect Response Codes
  DNN Platform/Library/Entities/Urls/AdvancedUrlRewriter.cs
  DNN Platform/Library/Entities/Urls/RedirectReason.cs
Labels: Type: Bug

#4387 Issue-4386 - Cannot Create Pages of Type "File"
  Dnn.AdminExperience/ClientSide/Pages.Web/src/components/PageDetails/PageUrl/PageFile/PageFile.jsx
Labels: Area: AE > PersonaBar Ext > Pages.Web, Type: Bug

#4305 New Quick Add Module option from the edit bar
  DNN Platform/DotNetNuke.Abstractions/Portals/IPortalSettings.cs
  DNN Platform/Library/Entities/Portals/PortalController.cs
  DNN Platform/Library/Entities/Portals/PortalSettings.cs
  DNN Platform/Website/DesktopModules/Admin/Portals/portal.template.xsd
  Dnn.AdminExperience/ClientSide/SiteSettings.Web/src/components/moreSettings/index.jsx
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Sites/SitesController.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/DTO/SiteSettings/UpdateOtherSettingsRequest.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/SiteSettingsController.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.SiteSettings/App_LocalResources/SiteSettings.resx
  Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/Dnn.EditBar.UI.csproj
  Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/Items/QuickAddModuleMenu.cs
  Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/editBar/App_LocalResources/QuickAddModule.resx
  Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/editBar/QuickAddModule.html
  Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/editBar/css/QuickAddModule.css
  Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/editBar/css/main.css
  Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/editBar/scripts/QuickAddModule.js
Labels: Area: AE > Dnn.EditBar.UI, Type: Enhancement, Type: Feature

#4406 Updates bug report template as per 9.8.1 release
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: Type: Build/Release

#4206 Removed the unused json2.js from the codebase
  DNN Platform/Modules/Journal/View.ascx.cs
  DNN Platform/Website/DotNetNuke.Website.csproj
  DNN Platform/Website/Licenses/json2 (Public Domain).txt.resources
  DNN Platform/Website/Resources/Shared/scripts/json2.js
Labels: Type: Maintenance

#4399 Admin Logs - Fixed Log Settings errors
  Dnn.AdminExperience/ClientSide/AdminLogs.Web/src/components/LogSettings/LogSettingEditor/index.jsx
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/AdminLogsController.cs
Labels: Area: AE > PersonaBar Ext > AdminLogs.Web, Type: Bug, Type: Enhancement

#4329 Support for secure settings in settings serialization
  DNN Platform/Library/Entities/Modules/Settings/ParameterAttributeBase.cs
  DNN Platform/Library/Entities/Modules/Settings/SettingsRepository.cs
  DNN Platform/Website/App_GlobalResources/SharedResources.resx
Labels: Area: Platform > Library, Type: Enhancement

#4397 Remove member with case-sensitive naming conflict
  DNN Platform/Library/Entities/Portals/PortalInfo.cs
Labels: Alert: Breaking Change, Noteworthy, Type: Bug

#4415 Add sitemap settings to portal template XSD
  DNN Platform/Website/DesktopModules/Admin/Portals/portal.template.xsd
Labels: Type: Bug

#4416 Corrected all license.txt files for module installers to be consistent
  Build/Symbols/license.txt
  DNN Platform/Admin Modules/Dnn.Modules.Console/license.txt
  DNN Platform/Connectors/Azure/license.txt
  DNN Platform/Dnn.AuthServices.Jwt/license.txt
  DNN Platform/DotNetNuke.Web.Deprecated/license.txt
  DNN Platform/DotNetNuke.WebUtility/license.txt
  DNN Platform/DotNetNuke.Website.Deprecated/license.txt
  DNN Platform/Modules/CoreMessaging/license.txt
  DNN Platform/Modules/DDRMenu/License.txt
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Google/license.txt
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.LiveConnect/license.txt
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Twitter/license.txt
  DNN Platform/Providers/ClientCapabilityProviders/Provider.AspNetCCP/License.txt
  DNN Platform/Providers/FolderProviders/license.txt
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Install/license.txt
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/license.txt
  Dnn.AdminExperience/ClientSide/Dnn.React.Common/LICENSE.txt
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/License.txt
  Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/license.txt
  Dnn.AdminExperience/LICENSE.txt
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/license.txt
Labels: Area: AE > Dnn.React.Common, Area: Platform > Admin Modules, Area: Platform > Modules, Type: Maintenance

#4417 Fixe Caching Issue in TermsController
  DNN Platform/Library/Entities/Content/Taxonomy/TermController.cs
Labels: Type: Bug

#4421 Fix DnnImageHandler bug when filepath mixedcase #4420
  DNN Platform/Library/Services/GeneratedImage/DnnImageHandler.cs
Labels: Type: Bug

#4418 Resolved issue with lowercase URL's and account verifications
  DNN Platform/Library/Entities/Urls/FriendlyUrlSettings.cs
Labels: Type: Bug

#4408 New personabar Web Servers tab
  Dnn.AdminExperience/ClientSide/Bundle.Web/src/dnn-common-components.js
  Dnn.AdminExperience/ClientSide/Dnn.React.Common/src/IconButton/index.jsx
  Dnn.AdminExperience/ClientSide/Dnn.React.Common/src/IconButton/style.less
  Dnn.AdminExperience/ClientSide/Dnn.React.Common/src/PermissionGrid/GridRow.jsx
  Dnn.AdminExperience/ClientSide/Dnn.React.Common/src/PermissionGrid/StatusSwitch.jsx
  Dnn.AdminExperience/ClientSide/Dnn.React.Common/src/PermissionGrid/Suggestion/index.jsx
  Dnn.AdminExperience/ClientSide/Dnn.React.Common/src/index.js
  Dnn.AdminExperience/ClientSide/Roles.Web/src/components/common/IconButton/index.jsx
  Dnn.AdminExperience/ClientSide/Roles.Web/src/components/common/IconButton/style.less
  Dnn.AdminExperience/ClientSide/Roles.Web/src/components/roles/FiltersBar/index.jsx
  Dnn.AdminExperience/ClientSide/Roles.Web/src/components/roles/RoleRow/index.jsx
  Dnn.AdminExperience/ClientSide/Roles.Web/src/components/roles/UsersInRole/UserRow/index.jsx
  Dnn.AdminExperience/ClientSide/Roles.Web/src/components/roles/UsersInRole/index.jsx
  Dnn.AdminExperience/ClientSide/Roles.Web/src/img/common/add.svg
  Dnn.AdminExperience/ClientSide/Roles.Web/src/img/common/arrow_down.svg
  Dnn.AdminExperience/ClientSide/Roles.Web/src/img/common/arrow_left.svg
  Dnn.AdminExperience/ClientSide/Roles.Web/src/img/common/arrow_right.svg
  Dnn.AdminExperience/ClientSide/Roles.Web/src/img/common/calendar_end.svg
  Dnn.AdminExperience/ClientSide/Roles.Web/src/img/common/calendar_start.svg
  Dnn.AdminExperience/ClientSide/Roles.Web/src/img/common/edit.svg
  Dnn.AdminExperience/ClientSide/Roles.Web/src/img/common/lock_closed.svg
  Dnn.AdminExperience/ClientSide/Roles.Web/src/img/common/search.svg
  Dnn.AdminExperience/ClientSide/Roles.Web/src/img/common/trash.svg
  Dnn.AdminExperience/ClientSide/Roles.Web/src/img/common/users.svg
  Dnn.AdminExperience/ClientSide/Servers.Web/src/actions/serversTab.js
  Dnn.AdminExperience/ClientSide/Servers.Web/src/components/Body/Body.jsx
  Dnn.AdminExperience/ClientSide/Servers.Web/src/components/Tabs/Servers/ServerList.jsx
  Dnn.AdminExperience/ClientSide/Servers.Web/src/components/Tabs/Servers/ServerRow/index.jsx
  Dnn.AdminExperience/ClientSide/Servers.Web/src/components/Tabs/Servers/ServerRow/style.less
  Dnn.AdminExperience/ClientSide/Servers.Web/src/components/Tabs/Servers/Servers/index.jsx
  Dnn.AdminExperience/ClientSide/Servers.Web/src/components/Tabs/Servers/Servers/style.less
  Dnn.AdminExperience/ClientSide/Servers.Web/src/components/Tabs/Servers/TextEdit.jsx
  Dnn.AdminExperience/ClientSide/Servers.Web/src/constants/actionTypes/index.js
  Dnn.AdminExperience/ClientSide/Servers.Web/src/constants/actionTypes/serversTab.js
  Dnn.AdminExperience/ClientSide/Servers.Web/src/reducers/rootReducer.js
  Dnn.AdminExperience/ClientSide/Servers.Web/src/reducers/serversTabReducer.js
  Dnn.AdminExperience/ClientSide/Servers.Web/src/services/serversTabService.js
  Dnn.AdminExperience/ClientSide/Servers.Web/src/utils.js
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/src/components/Row.jsx
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/src/components/common/IconButton/index.jsx
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/src/components/common/IconButton/style.less
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Dnn.PersonaBar.Extensions.csproj
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/DTO/DeleteServerDTO.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/DTO/EditServerUrlDTO.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/DTO/WebServer.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/SystemInfoServersController.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Servers/App_LocalResources/Servers.resx
Labels: Area: AE > PersonaBar Ext > Servers.Web, Type: Feature

#4422 Use pipeline artifacts instead of build artifacts
  azure-pipelines.yml
Labels: Type: Build/Release

#4430 Run unit tests in parallel
  Build/Cake/unit-tests.cs
  azure-pipelines.yml
Labels: Type: Build/Release

#4429 Enable more tests
  Build/Cake/unit-tests.cs
Labels: Type: Build/Release

#4435 DNN-46668 Unable to upload files when there's an unexpected line brea…
  DNN Platform/Library/Common/Utilities/EscapedString.cs
  DNN Platform/Library/Common/Utilities/FileExtensionWhitelist.cs
  DNN Platform/Tests/DotNetNuke.Tests.Core/EscapedStringTest.cs
Labels: Type: Bug

#4367 Add support for schema script in the script installer
  DNN Platform/Library/Services/Installer/Installers/ScriptInstaller.cs
  DNN Platform/Library/Services/Installer/Util.cs
  DNN Platform/Website/App_GlobalResources/SharedResources.resx
Labels: Type: Enhancement

#4431 removed languages not provided in dnnpages plugin
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/js/ckeditor/4.15.1/plugins/dnnpages/lang/fr.js
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/js/ckeditor/4.15.1/plugins/dnnpages/lang/nl.js
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/js/ckeditor/4.15.1/plugins/dnnpages/plugin.js
Labels: Area: Platform > Providers, Type: Bug

#4443 Issue-4442 - Azure Storage connector uses an outdated logo
  DNN Platform/Connectors/Azure/Images/Azure.png
Labels: Type: Enhancement

#4440 Use parameters instead of variables in pipeline
  azure-pipelines.yml
Labels: Type: Build/Release
