Repository dnnsoftware/Dnn.Platform, pull requests merged in 2021-07, with the labels that each got.

#4731 Enhanced styling for server summary in persona bar
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
Labels: Noteworthy, Type: Enhancement

#4730 Added support for absolute and relative URLs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Pages/PagesControllerImpl.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Pages/App_LocalResources/Pages.resx
Labels: Type: Enhancement

#4734 Fix for #4733: Profile image for anonymous user is not displayed.
  DNN Platform/Library/Services/GeneratedImage/ImageHandlerInternal.cs
Labels: Type: Enhancement

#4743 Fix some conflicts with ASP.NET dependencies
  Build/Tasks/packaging.json
  DNN Platform/Components/Microsoft.AspNetMvc/Microsoft.AspNetMvc.dnn
  DNN Platform/Components/Microsoft.AspNetWebPages/Microsoft.AspNetWebPages.dnn
  DNN Platform/Website/development.config
  DNN Platform/Website/release.config
Labels: Type: Build/Release

#4745 Resolve issues with hover and locked styles for new PersonaBar icons
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
Labels: Type: Bug

#4746 Updated develop with latest changes from 9.10.0 RC
  Build/Tasks/packaging.json
  DNN Platform/Components/Microsoft.AspNetMvc/Microsoft.AspNetMvc.dnn
  DNN Platform/Components/Microsoft.AspNetWebPages/Microsoft.AspNetWebPages.dnn
  DNN Platform/Website/development.config
  DNN Platform/Website/release.config
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
Labels: Type: Build/Release

#4749 Make binding redirect XML Merge case sensitive
  DNN Platform/Website/Install/Config/BindingRedirect.config
  DNN Platform/Website/Install/Config/RemoveBindingRedirect.config
Labels: Type: Bug

#4752 Merging regression fixes from v9.10.0 into develop
  DNN Platform/Website/Install/Config/BindingRedirect.config
  DNN Platform/Website/Install/Config/RemoveBindingRedirect.config
Labels: Type: Build/Release

#4763 Ensure dnn.js is requested for cookie consent
  DNN Platform/Website/Default.aspx.cs
Labels: Type: Bug
