Repository dnnsoftware/Dnn.Platform, pull requests merged in 2021-02, with the labels that each got.

#4433 Upgrade Cake to 1.0.0-RC3
  Build/Build.csproj
  Build/Cake/unit-tests.cs
  Build/Program.cs
  DNN Platform/Tests/DNN.Integration.Test.Framework/DNN.Integration.Test.Framework.csproj
  DNN Platform/Tests/DNN.Integration.Test.Framework/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.AspNetCCP/DotNetNuke.Tests.AspNetCCP.csproj
  DNN Platform/Tests/DotNetNuke.Tests.AspNetCCP/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Authentication/DotNetNuke.Tests.Authentication.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Authentication/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Content/DotNetNuke.Tests.Content.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Content/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Core/DotNetNuke.Tests.Core.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Core/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Data/DotNetNuke.Tests.Data.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Data/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Integration/DotNetNuke.Tests.Integration.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Integration/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.UI/DotNetNuke.Tests.UI.csproj
  DNN Platform/Tests/DotNetNuke.Tests.UI/app.config
  DNN Platform/Tests/DotNetNuke.Tests.UI/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Utilities/DotNetNuke.Tests.Utilities.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Utilities/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Web.Mvc/DotNetNuke.Tests.Web.Mvc.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Web.Mvc/app.config
  DNN Platform/Tests/DotNetNuke.Tests.Web.Mvc/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Web/DotNetNuke.Tests.Web.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Web/packages.config
  build.cake
  build.config
  tools/packages.config
Labels: Type: Build/Release

#4441 sitemappriority for new page set to 0.5
  Dnn.AdminExperience/ClientSide/Pages.Web/src/services/pageService.js
Labels: Type: Bug

#4156 Migrate to MailKit from System.Net.Mail
  DNN Platform/Library/DotNetNuke.Library.csproj
  DNN Platform/Library/Services/Mail/CoreMailProvider.cs
  DNN Platform/Library/Services/Mail/MailKitMailProvider.cs
  DNN Platform/Library/Services/Mail/MailProvider.cs
  DNN Platform/Library/packages.config
  DNN Platform/Tests/App.config
  DNN Platform/Website/Install/Config/09.09.00.config
  DNN Platform/Website/Licenses/MailKit (MIT).txt.resources
  DNN Platform/Website/Licenses/MimeKit (MIT).txt.resources
  DNN Platform/Website/Licenses/Portable.BouncyCastle (MIT).txt.resources
  DNN Platform/Website/development.config
  DNN Platform/Website/release.config
Labels: Noteworthy, Type: Feature

#4450 Added Support for Deterministic Builds
  DNN Platform/Admin Modules/Dnn.Modules.Console/Dnn.Modules.Console.csproj
  DNN Platform/Connectors/Azure/Dnn.AzureConnector.csproj
  DNN Platform/Connectors/GoogleAnalytics/Dnn.GoogleAnalyticsConnector.csproj
  DNN Platform/Connectors/GoogleTagManager/Dnn.GoogleTagManagerConnector.csproj
  DNN Platform/Controls/CountryListBox/CountryListBox.csproj
  DNN Platform/Dnn.AuthServices.Jwt/Dnn.AuthServices.Jwt.csproj
  DNN Platform/DotNetNuke.Abstractions/DotNetNuke.Abstractions.csproj
  DNN Platform/DotNetNuke.DependencyInjection/DotNetNuke.DependencyInjection.csproj
  DNN Platform/DotNetNuke.Instrumentation/DotNetNuke.Instrumentation.csproj
  DNN Platform/DotNetNuke.Log4net/DotNetNuke.Log4Net.csproj
  DNN Platform/DotNetNuke.ModulePipeline/DotNetNuke.ModulePipeline.csproj
  DNN Platform/DotNetNuke.Web.Client/DotNetNuke.Web.Client.csproj
  DNN Platform/DotNetNuke.Web.Deprecated/DotNetNuke.Web.Deprecated.csproj
  DNN Platform/DotNetNuke.Web.Mvc/DotNetNuke.Web.Mvc.csproj
  DNN Platform/DotNetNuke.Web.Razor/DotNetNuke.Web.Razor.csproj
  DNN Platform/DotNetNuke.Web/DotNetNuke.Web.csproj
  DNN Platform/DotNetNuke.WebUtility/DotNetNuke.WebUtility.vbproj
  DNN Platform/DotNetNuke.Website.Deprecated/DotNetNuke.Website.Deprecated.csproj
  DNN Platform/HttpModules/DotNetNuke.HttpModules.csproj
  DNN Platform/Library/DotNetNuke.Library.csproj
  DNN Platform/Modules/CoreMessaging/DotNetNuke.Modules.CoreMessaging.csproj
  DNN Platform/Modules/DDRMenu/DotNetNuke.Modules.DDRMenu.csproj
  DNN Platform/Modules/DigitalAssets/DotNetNuke.Modules.DigitalAssets.csproj
  DNN Platform/Modules/DnnExportImport/DnnExportImport.csproj
  DNN Platform/Modules/DnnExportImportLibrary/DnnExportImportLibrary.csproj
  DNN Platform/Modules/Groups/DotNetNuke.Modules.Groups.csproj
  DNN Platform/Modules/HTML/DotNetNuke.Modules.Html.csproj
  DNN Platform/Modules/HtmlEditorManager/DotNetNuke.Modules.HtmlEditorManager.csproj
  DNN Platform/Modules/Journal/DotNetNuke.Modules.Journal.csproj
  DNN Platform/Modules/MemberDirectory/DotNetNuke.Modules.MemberDirectory.csproj
  DNN Platform/Modules/RazorHost/DotNetNuke.Modules.RazorHost.csproj
  DNN Platform/Modules/ResourceManager/Dnn.Modules.ResourceManager.csproj
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Facebook/DotNetNuke.Authentication.Facebook.csproj
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Google/DotNetNuke.Authentication.Google.csproj
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.LiveConnect/DotNetNuke.Authentication.LiveConnect.csproj
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Twitter/DotNetNuke.Authentication.Twitter.csproj
  DNN Platform/Providers/CachingProviders/DotNetNuke.Providers.Caching.SimpleWebFarmCachingProvider/DotNetNuke.Providers.Caching.SimpleWebFarmCachingProvider.csproj
  DNN Platform/Providers/ClientCapabilityProviders/Provider.AspNetCCP/DotNetNuke.Providers.AspNetCCP.csproj
  DNN Platform/Providers/FolderProviders/DotNetNuke.Providers.FolderProviders.csproj
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/DNNConnect.CKEditorProvider.csproj
  DNN Platform/Syndication/DotNetNuke.Syndication.csproj
  DNN Platform/Website/DotNetNuke.Website.csproj
Labels: Type: Maintenance

#4449 Web.config Cleanup
  DNN Platform/DotNetNuke.Web.Client/ClientResourceManager.cs
  DNN Platform/Providers/CachingProviders/DotNetNuke.Providers.Caching.SimpleWebFarmCachingProvider/SimpleWebFarmCachingProvider.dnn
  DNN Platform/Tests/App.config
  DNN Platform/Website/Install/Config/09.09.00.config
  DNN Platform/Website/development.config
  DNN Platform/Website/release.config
Labels: Type: Maintenance

#4444 Feature/2334 setting for minimum username length
  DNN Platform/Library/Common/Globals.cs
  DNN Platform/Library/Entities/Users/UserController.cs
  DNN Platform/Website/DesktopModules/Admin/Security/App_LocalResources/SharedResources.resx
  Dnn.AdminExperience/ClientSide/Security.Web/src/components/registrationSettings/index.jsx
  Dnn.AdminExperience/ClientSide/Users.Web/src/_exportables/src/components/CreateUserBox/index.jsx
  Dnn.AdminExperience/ClientSide/Users.Web/src/_exportables/src/components/UserTable/UserSettings/index.jsx
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Users/UsersController.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Users/UsersMenuController.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/DTO/UpdateRegistrationSettingsRequest.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/SecurityController.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Security/App_LocalResources/Security.resx
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Users/App_LocalResources/Users.resx
Labels: Area: AE > PersonaBar Ext > Users.Web, Type: Enhancement

#4460 Improve build documentation
  .github/BUILD.md
Labels: Type: Documentation

#4459 Migrate from moment to dayjs for Sites.Web
  Dnn.AdminExperience/ClientSide/Sites.Web/package.json
  Dnn.AdminExperience/ClientSide/Sites.Web/src/_exportables/package.json
  Dnn.AdminExperience/ClientSide/Sites.Web/src/_exportables/src/Components/ListView/index.jsx
  Dnn.AdminExperience/ClientSide/Sites.Web/src/containers/Root.prod.js
Labels: Type: Enhancement

#4461 Remove moment package from SiteImportExport.Web
  Dnn.AdminExperience/ClientSide/SiteImportExport.Web/package.json
Labels: Type: Enhancement

#4462 Remove moment package from Roles.Web
  Dnn.AdminExperience/ClientSide/Roles.Web/package.json
Labels: Type: Enhancement

#4464 Remove moment package from AdminLogs.Web
  Dnn.AdminExperience/ClientSide/AdminLogs.Web/package.json
Labels: Type: Enhancement

#4465 Remove moment package from Prompt.Web
  Dnn.AdminExperience/ClientSide/Prompt.Web/package.json
Labels: Type: Enhancement

#4457 Fixed an issue that prevented Google Tag Manager to create scripts and delete connection
  DNN Platform/Connectors/GoogleAnalytics/GoogleAnalyticsConnector.cs
  DNN Platform/Connectors/GoogleTagManager/GoogleTagManagerConnector.cs
  DNN Platform/Connectors/GoogleTagManager/Scripts/connector.js
  DNN Platform/Library/Services/Analytics/Config/AnalyticsConfiguration.cs
Labels: Type: Bug

#4466 Migrate moment to dayjs for Dnn.React.Common
  Dnn.AdminExperience/ClientSide/Dnn.React.Common/.storybook/utils.js
  Dnn.AdminExperience/ClientSide/Dnn.React.Common/WebpackExternals/index.js
  Dnn.AdminExperience/ClientSide/Dnn.React.Common/package.json
  Dnn.AdminExperience/ClientSide/Dnn.React.Common/src/DatePicker/index.jsx
Labels: Type: Enhancement

#4456 MailKit missing BouncyCastle.Crypto
  DNN Platform/Library/DotNetNuke.Library.csproj
  DNN Platform/Library/Library.build
  DNN Platform/Library/packages.config
Labels: Type: Bug

#4463 Migrate moment to dayjs for Pages.Web
  Dnn.AdminExperience/ClientSide/Pages.Web/package.json
  Dnn.AdminExperience/ClientSide/Pages.Web/src/utils.js
Labels: Type: Enhancement

#4467 Deprecates dependencies in common bundle
  Dnn.AdminExperience/ClientSide/Dnn.React.Common/WebpackExternals/index.js
Labels: Type: Maintenance

#4455 Add Logging to the Dependency Injection SafeGetTypes function
  Build/Tools/NuGet/DotNetNuke.DependencyInjection.nuspec
  DNN Platform/DotNetNuke.DependencyInjection/DotNetNuke.DependencyInjection.csproj
  DNN Platform/DotNetNuke.DependencyInjection/Extensions/TypeExtensions.cs
  DNN Platform/DotNetNuke.Instrumentation/Properties/AssemblyInfo.cs
  DNN Platform/DotNetNuke.Web.Mvc/Extensions/StartupExtensions.cs
  DNN Platform/DotNetNuke.Web/Api/Extensions/StartupExtensions.cs
  DNN Platform/DotNetNuke.Web/DependencyInjectionInitialize.cs
Labels: Area: Platform > DotNetNuke.DependencyInjection, Type: Enhancement

#4473 Add BCC and CC before sending the email
  DNN Platform/Library/Services/Mail/CoreMailProvider.cs
  DNN Platform/Library/Services/Mail/MailKitMailProvider.cs
Labels: Type: Bug

#4470 Upgrade to stable version of Cake
  Build/Build.csproj
Labels: Type: Build/Release

#4477 Update bug-report.md
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: Type: Documentation

#4479 Automatically handle TLS negotiation for MailKit
  DNN Platform/Library/Services/Mail/MailKitMailProvider.cs
Labels: Type: Bug

#4490 Remove duplicate references to Yarn.MsBuild
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Dnn.PersonaBar.Extensions.csproj
Labels: Type: Build/Release

#4492 Fix PersonaBar loading when within an iframe
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/scripts/config.js
Labels: Type: Enhancement

#4486 Address potential email parsing error
  DNN Platform/Library/Services/Mail/MailKitMailProvider.cs
Labels: Type: Bug

#4495 Remove references to Module Creator
  DNN Platform/Website/Providers/DataProviders/SqlDataProvider/DotNetNuke.Data.SqlDataProvider
Labels: Type: Bug

#4493 Use latest Yarn 1.x
  Build/BuildScripts/AEModule.build
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/packages.config
  yarn.lock
Labels: Type: Build/Release

#4494 Adjust Yarn configuration for CI
  Build/BuildScripts/AEModule.build
  azure-pipelines.yml
Labels: Type: Build/Release

#4503 Use ReplyTo Address in MailProvider implementations
  DNN Platform/Library/Services/Mail/CoreMailProvider.cs
  DNN Platform/Library/Services/Mail/MailKitMailProvider.cs
Labels: Area: Platform > Library, Type: Bug

#4509 Resolve issue with dayjs relativeTime plugin and locale
  Dnn.AdminExperience/ClientSide/Sites.Web/src/_exportables/package.json
  Dnn.AdminExperience/ClientSide/Sites.Web/src/_exportables/src/Components/ListView/index.jsx
  yarn.lock
Labels: Type: Bug

#4516 Resolved localized date formats
  Dnn.AdminExperience/ClientSide/Users.Web/src/_exportables/src/helpers.js
Labels: Type: Bug

#4517 Resolved localized date formats
  Dnn.AdminExperience/ClientSide/Servers.Web/src/components/Tabs/LogFileRow/index.jsx
Labels: Type: Bug

#4510 Auto-generates packages checksums
  Build/Cake/build.cs
  Build/Cake/ci.cs
  Build/Cake/packaging.cs
  Build/Cake/version.cs
  DNN_Platform.sln
Labels: Type: Build/Release

#4518 Resolved localized date formats
  Dnn.AdminExperience/ClientSide/Pages.Web/src/utils.js
Labels: Type: Bug

#4500 Azure page css
  DNN Platform/DotNetNuke.Web.Client/ClientResourceManager.cs
  DNN Platform/Library/Services/FileSystem/FileContentTypeManager.cs
  DNN Platform/Website/Default.aspx.cs
  DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.09.01.SqlDataProvider
Labels: Type: Enhancement

#4519 Resolved localized date formats
  Dnn.AdminExperience/ClientSide/Dnn.React.Common/.storybook/utils.js
Labels: Type: Bug

#4528 Updates bug report as per 9.9.0 release
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: Type: Documentation

#4527 Make sure the content is decoded before being passed to tokenization providers.
  DNN Platform/Modules/HTML/Components/HtmlTextController.cs
Labels: Type: Bug

#4505 Remove extra spaces from UserAndLogin Theme Object fixes #4504
  DNN Platform/Website/admin/Skins/UserAndLogin.ascx
Labels: Type: Bug

#4530 Adjust .editorconfig
  .editorconfig
  DNN Platform/Tests/.editorconfig
  DNN_Platform.sln
  Dnn.AdminExperience/Tests/.editorconfig
Labels: Type: Build/Release, Type: Enhancement, Type: Maintenance
