Repository dnnsoftware/Dnn.Platform, pull requests merged in 2022-02, with the labels that each got.

#5007 Use windows-2019 image for CI build
  azure-pipelines.yml
Labels: Type: Build/Release

#5008 Rebases release/9.11.0 from develop branch
  azure-pipelines.yml
Labels: Type: Build/Release

#5006 Add JsonIgnore Attribute
  DNN Platform/Library/Entities/BaseEntityInfo.cs
  DNN Platform/Library/Entities/Content/ContentItem.cs
  DNN Platform/Library/Entities/Content/Taxonomy/Term.cs
  DNN Platform/Library/Entities/Modules/ModuleInfo.cs
  DNN Platform/Library/Entities/Modules/PortalDesktopModuleInfo.cs
  DNN Platform/Library/Entities/Portals/PortalInfo.cs
  DNN Platform/Library/Entities/Profile/ProfilePropertyDefinition.cs
  DNN Platform/Library/Entities/Tabs/TabInfo.cs
  DNN Platform/Library/Entities/Users/Profile/UserProfile.cs
  DNN Platform/Library/Entities/Users/Social/Relationship.cs
  DNN Platform/Library/Entities/Users/Social/RelationshipType.cs
  DNN Platform/Library/Entities/Users/Social/UserRelationship.cs
  DNN Platform/Library/Entities/Users/Social/UserRelationshipPreference.cs
  DNN Platform/Library/Security/Permissions/FolderPermissionInfo.cs
  DNN Platform/Library/Security/Permissions/ModulePermissionInfo.cs
  DNN Platform/Library/Security/Permissions/PermissionInfo.cs
  DNN Platform/Library/Security/Permissions/TabPermissionInfo.cs
  DNN Platform/Library/Security/Roles/RoleInfo.cs
  DNN Platform/Library/Services/Exceptions/BasePortalException.cs
  DNN Platform/Library/Services/FileSystem/FileInfo.cs
  DNN Platform/Library/Services/FileSystem/FolderInfo.cs
  DNN Platform/Library/Services/Installer/Packages/PackageInfo.cs
  DNN Platform/Library/Services/Journal/JournalItem.cs
  DNN Platform/Library/Services/Mobile/PreviewProfile.cs
  DNN Platform/Library/Services/Mobile/Redirection.cs
  DNN Platform/Library/Services/Social/Messaging/Message.cs
  DNN Platform/Library/Services/Social/Messaging/MessageAttachment.cs
  DNN Platform/Library/Services/Social/Messaging/MessageRecipient.cs
  DNN Platform/Library/Services/Social/Notifications/Notification.cs
  DNN Platform/Library/Services/Social/Notifications/NotificationType.cs
  DNN Platform/Library/Services/Social/Notifications/NotificationTypeAction.cs
  DNN Platform/Library/UI/Skins/SkinPackageInfo.cs
  Dnn.AdminExperience/Library/Dnn.PersonaBar.Library/Model/MenuPermissionInfo.cs
  Dnn.AdminExperience/Library/Dnn.PersonaBar.Library/Model/PermissionInfo.cs
Labels: Type: Enhancement

#5010 Upgrade Cake to 2.x
  Build/Build.csproj
  Build/Context.cs
  Build/Program.cs
  Build/Tasks/Build.cs
  Build/Tasks/BuildAll.cs
  Build/Tasks/BuildServerSetVersion.cs
  Build/Tasks/BuildToTempFolder.cs
  Build/Tasks/BuildWithDatabase.cs
  Build/Tasks/CopyWebsite.cs
  Build/Tasks/CreateDeploy.cs
  Build/Tasks/CreateInstall.cs
  Build/Tasks/CreateNugetPackages.cs
  Build/Tasks/CreateSymbols.cs
  Build/Tasks/CreateUpgrade.cs
  Build/Tasks/Default.cs
  Build/Tasks/GeneratePackagesChecksums.cs
  Build/Tasks/GenerateSecurityAnalyzerChecksums.cs
  Build/Tasks/GenerateSqlDataProvider.cs
  Build/Tasks/OtherPackages.cs
  Build/Tasks/PreparePackaging.cs
  Build/Tasks/ResetDevSite.cs
  Build/Tasks/RunUnitTests.cs
  Build/Tasks/SetPackageVersions.cs
  Build/Tasks/UpdateDnnManifests.cs
  azure-pipelines.yml
Labels: Type: Build/Release

#5001 Purge expired auth cookies
  DNN Platform/Library/DotNetNuke.Library.csproj
  DNN Platform/Library/Security/Cookies/PurgeAuthCookiesTask.cs
  DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.11.00.SqlDataProvider
Labels: Type: Enhancement, Area: Platform > Library

#5004 Setup the localization for partial MVC view requests.
  DNN Platform/DotNetNuke.Web.Mvc/DnnMvcHandler.cs
Labels: Type: Bug

#5016 Report build errors as errors to Azure DevOps
  Build/Tasks/Build.cs
Labels: Type: Build/Release

#5020 Fixed an issue where WebFormsMvp initial version mismatched with the config
  Build/Tasks/packaging.json
  DNN Platform/Website/Providers/DataProviders/SqlDataProvider/DotNetNuke.Data.SqlDataProvider
  DNN Platform/Website/release.config
Labels: Type: Bug

#5023 Update GTM to follow Google best practices
  DNN Platform/Connectors/GoogleTagManager/GoogleTagManager.config
Labels: Type: Bug

#5019 Corrected external repositories in build.md
  .github/BUILD.md
Labels: Type: Documentation

#5028 Fix versions of dependencies in Nuget spec files
  Build/Tools/NuGet/DotNetNuke.Web.Mvc.nuspec
  Build/Tools/NuGet/DotNetNuke.WebApi.nuspec
Labels: Type: Bug, Area: Platform > DotNetNuke.Web.Mvc, Priority: High
