Repository dnnsoftware/Dnn.Platform, pull requests merged in 2022-09, with the labels that each got.

#5249 Use JSON.parse over eval where appropriate
  DNN Platform/Controls/SolpartMenu/spmenu.js
  DNN Platform/DotNetNuke.WebUtility/js/dnn.js
  DNN Platform/Modules/CoreMessaging/Scripts/CoreMessaging.js
  DNN Platform/Modules/DDRMenu/DNNMenu/DNNMenu.min.js
  DNN Platform/Modules/DDRMenu/js/DDRMenu.js
  DNN Platform/Website/Resources/Shared/components/ComposeMessage/ComposeMessage.js
  DNN Platform/Website/Resources/Shared/components/CountriesRegions/dnn.CountriesRegions.js
  DNN Platform/Website/Resources/Shared/components/ProfileAutoComplete/dnn.ProfileAutoComplete.js
  DNN Platform/Website/Resources/Shared/scripts/dnn.jquery.js
  DNN Platform/Website/Resources/Shared/scripts/jquery.history.js
  DNN Platform/Website/js/Debug/dnn.controls.js
  DNN Platform/Website/js/Debug/dnn.js
  DNN Platform/Website/js/dnn.controls.js
  DNN Platform/Website/js/dnn.js
  Dnn.AdminExperience/ClientSide/Themes.Web/src/actions/theme.js
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.SqlConsole/scripts/SqlConsole.js
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/scripts/main.js
Labels: Type: Enhancement

#5252 Ensure Resource Manager script files are included in package
  DNN Platform/Modules/ResourceManager/Module.build
Labels: Type: Bug

#5264 Fixed an issue that prevent using resource-manager with CDF
  DNN Platform/Library/UI/Modules/Html5/RequestPropertyAccess.cs
  DNN Platform/Modules/ResourceManager/View.html
Labels: Type: Bug

#5267 Added support for RelativeAppPath in Request token
  DNN Platform/Library/UI/Modules/Html5/RequestPropertyAccess.cs
  DNN Platform/Modules/ResourceManager/View.html
Labels: Type: Bug

#5268 Added support for RelativeAppPath in Request token
  DNN Platform/Library/UI/Modules/Html5/RequestPropertyAccess.cs
  DNN Platform/Modules/ResourceManager/View.html
Labels: Type: Bug

#5269 Fixed an issue where Telerik analysis would fail
  DNN Platform/DotNetNuke.Maintenance/Telerik/TelerikUtils.cs
Labels: Type: Bug

#5273 Remove 9.11 merge workflow
  .github/workflows/open-merged-pr-to-future-9.11.0.yml
Labels: Type: Build/Release

#5277 Fix issue with resources manifest from DNNSecurityHotFix20171
  DNN Platform/DotNetNuke.Maintenance/Telerik/Removal/Steps/IRemoveExtensionStep.cs
  DNN Platform/DotNetNuke.Maintenance/Telerik/Removal/Steps/RemoveExtensionStep.cs
  DNN Platform/DotNetNuke.Maintenance/Telerik/Removal/TelerikUninstaller.cs
  DNN Platform/DotNetNuke.Maintenance/Telerik/Removal/UnInstaller.cs
Labels: Type: Enhancement, Area: Platform > Library

#5279 Fixed an issue where folder provider icons would not show
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-folder-mappings/dnn-rm-folder-mappings.scss
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-folder-mappings/dnn-rm-folder-mappings.tsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/services/ItemsClient.ts
  DNN Platform/Modules/ResourceManager/Services/ItemsController.cs
Labels: Type: Bug

#5282 Fixed an issue where folder provider icons would not show
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-folder-mappings/dnn-rm-folder-mappings.scss
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-folder-mappings/dnn-rm-folder-mappings.tsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/services/ItemsClient.ts
  DNN Platform/Modules/ResourceManager/Services/ItemsController.cs
Labels: Type: Bug

#5281 Fixed an issue that prevent upload when using application folder
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-queued-file/dnn-rm-queued-file.tsx
Labels: Type: Bug

#5283 Merged latest 9.11.0 RC Fixed into develop
  DNN Platform/DotNetNuke.Maintenance/Telerik/Removal/Steps/IRemoveExtensionStep.cs
  DNN Platform/DotNetNuke.Maintenance/Telerik/Removal/Steps/RemoveExtensionStep.cs
  DNN Platform/DotNetNuke.Maintenance/Telerik/Removal/TelerikUninstaller.cs
  DNN Platform/DotNetNuke.Maintenance/Telerik/Removal/UnInstaller.cs
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-queued-file/dnn-rm-queued-file.tsx
Labels: Type: Build/Release

#5286 Fixed an issue where resource manager menus would show under icons
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-actions-bar/dnn-rm-actions-bar.scss
Labels: Type: Bug

#5285 Fixed issue where the uninstall extension shows version 0.0.0
  Dnn.AdminExperience/ClientSide/Extensions.Web/src/components/DeleteExtension/index.jsx
Labels: Type: Bug

#5297 Exclude web.*.config from distribution zips
  Build/Tasks/packaging.json
Labels: Type: Bug, Type: Build/Release, Type: Maintenance

#5296 Add missing databaseOwner and objectQualifier
  DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.11.00.SqlDataProvider
Labels: Type: Bug

#5298 Updated dependencies on dnn-resource-manager
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteSettings.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteSettings.Web/src/main.jsx
  yarn.lock
Labels: Type: Bug

#5299 Updates develop with latest fixes from 9.11.0
  Build/Tasks/packaging.json
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/package.json
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-actions-bar/dnn-rm-actions-bar.scss
  DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.11.00.SqlDataProvider
  Dnn.AdminExperience/ClientSide/SiteSettings.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteSettings.Web/src/main.jsx
  yarn.lock
Labels: Type: Build/Release

#5305 Resolved an issue where the React modules would not load
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-resource-manager/readme.md
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-folder-mappings/readme.md
  yarn.lock
Labels: Type: Bug

#5306 Resolved an issue where the React modules would not load
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-resource-manager/readme.md
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-folder-mappings/readme.md
  yarn.lock
Labels: Type: Bug

#5307 Remove react-test-utils
  Dnn.AdminExperience/ClientSide/Dnn.React.Common/package.json
  yarn.lock
Labels: Type: Build/Release

#5313 Pass TabId instead of PortalId
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/MenuControllers/PagesMenuController.cs
Labels: Type: Bug

#5310 Smooth out potential issues using ResetDevSite
  Build/Tasks/CopyWebConfigToDevSite.cs
  Build/Tasks/ResetDatabase.cs
Labels: Type: Build/Release

#5314 Include SharpZipLib package
  Build/Tasks/OtherPackages.cs
Labels: Type: Bug, Type: Build/Release

#5317 Allowed creating different nested folder types
  DNN Platform/Modules/ResourceManager/Services/ItemsController.cs
Labels: Type: Enhancement

#5319 Merges latest 9.11.0 fixes into `develop`
  Build/Tasks/OtherPackages.cs
  DNN Platform/Modules/ResourceManager/Services/ItemsController.cs
  DNN Platform/Website/admin/Security/PasswordReset.ascx.cs
  Dnn.AdminExperience/ClientSide/Dnn.React.Common/package.json
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/MenuControllers/PagesMenuController.cs
  yarn.lock
Labels: Type: Build/Release

#5327 Update to Cake.Issues.MsBuild 2.0 Beta 1
  Build/Build.csproj
  Build/Program.cs
  Build/Tasks/Build.cs
Labels: Type: Build/Release
