Repository dnnsoftware/Dnn.Platform, pull requests merged in 2022-11, with the labels that each got.

#5368 Modify Next Button on install wizard
  Dnn.AdminExperience/ClientSide/Extensions.Web/src/components/InstallExtensionModal/index.jsx
Labels: Type: Bug

#5341 5339 Handle upload for image smaller than configured resize dimensions
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Browser/Browser.aspx.cs
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Browser/FileUploader.ashx.cs
Labels: Type: Bug

#5378 Fixed an infinite loop in schedule item.
  DNN Platform/Library/Services/Scheduling/ScheduleItem.cs
Labels: Type: Bug

#5380 Fixed an issue where comments in manifest would make install fail
  DNN Platform/Library/Services/Installer/Installer.cs
Labels: Type: Bug

#5385 Fix casing issue on SelectedItemTemplate property
  DNN Platform/Website/admin/Skins/Language.ascx.cs
Labels: Type: Bug, Priority: High

#5379 Upgrade to lerna 6.x
  package.json
  yarn.lock
Labels: Type: Build/Release

#5390 Resolve properties made incorrectly recursive
  DNN Platform/Website/DesktopModules/Admin/EditExtension/AuthenticationEditor.ascx.cs
  DNN Platform/Website/DesktopModules/Admin/Security/SecurityRoles.ascx.cs
  DNN Platform/Website/admin/Skins/tags.ascx.cs
Labels: Type: Bug

#5382 Fix localizing parent tabs breaking existing localized child tabs
  DNN Platform/Library/Entities/Tabs/TabController.cs
Labels: Type: Bug

#5396 Fix the library debug build to debug folder
  DNN Platform/Library/DotNetNuke.Library.csproj
  DNN Platform/Library/Library.build
Labels: Type: Bug, Type: Build/Release, Type: Maintenance

#5372 Fix issue #5371 to correctly handle Request IP Addresses
  DNN Platform/Library/Services/UserRequest/UserRequestIPAddressController.cs
Labels: Type: Enhancement

#5397 Reorganizing portal templates part 2
  DNN Platform/DotNetNuke.Abstractions/Portals/Templates/IPortalTemplateController.cs
  DNN Platform/DotNetNuke.Abstractions/Portals/Templates/IPortalTemplateInfo.cs
  DNN Platform/DotNetNuke.Abstractions/Portals/Templates/PortalTemplateModuleAction.cs
  DNN Platform/Library/DotNetNuke.Library.csproj
  DNN Platform/Library/Entities/Portals/IPortalController.cs
  DNN Platform/Library/Entities/Portals/PortalController.cs
  DNN Platform/Library/Entities/Portals/Templates/IPortalTemplateIO.cs
  DNN Platform/Library/Entities/Portals/Templates/IPortalTemplateInfo.cs
  DNN Platform/Library/Entities/Portals/Templates/PortalTemplateController.cs
  DNN Platform/Library/Entities/Portals/Templates/PortalTemplateExtensions.cs
  DNN Platform/Library/Entities/Portals/Templates/PortalTemplateIO.cs
  DNN Platform/Library/Entities/Portals/Templates/PortalTemplateImporter.cs
  DNN Platform/Library/Entities/Portals/Templates/PortalTemplateInfo.cs
  DNN Platform/Library/Obsolete/PortalController.cs
  DNN Platform/Library/Obsolete/PortalTemplateIOImpl.cs
  DNN Platform/Library/Services/Upgrade/Upgrade.cs
  DNN Platform/Tests/DNN.Integration.Test.Framework/DNN.Integration.Test.Framework.csproj
  DNN Platform/Tests/DNN.Integration.Test.Framework/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.AspNetCCP/App.config
  DNN Platform/Tests/DotNetNuke.Tests.AspNetCCP/DotNetNuke.Tests.AspNetCCP.csproj
  DNN Platform/Tests/DotNetNuke.Tests.AspNetCCP/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Authentication/DotNetNuke.Tests.Authentication.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Authentication/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Content/DotNetNuke.Tests.Content.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Content/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Core/Controllers/Portal/PortalControllerTests.cs
  DNN Platform/Tests/DotNetNuke.Tests.Core/DotNetNuke.Tests.Core.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Core/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Data/DotNetNuke.Tests.Data.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Data/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Integration/DotNetNuke.Tests.Integration.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Integration/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Modules/DotNetNuke.Tests.Modules.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Modules/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.UI/DotNetNuke.Tests.UI.csproj
  DNN Platform/Tests/DotNetNuke.Tests.UI/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Urls/DotNetNuke.Tests.Urls.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Urls/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Utilities/DotNetNuke.Tests.Utilities.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Utilities/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Web.Mvc/DotNetNuke.Tests.Web.Mvc.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Web.Mvc/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Web/DotNetNuke.Tests.Web.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Web/packages.config
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Sites/SitesController.cs
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.ConfigConsole.Tests/Dnn.PersonaBar.ConfigConsole.Tests.csproj
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.ConfigConsole.Tests/packages.config
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.Pages.Tests/Dnn.PersonaBar.Pages.Tests.csproj
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.Pages.Tests/packages.config
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.Security.Tests/Dnn.PersonaBar.Security.Tests.csproj
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.Security.Tests/packages.config
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.Users.Tests/Dnn.PersonaBar.Users.Tests.csproj
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.Users.Tests/packages.config
Labels: Area: Platform > Library, Type: Maintenance

#5386 Fix loading of progress file in content localizer
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/SiteSettings/LanguagesControllerTasks.cs
Labels: Type: Bug, Area: Localization

#5402 Fix issues that can cause duplicate rows to show in page->advanced->SEO
  Dnn.AdminExperience/ClientSide/Pages.Web/src/components/Seo/PageUrls/Table.jsx
Labels: Type: Bug

#5411 Added support for a Notes field in IP Filters
  DNN Platform/Library/Data/DataProvider.cs
  DNN Platform/Library/Entities/IPFilter/IIPFilterController.cs
  DNN Platform/Library/Entities/IPFilter/IPFilterController.cs
  DNN Platform/Library/Entities/IPFilter/IPFilterInfo.cs
  Dnn.AdminExperience/ClientSide/Security.Web/src/components/ipFilters/index.jsx
  Dnn.AdminExperience/ClientSide/Security.Web/src/components/ipFilters/ipFilterEditor/index.jsx
  Dnn.AdminExperience/ClientSide/Security.Web/src/components/ipFilters/ipFilterRow/index.jsx
  Dnn.AdminExperience/ClientSide/Security.Web/src/components/ipFilters/ipFilterRow/style.less
  Dnn.AdminExperience/ClientSide/Security.Web/src/components/ipFilters/style.less
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Dnn.PersonaBar.Extensions.csproj
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/DTO/UpdateIpFilterRequest.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/SecurityController.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/SqlDataProvider/09.11.01.SqlDataProvider
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Security/App_LocalResources/Security.resx
Labels: Type: Enhancement

#5407 5406 Fix uploading documents through link popup
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Browser/Browser.aspx.cs
Labels: Type: Bug

#5413 Correct GetUsersBasicSearch docs
  DNN Platform/Library/Entities/Users/IUserController.cs
Labels: Type: Documentation

#5412 Fix renamed public/protected properties and fields
  DNN Platform/Library/Security/Permissions/Controls/FolderPermissionsGrid.cs
  DNN Platform/Library/Services/Authentication/OAuth/OAuthSettingsBase.cs
  DNN Platform/Library/Services/Journal/JournalTypeInfo.cs
  DNN Platform/Library/Services/OutputCache/Providers/MemoryProvider.cs
  DNN Platform/Library/UI/Skins/Controls/LanguageTokenReplace.cs
  DNN Platform/Library/UI/Skins/SkinControl.cs
  DNN Platform/Library/UI/Skins/SkinThumbNailControl.cs
  DNN Platform/Library/UI/UserControls/DualListControl.cs
  DNN Platform/Library/UI/UserControls/Help.cs
  DNN Platform/Library/UI/UserControls/HelpButtonControl.cs
  DNN Platform/Library/UI/UserControls/SectionHeadControl.cs
  DNN Platform/Library/UI/UserControls/TextEditor.cs
  DNN Platform/Library/UI/UserControls/URLControl.cs
  DNN Platform/Library/UI/UserControls/URLTrackingControl.cs
  DNN Platform/Library/UI/UserControls/User.cs
  DNN Platform/Library/UI/WebControls/PagingControl.cs
Labels: Type: Bug, Type: Maintenance

#5404 Fix 'Add Missing Languages' when parent page only has some languages enabled
  DNN Platform/Library/Entities/Tabs/ITabController.cs
  DNN Platform/Library/Entities/Tabs/TabController.cs
  Dnn.AdminExperience/ClientSide/Pages.Web/src/components/PageLocalization/PageLocalization.jsx
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/PagesController.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Pages/App_LocalResources/Pages.resx
Labels: Type: Bug
