Repository dnnsoftware/Dnn.Platform, pull requests merged in 2022-08, with the labels that each got.

#5223 Disable PR merge for 10.0.0 branch
  .github/workflows/open-merged-pr-to-future.yml
Labels: Type: Build/Release

#5224 Specify latest version for 9.11 merge action
  .github/workflows/open-merged-pr-to-future-9.11.0.yml
Labels: Type: Build/Release

#5229 Create User invalid request has a response which returns 500 #5228
  DNN Platform/Library/DotNetNuke.Library.csproj
  DNN Platform/Library/Entities/Users/Exceptions/InvalidUserRegisterException.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Users/RegisterController.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/UsersController.cs
Labels: Type: Enhancement, Area: AE > Dnn.PersonaBar.Extensions, Area: Platform > Library

#5231 Resolve null reference when data types are missing
  DNN Platform/Library/Entities/Users/Profile/UserProfile.cs
Labels: Type: Bug

#5233 Restrict log viewing to files only
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/ServerSettingsLogsController.cs
Labels: Type: Bug

#5238 Fix wrong file name for jQuery UI
  DNN Platform/JavaScript Libraries/jQueryUI/jQueryUI.dnn
Labels: Type: Bug, Area: Platform > JavaScript Libraries

#5239 Use JSON.parse over eval where appropriate
  DNN Platform/Controls/SolpartMenu/spmenu.js
  DNN Platform/DotNetNuke.Web.Deprecated/UI/WebControls/Resources/TermsSelector.js
  DNN Platform/DotNetNuke.WebUtility/js/dnn.js
  DNN Platform/Modules/CoreMessaging/Scripts/CoreMessaging.js
  DNN Platform/Modules/DDRMenu/DNNMenu/DNNMenu.min.js
  DNN Platform/Modules/DDRMenu/js/DDRMenu.js
  DNN Platform/Modules/DigitalAssets/ClientScripts/dnn.DigitalAssets.js
  DNN Platform/Website/Resources/Shared/components/ComposeMessage/ComposeMessage.js
  DNN Platform/Website/Resources/Shared/components/CountriesRegions/dnn.CountriesRegions.js
  DNN Platform/Website/Resources/Shared/components/ProfileAutoComplete/dnn.ProfileAutoComplete.js
  DNN Platform/Website/Resources/Shared/scripts/dnn.jquery.js
  DNN Platform/Website/Resources/Shared/scripts/jquery.history.js
  DNN Platform/Website/js/Debug/dnn.controls.js
  DNN Platform/Website/js/Debug/dnn.js
  DNN Platform/Website/js/dnn.controls.js
  DNN Platform/Website/js/dnn.js
  Dnn.AdminExperience/ClientSide/Themes.Web/src/actions/theme.js
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.SqlConsole/scripts/SqlConsole.js
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/scripts/main.js
Labels: Type: Maintenance, javascript

#5241 Removes resource manager PB registration
  DNN Platform/Modules/ResourceManager/Components/PersonaBarMenuController.cs
  DNN Platform/Modules/ResourceManager/Dnn.Modules.ResourceManager.csproj
  DNN Platform/Modules/ResourceManager/ResourceManager.dnn
Labels: Type: Enhancement

#5242 Added support for HtmlAttributesAsString in html module views
  DNN Platform/DotNetNuke.Web.Client/ClientResourceManager.cs
  DNN Platform/Library/DotNetNuke.Library.csproj
  DNN Platform/Library/Services/Tokens/PropertyAccess/JavaScriptDto.cs
  DNN Platform/Library/Services/Tokens/PropertyAccess/JavaScriptPropertyAccess.cs
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/package.json
  DNN Platform/Modules/ResourceManager/View.html
  SolutionInfo.cs
Labels: Type: Enhancement

#5244 Improve HTML attribute support in client resource manager
  DNN Platform/DotNetNuke.Web.Client/ClientResourceManager.cs
  DNN Platform/Library/Services/Tokens/PropertyAccess/JavaScriptDto.cs
  DNN Platform/Library/Services/Tokens/PropertyAccess/JavaScriptPropertyAccess.cs
  DNN Platform/Modules/ResourceManager/View.html
Labels: Type: Enhancement
