Repository dnnsoftware/Dnn.Platform, pull requests merged in 2022-07, with the labels that each got.

#5171 Update a couple of test dependencies
  DNN Platform/Tests/App.config
  DNN Platform/Tests/DotNetNuke.Tests.Integration/DotNetNuke.Tests.Integration.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Integration/packages.config
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.ConfigConsole.Tests/Dnn.PersonaBar.ConfigConsole.Tests.csproj
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.ConfigConsole.Tests/app.config
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.ConfigConsole.Tests/packages.config
Labels: Type: Maintenance

#5078 Fix bug - postback issue with the cke editor
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Web/EditorControl.cs
Labels: Type: Bug

#5169 Upgrade NUnit to 3.13.3 and Test Adapter to 4.2.1
  Build/Program.cs
  DNN Platform/Tests/DNN.Integration.Test.Framework/DNN.Integration.Test.Framework.csproj
  DNN Platform/Tests/DNN.Integration.Test.Framework/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.AspNetCCP/DotNetNuke.Tests.AspNetCCP.csproj
  DNN Platform/Tests/DotNetNuke.Tests.AspNetCCP/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Authentication/DotNetNuke.Tests.Authentication.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Authentication/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Content/DotNetNuke.Tests.Content.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Content/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Core/DotNetNuke.Tests.Core.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Core/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Data/DotNetNuke.Tests.Data.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Data/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Integration/DotNetNuke.Tests.Integration.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Integration/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.UI/DotNetNuke.Tests.UI.csproj
  DNN Platform/Tests/DotNetNuke.Tests.UI/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Urls/DotNetNuke.Tests.Urls.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Urls/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Utilities/DotNetNuke.Tests.Utilities.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Utilities/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Web.Mvc/DotNetNuke.Tests.Web.Mvc.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Web.Mvc/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Web/DotNetNuke.Tests.Web.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Web/packages.config
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.ConfigConsole.Tests/Dnn.PersonaBar.ConfigConsole.Tests.csproj
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.ConfigConsole.Tests/packages.config
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.Pages.Tests/Dnn.PersonaBar.Pages.Tests.csproj
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.Pages.Tests/packages.config
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.Security.Tests/Dnn.PersonaBar.Security.Tests.csproj
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.Security.Tests/packages.config
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.Users.Tests/Dnn.PersonaBar.Users.Tests.csproj
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.Users.Tests/packages.config
Labels: Type: Maintenance

#5188 Resolve HTML module bug with invalid HTML
  DNN Platform/Modules/HTML/Components/HtmlTextController.cs
  DNN Platform/Tests/DotNetNuke.Tests.Modules/AssemblyInfo.cs
  DNN Platform/Tests/DotNetNuke.Tests.Modules/DotNetNuke.Tests.Modules.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Modules/Html/HtmlTextControllerTests.cs
  DNN Platform/Tests/DotNetNuke.Tests.Modules/TestSetup.cs
  DNN Platform/Tests/DotNetNuke.Tests.Modules/packages.config
  DNN_Platform.sln
Labels: Type: Bug

#5199 Add unique suffix to artifact name
  azure-pipelines.yml
Labels: Type: Build/Release

#5203 Move OutputCacheAddItem change into correct script
  DNN Platform/Website/DotNetNuke.Website.csproj
  DNN Platform/Website/Providers/DataProviders/09.10.03.SqlDataProvider
  DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.10.03.SqlDataProvider
Labels: Type: Bug

#5207 Revert "Merge pull request #5118 from DanielBolef/top-level-pages"
  DNN Platform/Library/Common/Utilities/DataCache.cs
  DNN Platform/Library/Data/DataProvider.cs
  DNN Platform/Library/DotNetNuke.Library.csproj
  DNN Platform/Library/Entities/Portals/PortalInfo.cs
  DNN Platform/Library/Obsolete/EventLogController.cs
  DNN Platform/Library/Security/Permissions/ComparePortalPermissions.cs
  DNN Platform/Library/Security/Permissions/PermissionProvider.cs
  DNN Platform/Library/Security/Permissions/PortalPermissionCollection.cs
  DNN Platform/Library/Security/Permissions/PortalPermissionController.cs
  DNN Platform/Library/Security/Permissions/PortalPermissionInfo.cs
  DNN Platform/Library/Security/Permissions/TabPermissionInfo.cs
  DNN Platform/Library/Security/PortalSecurity.cs
  DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.11.00.SqlDataProvider
  DNN Platform/Website/Providers/DataProviders/SqlDataProvider/UnInstall.SqlDataProvider
  Dnn.AdminExperience/ClientSide/Pages.Web/src/components/App.jsx
  Dnn.AdminExperience/ClientSide/Pages.Web/src/services/securityService.js
  Dnn.AdminExperience/ClientSide/Pages.Web/src/utils.js
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Pages/PagesControllerImpl.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Pages/Security/SecurityService.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/MenuControllers/PagesMenuController.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/PagesController.cs
Labels: Type: Maintenance

#5193 v9.11.0 Bump react-collapse from 4.0.3 to 5.1.0
  Build/Build.csproj
  Build/BuildScripts/AEModule.build
  Build/Program.cs
  Build/Tasks/unversionedManifests.txt
  DNN Platform/Library/Entities/Urls/AdvancedUrlRewriter.cs
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/package.json
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Web/EditorControl.cs
  DNN Platform/Tests/App.config
  DNN Platform/Tests/DNN.Integration.Test.Framework/DNN.Integration.Test.Framework.csproj
  DNN Platform/Tests/DNN.Integration.Test.Framework/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.AspNetCCP/DotNetNuke.Tests.AspNetCCP.csproj
  DNN Platform/Tests/DotNetNuke.Tests.AspNetCCP/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Authentication/DotNetNuke.Tests.Authentication.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Authentication/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Content/DotNetNuke.Tests.Content.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Content/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Core/DotNetNuke.Tests.Core.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Core/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Data/DotNetNuke.Tests.Data.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Data/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Integration/DotNetNuke.Tests.Integration.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Integration/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.UI/DotNetNuke.Tests.UI.csproj
  DNN Platform/Tests/DotNetNuke.Tests.UI/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Urls/DotNetNuke.Tests.Urls.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Urls/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Utilities/DotNetNuke.Tests.Utilities.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Utilities/PowershellManager.cs
  DNN Platform/Tests/DotNetNuke.Tests.Utilities/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Web.Mvc/DotNetNuke.Tests.Web.Mvc.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Web.Mvc/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Web/DotNetNuke.Tests.Web.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Web/packages.config
  Dnn.AdminExperience/ClientSide/Bundle.Web/package.json
  Dnn.AdminExperience/ClientSide/Dnn.React.Common/package.json
  Dnn.AdminExperience/ClientSide/Servers.Web/src/components/Tabs/SmtpServer.jsx
  Dnn.AdminExperience/ClientSide/Servers.Web/src/components/common/EditBlock.jsx
  Dnn.AdminExperience/ClientSide/Servers.Web/src/components/common/EditPwdBlock.jsx
  Dnn.AdminExperience/ClientSide/Servers.Web/src/components/common/style.less
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/ServerSettingsSmtpAdminController.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/ServerSettingsSmtpHostController.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Servers/App_LocalResources/Servers.resx
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.ConfigConsole.Tests/Dnn.PersonaBar.ConfigConsole.Tests.csproj
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.ConfigConsole.Tests/app.config
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.ConfigConsole.Tests/packages.config
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.Pages.Tests/Dnn.PersonaBar.Pages.Tests.csproj
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.Pages.Tests/packages.config
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.Security.Tests/Dnn.PersonaBar.Security.Tests.csproj
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.Security.Tests/packages.config
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.Users.Tests/Dnn.PersonaBar.Users.Tests.csproj
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.Users.Tests/packages.config
  yarn.lock
Labels: Type: Maintenance, javascript

#5206 Remove unused class
  DNN Platform/DotNetNuke.Web/UI/WebControls/Internal/DnnDropDownCheckBoxes.cs
Labels: Type: Maintenance

#5205 Use Client Resources Manager for CKEditor Provider dialogs
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/App_LocalResources/Browser.aspx.de-DE.resx
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/App_LocalResources/Browser.aspx.pl-PL.resx
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/App_LocalResources/Browser.aspx.resx
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Browser/Browser.aspx
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Browser/Browser.aspx.cs
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Browser/Browser.aspx.designer.cs
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/DNNConnect.CKEditorProvider.csproj
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Options.aspx
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Options.aspx.cs
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Options.aspx.designer.cs
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Provider.build
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Web/EditorControl.cs
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/packages.config
Labels: Type: Enhancement

#5211 Upgrade Lerna from 3.x to 5.3.0
  package.json
  yarn.lock
Labels: Type: Maintenance, javascript
