Repository dnnsoftware/Dnn.Platform, pull requests merged in 2022-12, with the labels that each got.

#5421 Possibly fixed intermittent build issues
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Dnn.PersonaBar.Extensions.csproj
Labels: Type: Build/Release

#5414 Keep track of whether in global assets mode
  DNN Platform/Modules/ResourceManager/Components/SettingsManager.cs
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-queued-file/dnn-rm-queued-file.tsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/services/ItemsClient.ts
Labels: Type: Bug

#5425 Resolve XCOPY error during build
  DNN Platform/DotNetNuke.Abstractions/DotNetNuke.Abstractions.csproj
  DNN Platform/DotNetNuke.DependencyInjection/DotNetNuke.DependencyInjection.csproj
  DNN Platform/DotNetNuke.Maintenance/DotNetNuke.Maintenance.csproj
  DNN Platform/DotNetNuke.ModulePipeline/DotNetNuke.ModulePipeline.csproj
Labels: Type: Build/Release

#5426 Update jQuery to 3.5.1 in editBar
  Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/editBar/scripts/contrib/jquery.js
Labels: Type: Enhancement, Area: AE > Dnn.EditBar.UI

#5369 Modify search placeholder
  Dnn.AdminExperience/ClientSide/Pages.Web/src/components/SearchPage/SearchPageInput.jsx
Labels: Type: Bug

#5432 Resolve CKEditor browser not loading
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Controls/HtmlGenericSelfClosing.cs
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/DNNConnect.CKEditorProvider.csproj
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Options.aspx.cs
Labels: Type: Bug

#5433 Changed build to run all npm builds before backend builds.
  Build/Build.csproj
  Build/BuildScripts/AEModule.build
  Build/Tasks/Build.cs
  Build/Tasks/BuildNpmPackages.cs
  DNN_Platform.sln
Labels: Type: Build/Release

#5416 Update Browser.aspx.cs
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Browser/Browser.aspx.cs
Labels: Type: Bug, Area: Platform > Components

#5292 Fix for #5291: Non-Integer Thumbnail Sizes Break API Calls
  DNN Platform/Library/Services/GeneratedImage/DnnImageHandler.cs
  DNN Platform/Tests/DotNetNuke.Tests.Integration/Tests/Library/ImageHandlerTests.cs
Labels: Type: Bug

#5440 Fix out-of-sync package versions in test projects
  DNN Platform/Tests/DotNetNuke.Tests.Integration/DotNetNuke.Tests.Integration.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Integration/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Modules/DotNetNuke.Tests.Modules.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Modules/packages.config
Labels: Type: Build/Release

#5441 Fix PersonaBar project referencing wrong version of Newtonsoft.Json
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Dnn.PersonaBar.Extensions.csproj
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/app.config
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/packages.config
Labels: Type: Maintenance

#5439 Remove now-unused Yarn.MsBuild package
  Build/Tasks/BuildNpmPackages.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Dnn.PersonaBar.Extensions.csproj
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/packages.config
Labels: Type: Build/Release

#5446 Remove `Settings` from Resource Manager display for users without permission
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-resource-manager/dnn-resource-manager.tsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-folder-list/dnn-rm-folder-list.tsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/services/ItemsClient.ts
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/store/store.ts
  DNN Platform/Modules/ResourceManager/Services/ItemsController.cs
Labels: Type: Bug

#5445 Fixed an issue that prevented sending smtp test emails
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/ServerSettingsSmtpAdminController.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/ServerSettingsSmtpHostController.cs
Labels: Type: Bug

#5409 Added host level setting for browser and upload folders of html editor
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/App_LocalResources/Options.aspx.resx
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Browser/Browser.aspx.cs
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/CKEditorOptions.ascx
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/CKEditorOptions.ascx.cs
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/CKEditorOptions.ascx.designer.cs
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Constants/SettingConstants.cs
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Objects/EditorProviderSettings.cs
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Utilities/SettingsUtil.cs
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Utilities/Utility.cs
Labels: Type: Bug

#5442 Upgrade Cake dependencies
  Build/Build.csproj
  azure-pipelines.yml
  build.config
Labels: Type: Build/Release

#5451 Updated Security Policy
  SECURITY.md
Labels: Priority: Medium, Type: Documentation

#5453 Fix monaco editor not being loaded when switching between css console and sql console
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.SqlConsole/SqlConsole.html
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.SqlConsole/scripts/SqlConsole.js
Labels: Type: Bug
