Repository dnnsoftware/Dnn.Platform, pull requests merged in 2022-10, with the labels that each got.

#5329 Save IsSecure property of Portal Setting
  DNN Platform/Library/Entities/Portals/PortalController.cs
  DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.11.01.SqlDataProvider
Labels: Type: Bug

#5331 Feature/5330 sitemap priorities revert to 1 in non us culture
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/SeoController.cs
Labels: Type: Bug, Area: AE > PersonaBar Ext > SEO.Web

#5328 Fix MonacoEditor not loading for child aliases
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.ConfigConsole/scripts/ConfigConsole.js
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.SqlConsole/scripts/SqlConsole.js
Labels: Type: Bug

#5342 Fixes #5338 CKE upload document with image upload resize dimensions c…
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Browser/Browser.aspx.cs
Labels: Type: Bug

#5343 5325 CKE fix for favicon in portal folder breaks browser
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Browser/Browser.aspx.cs
Labels: Type: Bug

#5351 Fixed an issue where resource manager would not have appropriate root folder
  DNN Platform/DotNetNuke.Web/InternalServices/ItemListServiceController.cs
  DNN Platform/Modules/ResourceManager/App_LocalResources/ResourceManager.resx
  DNN Platform/Modules/ResourceManager/Components/ItemsManager.cs
  DNN Platform/Modules/ResourceManager/Components/SettingsManager.cs
  DNN Platform/Modules/ResourceManager/Module.build
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-resource-manager/dnn-resource-manager.tsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-actions-bar/dnn-rm-actions-bar.tsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-folder-list/dnn-rm-folder-list.scss
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-folder-list/dnn-rm-folder-list.tsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/services/InternalServicesClient.ts
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/services/ItemsClient.ts
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/store/store.ts
  DNN Platform/Modules/ResourceManager/Services/ItemsController.cs
  DNN Platform/Modules/ResourceManager/Services/LocalizationController.cs
  yarn.lock
Labels: Type: Bug

#5352 Allows opening resource manager folders with double-click
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components.d.ts
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-folder-list-item/dnn-rm-folder-list-item.tsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-items-cardview/dnn-rm-items-cardview.tsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-items-cardview/readme.md
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-items-listview/dnn-rm-items-listview.tsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-items-listview/readme.md
Labels: Type: Enhancement

#5355 Fixed an issue where first level folders were auto-expanded.
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-folder-list/dnn-rm-folder-list.tsx
Labels: Type: Enhancement

#5359 Fixed an issue where resource manager modal could not contain long lists
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/package.json
  yarn.lock
Labels: Type: Bug
