Repository dnnsoftware/Dnn.Platform, pull requests merged in 2023-07, with the labels that each got.

#5724 Add JS libraries for jQuery.fileupload, jQuery.hoverIntent, and DNN jQuery Plugins
  Build/Tasks/thirdparty.json
  Build/Tasks/unversionedManifests.txt
  DNN Platform/JavaScript Libraries/DnnPlugins/DnnPlugins.dnn
  DNN Platform/JavaScript Libraries/DnnPlugins/LICENSE.txt
  DNN Platform/JavaScript Libraries/DnnPlugins/dnn.jquery.js
  DNN Platform/JavaScript Libraries/DnnPlugins/releaseNotes.txt
  DNN Platform/JavaScript Libraries/HoverIntent/HoverIntent.dnn
  DNN Platform/JavaScript Libraries/HoverIntent/LICENSE.txt
  DNN Platform/JavaScript Libraries/HoverIntent/jquery.hoverIntent.min.js
  DNN Platform/JavaScript Libraries/HoverIntent/releaseNotes.txt
  DNN Platform/JavaScript Libraries/jQuery.Fileupload/LICENSE.txt
  DNN Platform/JavaScript Libraries/jQuery.Fileupload/jQuery.Fileupload.dnn
  DNN Platform/JavaScript Libraries/jQuery.Fileupload/jquery.fileupload.js
  DNN Platform/JavaScript Libraries/jQuery.Fileupload/releaseNotes.txt
  DNN Platform/JavaScript Libraries/jQuery.iframe-transport/LICENSE.txt
  DNN Platform/JavaScript Libraries/jQuery.iframe-transport/jQuery.iframe-transport.dnn
  DNN Platform/JavaScript Libraries/jQuery.iframe-transport/jquery.iframe-transport.js
  DNN Platform/JavaScript Libraries/jQuery.iframe-transport/releaseNotes.txt
  DNN Platform/Library/Framework/JavaScriptLibraries/JavaScript.cs
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Browser/Browser.comb.css.bundle
  DNN_Platform.sln
Labels: Type: Enhancement

#5713 Bump Newtonsoft.Json from 13.0.2 to 13.0.3
  Build/Build.csproj
  Build/Tools/NuGet/DotNetNuke.WebApi.nuspec
  DNN Platform/Connectors/Azure/Dnn.AzureConnector.csproj
  DNN Platform/Connectors/Azure/packages.config
  DNN Platform/Connectors/GoogleAnalytics/Dnn.GoogleAnalyticsConnector.csproj
  DNN Platform/Connectors/GoogleAnalytics/packages.config
  DNN Platform/Connectors/GoogleAnalytics4/Dnn.GoogleAnalytics4Connector.csproj
  DNN Platform/Connectors/GoogleAnalytics4/app.config
  DNN Platform/Connectors/GoogleAnalytics4/packages.config
  DNN Platform/Connectors/GoogleTagManager/Dnn.GoogleTagManagerConnector.csproj
  DNN Platform/Connectors/GoogleTagManager/packages.config
  DNN Platform/Dnn.AuthServices.Jwt/Dnn.AuthServices.Jwt.csproj
  DNN Platform/Dnn.AuthServices.Jwt/packages.config
  DNN Platform/DotNetNuke.Web.Mvc/DotNetNuke.Web.Mvc.csproj
  DNN Platform/DotNetNuke.Web.Mvc/packages.config
  DNN Platform/DotNetNuke.Web/DotNetNuke.Web.csproj
  DNN Platform/DotNetNuke.Web/packages.config
  DNN Platform/Library/DotNetNuke.Library.csproj
  DNN Platform/Library/packages.config
  DNN Platform/Modules/CoreMessaging/DotNetNuke.Modules.CoreMessaging.csproj
  DNN Platform/Modules/CoreMessaging/packages.config
  DNN Platform/Modules/DnnExportImport/DnnExportImport.csproj
  DNN Platform/Modules/DnnExportImport/packages.config
  DNN Platform/Modules/Groups/DotNetNuke.Modules.Groups.csproj
  DNN Platform/Modules/Groups/packages.config
  DNN Platform/Modules/Journal/DotNetNuke.Modules.Journal.csproj
  DNN Platform/Modules/Journal/packages.config
  DNN Platform/Modules/MemberDirectory/DotNetNuke.Modules.MemberDirectory.csproj
  DNN Platform/Modules/MemberDirectory/packages.config
  DNN Platform/Modules/ResourceManager/Dnn.Modules.ResourceManager.csproj
  DNN Platform/Modules/ResourceManager/packages.config
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/DNNConnect.CKEditorProvider.csproj
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/packages.config
  DNN Platform/Skins/Xcillion/DotNetNuke.Skins.Xcillion.csproj
  DNN Platform/Skins/Xcillion/packages.config
  DNN Platform/Tests/DNN.Integration.Test.Framework/DNN.Integration.Test.Framework.csproj
  DNN Platform/Tests/DNN.Integration.Test.Framework/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Content/DotNetNuke.Tests.Content.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Content/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Integration/DotNetNuke.Tests.Integration.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Integration/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Web.Mvc/DotNetNuke.Tests.Web.Mvc.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Web.Mvc/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Web/DotNetNuke.Tests.Web.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Web/packages.config
  DNN Platform/Website/DotNetNuke.Website.csproj
  DNN Platform/Website/packages.config
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Dnn.PersonaBar.Extensions.csproj
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/packages.config
  Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/Dnn.EditBar.UI.csproj
  Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/packages.config
  Dnn.AdminExperience/Library/Dnn.PersonaBar.Library/Dnn.PersonaBar.Library.csproj
  Dnn.AdminExperience/Library/Dnn.PersonaBar.Library/packages.config
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/Dnn.PersonaBar.UI.csproj
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/packages.config
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.Security.Tests/Dnn.PersonaBar.Security.Tests.csproj
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.Security.Tests/packages.config
Labels: Type: Maintenance

#5729 Updated GA4 Connector to build for DNN10
  DNN Platform/Connectors/GoogleAnalytics4/Dnn.GoogleAnalytics4Connector.csproj
  DNN Platform/Connectors/GoogleAnalytics4/GoogleAnalytics4Connector.cs
  DNN Platform/Connectors/GoogleAnalytics4/GoogleAnalytics4Connector.dnn
  DNN Platform/Connectors/GoogleAnalytics4/packages.config
  DNN Platform/Modules/HtmlEditorManager/DotNetNuke.Modules.HtmlEditorManager.csproj
Labels: Type: Bug

#5742 Fixed an issue with settings caching using SettingsRepository
  DNN Platform/Library/Entities/Modules/Settings/SettingsRepository.cs
Labels: Type: Bug

#5741 Fixed an issue where DnnPlugins package was not being produced
  Build/Tasks/thirdparty.json
Labels: Type: Bug

#5748 Updates `release/10.0.0` with latest changes from `develop`
  Build/Tasks/thirdparty.json
  DNN Platform/Library/Entities/Modules/Settings/SettingsRepository.cs
  yarn.lock
Labels: Type: Build/Release

#5738 Fix casing mismatch between codebehind and ascx
  DNN Platform/Providers/FolderProviders/AzureFolderProvider/Settings.ascx.cs
Labels: Type: Bug

#5749 Updated the name of the connector for #5700
  DNN Platform/Connectors/GoogleAnalytics/App_LocalResources/SharedResources.resx
  DNN Platform/Connectors/GoogleAnalytics/GoogleAnalyticsConnector.cs
  DNN Platform/Connectors/GoogleAnalytics/GoogleAnalyticsConnector.dnn
Labels: Type: Enhancement

#5752 Partial solution for #5552 to remove a stored procedure
  DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.12.01.SqlDataProvider
Labels: Type: Bug

#5751 Fixed the retry fequency if un-changed for the WebServerMonitor
  DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.12.01.SqlDataProvider
Labels: Type: Bug

#5756 Adjust help text for SMTP SSL setting
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Servers/App_LocalResources/Servers.resx
Labels: Area: AE > PersonaBar Ext > Servers.Web, Type: Documentation

#5759 Updates `release/10.0.0` with latest fixes from `develop`
  DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.12.01.SqlDataProvider
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Servers/App_LocalResources/Servers.resx
  yarn.lock
Labels: Type: Build/Release

#5762 CKE Adds option to allow browser by permissions
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/App_LocalResources/Options.aspx.resx
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/CKEditorOptions.ascx
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/CKEditorOptions.ascx.cs
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/CKEditorOptions.ascx.designer.cs
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Constants/SettingConstants.cs
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Objects/EditorProviderSettings.cs
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Objects/SettingBase.cs
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Utilities/SettingsUtil.cs
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Utilities/Utility.cs
Labels: Type: Enhancement, Area: Platform > Providers

#5766 Fix incorrect deprecation versions
  DNN Platform/Library/Common/Globals.cs
  DNN Platform/Library/Obsolete/EventLogController.cs
  DNN Platform/Library/Obsolete/SerializationController.cs
Labels: Type: Maintenance

#5764 Do all non-major npm upgrades
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/package.json
  Dnn.AdminExperience/ClientSide/AdminLogs.Web/package.json
  Dnn.AdminExperience/ClientSide/Bundle.Web/package.json
  Dnn.AdminExperience/ClientSide/Dnn.React.Common/package.json
  Dnn.AdminExperience/ClientSide/Extensions.Web/package.json
  Dnn.AdminExperience/ClientSide/Licensing.Web/package.json
  Dnn.AdminExperience/ClientSide/Pages.Web/package.json
  Dnn.AdminExperience/ClientSide/Prompt.Web/package.json
  Dnn.AdminExperience/ClientSide/Prompt.Web/src/components/App.jsx
  Dnn.AdminExperience/ClientSide/Roles.Web/package.json
  Dnn.AdminExperience/ClientSide/Security.Web/package.json
  Dnn.AdminExperience/ClientSide/Seo.Web/package.json
  Dnn.AdminExperience/ClientSide/Servers.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteImportExport.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteSettings.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteSettings.Web/src/components/moreSettings/index.jsx
  Dnn.AdminExperience/ClientSide/Sites.Web/package.json
  Dnn.AdminExperience/ClientSide/Sites.Web/src/_exportables/package.json
  Dnn.AdminExperience/ClientSide/TaskScheduler.Web/package.json
  Dnn.AdminExperience/ClientSide/Themes.Web/package.json
  Dnn.AdminExperience/ClientSide/Users.Web/package.json
  Dnn.AdminExperience/ClientSide/Users.Web/src/_exportables/package.json
  Dnn.AdminExperience/ClientSide/Vocabularies.Web/package.json
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/scripts/exports/export-bundle.js.LICENSE.txt
  package.json
  yarn.lock
Labels: Type: Maintenance, javascript

#5768 Merge `develop` into `release/10.0.0`
  DNN Platform/Library/Common/Globals.cs
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/package.json
  Dnn.AdminExperience/ClientSide/AdminLogs.Web/package.json
  Dnn.AdminExperience/ClientSide/Bundle.Web/package.json
  Dnn.AdminExperience/ClientSide/Dnn.React.Common/package.json
  Dnn.AdminExperience/ClientSide/Extensions.Web/package.json
  Dnn.AdminExperience/ClientSide/Licensing.Web/package.json
  Dnn.AdminExperience/ClientSide/Pages.Web/package.json
  Dnn.AdminExperience/ClientSide/Prompt.Web/package.json
  Dnn.AdminExperience/ClientSide/Prompt.Web/src/components/App.jsx
  Dnn.AdminExperience/ClientSide/Roles.Web/package.json
  Dnn.AdminExperience/ClientSide/Security.Web/package.json
  Dnn.AdminExperience/ClientSide/Seo.Web/package.json
  Dnn.AdminExperience/ClientSide/Servers.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteImportExport.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteSettings.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteSettings.Web/src/components/moreSettings/index.jsx
  Dnn.AdminExperience/ClientSide/Sites.Web/package.json
  Dnn.AdminExperience/ClientSide/Sites.Web/src/_exportables/package.json
  Dnn.AdminExperience/ClientSide/TaskScheduler.Web/package.json
  Dnn.AdminExperience/ClientSide/Themes.Web/package.json
  Dnn.AdminExperience/ClientSide/Users.Web/package.json
  Dnn.AdminExperience/ClientSide/Users.Web/src/_exportables/package.json
  Dnn.AdminExperience/ClientSide/Vocabularies.Web/package.json
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/scripts/exports/export-bundle.js.LICENSE.txt
  package.json
  yarn.lock
Labels: Type: Maintenance

#5769 Updated to remove additional elements
  DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.12.01.SqlDataProvider
Labels: Type: Bug
