Repository dnnsoftware/Dnn.Platform, pull requests merged in 2023-06, with the labels that each got.

#5650 Update README.md
  README.md
Labels: Type: Documentation

#5652 Add ComponentFactory fallback to service provider
  DNN Platform/DotNetNuke.Web/Common/DotNetNukeHttpApplication.cs
  DNN Platform/Library/ComponentModel/ContainerWithServiceProviderFallback.cs
  DNN Platform/Library/ComponentModel/SimpleContainer.cs
  DNN Platform/Library/DotNetNuke.Library.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Core/ComponentModel/ContainerWithServiceProviderFallbackTests.cs
  DNN Platform/Tests/DotNetNuke.Tests.Core/ComponentModel/SimpleContainerTests.cs
  DNN Platform/Tests/DotNetNuke.Tests.Core/DotNetNuke.Tests.Core.csproj
Labels: Type: Enhancement

#5654 Change site localization mode to be "Site" instead of `Site Title`
  Dnn.AdminExperience/ClientSide/SiteSettings.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteSettings.Web/src/components/editLanguagePanel/index.jsx
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.SiteSettings/App_LocalResources/SiteSettings.resx
Labels: Type: Enhancement

#5655 Resolve StackOverflowException
  DNN Platform/DotNetNuke.Maintenance/Telerik/Removal/Startup.cs
  DNN Platform/Library/Startup.cs
Labels: Type: Bug

#5648 Enable lazy DI registration
  DNN Platform/DotNetNuke.DependencyInjection/DotNetNuke.DependencyInjection.csproj
  DNN Platform/DotNetNuke.DependencyInjection/LazyWrapper.cs
  DNN Platform/Library/Startup.cs
Labels: Type: Enhancement, Area: Platform > DotNetNuke.DependencyInjection

#5658 Fixes #5657 issue with CKE loading previously set toolbar options
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Browser/Browser.aspx.cs
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Utilities/SettingsUtil.cs
Labels: Type: Bug

#5661 Fixes #5660 - Broken link on BUILD.md
  .github/BUILD.md
Labels: Type: Documentation

#5662 Correct broken link to `Contribute Page` within PR process documentation
  .github/PULL_REQUEST_PROCESS.md
Labels: Type: Documentation

#5666 Add `Google Analytics 4` Connector
  DNN Platform/Connectors/GoogleAnalytics4/App_LocalResources/SharedResources.resx
  DNN Platform/Connectors/GoogleAnalytics4/Connector.css
  DNN Platform/Connectors/GoogleAnalytics4/Constants.cs
  DNN Platform/Connectors/GoogleAnalytics4/Dnn.GoogleAnalytics4Connector.csproj
  DNN Platform/Connectors/GoogleAnalytics4/GoogleAnalytics4.config
  DNN Platform/Connectors/GoogleAnalytics4/GoogleAnalytics4Connector.cs
  DNN Platform/Connectors/GoogleAnalytics4/GoogleAnalytics4Connector.dnn
  DNN Platform/Connectors/GoogleAnalytics4/Images/GoogleAnalytics4_32X32_Standard.png
  DNN Platform/Connectors/GoogleAnalytics4/License.txt
  DNN Platform/Connectors/GoogleAnalytics4/Module.build
  DNN Platform/Connectors/GoogleAnalytics4/ReleaseNotes.txt
  DNN Platform/Connectors/GoogleAnalytics4/Scripts/connector.js
  DNN Platform/Connectors/GoogleAnalytics4/app.config
  DNN Platform/Connectors/GoogleAnalytics4/connector.htm
  DNN Platform/Connectors/GoogleAnalytics4/packages.config
  DNN Platform/Library/DotNetNuke.Library.csproj
  DNN Platform/Library/Services/Analytics/GoogleAnalytics4Engine.cs
  DNN_Platform.sln
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Connectors/css/Connectors.css
  SolutionInfo.cs
Labels: Type: Feature

#5668 Bug issue form
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: Type: Maintenance

#5669 Resolve connector checkbox saving
  DNN Platform/Connectors/GoogleAnalytics/Scripts/connector.js
  DNN Platform/Connectors/GoogleAnalytics/connector.htm
  DNN Platform/Connectors/GoogleAnalytics4/Scripts/connector.js
  DNN Platform/Connectors/GoogleAnalytics4/connector.htm
  DNN Platform/Connectors/GoogleTagManager/Scripts/connector.js
  DNN Platform/Connectors/GoogleTagManager/connector.htm
Labels: Type: Bug, Area: Platform > Connectors

#5672 Update bug report issue form to require versions
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: Type: Maintenance

#5673 Update `what-happened` field of bug issue form
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: Type: Maintenance

#5674 Initial implementation of enhancement request issue form
  .github/ISSUE_TEMPLATE/enhancement-request.md
  .github/ISSUE_TEMPLATE/enhancement-request.yml
Labels: Type: Maintenance

#5675 Correct checkboxes in enhancement request form
  .github/ISSUE_TEMPLATE/enhancement-request.yml
Labels: Type: Maintenance

#5676 Correct YML formatting
  .github/ISSUE_TEMPLATE/enhancement-request.yml
Labels: Type: Maintenance

#5677 Attempt to fix YML issue in `enhancement-request.yml`
  .github/ISSUE_TEMPLATE/enhancement-request.yml
Labels: Type: Maintenance

#5678 Correct `Yes` in `enhancement-request.yml`
  .github/ISSUE_TEMPLATE/enhancement-request.yml
Labels: Type: Maintenance

#5681 Updated `release/10.0.0` with latest fixes from `develop`
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/enhancement-request.md
  .github/ISSUE_TEMPLATE/enhancement-request.yml
Labels: Type: Build/Release

#5671 Update build packages
  Build/Build.csproj
  Build/Program.cs
  DNN Platform/Tests/DNN.Integration.Test.Framework/DNN.Integration.Test.Framework.csproj
  DNN Platform/Tests/DNN.Integration.Test.Framework/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.AspNetCCP/DotNetNuke.Tests.AspNetCCP.csproj
  DNN Platform/Tests/DotNetNuke.Tests.AspNetCCP/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Authentication/DotNetNuke.Tests.Authentication.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Authentication/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Content/DotNetNuke.Tests.Content.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Content/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Core/DotNetNuke.Tests.Core.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Core/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Data/DotNetNuke.Tests.Data.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Data/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Integration/DotNetNuke.Tests.Integration.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Integration/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Modules/DotNetNuke.Tests.Modules.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Modules/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.UI/DotNetNuke.Tests.UI.csproj
  DNN Platform/Tests/DotNetNuke.Tests.UI/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Urls/DotNetNuke.Tests.Urls.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Urls/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Utilities/DotNetNuke.Tests.Utilities.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Utilities/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Web.Mvc/DotNetNuke.Tests.Web.Mvc.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Web.Mvc/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Web/DotNetNuke.Tests.Web.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Web/packages.config
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.ConfigConsole.Tests/Dnn.PersonaBar.ConfigConsole.Tests.csproj
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.ConfigConsole.Tests/packages.config
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.Pages.Tests/Dnn.PersonaBar.Pages.Tests.csproj
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.Pages.Tests/packages.config
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.Security.Tests/Dnn.PersonaBar.Security.Tests.csproj
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.Security.Tests/packages.config
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.Users.Tests/Dnn.PersonaBar.Users.Tests.csproj
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.Users.Tests/packages.config
Labels: Type: Build/Release, Type: Maintenance

#5656 Fixes #5645 image upload problem
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Browser/Browser.aspx.cs
Labels: Type: Bug

#5682 Added 9.12.0-rc1 to bug report template
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: Type: Documentation

#5683 Cleaned up format of affected-versions dropdown
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: Type: Maintenance

#5684 Another cleanup attempt for line spacing
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: Type: Maintenance

#5685 Update `release/10.0.0` with latest fixes from `develop`
  .github/ISSUE_TEMPLATE/bug-report.yml
  Build/Build.csproj
  Build/Program.cs
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/Browser/Browser.aspx.cs
  DNN Platform/Tests/DNN.Integration.Test.Framework/DNN.Integration.Test.Framework.csproj
  DNN Platform/Tests/DNN.Integration.Test.Framework/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.AspNetCCP/DotNetNuke.Tests.AspNetCCP.csproj
  DNN Platform/Tests/DotNetNuke.Tests.AspNetCCP/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Authentication/DotNetNuke.Tests.Authentication.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Authentication/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Content/DotNetNuke.Tests.Content.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Content/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Core/DotNetNuke.Tests.Core.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Core/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Data/DotNetNuke.Tests.Data.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Data/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Integration/DotNetNuke.Tests.Integration.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Integration/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Modules/DotNetNuke.Tests.Modules.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Modules/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.UI/DotNetNuke.Tests.UI.csproj
  DNN Platform/Tests/DotNetNuke.Tests.UI/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Urls/DotNetNuke.Tests.Urls.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Urls/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Utilities/DotNetNuke.Tests.Utilities.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Utilities/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Web.Mvc/DotNetNuke.Tests.Web.Mvc.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Web.Mvc/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Web/DotNetNuke.Tests.Web.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Web/packages.config
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.ConfigConsole.Tests/Dnn.PersonaBar.ConfigConsole.Tests.csproj
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.ConfigConsole.Tests/packages.config
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.Pages.Tests/Dnn.PersonaBar.Pages.Tests.csproj
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.Pages.Tests/packages.config
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.Security.Tests/Dnn.PersonaBar.Security.Tests.csproj
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.Security.Tests/packages.config
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.Users.Tests/Dnn.PersonaBar.Users.Tests.csproj
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.Users.Tests/packages.config
Labels: Type: Maintenance

#5690 Install CodeDOM provider by default
  Build/Tasks/thirdparty.json
Labels: Type: Enhancement, Noteworthy

#5687 Bump NUnit3TestAdapter for DotNetNuke.Tests.Modules.DDRMenu
  DNN Platform/Tests/DotNetNuke.Tests.Modules.DDRMenu/DotNetNuke.Tests.Modules.DDRMenu.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Modules.DDRMenu/packages.config
Labels: Type: Maintenance, .NET

#5692 Fixed an issue where users module would not show user picture
  Build/Symbols/DotNetNuke_Symbols.dnn
  DNN Platform/Admin Modules/Dnn.Modules.Console/dnn_Console.dnn
  DNN Platform/Connectors/Azure/AzureConnector.dnn
  DNN Platform/Connectors/GoogleAnalytics/GoogleAnalyticsConnector.dnn
  DNN Platform/Connectors/GoogleAnalytics4/GoogleAnalytics4Connector.dnn
  DNN Platform/Connectors/GoogleTagManager/GoogleTagManagerConnector.dnn
  DNN Platform/Dnn.AuthServices.Jwt/Dnn.Jwt.dnn
  DNN Platform/DotNetNuke.WebUtility/DotNetNuke.ClientAPI.dnn
  DNN Platform/Modules/CoreMessaging/CoreMessaging.dnn
  DNN Platform/Modules/DDRMenu/DDRMenu.dnn
  DNN Platform/Modules/DnnExportImport/dnn_SiteExportImport.dnn
  DNN Platform/Modules/Groups/SocialGroups.dnn
  DNN Platform/Modules/HTML/dnn_HTML.dnn
  DNN Platform/Modules/HtmlEditorManager/dnn_HtmlEditorManager.dnn
  DNN Platform/Modules/Journal/Journal.dnn
  DNN Platform/Modules/MemberDirectory/MemberDirectory.dnn
  DNN Platform/Modules/RazorHost/Manifest.dnn
  DNN Platform/Modules/RazorHost/RazorHost.dnn
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/package.json
  DNN Platform/Modules/ResourceManager/ResourceManager.dnn
  DNN Platform/Modules/TelerikRemoval/TelerikRemoval.dnn
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Facebook/Facebook_Auth.dnn
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Google/Google_Auth.dnn
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.LiveConnect/Live_Auth.dnn
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Twitter/Twitter_Auth.dnn
  DNN Platform/Providers/CachingProviders/DotNetNuke.Providers.Caching.SimpleWebFarmCachingProvider/SimpleWebFarmCachingProvider.dnn
  DNN Platform/Providers/ClientCapabilityProviders/Provider.AspNetCCP/AspNetClientCapabilityProvider.dnn
  DNN Platform/Providers/FolderProviders/FolderProviders.dnn
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/DNNConnect.CKEditorProvider.dnn
  DNN Platform/Skins/Xcillion/DNN_Skin_Xcillion.dnn
  DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.12.00.SqlDataProvider
  Dnn.AdminExperience/ClientSide/AdminLogs.Web/package.json
  Dnn.AdminExperience/ClientSide/Bundle.Web/package.json
  Dnn.AdminExperience/ClientSide/Dnn.React.Common/package.json
  Dnn.AdminExperience/ClientSide/Extensions.Web/package.json
  Dnn.AdminExperience/ClientSide/Licensing.Web/package.json
  Dnn.AdminExperience/ClientSide/Pages.Web/package.json
  Dnn.AdminExperience/ClientSide/Prompt.Web/package.json
  Dnn.AdminExperience/ClientSide/Roles.Web/package.json
  Dnn.AdminExperience/ClientSide/Security.Web/package.json
  Dnn.AdminExperience/ClientSide/Seo.Web/package.json
  Dnn.AdminExperience/ClientSide/Servers.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteImportExport.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteSettings.Web/package.json
  Dnn.AdminExperience/ClientSide/Sites.Web/package.json
  Dnn.AdminExperience/ClientSide/Sites.Web/src/_exportables/package.json
  Dnn.AdminExperience/ClientSide/TaskScheduler.Web/package.json
  Dnn.AdminExperience/ClientSide/Themes.Web/package.json
  Dnn.AdminExperience/ClientSide/Users.Web/package.json
  Dnn.AdminExperience/ClientSide/Users.Web/src/_exportables/package.json
  Dnn.AdminExperience/ClientSide/Users.Web/src/_exportables/src/components/UserTable/DetailRow/index.jsx
  Dnn.AdminExperience/ClientSide/Users.Web/src/_exportables/src/components/UserTable/DetailRow/style.less
  Dnn.AdminExperience/ClientSide/Vocabularies.Web/package.json
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Dnn.PersonaBar.Extensions.dnn
  Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/Dnn.EditBar.UI.dnn
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/Dnn.PersonaBar.UI.dnn
  SolutionInfo.cs
  yarn.lock
Labels: Type: Enhancement

#5701 Updated `develop` with the latest hotfixes on `9.12.0`
  Build/Symbols/DotNetNuke_Symbols.dnn
  DNN Platform/Admin Modules/Dnn.Modules.Console/dnn_Console.dnn
  DNN Platform/Connectors/Azure/AzureConnector.dnn
  DNN Platform/Connectors/GoogleAnalytics/GoogleAnalyticsConnector.dnn
  DNN Platform/Connectors/GoogleAnalytics4/GoogleAnalytics4Connector.dnn
  DNN Platform/Connectors/GoogleTagManager/GoogleTagManagerConnector.dnn
  DNN Platform/Dnn.AuthServices.Jwt/Dnn.Jwt.dnn
  DNN Platform/DotNetNuke.WebUtility/DotNetNuke.ClientAPI.dnn
  DNN Platform/Modules/CoreMessaging/CoreMessaging.dnn
  DNN Platform/Modules/DDRMenu/DDRMenu.dnn
  DNN Platform/Modules/DnnExportImport/dnn_SiteExportImport.dnn
  DNN Platform/Modules/Groups/SocialGroups.dnn
  DNN Platform/Modules/HTML/dnn_HTML.dnn
  DNN Platform/Modules/HtmlEditorManager/dnn_HtmlEditorManager.dnn
  DNN Platform/Modules/Journal/Journal.dnn
  DNN Platform/Modules/MemberDirectory/MemberDirectory.dnn
  DNN Platform/Modules/RazorHost/Manifest.dnn
  DNN Platform/Modules/RazorHost/RazorHost.dnn
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/package.json
  DNN Platform/Modules/ResourceManager/ResourceManager.dnn
  DNN Platform/Modules/TelerikRemoval/TelerikRemoval.dnn
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Facebook/Facebook_Auth.dnn
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Google/Google_Auth.dnn
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.LiveConnect/Live_Auth.dnn
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Twitter/Twitter_Auth.dnn
  DNN Platform/Providers/CachingProviders/DotNetNuke.Providers.Caching.SimpleWebFarmCachingProvider/SimpleWebFarmCachingProvider.dnn
  DNN Platform/Providers/ClientCapabilityProviders/Provider.AspNetCCP/AspNetClientCapabilityProvider.dnn
  DNN Platform/Providers/FolderProviders/FolderProviders.dnn
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/DNNConnect.CKEditorProvider.dnn
  DNN Platform/Skins/Xcillion/DNN_Skin_Xcillion.dnn
  DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.12.00.SqlDataProvider
  Dnn.AdminExperience/ClientSide/AdminLogs.Web/package.json
  Dnn.AdminExperience/ClientSide/Bundle.Web/package.json
  Dnn.AdminExperience/ClientSide/Dnn.React.Common/package.json
  Dnn.AdminExperience/ClientSide/Extensions.Web/package.json
  Dnn.AdminExperience/ClientSide/Licensing.Web/package.json
  Dnn.AdminExperience/ClientSide/Pages.Web/package.json
  Dnn.AdminExperience/ClientSide/Prompt.Web/package.json
  Dnn.AdminExperience/ClientSide/Roles.Web/package.json
  Dnn.AdminExperience/ClientSide/Security.Web/package.json
  Dnn.AdminExperience/ClientSide/Seo.Web/package.json
  Dnn.AdminExperience/ClientSide/Servers.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteImportExport.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteSettings.Web/package.json
  Dnn.AdminExperience/ClientSide/Sites.Web/package.json
  Dnn.AdminExperience/ClientSide/Sites.Web/src/_exportables/package.json
  Dnn.AdminExperience/ClientSide/TaskScheduler.Web/package.json
  Dnn.AdminExperience/ClientSide/Themes.Web/package.json
  Dnn.AdminExperience/ClientSide/Users.Web/package.json
  Dnn.AdminExperience/ClientSide/Users.Web/src/_exportables/package.json
  Dnn.AdminExperience/ClientSide/Users.Web/src/_exportables/src/components/UserTable/DetailRow/index.jsx
  Dnn.AdminExperience/ClientSide/Users.Web/src/_exportables/src/components/UserTable/DetailRow/style.less
  Dnn.AdminExperience/ClientSide/Vocabularies.Web/package.json
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Dnn.PersonaBar.Extensions.dnn
  Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/Dnn.EditBar.UI.dnn
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/Dnn.PersonaBar.UI.dnn
  SolutionInfo.cs
  yarn.lock
Labels: Type: Maintenance

#5702 Update `release/10` with the latest hotfixes on `develop`
  DNN Platform/Connectors/GoogleAnalytics4/GoogleAnalytics4Connector.dnn
  DNN Platform/Connectors/GoogleAnalytics4/Images/GoogleAnalytics4_32X32_Standard.png
  DNN Platform/Website/DotNetNuke.Website.csproj
  DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.12.00.SqlDataProvider
  DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.12.01.SqlDataProvider
  Dnn.AdminExperience/ClientSide/AdminLogs.Web/package.json
  Dnn.AdminExperience/ClientSide/Bundle.Web/package.json
  Dnn.AdminExperience/ClientSide/Extensions.Web/package.json
  Dnn.AdminExperience/ClientSide/Licensing.Web/package.json
  Dnn.AdminExperience/ClientSide/Pages.Web/package.json
  Dnn.AdminExperience/ClientSide/Prompt.Web/package.json
  Dnn.AdminExperience/ClientSide/Roles.Web/package.json
  Dnn.AdminExperience/ClientSide/Security.Web/package.json
  Dnn.AdminExperience/ClientSide/Seo.Web/package.json
  Dnn.AdminExperience/ClientSide/Servers.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteImportExport.Web/package.json
  Dnn.AdminExperience/ClientSide/Sites.Web/package.json
  Dnn.AdminExperience/ClientSide/Sites.Web/src/_exportables/package.json
  Dnn.AdminExperience/ClientSide/TaskScheduler.Web/package.json
  Dnn.AdminExperience/ClientSide/Themes.Web/package.json
  Dnn.AdminExperience/ClientSide/Users.Web/package.json
  Dnn.AdminExperience/ClientSide/Users.Web/src/_exportables/package.json
  Dnn.AdminExperience/ClientSide/Users.Web/src/_exportables/src/components/UserTable/DetailRow/index.jsx
  Dnn.AdminExperience/ClientSide/Users.Web/src/_exportables/src/components/UserTable/DetailRow/style.less
  Dnn.AdminExperience/ClientSide/Vocabularies.Web/package.json
Labels: Type: Maintenance

#5694 Bump System.IdentityModel.Tokens.Jwt from 4.0.2.206221351 to 6.31.0
  Build/Tasks/packaging.json
  DNN Platform/Dnn.AuthServices.Jwt/Auth/JwtAuthMessageHandler.cs
  DNN Platform/Dnn.AuthServices.Jwt/Components/Common/Controllers/JwtController.cs
  DNN Platform/Dnn.AuthServices.Jwt/Dnn.AuthServices.Jwt.csproj
  DNN Platform/Dnn.AuthServices.Jwt/Dnn.Jwt.dnn
  DNN Platform/Dnn.AuthServices.Jwt/Library.build
  DNN Platform/Dnn.AuthServices.Jwt/app.config
  DNN Platform/Dnn.AuthServices.Jwt/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Web/Api/JwtAuthMessageHandlerTests.cs
  DNN Platform/Tests/DotNetNuke.Tests.Web/App.config
Labels: Area: Platform > Dnn.AuthServices.Jwt, Type: Maintenance, .NET

#5705 Updated bug-report.yml as per v9.12.0 release
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: Type: Documentation

#5707 Match Newtonsoft dependency version for NuGet pkg
  Build/Tools/NuGet/DotNetNuke.WebApi.nuspec
Labels: Type: Build/Release

#5712 Log all loader errors at once, at warning level
  DNN Platform/DotNetNuke.DependencyInjection/Extensions/TypeExtensions.cs
  DNN Platform/DotNetNuke.DependencyInjection/Extensions/TypesResult.cs
  DNN Platform/DotNetNuke.Web.Mvc/DotNetNuke.Web.Mvc.csproj
  DNN Platform/DotNetNuke.Web.Mvc/Extensions/StartupExtensions.cs
  DNN Platform/DotNetNuke.Web/Api/Extensions/StartupExtensions.cs
  DNN Platform/DotNetNuke.Web/DependencyInjectionInitialize.cs
  DNN Platform/DotNetNuke.Web/DotNetNuke.Web.csproj
Labels: Type: Enhancement
