Repository dnnsoftware/Dnn.Platform, pull requests merged in 2023-01, with the labels that each got.

#5461 Fixes an issue where URLControl checks upload permissions wrong
  DNN Platform/Library/UI/UserControls/URLControl.cs
Labels: Type: Bug

#5465 Correctly save the attribute maxAllowedContentLength
  DNN Platform/Library/Common/Utilities/Config.cs
Labels: Type: Bug

#5474 Update GitVersion.Tool and remove .NET 5 SDK
  Build/Program.cs
  azure-pipelines.yml
Labels: Type: Build/Release, Type: Maintenance

#5485 Fixed an issue where it was not possible to edit the root folder
  DNN Platform/Modules/ResourceManager/Components/ItemsManager.cs
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components.d.ts
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/context-menus/dnn-rm-folder-context-menu/dnn-rm-folder-context-menu.tsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-folder-list/dnn-rm-folder-list.scss
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-folder-list/dnn-rm-folder-list.tsx
Labels: Type: Bug

#5473 Update NUnit3TestAdapter to 4.3.1
  Build/Program.cs
  DNN Platform/Tests/DNN.Integration.Test.Framework/DNN.Integration.Test.Framework.csproj
  DNN Platform/Tests/DNN.Integration.Test.Framework/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.AspNetCCP/DotNetNuke.Tests.AspNetCCP.csproj
  DNN Platform/Tests/DotNetNuke.Tests.AspNetCCP/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Authentication/DotNetNuke.Tests.Authentication.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Authentication/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Content/DotNetNuke.Tests.Content.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Content/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Core/DotNetNuke.Tests.Core.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Core/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Data/DotNetNuke.Tests.Data.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Data/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Integration/DotNetNuke.Tests.Integration.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Integration/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Modules/DotNetNuke.Tests.Modules.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Modules/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.UI/DotNetNuke.Tests.UI.csproj
  DNN Platform/Tests/DotNetNuke.Tests.UI/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Urls/DotNetNuke.Tests.Urls.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Urls/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Utilities/DotNetNuke.Tests.Utilities.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Utilities/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Web.Mvc/DotNetNuke.Tests.Web.Mvc.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Web.Mvc/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Web/DotNetNuke.Tests.Web.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Web/packages.config
  DNN_Platform.sln.DotSettings
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.ConfigConsole.Tests/Dnn.PersonaBar.ConfigConsole.Tests.csproj
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.ConfigConsole.Tests/packages.config
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.Pages.Tests/Dnn.PersonaBar.Pages.Tests.csproj
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.Pages.Tests/packages.config
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.Security.Tests/Dnn.PersonaBar.Security.Tests.csproj
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.Security.Tests/packages.config
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.Users.Tests/Dnn.PersonaBar.Users.Tests.csproj
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.Users.Tests/packages.config
Labels: Type: Maintenance

#5475 Update NuGet.CommandLine from 5.10.0 to 6.4.0
  Build/Program.cs
Labels: Type: Build/Release, Type: Maintenance

#5476 Update Microsoft.TestPlatform from 16.11.0 to 17.4.1
  Build/Program.cs
Labels: Type: Build/Release, Type: Maintenance

#5484 Fixed an issue that prevented managing folders in user mode
  DNN Platform/Modules/ResourceManager/Components/PermissionsManager.cs
Labels: Type: Bug

#5488 Fixed an issue where sourcemaps would not load
  DNN Platform/Skins/Xcillion/Skin/Bootstrap/css/bootstrap.min.css.map
  Dnn.AdminExperience/.gitignore
  Dnn.AdminExperience/ClientSide/AdminLogs.Web/package.json
  Dnn.AdminExperience/ClientSide/AdminLogs.Web/webpack.config.js
  Dnn.AdminExperience/ClientSide/Bundle.Web/webpack.config.js
  Dnn.AdminExperience/ClientSide/Extensions.Web/webpack.config.js
  Dnn.AdminExperience/ClientSide/Licensing.Web/webpack.config.js
  Dnn.AdminExperience/ClientSide/Pages.Web/src/components/dnn-persona-bar-page-treeview/src/PersonaBarPageTreeviewInteractor.jsx
  Dnn.AdminExperience/ClientSide/Pages.Web/webpack.config.js
  Dnn.AdminExperience/ClientSide/Prompt.Web/package.json
  Dnn.AdminExperience/ClientSide/Prompt.Web/webpack.config.js
  Dnn.AdminExperience/ClientSide/Roles.Web/package.json
  Dnn.AdminExperience/ClientSide/Roles.Web/webpack.config.js
  Dnn.AdminExperience/ClientSide/Security.Web/package.json
  Dnn.AdminExperience/ClientSide/Security.Web/src/components/basicSettings/index.jsx
  Dnn.AdminExperience/ClientSide/Security.Web/src/components/registrationSettings/index.jsx
  Dnn.AdminExperience/ClientSide/Security.Web/src/components/sslSettings/index.jsx
  Dnn.AdminExperience/ClientSide/Security.Web/webpack.config.js
  Dnn.AdminExperience/ClientSide/Seo.Web/webpack.config.js
  Dnn.AdminExperience/ClientSide/Servers.Web/webpack.config.js
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/webpack.config.js
  Dnn.AdminExperience/ClientSide/SiteImportExport.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteImportExport.Web/src/services/applicationService.js
  Dnn.AdminExperience/ClientSide/SiteImportExport.Web/webpack.config.js
  Dnn.AdminExperience/ClientSide/SiteSettings.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteSettings.Web/webpack.config.js
  Dnn.AdminExperience/ClientSide/Sites.Web/webpack.config.js
  Dnn.AdminExperience/ClientSide/TaskScheduler.Web/package.json
  Dnn.AdminExperience/ClientSide/TaskScheduler.Web/webpack.config.js
  Dnn.AdminExperience/ClientSide/Themes.Web/webpack.config.js
  Dnn.AdminExperience/ClientSide/Users.Web/webpack.config.js
  Dnn.AdminExperience/ClientSide/Vocabularies.Web/webpack.config.js
  yarn.lock
Labels: Type: Bug

#5491 Fixed an issue where the SQL editor would not have height
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.SqlConsole/css/SqlConsole.css
Labels: Type: Bug

#5494 Updated Moment.JS to 2.29.4
  DNN Platform/Website/Licenses/Moment.js (MIT).txt.resources
  DNN Platform/Website/Resources/Shared/components/DatePicker/moment.min.js
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/scripts/contrib/moment.js
Labels: Type: Maintenance

#5490 Bumps React from 16.6.3 to 16.14.0
  Dnn.AdminExperience/ClientSide/AdminLogs.Web/package.json
  Dnn.AdminExperience/ClientSide/Bundle.Web/package.json
  Dnn.AdminExperience/ClientSide/Extensions.Web/package.json
  Dnn.AdminExperience/ClientSide/Pages.Web/package.json
  Dnn.AdminExperience/ClientSide/Prompt.Web/package.json
  Dnn.AdminExperience/ClientSide/Roles.Web/package.json
  Dnn.AdminExperience/ClientSide/Security.Web/package.json
  Dnn.AdminExperience/ClientSide/Seo.Web/package.json
  Dnn.AdminExperience/ClientSide/Servers.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteImportExport.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteSettings.Web/package.json
  Dnn.AdminExperience/ClientSide/Sites.Web/package.json
  Dnn.AdminExperience/ClientSide/Sites.Web/src/_exportables/package.json
  Dnn.AdminExperience/ClientSide/TaskScheduler.Web/package.json
  Dnn.AdminExperience/ClientSide/Themes.Web/package.json
  Dnn.AdminExperience/ClientSide/Users.Web/package.json
  Dnn.AdminExperience/ClientSide/Users.Web/src/_exportables/package.json
  Dnn.AdminExperience/ClientSide/Vocabularies.Web/package.json
  yarn.lock
Labels: Type: Maintenance

#5493 Fixed an issue that prevented creating packages from UI
  DNN Platform/Library/Common/Utilities/FileSystemUtils.cs
  DNN Platform/Library/Services/Installer/Writers/PackageWriterBase.cs
Labels: Type: Bug

#5501 Fixes #2140 issue
  DNN Platform/Controls/CountryListBox/CountryLookup.cs
  DNN Platform/Library/UI/WebControls/PropertyEditor/Edit Controls/DNN Edit Controls/DNNCountryAutocompleteControl.cs
Labels: Type: Bug

#5496 Fixed an issue where sourcemaps would only load on home page
  Dnn.AdminExperience/ClientSide/AdminLogs.Web/webpack.config.js
  Dnn.AdminExperience/ClientSide/Extensions.Web/webpack.config.js
  Dnn.AdminExperience/ClientSide/Licensing.Web/webpack.config.js
  Dnn.AdminExperience/ClientSide/Pages.Web/webpack.config.js
  Dnn.AdminExperience/ClientSide/Prompt.Web/webpack.config.js
  Dnn.AdminExperience/ClientSide/Roles.Web/webpack.config.js
  Dnn.AdminExperience/ClientSide/Security.Web/webpack.config.js
  Dnn.AdminExperience/ClientSide/Seo.Web/webpack.config.js
  Dnn.AdminExperience/ClientSide/Servers.Web/webpack.config.js
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/webpack.config.js
  Dnn.AdminExperience/ClientSide/SiteImportExport.Web/webpack.config.js
  Dnn.AdminExperience/ClientSide/SiteSettings.Web/webpack.config.js
  Dnn.AdminExperience/ClientSide/Sites.Web/webpack.config.js
  Dnn.AdminExperience/ClientSide/TaskScheduler.Web/webpack.config.js
  Dnn.AdminExperience/ClientSide/Themes.Web/webpack.config.js
  Dnn.AdminExperience/ClientSide/Users.Web/webpack.config.js
  Dnn.AdminExperience/ClientSide/Vocabularies.Web/webpack.config.js
Labels: Type: Bug

#5507 Resolve Resource Manager issue uploading files with uppercase extensions
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-queued-file/dnn-rm-queued-file.tsx
Labels: Type: Bug

#5508 Fixed an issue that caused an infinite loop when saving pofiles
  DNN Platform/Library/UI/WebControls/PropertyEditor/FieldEditorControl.cs
Labels: Type: Bug

#5489 Commited docs for dnn-resource-manager
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/actions/dnn-action-move-items/readme.md
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/context-menus/dnn-rm-file-context-menu/readme.md
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/context-menus/dnn-rm-folder-context-menu/readme.md
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-resource-manager/readme.md
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-actions-bar/readme.md
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-files-pane/readme.md
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-folder-list/readme.md
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-items-cardview/readme.md
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-items-listview/readme.md
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-left-pane/readme.md
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-move-items/readme.md
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-right-pane/readme.md
Labels: Type: Documentation

#5510 Fix some obsolete method usages
  DNN Platform/Library/Application/Application.cs
  DNN Platform/Library/Application/ApplicationStatusInfo.cs
  DNN Platform/Library/Common/NavigationManager.cs
  DNN Platform/Library/Common/Utilities/Config.cs
  DNN Platform/Library/Common/Utilities/UrlUtils.cs
  DNN Platform/Library/Entities/Controllers/HostController.cs
  DNN Platform/Library/Entities/Host/Host.cs
  DNN Platform/Library/Entities/Icons/IconController.cs
  DNN Platform/Library/Entities/Modules/DesktopModuleController.cs
  DNN Platform/Library/Entities/Tabs/TabController.cs
  DNN Platform/Library/Entities/Urls/AdvancedFriendlyUrlProvider.cs
  DNN Platform/Library/Entities/Urls/FriendlyUrlProviderBase.cs
  DNN Platform/Modules/HtmlEditorManager/Components/UpgradeController.cs
  DNN Platform/Modules/HtmlEditorManager/DotNetNuke.Modules.HtmlEditorManager.csproj
  DNN Platform/Modules/RazorHost/DotNetNuke.Modules.RazorHost.csproj
  DNN Platform/Modules/ResourceManager/Services/ItemsController.cs
  DNN Platform/Tests/DotNetNuke.Tests.Core/Common/NavigationManagerTests.cs
  DNN Platform/Website/Default.aspx.cs
  DNN Platform/Website/ErrorPage.aspx.cs
  DNN Platform/Website/admin/Skins/Links.ascx.cs
  DNN Platform/Website/admin/Skins/User.ascx.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Security/Checks/CheckModuleHeaderAndFooter.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Seo/SeoController.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Servers/Log/LogController.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/SeoController.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/SiteSettingsController.cs
  Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/Services/ContentEditorController.cs
Labels: Type: Maintenance
