Repository dnnsoftware/Dnn.Platform, pull requests merged in 2023-05, with the labels that each got.

#5640 Add params array constructor to SupportedModulesAttribute
  DNN Platform/DotNetNuke.Web/Api/SupportedModulesAttribute.cs
Labels: Type: Enhancement

#5642 Don't prefix icon path if it's rooted
  DNN Platform/Website/admin/Containers/Icon.ascx.cs
Labels: Type: Bug

#5643 Updated `release/10.0.0` with latest fixes from `9.x.x`
  DNN Platform/Website/admin/Containers/Icon.ascx.cs
Labels: Type: Maintenance
