Repository dnnsoftware/Dnn.Platform, pull requests merged in 2023-03, with the labels that each got.

#5568 Remove SQL syntax that's incompatible with 2012
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Dnn.PersonaBar.Extensions.csproj
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Dnn.PersonaBar.Extensions.dnn
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/SqlDataProvider/09.11.01.SqlDataProvider
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/SqlDataProvider/09.11.02.SqlDataProvider
Labels: Type: Bug

#5569 Upgrade Yarn to 3.4.1
  .yarn/releases/yarn-3.2.0.cjs
  .yarn/releases/yarn-3.4.1.cjs
  .yarnrc.yml
  package.json
  yarn.lock
Labels: Type: Maintenance

#5574 Fix exception when emailing admin logs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/AdminLogs/AdminLogsController.cs
Labels: Type: Bug

#5583 Remove DotNetNuke.Web.Deprecated from DotNetNuke.Bundle
  Build/Tools/NuGet/DotNetNuke.Bundle.nuspec
Labels: Type: Build/Release

#5578 Fix unintentional recursion (i.e. stack overflow)
  DNN Platform/Library/UI/UserControls/HelpButtonControl.cs
  DNN Platform/Library/UI/UserControls/SectionHeadControl.cs
  DNN Platform/Library/UI/UserControls/TextEditor.cs
  DNN Platform/Library/UI/UserControls/URLTrackingControl.cs
Labels: Type: Bug

#5525 Resolve warnings in DotNetNuke.Syndication
  DNN Platform/Library/Services/Syndication/RssHandler.cs
  DNN Platform/Library/Services/Syndication/SyndicationHandlerBase.cs
  DNN Platform/Syndication/DotNetNuke.Syndication.csproj
  DNN Platform/Syndication/OPML/Opml.cs
  DNN Platform/Syndication/OPML/OpmlDownloadManager.cs
  DNN Platform/Syndication/OPML/OpmlOutline.cs
  DNN Platform/Syndication/OPML/OpmlOutlines.cs
  DNN Platform/Syndication/RSS/GenericRssChannel.cs
  DNN Platform/Syndication/RSS/GenericRssElement.cs
  DNN Platform/Syndication/RSS/RssChannelBase.cs
  DNN Platform/Syndication/RSS/RssChannelDom.cs
  DNN Platform/Syndication/RSS/RssDataSource.cs
  DNN Platform/Syndication/RSS/RssDataSourceView.cs
  DNN Platform/Syndication/RSS/RssDownloadManager.cs
  DNN Platform/Syndication/RSS/RssElementBase.cs
  DNN Platform/Syndication/RSS/RssElementCustomTypeDescriptor.cs
  DNN Platform/Syndication/RSS/RssHttpHandlerBase.cs
  DNN Platform/Syndication/RSS/RssHttpHandlerHelper.cs
  DNN Platform/Syndication/RSS/RssHyperLink.cs
  DNN Platform/Syndication/RSS/RssXmlHelper.cs
  DNN Platform/Syndication/Settings.cs
Labels: Type: Documentation

#5587 Fixed an issue resolving LiteDB
  DNN Platform/Modules/DnnExportImport/DnnExportImport.csproj
  DNN Platform/Modules/DnnExportImportLibrary/DnnExportImportLibrary.csproj
  yarn.lock
Labels: Type: Bug

#5592 Enhance PersonaBarTheme.css to Resize the PersonaBar Logo
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/theme.css
Labels: Type: Enhancement
