Repository dnnsoftware/Dnn.Platform, pull requests merged in 2023-09, with the labels that each got.

#5806 Fixed an issue where filenames of downloads would get mangled
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/actions/dnn-action-download-item/dnn-action-download-item.tsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/services/ItemsClient.ts
Labels: Type: Bug

#5807 Update `web.config` max upload size defaults, correct backend calcs, and fix validation issue preventing increasing
  DNN Platform/Tests/App.config
  DNN Platform/Website/development.config
  DNN Platform/Website/release.config
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/SecurityController.cs
Labels: Type: Bug, Type: Enhancement, Area: AE > PersonaBar Ext > Security.Web, Area: Platform > Website, Effort: Medium, Priority: Medium, Status: Review

#5814 Update bug-report.yml to include v9.13-rc
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: Type: Documentation

#5816 Move DnnDeprecatedAttribute to Abstractions
  DNN Platform/DotNetNuke.Abstractions/DnnDeprecatedAttribute.cs
  DNN Platform/DotNetNuke.Abstractions/DotNetNuke.Abstractions.csproj
  DNN Platform/DotNetNuke.DependencyInjection/DotNetNuke.DependencyInjection.csproj
  DNN Platform/DotNetNuke.Instrumentation/DotNetNuke.Instrumentation.csproj
  DNN Platform/DotNetNuke.Web.Client/DotNetNuke.Web.Client.csproj
  DNN Platform/DotNetNuke.Web.Mvc/DotNetNuke.Web.Mvc.csproj
  DNN Platform/DotNetNuke.Web.Razor/DotNetNuke.Web.Razor.csproj
  DNN Platform/DotNetNuke.Web/DotNetNuke.Web.csproj
  DNN Platform/HttpModules/DotNetNuke.HttpModules.csproj
  DNN Platform/Library/DotNetNuke.Library.csproj
  DNN Platform/Modules/DDRMenu/DotNetNuke.Modules.DDRMenu.csproj
  DNN Platform/Modules/DnnExportImport/DnnExportImport.csproj
  DNN Platform/Modules/HTML/DotNetNuke.Modules.Html.csproj
  DNN Platform/Modules/HtmlEditorManager/DotNetNuke.Modules.HtmlEditorManager.csproj
  DNN Platform/Modules/MemberDirectory/DotNetNuke.Modules.MemberDirectory.csproj
  DNN Platform/Modules/RazorHost/DotNetNuke.Modules.RazorHost.csproj
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/DNNConnect.CKEditorProvider.csproj
  DNN Platform/Tests/DNN.Integration.Test.Framework/DNN.Integration.Test.Framework.csproj
  DNN Platform/Tests/DotNetNuke.Tests.SourceGenerators/DnnDeprecatedGeneratorTests.cs
  DNN Platform/Tests/DotNetNuke.Tests.SourceGenerators/Snapshots/DnnDeprecatedGeneratorTests.DeprecatedExtensionMethod_AddsPartialWithObsoleteAttribute#DnnDeprecatedAttribute.g.verified.cs
  DNN Platform/Tests/DotNetNuke.Tests.SourceGenerators/Snapshots/DnnDeprecatedGeneratorTests.DeprecatedGenericPartialClass_AddsPartialWithObsoleteAttribute#DnnDeprecatedAttribute.g.verified.cs
  DNN Platform/Tests/DotNetNuke.Tests.SourceGenerators/Snapshots/DnnDeprecatedGeneratorTests.DeprecatedMethodWithOptionalParameters_AddsPartialWithObsoleteAttribute#DnnDeprecatedAttribute.g.verified.cs
  DNN Platform/Tests/DotNetNuke.Tests.SourceGenerators/Snapshots/DnnDeprecatedGeneratorTests.DeprecatedMethodWithParamsParameter_AddsPartialWithObsoleteAttribute#DnnDeprecatedAttribute.g.verified.cs
  DNN Platform/Tests/DotNetNuke.Tests.SourceGenerators/Snapshots/DnnDeprecatedGeneratorTests.DeprecatedMethods_AddsPartialWithObsoleteAttribute#DnnDeprecatedAttribute.g.verified.cs
  DNN Platform/Tests/DotNetNuke.Tests.SourceGenerators/Snapshots/DnnDeprecatedGeneratorTests.DeprecatedNestedGenericPartialClass_AddsPartialWithObsoleteAttribute#DnnDeprecatedAttribute.g.verified.cs
  DNN Platform/Tests/DotNetNuke.Tests.SourceGenerators/Snapshots/DnnDeprecatedGeneratorTests.DeprecatedNestedPartialRecord_AddsPartialWithObsoleteAttribute#DnnDeprecatedAttribute.g.verified.cs
  DNN Platform/Tests/DotNetNuke.Tests.SourceGenerators/Snapshots/DnnDeprecatedGeneratorTests.DeprecatedNonPartialClass_ReportsAnErrorDiagnostic#DnnDeprecatedAttribute.g.verified.cs
  DNN Platform/Tests/DotNetNuke.Tests.SourceGenerators/Snapshots/DnnDeprecatedGeneratorTests.DeprecatedPartialClass_AddsPartialWithObsoleteAttribute#DnnDeprecatedAttribute.g.verified.cs
  DNN Platform/Tests/DotNetNuke.Tests.SourceGenerators/Snapshots/DnnDeprecatedGeneratorTests.DeprecatedPartialGenericInterface_AddsPartialWithObsoleteAttribute#DnnDeprecatedAttribute.g.verified.cs
  DNN Platform/Tests/DotNetNuke.Tests.SourceGenerators/Snapshots/DnnDeprecatedGeneratorTests.DeprecatedPartialInterface_AddsPartialWithObsoleteAttribute#DnnDeprecatedAttribute.g.verified.cs
  DNN Platform/Tests/DotNetNuke.Tests.SourceGenerators/Snapshots/DnnDeprecatedGeneratorTests.DeprecatedPartialRecord_AddsPartialWithObsoleteAttribute#DnnDeprecatedAttribute.g.verified.cs
  DNN Platform/Tests/DotNetNuke.Tests.SourceGenerators/Snapshots/DnnDeprecatedGeneratorTests.DeprecatedPartialStruct_AddsPartialWithObsoleteAttribute#DnnDeprecatedAttribute.g.verified.cs
  DNN Platform/Tests/DotNetNuke.Tests.SourceGenerators/Snapshots/DnnDeprecatedGeneratorTests.DeprecatedWithSpecialCharacters_AddsPartialWithObsoleteAttribute#DnnDeprecatedAttribute.g.verified.cs
  DNN Platform/Tests/DotNetNuke.Tests.SourceGenerators/Snapshots/DnnDeprecatedGeneratorTests.NotDeprecatedClass_DoesNotGenerateAnything#DnnDeprecatedAttribute.g.verified.cs
  DNN Platform/Tests/DotNetNuke.Tests.Utilities/DotNetNuke.Tests.Utilities.csproj
  DNN Platform/Website/DotNetNuke.Website.csproj
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Dnn.PersonaBar.Extensions.csproj
  Dnn.AdminExperience/Library/Dnn.PersonaBar.Library/Dnn.PersonaBar.Library.csproj
  DotNetNuke.Internal.SourceGenerators/DnnDeprecatedGenerator.cs
Labels: Type: Build/Release

#5817 resourceManager bad url using Azure
  .github/ISSUE_TEMPLATE/bug-report.yml
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/actions/dnn-action-copy-url/dnn-action-copy-url.tsx
Labels: Type: Bug

#5825 Merge `release/9.13.0` into `develop`
  DNN Platform/DotNetNuke.Abstractions/DnnDeprecatedAttribute.cs
  DNN Platform/DotNetNuke.Abstractions/DotNetNuke.Abstractions.csproj
  DNN Platform/DotNetNuke.DependencyInjection/DotNetNuke.DependencyInjection.csproj
  DNN Platform/DotNetNuke.Instrumentation/DotNetNuke.Instrumentation.csproj
  DNN Platform/DotNetNuke.Web.Client/DotNetNuke.Web.Client.csproj
  DNN Platform/DotNetNuke.Web.Mvc/DotNetNuke.Web.Mvc.csproj
  DNN Platform/DotNetNuke.Web.Razor/DotNetNuke.Web.Razor.csproj
  DNN Platform/DotNetNuke.Web/DotNetNuke.Web.csproj
  DNN Platform/HttpModules/DotNetNuke.HttpModules.csproj
  DNN Platform/Library/DotNetNuke.Library.csproj
  DNN Platform/Modules/DDRMenu/DotNetNuke.Modules.DDRMenu.csproj
  DNN Platform/Modules/DnnExportImport/DnnExportImport.csproj
  DNN Platform/Modules/HTML/DotNetNuke.Modules.Html.csproj
  DNN Platform/Modules/HtmlEditorManager/DotNetNuke.Modules.HtmlEditorManager.csproj
  DNN Platform/Modules/MemberDirectory/DotNetNuke.Modules.MemberDirectory.csproj
  DNN Platform/Modules/RazorHost/DotNetNuke.Modules.RazorHost.csproj
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/actions/dnn-action-copy-url/dnn-action-copy-url.tsx
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/DNNConnect.CKEditorProvider.csproj
  DNN Platform/Tests/DNN.Integration.Test.Framework/DNN.Integration.Test.Framework.csproj
  DNN Platform/Tests/DotNetNuke.Tests.SourceGenerators/DotNetNuke.Tests.SourceGenerators.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Utilities/DotNetNuke.Tests.Utilities.csproj
  DNN Platform/Website/DotNetNuke.Website.csproj
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Dnn.PersonaBar.Extensions.csproj
  Dnn.AdminExperience/Library/Dnn.PersonaBar.Library/Dnn.PersonaBar.Library.csproj
  DotNetNuke.Internal.SourceGenerators/DnnDeprecatedGenerator.cs
Labels: Type: Build/Release

#5828 Updates issue template as per having released `v9.13.0`
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: Type: Documentation
