Repository dnnsoftware/Dnn.Platform, pull requests merged in 2023-12, with the labels that each got.

#5851 Implemented core support for portal styles
  DNN Platform/Connectors/GoogleAnalytics4/GoogleAnalytics4Connector.dnn
  DNN Platform/DotNetNuke.Abstractions/Portals/IPortalStyles.cs
  DNN Platform/DotNetNuke.Abstractions/Portals/StyleColor.cs
  DNN Platform/JavaScript Libraries/DnnPlugins/DnnPlugins.dnn
  DNN Platform/Library/Common/Utilities/DataCache.cs
  DNN Platform/Library/DotNetNuke.Library.csproj
  DNN Platform/Library/Entities/Portals/Extensions/IPortalSettingsExtensions.cs
  DNN Platform/Library/Entities/Portals/PortalSettingsController.cs
  DNN Platform/Library/Entities/Portals/PortalStyles.cs
  DNN Platform/Library/Entities/Portals/PortalStylesRepository.cs
  DNN Platform/Providers/SmtpOAuthProviders/ExchangeOnlineAuthProvider/ExchangeOnlineAuthProvider.dnn
  DNN Platform/Providers/SmtpOAuthProviders/GoogleMailAuthProvider/GoogleMailAuthProvider.dnn
  DNN Platform/Tests/DotNetNuke.Tests.Core/Entities/Portals/PortalSettingsControllerTests.cs
  DNN Platform/Website/Default.aspx
  DNN Platform/Website/Default.aspx.cs
  DNN Platform/Website/Default.aspx.designer.cs
  DNN Platform/Website/Providers/DataProviders/SqlDataProvider/10.00.00.SqlDataProvider
  Dnn.AdminExperience/ClientSide/AdminLogs.Web/package.json
  Dnn.AdminExperience/ClientSide/Extensions.Web/package.json
  Dnn.AdminExperience/ClientSide/Licensing.Web/package.json
  Dnn.AdminExperience/ClientSide/Pages.Web/package.json
  Dnn.AdminExperience/ClientSide/Prompt.Web/package.json
  Dnn.AdminExperience/ClientSide/Roles.Web/package.json
  Dnn.AdminExperience/ClientSide/Seo.Web/package.json
  Dnn.AdminExperience/ClientSide/Servers.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteImportExport.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteSettings.Web/package.json
  Dnn.AdminExperience/ClientSide/Sites.Web/package.json
  Dnn.AdminExperience/ClientSide/Sites.Web/src/_exportables/package.json
  Dnn.AdminExperience/ClientSide/TaskScheduler.Web/package.json
  Dnn.AdminExperience/ClientSide/Themes.Web/package.json
  Dnn.AdminExperience/ClientSide/Users.Web/src/_exportables/package.json
  Dnn.AdminExperience/ClientSide/Vocabularies.Web/package.json
  SolutionInfo.cs
  yarn.lock
Labels: Type: Feature

#5887 Merged latest fixes on `develop` into `release/10.0.0`
  .github/dependabot.yml
  .yarnrc.yml
  Build/Build.csproj
  DNN Platform/Tests/DotNetNuke.Tests.SourceGenerators/DotNetNuke.Tests.SourceGenerators.csproj
  azure-pipelines.yml
  gitversion.yml
  global.json
  package.json
Labels: Type: Maintenance

#5892 Fixed an issue that kept rm items selected after changing folders
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-left-pane/dnn-rm-left-pane.tsx
  azure-pipelines.yml
Labels: Type: Bug

#5895 DNN 10 Theme: Update styling of login
  DNN Platform/Skins/Aperture/src/scss/components/_dnn.scss
  DNN Platform/Skins/Aperture/src/scss/components/_login.scss
  DNN Platform/Skins/Aperture/src/scss/mixins/_mixins.scss
  DNN Platform/Skins/Aperture/src/scss/variables/_controls.scss
Labels: Type: Feature, Area: Platform > Skins, Effort: Medium, Priority: High, Status: Review

#5899 Resources manager module: added file open commands
  DNN Platform/Modules/ResourceManager/App_LocalResources/ResourceManager.resx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components.d.ts
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/actions/dnn-action-open-file/dnn-action-open-file.tsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/context-menus/dnn-rm-file-context-menu/dnn-rm-file-context-menu.tsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-actions-bar/dnn-rm-actions-bar.tsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-files-pane/dnn-rm-files-pane.tsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-items-cardview/dnn-rm-items-cardview.tsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-items-listview/dnn-rm-items-listview.tsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/services/LocalizationClient.ts
Labels: Type: Enhancement
