Repository dnnsoftware/Dnn.Platform, pull requests merged in 2023-11, with the labels that each got.

#5865 Fix exception saving folder permissions
  DNN Platform/Library/Security/Permissions/FolderPermissionInfo.cs
  DNN Platform/Tests/DotNetNuke.Tests.Core/DotNetNuke.Tests.Core.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Core/Security/Permissions/PermissionProviderTests.cs
Labels: Type: Bug

#5868 Updates `release/10.0.0` with latest fixes on 'develop'
  DNN Platform/Library/Security/Permissions/FolderPermissionInfo.cs
  DNN Platform/Tests/DotNetNuke.Tests.Core/DotNetNuke.Tests.Core.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Core/Security/Permissions/PermissionProviderTests.cs
Labels: Type: Maintenance

#5872 Fixed an issue where develop was publishing wrong version
  gitversion.yml
Labels: Type: Build/Release

#5874 Upgrade Yarn from 3.4.1 to 4.0.2
  .yarnrc.yml
  package.json
  yarn.lock
Labels: Type: Maintenance, javascript

#5873 Use .NET 8.x and Cake 4.0.0 for build
  Build/Build.csproj
  DNN Platform/Tests/DotNetNuke.Tests.SourceGenerators/DotNetNuke.Tests.SourceGenerators.csproj
  azure-pipelines.yml
  global.json
Labels: Type: Build/Release, Type: Maintenance

#5866 Add Dependabot groups for NuGet
  .github/dependabot.yml
Labels: Type: Maintenance

#5875 Fixed a CI issue that prevented yarn package caching
  azure-pipelines.yml
Labels: Type: Build/Release
