Repository dnnsoftware/Dnn.Platform, pull requests merged in 2024-07, with the labels that each got.

#6093 Update SECURITY.md
  SECURITY.md
Labels: Effort: Low, Priority: High, Type: Maintenance, Status: Review

#6038 Fixes to sql script and new rollup scripts for version 10
  DNN Platform/Website/Install/DotNetNuke.install.config.resources
  DNN Platform/Website/Providers/DataProviders/SqlDataProvider/10.00.00.SqlDataProvider
  DNN Platform/Website/Providers/DataProviders/SqlDataProvider/DotNetNuke.Data.SqlDataProvider
  DNN Platform/Website/Providers/DataProviders/SqlDataProvider/DotNetNuke.Schema.SqlDataProvider
Labels: Type: Bug, Type: Enhancement, Area: Platform > Providers

#6092 Update PULL_REQUEST_PROCESS.md
  .github/PULL_REQUEST_PROCESS.md
Labels: Effort: Low, Priority: High, Type: Maintenance, Status: Review

#6096 Bumps all version to 9.13.4 on `develop` branch.
  Build/Symbols/DotNetNuke_Symbols.dnn
  DNN Platform/Admin Modules/Dnn.Modules.Console/dnn_Console.dnn
  DNN Platform/Connectors/Azure/AzureConnector.dnn
  DNN Platform/Connectors/GoogleAnalytics/GoogleAnalyticsConnector.dnn
  DNN Platform/Connectors/GoogleAnalytics4/GoogleAnalytics4Connector.dnn
  DNN Platform/Connectors/GoogleTagManager/GoogleTagManagerConnector.dnn
  DNN Platform/Dnn.AuthServices.Jwt/Dnn.Jwt.dnn
  DNN Platform/DotNetNuke.WebUtility/DotNetNuke.ClientAPI.dnn
  DNN Platform/JavaScript Libraries/DnnPlugins/DnnPlugins.dnn
  DNN Platform/Modules/CoreMessaging/CoreMessaging.dnn
  DNN Platform/Modules/DDRMenu/DDRMenu.dnn
  DNN Platform/Modules/DnnExportImport/dnn_SiteExportImport.dnn
  DNN Platform/Modules/Groups/SocialGroups.dnn
  DNN Platform/Modules/HTML/dnn_HTML.dnn
  DNN Platform/Modules/HtmlEditorManager/dnn_HtmlEditorManager.dnn
  DNN Platform/Modules/Journal/Journal.dnn
  DNN Platform/Modules/MemberDirectory/MemberDirectory.dnn
  DNN Platform/Modules/RazorHost/Manifest.dnn
  DNN Platform/Modules/RazorHost/RazorHost.dnn
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/package.json
  DNN Platform/Modules/ResourceManager/ResourceManager.dnn
  DNN Platform/Modules/TelerikRemoval/TelerikRemoval.dnn
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Facebook/Facebook_Auth.dnn
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Google/Google_Auth.dnn
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.LiveConnect/Live_Auth.dnn
  DNN Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.Twitter/Twitter_Auth.dnn
  DNN Platform/Providers/CachingProviders/DotNetNuke.Providers.Caching.SimpleWebFarmCachingProvider/SimpleWebFarmCachingProvider.dnn
  DNN Platform/Providers/ClientCapabilityProviders/Provider.AspNetCCP/AspNetClientCapabilityProvider.dnn
  DNN Platform/Providers/FolderProviders/FolderProviders.dnn
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/DNNConnect.CKEditorProvider.dnn
  DNN Platform/Providers/SmtpOAuthProviders/ExchangeOnlineAuthProvider/ExchangeOnlineAuthProvider.dnn
  DNN Platform/Providers/SmtpOAuthProviders/GoogleMailAuthProvider/GoogleMailAuthProvider.dnn
  DNN Platform/Skins/Xcillion/DNN_Skin_Xcillion.dnn
  Dnn.AdminExperience/ClientSide/AdminLogs.Web/package.json
  Dnn.AdminExperience/ClientSide/Bundle.Web/package.json
  Dnn.AdminExperience/ClientSide/Dnn.React.Common/package.json
  Dnn.AdminExperience/ClientSide/Extensions.Web/package.json
  Dnn.AdminExperience/ClientSide/Licensing.Web/package.json
  Dnn.AdminExperience/ClientSide/Pages.Web/package.json
  Dnn.AdminExperience/ClientSide/Prompt.Web/package.json
  Dnn.AdminExperience/ClientSide/Roles.Web/package.json
  Dnn.AdminExperience/ClientSide/Security.Web/package.json
  Dnn.AdminExperience/ClientSide/Seo.Web/package.json
  Dnn.AdminExperience/ClientSide/Servers.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteGroups.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteImportExport.Web/package.json
  Dnn.AdminExperience/ClientSide/SiteSettings.Web/package.json
  Dnn.AdminExperience/ClientSide/Sites.Web/package.json
  Dnn.AdminExperience/ClientSide/Sites.Web/src/_exportables/package.json
  Dnn.AdminExperience/ClientSide/TaskScheduler.Web/package.json
  Dnn.AdminExperience/ClientSide/Themes.Web/package.json
  Dnn.AdminExperience/ClientSide/Users.Web/package.json
  Dnn.AdminExperience/ClientSide/Users.Web/src/_exportables/package.json
  Dnn.AdminExperience/ClientSide/Vocabularies.Web/package.json
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Dnn.PersonaBar.Extensions.dnn
  Dnn.AdminExperience/EditBar/Dnn.EditBar.UI/Dnn.EditBar.UI.dnn
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/Dnn.PersonaBar.UI.dnn
  SolutionInfo.cs
  yarn.lock
Labels: Type: Build/Release

#6097 Bump react-widgets from 4.4.6 to 5.8.4
  Dnn.AdminExperience/ClientSide/Bundle.Web/package.json
  Dnn.AdminExperience/ClientSide/Dnn.React.Common/package.json
  Dnn.AdminExperience/ClientSide/Dnn.React.Common/src/PermissionGrid/Suggestion/index.jsx
  Dnn.AdminExperience/ClientSide/Dnn.React.Common/src/PermissionGrid/Suggestion/style.less
  Dnn.AdminExperience/ClientSide/Pages.Web/package.json
  Dnn.AdminExperience/ClientSide/Roles.Web/package.json
  Dnn.AdminExperience/ClientSide/Roles.Web/src/components/roles/FiltersBar/index.jsx
  Dnn.AdminExperience/ClientSide/Roles.Web/src/components/roles/UsersInRole/index.jsx
  Dnn.AdminExperience/ClientSide/Users.Web/package.json
  Dnn.AdminExperience/ClientSide/Users.Web/src/_exportables/package.json
  Dnn.AdminExperience/ClientSide/Users.Web/src/_exportables/src/components/UserTable/UsersRoles/index.jsx
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Roles/scripts/bundles/roles-bundle.js.LICENSE.txt
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Users/scripts/bundles/users-bundle.js.LICENSE.txt
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Users/scripts/exportables/Users/UsersCommon.js.LICENSE.txt
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/scripts/exports/export-bundle.js.LICENSE.txt
  yarn.lock
Labels: Type: Maintenance, javascript

#6098 Removed optimize-css-assets-webpack-plugin dependency
  Dnn.AdminExperience/ClientSide/Prompt.Web/package.json
  yarn.lock
Labels: Type: Maintenance, javascript
