Repository dnnsoftware/Dnn.Platform, pull requests merged in 2024-03, with the labels that each got.

#5989 Bulk Install: Resolved various build and watch issues
  Build/Tasks/SetPackageVersions.cs
  DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components.d.ts
  DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/dnn-bulk-install/dnn-bulk-install.scss
  DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/dnn-bulk-install/dnn-bulk-install.tsx
  DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/dnn-bulk-install/readme.md
  DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/my-component/my-component.tsx
  DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/utils/utils.ts
  DNN Platform/Modules/BulkInstall/BulkInstall.Web/stencil.dnn.config.ts
  DNN Platform/Modules/BulkInstall/BulkInstall.dnn
  DNN Platform/Modules/BulkInstall/Dnn.Modules.BulkInstall.csproj
  DNN Platform/Modules/BulkInstall/Images/bulk-install-icon.png
  DNN Platform/Modules/BulkInstall/Module.build
  DNN Platform/Modules/BulkInstall/Properties/AssemblyInfo.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Roles/scripts/bundles/roles-bundle.js.LICENSE.txt
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Users/scripts/bundles/users-bundle.js.LICENSE.txt
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Users/scripts/exportables/Users/UsersCommon.js.LICENSE.txt
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/scripts/exports/export-bundle.js.LICENSE.txt
  package.json
Labels: Type: Feature, Area: Platform > Modules, Effort: Medium, Priority: High, Status: Review

#5988 Fixed a performance issue while navigating folders for providers
  DNN Platform/Library/Services/FileSystem/FolderManager.cs
Labels: Type: Enhancement

#5992 Replaced the boolean values by the corresponding permissions constants values
  DNN Platform/Library/Framework/SecurityPolicy.cs
Labels: Type: Bug

#5976 fix the user roles cache issue.
  DNN Platform/Library/Entities/Users/UserInfo.cs
Labels: Type: Bug

#6002 CodeDOM installed by default
  Build/Tasks/thirdparty.json
Labels: Type: Enhancement
