Repository dnnsoftware/Dnn.Platform, pull requests merged in 2024-05, with the labels that each got.

#6018 Fix #5994: Sorting (A-Z) members of roles in PersonaBar
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/RolesController.cs
Labels: Type: Enhancement

#6025 Fix #6011: Non conforming favicon meta tags
  DNN Platform/Library/UI/FavIcon.cs
Labels: Type: Enhancement

#6015 Update jQuery UI from 1.13.2 to 1.13.3
  DNN Platform/JavaScript Libraries/jQueryUI/jQueryUI.dnn
  DNN Platform/JavaScript Libraries/jQueryUI/jquery-ui.min.js
  DNN Platform/Library/Framework/jQuery.cs
  DNN Platform/Website/Resources/Shared/components/CodeEditor/mode/slim/index.html
  DNN Platform/Website/Resources/Shared/scripts/jquery/jquery-ui.js
  DNN Platform/Website/Resources/Shared/scripts/jquery/jquery-ui.min.js
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/scripts/contrib/jquery-ui.min.js
Labels: Type: Maintenance, javascript

#6031 Make MvcServicePath regex matching ignore case.
  DNN Platform/DotNetNuke.Web.Mvc/MvcHttpModule.cs
  DNN Platform/HttpModules/MobileRedirect/MobileRedirectModule.cs
Labels: Type: Bug

#6034 Add MaximumPageSize const property for limit page size
  DNN Platform/DotNetNuke.Web/InternalServices/SearchServiceController.cs
  Dnn.AdminExperience/ClientSide/SiteSettings.Web/src/components/basicSearchSettings/index.jsx
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/DTO/SiteSettings/UpdateBasicSearchSettingsRequest.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/SiteSettingsController.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.SiteSettings/App_LocalResources/SiteSettings.resx
Labels: Type: Enhancement

#6044 Merge changes from develop branch into release/10.0.0
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/workflows/open-merged-pr-to-future.yml
  Build/Build.csproj
  DNN Platform/DotNetNuke.Web.Mvc/MvcHttpModule.cs
  DNN Platform/DotNetNuke.Web/InternalServices/SearchServiceController.cs
  DNN Platform/HttpModules/MobileRedirect/MobileRedirectModule.cs
  DNN Platform/JavaScript Libraries/jQueryUI/jQueryUI.dnn
  DNN Platform/JavaScript Libraries/jQueryUI/jquery-ui.min.js
  DNN Platform/Library/Entities/Users/UserInfo.cs
  DNN Platform/Library/Framework/SecurityPolicy.cs
  DNN Platform/Library/Framework/jQuery.cs
  DNN Platform/Library/Services/FileSystem/FolderManager.cs
  DNN Platform/Library/UI/FavIcon.cs
  DNN Platform/Tests/DotNetNuke.Tests.Integration/DotNetNuke.Tests.Integration.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Integration/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.SourceGenerators/DotNetNuke.Tests.SourceGenerators.csproj
  DNN Platform/Website/Resources/Shared/components/CodeEditor/mode/slim/index.html
  DNN Platform/Website/Resources/Shared/scripts/jquery/jquery-ui.js
  DNN Platform/Website/Resources/Shared/scripts/jquery/jquery-ui.min.js
  Dnn.AdminExperience/ClientSide/SiteSettings.Web/src/components/basicSearchSettings/index.jsx
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/DTO/SiteSettings/UpdateBasicSearchSettingsRequest.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/RolesController.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/SiteSettingsController.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.SiteSettings/App_LocalResources/SiteSettings.resx
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/scripts/contrib/jquery-ui.min.js
  DotNetNuke.Internal.SourceGenerators/DotNetNuke.Internal.SourceGenerators.csproj
  yarn.lock
Labels: Type: Maintenance

#6050 Resolved issue with file watching and `browsersync`
  DNN Platform/Skins/Aperture/package.json
  DNN Platform/Skins/Aperture/rollup-plugin-browsersync.ts
  DNN Platform/Skins/Aperture/rollup-plugin-chokidar.ts
  DNN Platform/Skins/Aperture/rollup.config.dev.ts
  DNN Platform/Skins/Aperture/rollup.config.prod.ts
  yarn.lock
Labels: Type: Bug, Area: Platform > Skins, Priority: Medium, Status: Review

#6061 Adds lock on calls to ComputeHash to handle concurrency
  DNN Platform/Dnn.AuthServices.Jwt/Components/Common/Controllers/JwtController.cs
Labels: Type: Bug
