Repository dnnsoftware/Dnn.Platform, pull requests merged in 2024-06, with the labels that each got.

#6048 Add module id information.
  DNN Platform/Website/admin/Menus/ModuleActions/ModuleActions.js
  DNN Platform/Website/admin/Modules/App_LocalResources/ModuleSettings.ascx.resx
  DNN Platform/Website/admin/Modules/Modulesettings.ascx
  DNN Platform/Website/admin/Modules/Modulesettings.ascx.cs
  DNN Platform/Website/admin/Modules/Modulesettings.ascx.designer.cs
Labels: Type: Enhancement

#6071 Updates `release/10.0.0` branch with latest fixes from `develop`
  Build/Build.csproj
  DNN Platform/Dnn.AuthServices.Jwt/Components/Common/Controllers/JwtController.cs
Labels: Type: Maintenance

#6080 Updates `release/10.0.0` with the latest changes from `develop`
  DNN Platform/Website/admin/Menus/ModuleActions/ModuleActions.js
  DNN Platform/Website/admin/Modules/App_LocalResources/ModuleSettings.ascx.resx
  DNN Platform/Website/admin/Modules/Modulesettings.ascx
  DNN Platform/Website/admin/Modules/Modulesettings.ascx.cs
  DNN Platform/Website/admin/Modules/Modulesettings.ascx.designer.cs
Labels: Type: Maintenance

#6078 Fixed an issue where the wrong deletion date was shown in recycle bin
  DNN Platform/Website/DotNetNuke.Website.csproj
  DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.13.04.SqlDataProvider
Labels: Type: Bug

#6079 Add sorting functionality to recycle bin items
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Recyclebin/IRecyclebinController.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Recyclebin/RecyclebinController.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Services/RecyclebinController.cs
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Recyclebin/App_LocalResources/Recyclebin.resx
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Recyclebin/Recyclebin.html
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Recyclebin/css/RecycleBin.css
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Recyclebin/scripts/RecycleBin.ViewModel.js
Labels: Type: Enhancement

#6046 Fix resource manager permissions save issues
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-edit-folder/dnn-rm-edit-folder.tsx
  DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.13.04.SqlDataProvider
Labels: Type: Bug

#6076 Fix build Project file does not exist.
  build.ps1
  build.sh
Labels: Effort: Low, Priority: High, Type: Build/Release, Status: Review

#6066 Update Cake-Issues Dependabot group
  .github/dependabot.yml
Labels: Type: Build/Release
