Repository dnnsoftware/Dnn.Platform, pull requests merged in 2024-10, with the labels that each got.

#6138 Fix SharpZipLib issues
  Build/Tasks/packaging.json
  DNN Platform/Admin Modules/Dnn.Modules.Console/web.config
  DNN Platform/Connectors/Azure/app.config
  DNN Platform/Connectors/GoogleAnalytics/app.config
  DNN Platform/Connectors/GoogleAnalytics4/app.config
  DNN Platform/Connectors/GoogleTagManager/app.config
  DNN Platform/Dnn.AuthServices.Jwt/app.config
  DNN Platform/DotNetNuke.Web.Mvc/app.config
  DNN Platform/DotNetNuke.Web/app.config
  DNN Platform/Modules/CoreMessaging/web.config
  DNN Platform/Modules/DnnExportImport/app.config
  DNN Platform/Modules/Groups/web.config
  DNN Platform/Modules/HTML/web.config
  DNN Platform/Modules/HtmlEditorManager/web.config
  DNN Platform/Modules/Journal/web.config
  DNN Platform/Modules/MemberDirectory/web.config
  DNN Platform/Modules/RazorHost/web.config
  DNN Platform/Modules/ResourceManager/web.config
  DNN Platform/Modules/TelerikRemoval/Web.config
  DNN Platform/Providers/HtmlEditorProviders/DNNConnect.CKE/web.config
  DNN Platform/Tests/App.config
  DNN Platform/Tests/DotNetNuke.Tests.AspNetCCP/App.config
  DNN Platform/Tests/DotNetNuke.Tests.AspNetCCP/DotNetNuke.Tests.AspNetCCP.csproj
  DNN Platform/Tests/DotNetNuke.Tests.AspNetCCP/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Content/app.config
  DNN Platform/Tests/DotNetNuke.Tests.Data/DotNetNuke.Tests.Data.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Data/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.UI/app.config
  DNN Platform/Tests/DotNetNuke.Tests.Utilities/app.config
  DNN Platform/Tests/DotNetNuke.Tests.Web.Mvc/app.config
  DNN Platform/Tests/DotNetNuke.Tests.Web/App.config
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Dnn.PersonaBar.Extensions.csproj
Labels: Area: Platform > Components, Type: Maintenance

#6154 Update PersonaBar Manage/Roles to show Role ID
  Dnn.AdminExperience/ClientSide/Roles.Web/src/components/roles/RoleEditor/index.jsx
  Dnn.AdminExperience/ClientSide/Roles.Web/src/components/roles/RoleRow/index.jsx
  Dnn.AdminExperience/ClientSide/Roles.Web/src/components/roles/UsersInRole/UserRow/index.jsx
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Roles/App_LocalResources/Roles.resx
Labels: Type: Enhancement, Area: AE > PersonaBar Ext > Roles.Web, Effort: Low, Priority: Low, Status: Review

#6164 Bump Yarn from 4.0.2 to 4.5.0
  package.json
  yarn.lock
Labels: Type: Maintenance

#6166 Fixed an issue that cause wrong size of + icon in SEO module
  Dnn.AdminExperience/ClientSide/Pages.Web/src/components/Seo/PageUrls/Table.jsx
Labels: Type: Bug

#6174 Update DotNetNuke.Newtonsoft.Json.dnn to reference version 13.0.3
  Build/ContextExtensions.cs
  Build/Tasks/PackageAspNetMvc.cs
  Build/Tasks/PackageAspNetWebApi.cs
  Build/Tasks/PackageAspNetWebPages.cs
  Build/Tasks/PackageComponentTask.cs
  Build/Tasks/PackageMailKit.cs
  Build/Tasks/PackageMicrosoftGlobbing.cs
  Build/Tasks/PackageNewtonsoft.cs
  Build/Tasks/PackageSharpZipLib.cs
  Build/Tasks/PackageWebFormsMvp.cs
  Build/Tasks/thirdparty.json
  DNN Platform/Components/Newtonsoft/DotNetNuke.Newtonsoft.Json.dnn
Labels: Type: Bug, Type: Maintenance

#6180 Fix nuspec dependencies
  Build/Tools/NuGet/DotNetNuke.Web.Mvc.nuspec
  Build/Tools/NuGet/DotNetNuke.Web.nuspec
  Build/Tools/NuGet/DotNetNuke.WebApi.nuspec
Labels: Type: Maintenance
