Repository dnnsoftware/Dnn.Platform, pull requests merged in 2025-07, with the labels that each got.

#6610 Bump Yarn from 4.9.1 to 4.9.2
  package.json
Labels: Type: Maintenance

#6577 Bump Microsoft.TestPlatform from 17.12.0 to 17.14.1
  Build/Program.cs
Labels: Type: Build/Release, Type: Maintenance

#6555 Added eslint to resource-manager project and updated dnn-elements to latest
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/.hintrc
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/eslint.config.ts
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/package.json
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components.d.ts
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/actions/dnn-action-copy-url/dnn-action-copy-url.tsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/actions/dnn-action-copy-url/readme.md
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/actions/dnn-action-create-folder/dnn-action-create-folder.tsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/actions/dnn-action-create-folder/readme.md
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/actions/dnn-action-delete-items/dnn-action-delete-items.tsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/actions/dnn-action-delete-items/readme.md
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/actions/dnn-action-download-item/dnn-action-download-item.tsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/actions/dnn-action-download-item/readme.md
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/actions/dnn-action-edit-item/dnn-action-edit-item.tsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/actions/dnn-action-edit-item/readme.md
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/actions/dnn-action-move-items/dnn-action-move-items.tsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/actions/dnn-action-move-items/readme.md
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/actions/dnn-action-open-file/dnn-action-open-file.tsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/actions/dnn-action-open-file/readme.md
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/actions/dnn-action-unlink-items/dnn-action-unlink-items.tsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/actions/dnn-action-unlink-items/readme.md
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/actions/dnn-action-upload-file/dnn-action-upload-file.tsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/actions/dnn-action-upload-file/readme.md
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-resource-manager/dnn-resource-manager.tsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-actions-bar/dnn-rm-actions-bar.tsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-create-folder/dnn-rm-create-folder.tsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-delete-items/dnn-rm-delete-items.tsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-edit-file/dnn-rm-edit-file.tsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-edit-folder/dnn-rm-edit-folder.tsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-files-pane/dnn-rm-files-pane.tsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-folder-list-item/dnn-rm-folder-list-item.tsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-folder-list/dnn-rm-folder-list.tsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-folder-mappings/dnn-rm-folder-mappings.tsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-items-cardview/dnn-rm-items-cardview.tsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-items-listview/dnn-rm-items-listview.tsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-left-pane/dnn-rm-left-pane.tsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-move-items/dnn-rm-move-items.tsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-queued-file/dnn-rm-queued-file.tsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-top-bar/dnn-rm-top-bar.tsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-unlink-items/dnn-rm-unlink-items.tsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/components/dnn-rm-upload-file/dnn-rm-upload-file.tsx
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/services/InternalServicesClient.ts
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/services/ItemsClient.ts
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/src/services/LocalizationClient.ts
  DNN Platform/Modules/ResourceManager/Services/ItemsController.cs
  yarn.lock
Labels: Type: Maintenance

#6624 Deprecate `ClientResourceManager.RegisterIEStylesheet`
  DNN Platform/DotNetNuke.Web.Client/ClientResourceManager.cs
Labels: Type: Maintenance

#6633 Fix/move tab stored procedures to avoid concurrency issues
  DNN Platform/Website/Providers/DataProviders/SqlDataProvider/10.01.00.SqlDataProvider
Labels: Type: Bug

#6642 Fixed an issue where CustomCss module would not load
  Dnn.AdminExperience/ClientSide/AdminLogs.Web/src/components/AdminLog/index.jsx
  Dnn.AdminExperience/ClientSide/AdminLogs.Web/src/reducerHelpers/index.js
  Dnn.AdminExperience/ClientSide/Security.Web/src/components/apiTokens/index.jsx
  Dnn.AdminExperience/ClientSide/SiteImportExport.Web/src/components/Dashboard/index.jsx
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.CssEditor/scripts/CssEditor.js
Labels: Type: Bug
