Repository dnnsoftware/Dnn.Platform, pull requests merged in 2025-01, with the labels that each got.

#6286 Merged latest changes from `develop` into `release/10.0.0`
  .github/workflows/browserslist-update-db.yml
  DNN Platform/Tests/DNN.Integration.Test.Framework/DNN.Integration.Test.Framework.csproj
  DNN Platform/Tests/DNN.Integration.Test.Framework/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.AspNetCCP/DotNetNuke.Tests.AspNetCCP.csproj
  DNN Platform/Tests/DotNetNuke.Tests.AspNetCCP/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Authentication/DotNetNuke.Tests.Authentication.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Authentication/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Content/DotNetNuke.Tests.Content.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Content/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Core/DotNetNuke.Tests.Core.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Core/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Data/DotNetNuke.Tests.Data.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Data/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Integration/DotNetNuke.Tests.Integration.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Integration/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Mail/DotNetNuke.Tests.Mail.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Mail/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Modules/DotNetNuke.Tests.Modules.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Modules/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.SourceGenerators/DotNetNuke.Tests.SourceGenerators.csproj
  DNN Platform/Tests/DotNetNuke.Tests.SourceGenerators/Snapshots/GeneratorTests.NotPartial_ReportsError.verified.txt
  DNN Platform/Tests/DotNetNuke.Tests.UI/DotNetNuke.Tests.UI.csproj
  DNN Platform/Tests/DotNetNuke.Tests.UI/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Urls/DotNetNuke.Tests.Urls.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Urls/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Utilities/DotNetNuke.Tests.Utilities.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Utilities/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Web.Mvc/DotNetNuke.Tests.Web.Mvc.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Web.Mvc/packages.config
  DNN Platform/Tests/DotNetNuke.Tests.Web/DotNetNuke.Tests.Web.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Web/packages.config
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/Components/Themes/ThemesController.cs
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.ConfigConsole.Tests/Dnn.PersonaBar.ConfigConsole.Tests.csproj
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.ConfigConsole.Tests/packages.config
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.Pages.Tests/Dnn.PersonaBar.Pages.Tests.csproj
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.Pages.Tests/packages.config
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.Security.Tests/Dnn.PersonaBar.Security.Tests.csproj
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.Security.Tests/packages.config
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.Users.Tests/Dnn.PersonaBar.Users.Tests.csproj
  Dnn.AdminExperience/Tests/Dnn.PersonaBar.Users.Tests/packages.config
  DotNetNuke.Internal.SourceGenerators/DotNetNuke.Internal.SourceGenerators.csproj
  package.json
Labels: Type: Maintenance

#6279 Imports css-variables into Persona Bar main styles
  Dnn.AdminExperience/Library/Dnn.PersonaBar.Library/Containers/PersonaBarContainer.cs
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/main.css
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/css/theme.css
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/scripts/bootstrap.js
Labels: Type: Enhancement

#6292 Fixed a typo in default website template
  DNN Platform/Website/Portals/_default/Default Website.template
Labels: Type: Bug

#6288 Resolved issue with disabled page names and refactored logic
  DNN Platform/Skins/Aperture/menus/desktop/RazorMenu.cshtml
  DNN Platform/Skins/Aperture/menus/footer/RazorMenu.cshtml
Labels: Type: Feature, Type: Bug, Area: Platform > Skins, Effort: Low, Priority: High, Status: Review

#6280 Updated all references from dnndocs.com to docs.dnncommunity.org
  DNN Platform/DotNetNuke.Abstractions/Application/IApplicationInfo.cs
  DNN Platform/Library/Application/Application.cs
  DNN Platform/Modules/CoreMessaging/CoreMessaging.dnn
  DNN Platform/Modules/Groups/SocialGroups.dnn
  DNN Platform/Modules/HTML/dnn_HTML.dnn
  DNN Platform/Modules/HtmlEditorManager/dnn_HtmlEditorManager.dnn
  DNN Platform/Modules/Journal/Journal.dnn
  DNN Platform/Modules/MemberDirectory/MemberDirectory.dnn
  DNN Platform/Website/Portals/_default/Default Website.template.en-US.resx
  Dnn.AdminExperience/ClientSide/Licensing.Web/src/components/platform/index.jsx
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/scripts/serversummary.js
  README.md
Labels: Type: Enhancement, Area: AE > PersonaBar Ext > Licensing.Web, Area: AE > Dnn.PersonaBar.UI, Area: Platform > Library, Area: Platform > Modules, Area: Platform > Website, Effort: Low, Priority: Low, Status: Review

#6294 Updated dnn-elements to v0.25.0 in Resource Manager module
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/package.json
  yarn.lock
Labels: Type: Maintenance

#6297 Added prefixes to css variables portal settings
  DNN Platform/Library/Entities/Portals/PortalStyles.cs
Labels: Type: Enhancement

#6299 Update release and development configs to reflect API Tokens auth addition
  DNN Platform/Website/development.config
  DNN Platform/Website/release.config
Labels: Type: Bug, Area: Platform > Website

#6301 Merge `develop` into `release/10.0.0`
  DNN Platform/DotNetNuke.Abstractions/Application/IApplicationInfo.cs
  DNN Platform/Library/Application/Application.cs
  DNN Platform/Modules/CoreMessaging/CoreMessaging.dnn
  DNN Platform/Modules/Groups/SocialGroups.dnn
  DNN Platform/Modules/HTML/dnn_HTML.dnn
  DNN Platform/Modules/HtmlEditorManager/dnn_HtmlEditorManager.dnn
  DNN Platform/Modules/Journal/Journal.dnn
  DNN Platform/Modules/MemberDirectory/MemberDirectory.dnn
  DNN Platform/Modules/ResourceManager/ResourceManager.Web/package.json
  DNN Platform/Website/Portals/_default/Default Website.template.en-US.resx
  Dnn.AdminExperience/ClientSide/Licensing.Web/src/components/platform/index.jsx
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/scripts/serversummary.js
  README.md
  yarn.lock
Labels: Type: Maintenance

#6303 Updated component folder structure for better organization
  DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/tabs/api-users/api-user.model.ts
  DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/tabs/api-users/api-users.scss
  DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/tabs/api-users/api-users.tsx
  DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/tabs/api-users/readme.md
  DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/tabs/ip-safelist/ip-safelist.model.ts
  DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/tabs/ip-safelist/ip-safelist.scss
  DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/tabs/ip-safelist/ip-safelist.tsx
  DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/tabs/ip-safelist/readme.md
  yarn.lock
Labels: Type: Feature, Area: Platform > Modules, Effort: Low, Priority: High, Status: Review

#6304 Bulk Install: Implemented initial UI for Event Logs
  DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components.d.ts
  DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/dnn-bulk-install/dnn-bulk-install.tsx
  DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/dnn-bulk-install/readme.md
  DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/tabs/api-users/readme.md
  DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/tabs/event-log/event-log.model.ts
  DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/tabs/event-log/event-log.scss
  DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/tabs/event-log/event-log.tsx
  DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/tabs/event-log/readme.md
  DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/tabs/ip-safelist/readme.md
Labels: Type: Feature, Area: Platform > Modules, Effort: Low, Priority: High, Status: Review

#6305 BulkInstall: Changed to use new form pattern from dnn-elements
  DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/dnn-bulk-install/readme.md
  DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/tabs/api-users/api-users.scss
  DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/tabs/api-users/api-users.tsx
  DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/tabs/api-users/readme.md
Labels: Type: Enhancement

#6306 Bulk Install: Updated component names to ensure uniqueness
  DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components.d.ts
  DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/dnn-bulk-install/dnn-bulk-install.tsx
  DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/dnn-bulk-install/readme.md
  DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/tabs/bulk-install-api-users/bulk-install-api-users.model.ts
  DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/tabs/bulk-install-api-users/bulk-install-api-users.scss
  DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/tabs/bulk-install-api-users/bulk-install-api-users.tsx
  DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/tabs/bulk-install-api-users/readme.md
  DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/tabs/bulk-install-ip-safelist/bulk-install-ip-safelist.model.ts
  DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/tabs/bulk-install-ip-safelist/bulk-install-ip-safelist.scss
  DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/tabs/bulk-install-ip-safelist/bulk-install-ip-safelist.tsx
  DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/tabs/bulk-install-ip-safelist/readme.md
  DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/tabs/bulk-install-logs/bulk-install-logs.model.ts
  DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/tabs/bulk-install-logs/bulk-install-logs.scss
  DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/tabs/bulk-install-logs/bulk-install-logs.tsx
  DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/tabs/bulk-install-logs/readme.md
  DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/tabs/event-log/readme.md
Labels: Type: Feature, Area: Platform > Modules, Effort: Medium, Priority: High, Status: Review

#6307 Implemented localization on bulk-install
  DNN Platform/Modules/BulkInstall/App_LocalResources/BulkInstall.resx
  DNN Platform/Modules/BulkInstall/BulkInstall.Web/package.json
  DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/clients/localization-client.ts
  DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components.d.ts
  DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/dnn-bulk-install/dnn-bulk-install.tsx
  DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/tabs/bulk-install-api-users/bulk-install-api-users.tsx
  DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/tabs/bulk-install-ip-safelist/bulk-install-ip-safelist.tsx
  DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/components/tabs/bulk-install-logs/bulk-install-logs.tsx
  DNN Platform/Modules/BulkInstall/BulkInstall.Web/src/stores/store.ts
  DNN Platform/Modules/BulkInstall/Components/WebAPI/LocalizationController.cs
  DNN Platform/Modules/BulkInstall/Components/WebAPI/Routes.cs
  DNN Platform/Modules/BulkInstall/Dnn.Modules.BulkInstall.csproj
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Roles/scripts/bundles/roles-bundle.js.LICENSE.txt
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Users/scripts/bundles/users-bundle.js.LICENSE.txt
  Dnn.AdminExperience/Dnn.PersonaBar.Extensions/admin/personaBar/Dnn.Users/scripts/exportables/Users/UsersCommon.js.LICENSE.txt
  Dnn.AdminExperience/Library/Dnn.PersonaBar.UI/admin/personaBar/scripts/exports/export-bundle.js.LICENSE.txt
  yarn.lock
Labels: Type: Enhancement

#6311 Updated default template content to use proper background class from Aperture
  DNN Platform/Website/Portals/_default/Default Website.template
Labels: Type: Feature, Area: Platform > Website, Effort: Low, Priority: High, Status: Review

#6315 Updates `relese/10.0.0` with latest changes from `develop`
  global.json
Labels: Type: Maintenance

#6321 delete authentication cookie when the cookie expires or is invalid
  DNN Platform/DotNetNuke.Web/Common/DotNetNukeHttpApplication.cs
Labels: Type: Bug

#6310 Add DataContext to DI
  DNN Platform/DotNetNuke.Web/Api/Auth/ApiTokens/Repositories/ApiTokenRepository.cs
  DNN Platform/DotNetNuke.Web/Startup.cs
  DNN Platform/Library/Startup.cs
Labels: Type: Enhancement, Area: Platform > Library

#6295 Fixed a typo (missing prefix) for variation-opacity
  DNN Platform/Library/Entities/Portals/PortalStyles.cs
Labels: Type: Bug

#6262 Update HtmlText to Content Workflow API
  DNN Platform/Modules/HTML/Components/HtmlTextController.cs
  DNN Platform/Modules/HTML/Components/WorkflowStateController.cs
  DNN Platform/Modules/HTML/Components/WorkflowStateInfo.cs
  DNN Platform/Modules/HTML/DotNetNuke.Modules.Html.csproj
  DNN Platform/Modules/HTML/DotNetNuke.Modules.Html.csproj.DotSettings
  DNN Platform/Modules/HTML/EditHtml.ascx
  DNN Platform/Modules/HTML/EditHtml.ascx.cs
  DNN Platform/Modules/HTML/EditHtml.ascx.designer.cs
  DNN Platform/Modules/HTML/HtmlModule.ascx.cs
  DNN Platform/Modules/HTML/Providers/DataProviders/SqlDataProvider/10.00.00.SqlDataProvider
  DNN Platform/Modules/HTML/Settings.ascx.cs
  DNN Platform/Modules/HTML/dnn_HTML.dnn
Labels: Type: Enhancement

#6314 Feature/6313 unique profile property per portal
  DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.13.08.SqlDataProvider
  DNN Platform/Website/Providers/DataProviders/SqlDataProvider/DotNetNuke.Schema.SqlDataProvider
Labels: Type: Bug

#6322 Rebased `release/10.0.0` with latest fixes from `develop`
  DNN Platform/Dnn.ClientSide/package-lock.json
  DNN Platform/DotNetNuke.Web/Common/DotNetNukeHttpApplication.cs
  DNN Platform/Website/Providers/DataProviders/SqlDataProvider/09.13.08.SqlDataProvider
  DNN Platform/Website/Providers/DataProviders/SqlDataProvider/DotNetNuke.Schema.SqlDataProvider
  Dnn.AdminExperience/ClientSide/SiteImportExport.Web/package.json
  package-lock.json
  yarn.lock
Labels: Type: Maintenance

#6324 SQL 2017 fix
  DNN Platform/Website/Providers/DataProviders/SqlDataProvider/10.00.00.SqlDataProvider
Labels: Type: Bug

#6325 Resolved issue with default template image src paths
  DNN Platform/Website/Portals/_default/Default Website.template
Labels: Type: Bug, Area: Platform > Website, Effort: Low, Priority: High, Status: Review

#6326 Improvements for Dnn.ClientSide project
  DNN Platform/Dnn.ClientSide/Dnn.ClientSide.esproj
Labels: Type: Enhancement

#6328 Fixed a tab position issue in install/upgrade wizard
  DNN Platform/Dnn.ClientSide/src/styles/install/install.scss
Labels: Type: Bug

#6331 Fixes browsersync in aperture theme
  DNN Platform/Skins/Aperture/LICENSE
  DNN Platform/Skins/Aperture/build.ts
  DNN Platform/Skins/Aperture/manifest.dnn
  DNN Platform/Skins/Aperture/package.json
  DNN Platform/Skins/Aperture/rollup-plugin-browsersync.ts
  DNN Platform/Skins/Aperture/rollup-plugin-chokidar.ts
  DNN Platform/Skins/Aperture/rollup-plugin-package.ts
  DNN Platform/Skins/Aperture/rollup.config.dev.ts
  DNN Platform/Skins/Aperture/rollup.config.prod.ts
  DNN Platform/Skins/Aperture/src/scripts/main.ts
  DNN Platform/Skins/Aperture/src/scss/_base.scss
  DNN Platform/Skins/Aperture/src/scss/components/_components.scss
  DNN Platform/Skins/Aperture/src/scss/components/_nav.scss
  DNN Platform/Skins/Aperture/src/scss/components/_search.scss
  DNN Platform/Skins/Aperture/src/scss/sections/_footer.scss
  DNN Platform/Skins/Aperture/src/scss/sections/_header.scss
  DNN Platform/Skins/Aperture/src/scss/sections/_sections.scss
  DNN Platform/Skins/Aperture/src/scss/style.scss
  DNN Platform/Skins/Aperture/src/scss/utilities/_backgrounds.scss
  DNN Platform/Skins/Aperture/src/scss/utilities/_borders.scss
  DNN Platform/Skins/Aperture/src/scss/utilities/_buttons.scss
  DNN Platform/Skins/Aperture/src/scss/utilities/_dimension.scss
  DNN Platform/Skins/Aperture/src/scss/utilities/_display.scss
  DNN Platform/Skins/Aperture/src/scss/utilities/_flex.scss
  DNN Platform/Skins/Aperture/src/scss/utilities/_gap.scss
  DNN Platform/Skins/Aperture/src/scss/utilities/_margin.scss
  DNN Platform/Skins/Aperture/src/scss/utilities/_media-queries.scss
  DNN Platform/Skins/Aperture/src/scss/utilities/_overflow.scss
  DNN Platform/Skins/Aperture/src/scss/utilities/_padding.scss
  DNN Platform/Skins/Aperture/src/scss/utilities/_position.scss
  DNN Platform/Skins/Aperture/src/scss/utilities/_text.scss
  DNN Platform/Skins/Aperture/src/scss/utilities/_utilities.scss
  DNN Platform/Skins/Aperture/src/scss/variables/_colors.scss
  DNN Platform/Skins/Aperture/src/scss/variables/_controls.scss
  DNN Platform/Skins/Aperture/src/scss/variables/_type.scss
  DNN Platform/Skins/Aperture/src/scss/variables/_variables.scss
  yarn.lock
Labels: Type: Bug

#6327 Force Telerik uninstall
  Build/Build.csproj
  DNN Platform/DotNetNuke.Maintenance/Constants.cs
  DNN Platform/DotNetNuke.Maintenance/DotNetNuke.Maintenance.csproj
  DNN Platform/DotNetNuke.Maintenance/Telerik/ITelerikUtils.cs
  DNN Platform/DotNetNuke.Maintenance/Telerik/Removal/TelerikUninstaller.cs
  DNN Platform/DotNetNuke.Maintenance/Telerik/TelerikUtils.cs
  DNN Platform/DotNetNuke.ModulePipeline/DotNetNuke.ModulePipeline.csproj
  DNN Platform/Modules/TelerikRemoval/Dnn.Modules.TelerikRemoval.csproj
  DNN Platform/Modules/TelerikRemoval/TelerikRemoval.dnn
  DNN Platform/Modules/TelerikRemoval/UpgradeController.cs
  DNN Platform/Skins/Aperture/Dnn.Skins.Aperture.csproj
  DNN Platform/Tests/DotNetNuke.Tests.Modules.DDRMenu/DotNetNuke.Tests.Modules.DDRMenu.csproj
  DNN Platform/Website/Install/App_LocalResources/UpgradeWizard.aspx.resx
  DNN Platform/Website/Install/Install.aspx.cs
  DNN Platform/Website/Install/UpgradeWizard.aspx.cs
Labels: Type: Feature, Alert: Breaking Change
